/**
 * Intake orchestration.
 *
 * ORDER MATTERS AND IS DELIBERATE. Store first, queue second, return third. The
 * durable record is the only artifact that cannot be reconstructed afterwards, so it
 * is written before anything that can fail slowly. Email, calendar, and contact
 * synchronization are all recoverable by hand; a dropped submission is not.
 *
 * The whole thing runs under one lock, because two concurrent submissions from the
 * same person would otherwise each see "no existing contact" and create two.
 */

/**
 * Processes a validated envelope. `envelope` has already passed parseEnvelope, so
 * this function never re-checks shapes; it makes decisions.
 */
function processSubmission(envelope, deps) {
  return deps.lock.withLock(function () {
    var now = deps.clock.now();

    // Replay protection. The submissionId is generated by the browser once per
    // completed form, so a retried request, a double-click, or a flaky network
    // returns the ORIGINAL result instead of creating a second lead.
    var existing = deps.leads.findLeadBySubmissionId(envelope.submissionId);
    if (existing) {
      return {
        ok: true,
        replay: true,
        leadId: existing.leadId,
        contactId: existing.contactId,
        slaDueAt: existing.slaDueAt || null
      };
    }

    var screening = screenSubmission(envelope);
    var identity = resolveIdentity(envelope, deps, now);

    var pathway = envelope.submissionKind === 'service_inquiry' ? envelope.payload.pathway : null;
    var slaDueAt = computeSlaDueAt(envelope.submissionKind, pathway, now, deps.offsetResolver);

    var leadId = deps.ids.newId();
    var attribution = buildAttributionRecord(envelope.attribution);
    var provisional = routeNotification({
      sourceCategory: attribution.sourceCategory,
      scannedPartner: attribution.scannedPartner,
      scannedSlugUnresolved: attribution.scannedSlugUnresolved
    }, screening);

    var lead = buildLead(envelope, {
      leadId: leadId,
      contactId: identity.contactId,
      receivedAt: now,
      slaDueAt: slaDueAt,
      screening: screening,
      possibleMatches: identity.possibleMatches,
      ownerPartner: provisional.ownerPartner
    });

    deps.leads.insertLead(lead);
    persistIdentity(identity, envelope, deps, { leadId: leadId, receivedAt: now });

    enqueueSubmissionWork(lead, deps, now);

    // Logged through the safe wrapper: the log is a diagnostic, and a diagnostic must
    // never be the reason a stored submission reports failure to the visitor.
    tryLog(deps, {
      level: 'info',
      event: 'submission_accepted',
      submissionId: envelope.submissionId,
      leadId: leadId,
      // Redacted. A log line is read casually and copied around; personal data does
      // not belong in one.
      detail: [
        envelope.submissionKind,
        pathway || '',
        attribution.sourceCategory,
        redactEmail(lead.email),
        screening.spamSuspected ? 'flagged:' + screening.spamReason : 'clean'
      ].join(' ')
    });

    return {
      ok: true,
      replay: false,
      leadId: leadId,
      contactId: identity.contactId,
      slaDueAt: lead.slaDueAt || null
    };
  });
}

/**
 * Finds or creates the Contact this submission belongs to.
 *
 * Only a STRONG match links automatically, and linking is not merging: no stored
 * value is discarded, the lead simply points at the existing person. Probable and
 * weak candidates are recorded in `possibleMatches` for a human, because a wrong
 * automatic link puts one person's inquiry in another person's history.
 */
function resolveIdentity(envelope, deps, now) {
  var isExchange = envelope.submissionKind === 'contact_exchange';
  var p = envelope.payload;
  var source = isExchange ? p : (p.contact || {});

  var incoming = {
    fullName: source.fullName || '',
    email: source.email || '',
    phone: source.phone || '',
    company: isExchange ? (p.company || '') : (source.organization || '')
  };

  var candidates = deps.contacts.listContactCandidates({
    emailKey: emailKey(incoming.email),
    phoneKey: phoneKey(incoming.phone),
    nameKey: lowerTrim(incoming.fullName)
  });

  var matches = findPossibleMatches(incoming, candidates || []);
  var strong = matches.filter(function (m) { return m.confidence === MATCH_CONFIDENCE.STRONG; });

  // Two different strong candidates means the existing data already disagrees with
  // itself. Picking one would hide that; a new record plus the suggestions surfaces it.
  if (strong.length === 1) {
    return {
      contactId: strong[0].contactId,
      isNew: false,
      possibleMatches: matches,
      incoming: incoming
    };
  }

  return {
    contactId: deps.ids.newId(),
    isNew: true,
    possibleMatches: matches,
    incoming: incoming
  };
}

function persistIdentity(identity, envelope, deps, ctx) {
  if (identity.isNew) {
    deps.contacts.insertContact(buildContact(envelope, {
      contactId: identity.contactId,
      leadId: ctx.leadId,
      receivedAt: ctx.receivedAt,
      possibleMatches: identity.possibleMatches
    }));
    return;
  }

  var existing = deps.contacts.findContactById(identity.contactId);
  if (!existing) {
    // The candidate list named a contact that is no longer there. Rather than losing
    // the person entirely, write the record under the id that was matched.
    deps.contacts.insertContact(buildContact(envelope, {
      contactId: identity.contactId,
      leadId: ctx.leadId,
      receivedAt: ctx.receivedAt,
      possibleMatches: identity.possibleMatches
    }));
    return;
  }

  var locale = buildLocaleRecord(envelope.locale);
  var isExchange = envelope.submissionKind === 'contact_exchange';
  var p = envelope.payload;

  deps.contacts.updateContact(mergeContact(existing, {
    fullName: identity.incoming.fullName,
    email: identity.incoming.email,
    phone: identity.incoming.phone,
    company: identity.incoming.company,
    roleOrTitle: isExchange ? (p.roleOrTitle || '') : '',
    contactCategory: isExchange ? p.contactCategory : '',
    preferredFollowUpLocale: locale.preferredFollowUpLocale,
    preferredFollowUpStated: locale.preferredFollowUpStated
  }, ctx));
}

/**
 * Queues the side effects. Both are enqueued even when the relevant service is not
 * configured: the handler records `not_configured` against the lead, which is a
 * visible, auditable state. Skipping the enqueue would leave `pending` forever and
 * look like a stuck queue instead of a missing setting.
 */
function enqueueSubmissionWork(lead, deps, now) {
  deps.work.enqueue(buildWorkItem('send_acknowledgement', lead.leadId, {}, {
    workId: deps.ids.newId(),
    now: now,
    discriminator: 'ack'
  }));

  deps.work.enqueue(buildWorkItem('notify_partners', lead.leadId, {}, {
    workId: deps.ids.newId(),
    now: now,
    discriminator: 'notify'
  }));
}
