/**
 * The V2 email templates.
 *
 * ONE COPY OF EACH. Pure functions returning { ok, subject, htmlBody, textBody }. The
 * plain-text part is written here as a specification, not generated by stripping tags,
 * because the design treats it as the real second half of a multipart alternative: a
 * partner has to be able to work a whole digest from the text part alone.
 *
 * TWO RULES RUN THROUGH EVERY TEMPLATE.
 *
 * 1. Human labels, never wire tokens. `property_owner_operator` is a storage value.
 *    See Labels.js.
 *
 * 2. Missing optional values DISAPPEAR rather than rendering empty. A row that must
 *    exist but has no verified value is omitted, never shown blank and never filled
 *    with an invented placeholder. The single exception is the digest, where "Not
 *    provided" is itself information: an empty Email row is the signal that no
 *    acknowledgement could be sent.
 *
 * Nothing here contains a tracking pixel, an open-tracking image, a click-wrapped link,
 * marketing enrollment, nurture language, or a preference centre. These are
 * transactional messages.
 */

var FIRM_DISPLAY_NAME = 'AxisPoint Partners';
var FIRM_FOCUS = 'Property Management, Houston, Texas';

/* ── Shared pieces ────────────────────────────────────────────────────────── */

function firstNameOf(fullName) {
  var n = normalizeWhitespace(fullName);
  if (n === '') return '';
  return n.split(' ')[0];
}

/**
 * The correction and removal block.
 *
 * RENDERED ONLY WHEN BOTH FLAGS ARE SET. Its copy promises that a reply reaches a human
 * who will correct or delete someone's record. With no monitored mailbox and no written
 * procedure behind it, printing it tells a real person something untrue, so it is
 * omitted entirely rather than softened. `configHealth` reports both as launch blockers.
 */
function canPromiseReply(config) {
  return config.replyToMonitored === true && config.removalProcedureConfigured === true;
}

function replyPromiseHtml(config) {
  if (!canPromiseReply(config)) return '';
  return para('If your details need correcting, reply to this message and we will update them.') +
    para('If you did not submit this, reply and we will remove your information.');
}

function replyPromiseText(config) {
  if (!canPromiseReply(config)) return '';
  return '\n' + textWrap('If your details need correcting, reply to this message and we will update them.') +
    '\n\n' + textWrap('If you did not submit this, reply and we will remove your information.') + '\n';
}

/** Footer legal line. Drops the reply invitation when no one is reading replies. */
function footerLegalFor(config) {
  return canPromiseReply(config)
    ? 'Sent from Houston, Texas. You can reply to this message at any time.'
    : 'Sent from Houston, Texas.';
}

/**
 * Who the acknowledgement says has the details.
 *
 * Falls back to the firm whenever the partner's own direct address is not configured,
 * because a partner block with no way to reach that partner is worse than the firm
 * block, which at least resolves.
 */
function acknowledgementIdentity(acquisitionSource, config) {
  var isPartner = PARTNERS.indexOf(acquisitionSource) !== -1;
  var directEmail = isPartner ? (config.partnerDirectEmail || {})[acquisitionSource] : '';

  if (isPartner && directEmail) {
    return {
      isPartner: true,
      name: PARTNER_LABELS[acquisitionSource],
      title: 'Partner, AxisPoint Partners',
      email: directEmail,
      phone: (config.partnerDirectPhone || {})[acquisitionSource] || '',
      website: config.websiteUrl || ''
    };
  }

  return {
    isPartner: false,
    name: FIRM_DISPLAY_NAME,
    title: FIRM_FOCUS,
    email: config.firmEmail || '',
    phone: config.firmPhone || '',
    website: config.websiteUrl || ''
  };
}

/** Rows for the "who you connected with" panel. Unverified rows are omitted. */
function identityRows(identity) {
  var rows = [[identity.isPartner ? 'Name' : 'Name', identity.name]];
  rows.push([identity.isPartner ? 'Title' : 'Focus', identity.title]);
  if (identity.email) rows.push(['Email', identity.email]);
  if (identity.phone) rows.push(['Phone', identity.phone]);
  if (identity.website) rows.push(['Website', identity.website]);
  return rows;
}

function identityTextRows(identity) {
  var out = [textRow('Name', identity.name), textRow(identity.isPartner ? 'Title' : 'Focus', identity.title)];
  if (identity.email) out.push(textRow('Email', identity.email));
  if (identity.phone) out.push(textRow('Phone', identity.phone));
  if (identity.website) out.push(textRow('Website', identity.website));
  return out.join('\n');
}

/* ── 1. QR Contact acknowledgement ────────────────────────────────────────── */

/**
 * Sent to the person who shared their details from a scanned card.
 *
 * DATA MINIMIZATION IS THE SHAPE OF THIS EMAIL. The submitted address has not been
 * verified as belonging to the person who typed it, so the DISPLAY NAME is the only
 * submitted value that appears anywhere in it. Phone, company, role, and category are
 * never echoed. Echoing an unverified record back would mail somebody else's phone
 * number to whoever the address actually belongs to.
 *
 * There is also no button. The approved shell allows one dominant action and this
 * message has nothing for the recipient to do; a Save Contact action is deliberately
 * withheld until a permanent profile URL or a verified vCard delivery method exists.
 */
function renderQrAcknowledgement(contact, config) {
  if (!contact || !contact.email) {
    return { ok: false, permanent: true, reason: 'no_recipient_address' };
  }

  var identity = acknowledgementIdentity(contact.acquisitionSource, config);
  if (!identity.email) {
    return { ok: false, permanent: true, reason: 'no_verified_sender_identity' };
  }

  var first = firstNameOf(contact.fullName);
  var greeting = first ? 'Thank you, ' + first + '.' : 'Thank you.';
  var headlineText = greeting + ' Your details are with ' + identity.name + '.';

  var leadText = identity.isPartner
    ? 'You shared your contact information from ' + identity.name +
      "'s AxisPoint card. It has been received. Nothing further is needed from you."
    : 'You shared your contact information from an AxisPoint card that did not resolve to a ' +
      'partner profile. It has been received by AxisPoint Partners. Nothing further is needed from you.';

  var receipt = identity.isPartner
    ? 'Received and stored. They are not repeated in this email, because this address has not been verified as yours.'
    : 'Received and stored by AxisPoint Partners. They are not repeated in this email, because this address has not been verified as yours.';

  var body =
    block(eyebrow('Your details were received')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    block(panel('Your contact details', [['Status', receipt, true]]), 'padding-top:22px;') +
    block(panel(identity.isPartner ? 'Who you connected with' : 'Who has your details', identityRows(identity)), 'padding-top:16px;') +
    block(callout('info', '', 'This is not a mailing list',
      'Sharing your details from a card does not subscribe you to anything. They are used only to follow up on the conversation you had.'), 'padding-top:16px;') +
    (replyPromiseHtml(config) ? block(replyPromiseHtml(config)) : '') +
    block(signatureHtml(identity), 'padding-top:20px;');

  var subject = identity.name + ' has your contact details';

  var text = [
    textRule(subject),
    '',
    greeting,
    '',
    textWrap(leadText),
    '',
    textRule('Your contact details'),
    textWrap(receipt),
    '',
    textRule(identity.isPartner ? 'Who you connected with' : 'Who has your details'),
    identityTextRows(identity),
    '',
    textRule('This is not a mailing list'),
    textWrap('Sharing your details from a card does not subscribe you to anything. They are used only to follow up on the conversation you had.'),
    replyPromiseText(config),
    '--',
    identity.name,
    identity.title,
    identity.email,
    identity.phone || '',
    identity.website || '',
    '',
    FIRM_DISPLAY_NAME + ' | Houston, Texas',
    textWrap('You are receiving this because you shared your details from an AxisPoint card.')
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Contact exchange',
      preheader: 'Your contact details were received. Reply if anything needs correcting.',
      body: body,
      footerNote: 'You are receiving this because you shared your details from an AxisPoint card.',
      footerLegal: footerLegalFor(config),
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}

function signatureHtml(identity) {
  var out = '<div style="border-top:1px solid ' + PALETTE.hair + ';padding-top:18px;">' +
    '<div style="' + styleFont(16, 700, PALETTE.ink, 1.4) + 'letter-spacing:-0.01em;">' + esc(identity.name) + '</div>' +
    '<div style="' + styleFont(14, 400, PALETTE.muted, 1.5) + 'padding-top:2px;">' + esc(identity.title) + '</div>';
  if (identity.email) {
    out += '<div style="' + styleFont(14, 600, PALETTE.tealDeep, 1.5) + 'padding-top:8px;">' + esc(identity.email) + '</div>';
  }
  if (identity.phone) {
    out += '<div style="' + styleFont(14, 400, PALETTE.muted, 1.5) + '">' + esc(identity.phone) + '</div>';
  }
  if (identity.website) {
    out += '<div style="' + styleFont(14, 400, PALETTE.muted, 1.5) + '">' + esc(identity.website) + ', Houston, Texas</div>';
  }
  return out + '</div>';
}

/* ── 2. Website inquiry acknowledgement ───────────────────────────────────── */

/**
 * Sent to somebody who submitted a service inquiry on the website.
 *
 * Unlike the QR acknowledgement this one DOES repeat the submission back, because the
 * person deliberately described a property and the repetition is the proof that a human
 * will read it. It still carries no response-time promise beyond what the SLA policy
 * actually commits to, and it makes no claim about who will reply.
 */
function renderWebsiteAcknowledgement(lead, config) {
  if (!lead || !lead.email) return { ok: false, permanent: true, reason: 'no_recipient_address' };

  var first = firstNameOf(lead.fullName);
  var isProposal = lead.pathway === 'management_proposal';

  var headlineText = (first ? 'Thank you, ' + first + '. ' : 'Thank you. ') +
    (isProposal ? 'We have your property details.' : 'We have your message.');

  var rows = [];
  if (isProposal) {
    pushRow(rows, 'Property or portfolio', lead.propertyLocation);
    pushRow(rows, 'Type', labelFor(PROPERTY_TYPE_LABELS, lead.propertyType, ''));
    pushRow(rows, 'Scope', labelFor(PROPERTY_SCOPE_LABELS, lead.propertyScope, ''));
    pushRow(rows, 'Units or square footage', lead.propertyScaleUnknown === true || lead.propertyScaleUnknown === 'TRUE' ? '' : lead.propertyScale);
    pushRow(rows, 'Ownership group', lead.organization);
    pushRow(rows, 'Service interest', labelFor(SERVICE_SCOPE_LABELS, lead.serviceScope, ''));
    pushRow(rows, 'Timing', labelFor(TIMING_LABELS, lead.situationTiming, ''));
  } else {
    pushRow(rows, 'Pathway', labelFor(PATHWAY_LABELS, lead.pathway, ''));
    pushRow(rows, 'Topic', labelFor(TOPIC_LABELS, lead.topic, ''));
    pushRow(rows, 'Ownership group', lead.organization);
  }

  var leadText = 'A Partner will review what you sent and reply to you. This message confirms what reached us.';

  var body =
    block(eyebrow('Your request')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    (rows.length > 0
      ? block(panel(isProposal ? 'The property' : 'What you sent', rows), 'padding-top:22px;')
      : '') +
    block(para('You can reply to this message with anything you would like to add.'));

  var subject = isProposal
    ? 'We have your property details'
    : 'We have your message';

  var textRows = rows.map(function (r) { return textRow(r[0], r[1]); }).join('\n');

  var text = [
    textRule(subject),
    '',
    headlineText,
    '',
    textWrap(leadText),
    '',
    rows.length > 0 ? textRule(isProposal ? 'The property' : 'What you sent') : '',
    textRows,
    '',
    textWrap('You can reply to this message with anything you would like to add.'),
    '',
    '--',
    FIRM_DISPLAY_NAME,
    FIRM_FOCUS
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Property Management',
      preheader: 'We have your details. Here is what happens next.',
      body: body,
      footerNote: 'You are receiving this because you contacted AxisPoint Partners about property management.',
      footerLegal: 'Sent from Houston, Texas. You can reply to this message with anything you would like to add.',
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}

/** Adds a row only when the value is present. Optional values disappear cleanly. */
function pushRow(rows, key, value) {
  var v = normalizeWhitespace(value);
  if (v !== '') rows.push([key, v]);
}

/* ── 3. Internal website inquiry notification ─────────────────────────────── */

/**
 * Sent to the partners immediately when a website service inquiry arrives.
 *
 * Website inquiries keep IMMEDIATE notification. Only QR Contacts moved to the daily
 * digest, because a scanned card is an acquisition record and an inquiry is a request
 * with a clock running on it.
 *
 * There is deliberately NO action button. The approved Pass 2A specimen draws one at a
 * placeholder destination; the internal review surface still does not exist, and a dead
 * link in an internal email is worse than no link.
 */
function renderInternalNotification(lead, config) {
  if (!lead) return { ok: false, permanent: true, reason: 'lead_missing' };

  var pathwayLabel = labelFor(PATHWAY_LABELS, lead.pathway, 'Inquiry');
  var headlineText = normalizeWhitespace(lead.fullName) +
    (normalizeWhitespace(lead.organization) ? ', ' + normalizeWhitespace(lead.organization) : '');

  var contactRows = [
    ['Name', lead.fullName],
    ['Email', lead.email || NOT_PROVIDED_LABEL, !lead.email],
    ['Phone', lead.phone || NOT_PROVIDED_LABEL, !lead.phone],
    ['Ownership group', lead.organization || NOT_PROVIDED_LABEL, !lead.organization],
    ['Preferred language', localeLabel(lead.preferredFollowUpLocale)]
  ];

  var body =
    block(eyebrow('New ' + pathwayLabel.toLowerCase() + ' request')) +
    block(headline(headlineText || 'New inquiry')) +
    block(panel('Contact', contactRows), 'padding-top:22px;');

  var propertyRows = [];
  if (lead.pathway === 'management_proposal') {
    propertyRows = [
      ['Property or portfolio', lead.propertyLocation || NOT_PROVIDED_LABEL, !lead.propertyLocation],
      ['Type', labelFor(PROPERTY_TYPE_LABELS, lead.propertyType)],
      ['Scope', labelFor(PROPERTY_SCOPE_LABELS, lead.propertyScope)],
      ['Units or square footage', lead.propertyScale || NOT_PROVIDED_LABEL, !lead.propertyScale],
      ['Current situation', labelFor(SITUATION_LABELS, lead.situationCurrent)],
      ['Service intent', labelFor(SERVICE_SCOPE_LABELS, lead.serviceScope)],
      ['Timing', labelFor(TIMING_LABELS, lead.situationTiming)]
    ];
    body += block(panel('Property', propertyRows), 'padding-top:16px;');
    if (normalizeWhitespace(lead.situationNotes)) {
      body += block(panel('In their words', [['Notes', lead.situationNotes]]), 'padding-top:16px;');
    }
  } else {
    propertyRows = [['Topic', labelFor(TOPIC_LABELS, lead.topic)]];
    body += block(panel('Request', propertyRows), 'padding-top:16px;');
  }

  var submissionRows = [
    ['Source', lead.sourceCategory === 'qr' ? 'QR card' : 'Website'],
    ['Landing page', lead.landingPage || NOT_PROVIDED_LABEL, !lead.landingPage],
    ['Response due', lead.slaDueAt ? formatInstant(lead.slaDueAt, config) : 'No commitment', !lead.slaDueAt],
    ['Current owner', ownerLabel(lead.ownerPartner)],
    ['Possible existing contact', lead.possibleMatches ? 'Yes, see the Contacts tab' : 'None', !lead.possibleMatches]
  ];
  body += block(panel('Submission', submissionRows), 'padding-top:16px;');
  body += block(note('Internal only. This message stays in English regardless of the visitor preferred language, which is shown above so the reply goes out in the right language.'));

  var subject = 'New ' + pathwayLabel.toLowerCase() + ' request';

  var text = [
    textRule(subject),
    headlineText,
    '',
    textRule('Contact'),
    contactRows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    '',
    textRule(lead.pathway === 'management_proposal' ? 'Property' : 'Request'),
    propertyRows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    normalizeWhitespace(lead.situationNotes) ? '\n' + textRule('In their words') + '\n' + textWrap(lead.situationNotes) : '',
    '',
    textRule('Submission'),
    submissionRows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    '',
    textWrap('Internal only. This message stays in English regardless of the visitor preferred language.')
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Internal notification',
      preheader: subject + ', ' + (lead.propertyLocation || 'website'),
      body: body,
      footerNote: 'Internal AxisPoint notification. Do not forward outside the firm.',
      footerLegal: 'Generated from a website submission.',
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}

/* ── 4. Daily QR Contact digest ───────────────────────────────────────────── */

/**
 * One digest part.
 *
 * `model` is produced by Digest.js and is already grouped, ordered, and split. This
 * function only renders; it makes no eligibility or routing decision, which is what
 * lets the splitting logic be tested without rendering and the rendering be tested
 * without a repository.
 */
function renderQrDigest(model, config) {
  var total = model.totalCount;
  var noun = total === 1 ? 'contact' : 'contacts';
  var partSuffix = model.partCount > 1 ? ', part ' + model.partIndex + ' of ' + model.partCount : '';

  var headlineText = total + ' new QR ' + noun + '.';
  var subject = 'Daily QR contact digest, ' + total + ' new ' + noun + partSuffix;

  var body =
    block(eyebrow('Internal, QR contacts')) +
    block(headline(headlineText)) +
    block(leadPara(model.windowLine));

  if (model.partCount > 1) {
    body += block(callout('info', '', 'Part ' + model.partIndex + ' of ' + model.partCount,
      'This window was split across ' + model.partCount + ' emails so nothing is clipped. No contact is split across parts.'), 'padding-top:16px;');
  }

  if (model.counts.length > 0) {
    body += block(panel('By contact category', model.counts.map(function (c) {
      return [c.label, String(c.count)];
    })), 'padding-top:22px;');
  }

  for (var g = 0; g < model.groups.length; g++) {
    var group = model.groups[g];
    body += block(groupHeading(group.title, group.sub), 'padding-top:24px;');
    for (var r = 0; r < group.records.length; r++) {
      body += block(digestRecordHtml(group.records[r]), 'padding-top:12px;');
    }
  }

  body += block('<div style="' + styleFont(13.5, 400, PALETTE.faint, 1.6) +
    'padding-top:16px;border-top:1px solid ' + PALETTE.hair + ';">' +
    esc('Every record above is a Contact. None is a Lead, none is assigned, and none has been contacted.') +
    '</div>', 'padding-top:24px;');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Internal, QR contacts',
      preheader: total + ' new ' + noun + '. All unassigned, none contacted.',
      body: body,
      footerNote: 'Internal distribution.',
      footerLegal: 'Sent at 8:00 AM America/Chicago. Nothing is sent on a day with no new contacts.',
      logoUrl: config.logoUrl
    }),
    textBody: digestText(model, headlineText, subject)
  };
}

/**
 * A digest record.
 *
 * SEVEN ROWS IN A FIXED ORDER, EVERY TIME. The order never changes, so a partner who
 * learned the shape on a one-contact day reads the same shape on a thirty-contact day.
 * Absent values print "Not provided" rather than disappearing, because here the absence
 * IS the information: an empty Email row is why no acknowledgement was sent.
 *
 * "Gathered through" and "Current owner" are separate rows and always both present.
 * Attribution is immutable; ownership is whatever is stored at generation time.
 */
function digestRecordHtml(rec) {
  // Font family is declared ONCE, on the cell that contains everything else, rather than
  // on all fourteen row cells. At thirty records the repeated stack alone was pushing the
  // email toward the Gmail clipping threshold, and the approved budget guidance names
  // reducing inline style repetition as the first lever before anything else changes.
  var out = '<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" ' +
    'style="width:100%;border:1px solid ' + PALETTE.hair + ';"><tr>' +
    '<td style="padding:16px 18px;font-family:' + FONT_BODY + ';">' +
    '<div style="font-size:17px;font-weight:700;line-height:1.35;color:' + PALETTE.ink +
    ';letter-spacing:-0.015em;word-break:break-word;">' + esc(rec.name) + '</div>';

  if (rec.org) {
    out += '<div style="font-size:14px;line-height:1.5;color:' + PALETTE.muted +
      ';padding-top:4px;word-break:break-word;">' + esc(rec.org) + '</div>';
  }

  if (rec.matchNote) {
    out += '<div style="padding-top:12px;">' +
      callout('match', '!', 'Possible existing contact', rec.matchNote) + '</div>';
  }

  out += '<div style="padding-top:12px;">' + digestRowsHtml([
    ['Category', rec.category, false],
    ['Email', rec.email || NOT_PROVIDED_LABEL, !rec.email],
    ['Phone', rec.phone || NOT_PROVIDED_LABEL, !rec.phone],
    ['Collected', rec.collected, false],
    ['Gathered through', rec.gatheredThrough, false],
    ['Current owner', rec.currentOwner, rec.currentOwner === UNASSIGNED_LABEL],
    ['Follow-up', rec.followUp, true]
  ]) + '</div>';

  return out + '</td></tr></table>';
}

/**
 * The seven rows, in the fixed order, rendered lean.
 *
 * The style strings are constants rather than built per row, and colour and font are
 * inherited from the enclosing cell. Every muted value still carries its own colour,
 * because "Not provided" and "Unassigned" are status words a reader must be able to see,
 * and the approved accessibility note is explicit that no status word may fade into
 * decoration.
 */
/*
 * Built INSIDE the function, not as top-level constants.
 *
 * PALETTE lives in Html.js, and Apps Script evaluates pushed files in an order this
 * repository does not control. A top-level `var X = '...' + PALETTE.faint` here throws
 * for every request and every trigger whenever Templates.js is evaluated first. That is
 * a full outage, and `deployability.test.js` loads src in reverse order precisely to
 * catch it.
 */
function digestRowStyles() {
  return {
    key: 'padding:7px 14px 7px 0;vertical-align:top;width:148px;font-size:13px;color:' +
      PALETTE.faint + ';',
    value: 'padding:7px 0;vertical-align:top;word-break:break-word;font-size:15px;' +
      'font-weight:600;color:' + PALETTE.ink + ';',
    valueMuted: 'padding:7px 0;vertical-align:top;word-break:break-word;font-size:15px;' +
      'font-weight:500;color:' + PALETTE.faint + ';',
    border: 'border-top:1px solid ' + PALETTE.hair + ';'
  };
}

function digestRowsHtml(rows) {
  var s = digestRowStyles();
  var out = '<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" ' +
    'style="width:100%;background:' + PALETTE.panel + ';border:1px solid ' + PALETTE.hair +
    ';padding:0;line-height:1.5;">';

  for (var i = 0; i < rows.length; i++) {
    var border = i === 0 ? '' : s.border;
    out += '<tr><td class="axp-k" style="' + border + s.key + '">' + esc(rows[i][0]) + '</td>' +
      '<td class="axp-v" style="' + border + (rows[i][2] ? s.valueMuted : s.value) + '">' +
      esc(rows[i][1]) + '</td></tr>';
  }
  return out + '</table>';
}

function digestText(model, headlineText, subject) {
  var lines = [textRule('Daily QR contact digest'), headlineText, model.windowLine, ''];

  if (model.partCount > 1) {
    lines.push('Part ' + model.partIndex + ' of ' + model.partCount + '. No contact is split across parts.');
    lines.push('');
  }

  if (model.counts.length > 0) {
    lines.push(textRule('By contact category'));
    model.counts.forEach(function (c) { lines.push('  ' + textRow(c.label, String(c.count), 40)); });
    lines.push('');
  }

  var n = 0;
  model.groups.forEach(function (group) {
    lines.push('=== ' + textRule(group.title) + ' ===');
    if (group.sub) lines.push(textWrap(group.sub));
    lines.push('');
    group.records.forEach(function (rec) {
      n += 1;
      lines.push(n + '. ' + escText(rec.name).toUpperCase());
      if (rec.org) lines.push('   ' + escText(rec.org));
      if (rec.matchNote) {
        lines.push('   ** POSSIBLE EXISTING CONTACT **');
        lines.push('   ' + textWrap(rec.matchNote, 58).split('\n').join('\n   '));
      }
      lines.push('   ' + textRow('Category', rec.category));
      lines.push('   ' + textRow('Email', rec.email || NOT_PROVIDED_LABEL));
      lines.push('   ' + textRow('Phone', rec.phone || NOT_PROVIDED_LABEL));
      lines.push('   ' + textRow('Collected', rec.collected));
      lines.push('   ' + textRow('Gathered through', rec.gatheredThrough));
      lines.push('   ' + textRow('Current owner', rec.currentOwner));
      lines.push('   ' + textRow('Follow-up', rec.followUp));
      if (!rec.email) lines.push('   Note: phone only. No acknowledgement email was sent.');
      lines.push('');
    });
  });

  lines.push(textWrap('Every record above is a Contact. None is a Lead, none is assigned, and none has been contacted.'));
  lines.push('');
  lines.push(textWrap('Sent at 8:00 AM America/Chicago. Nothing is sent on a day with no new contacts.'));
  return lines.join('\n');
}

/* ── 5. Booking confirmation ──────────────────────────────────────────────── */

/**
 * Sent ONLY after the Calendar service has confirmed the event exists.
 *
 * The approved Pass 2A source carries this template ("Call confirmed"), so it is
 * implemented. It is never rendered speculatively: Booking.js calls the calendar
 * synchronously and only a confirmed result reaches here, because a message headed
 * "You are on the calendar" that was sent before the calendar agreed is the single
 * worst thing this system could send.
 */
function renderBookingConfirmation(lead, booking, config) {
  if (!lead || !lead.email) return { ok: false, permanent: true, reason: 'no_recipient_address' };
  if (!booking || booking.status !== 'confirmed') {
    return { ok: false, permanent: true, reason: 'booking_not_confirmed' };
  }

  var first = firstNameOf(lead.fullName);
  var headlineText = first ? 'You are on the calendar, ' + first + '.' : 'You are on the calendar.';

  var rows = [
    ['When', formatInstant(booking.slotStart, config)],
    ['Format', labelFor(BOOKING_MODE_LABELS, booking.mode)],
    ['Length', booking.durationMinutes + ' minutes']
  ];

  var leadText = 'Here are the details. You can reply to this message if anything needs to change.';

  var body =
    block(eyebrow('Call confirmed')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    block(panel('Your call', rows), 'padding-top:22px;') +
    block(note('Nothing to prepare. If you already have a rent roll or operating statement at hand it can be useful, and if not the conversation works without it.'));

  var subject = 'Your call is confirmed';

  var text = [
    textRule(subject),
    '',
    headlineText,
    '',
    textWrap(leadText),
    '',
    textRule('Your call'),
    rows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    '',
    textWrap('Nothing to prepare. If you already have a rent roll or operating statement at hand it can be useful, and if not the conversation works without it.'),
    '',
    '--',
    FIRM_DISPLAY_NAME,
    FIRM_FOCUS
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Property Management',
      preheader: 'Your call is confirmed.',
      body: body,
      footerNote: 'You are receiving this because you scheduled a call with AxisPoint Partners.',
      footerLegal: 'Sent from Houston, Texas. You can reply to this message at any time.',
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}

/**
 * Human date and time with the zone NAMED IN WORDS.
 *
 * The zone is never omitted. A time without a zone in an email that crosses time zones
 * is an appointment somebody will miss, so if the offset cannot be resolved the ISO
 * instant is printed instead of a friendly-looking but ambiguous local time.
 */
function formatInstant(iso, config) {
  var d = parseIso(iso);
  if (!d) return String(iso || '');
  var resolver = (config && config.offsetResolver) || null;
  if (typeof resolver !== 'function') return d.toISOString();

  var local = new Date(d.getTime() + resolver(d) * 60000);
  var months = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  var days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

  var hour24 = local.getUTCHours();
  var suffix = hour24 >= 12 ? 'PM' : 'AM';
  var hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  var minutes = local.getUTCMinutes();
  var mm = minutes < 10 ? '0' + minutes : String(minutes);

  return days[local.getUTCDay()] + ', ' + months[local.getUTCMonth()] + ' ' + local.getUTCDate() +
    ', ' + local.getUTCFullYear() + ', ' + hour12 + ':' + mm + ' ' + suffix + ' Central Time';
}

/** Short form used inside a digest record, where the year is already in the window line. */
function formatCollected(iso, config) {
  var d = parseIso(iso);
  if (!d) return String(iso || '');
  var resolver = (config && config.offsetResolver) || null;
  if (typeof resolver !== 'function') return d.toISOString();

  var local = new Date(d.getTime() + resolver(d) * 60000);
  var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  var hour24 = local.getUTCHours();
  var suffix = hour24 >= 12 ? 'PM' : 'AM';
  var hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  var minutes = local.getUTCMinutes();
  var mm = minutes < 10 ? '0' + minutes : String(minutes);

  return months[local.getUTCMonth()] + ' ' + local.getUTCDate() + ', ' + hour12 + ':' + mm + ' ' + suffix + ' Central';
}

/** The template port implementation wired in production. */
/* ── Locale-aware visitor templates ───────────────────────────────────────── */

/**
 * The English visitor-facing template set.
 *
 * ENGLISH IS THE ONLY REAL SET, and that is the honest state: no professional translation
 * pass has happened. What changed is that selection is a lookup rather than a hardcoded
 * call, so adding a reviewed locale later means adding approved content instead of
 * rewriting dispatch.
 *
 * INTERNAL MAIL IS DELIBERATELY ABSENT. Partner notifications and the QR digest stay English
 * regardless of what the visitor asked for: they are read by the two partners, not by the
 * visitor, and they already display the visitor's preferred language as a field.
 */
function englishVisitorTemplates() {
  return {
    renderAcknowledgement: renderWebsiteAcknowledgement,
    renderQrAcknowledgement: renderQrAcknowledgement,
    renderBookingConfirmation: renderBookingConfirmation
  };
}

/**
 * THE ONE FALLBACK RULE: a renderer comes from the requested locale's set when that set
 * exists AND defines it; otherwise English.
 *
 * That covers both failure shapes with one rule. An unknown locale has no set, so English.
 * A supplied but incomplete set is missing this renderer, so English for this message while
 * its other messages still come from its own set. Falling back per renderer rather than per
 * locale is safe because each is a separate, self-contained email: an English booking
 * confirmation beside a translated acknowledgement is two correct messages, not one
 * half-translated one.
 */
function pickTemplate(sets, locale, name) {
  var wanted = sets[locale];
  if (wanted && typeof wanted[name] === 'function') return wanted[name];
  var english = sets.en;
  if (english && typeof english[name] === 'function') return english[name];
  return null;
}

/**
 * Builds the templates port.
 *
 * `extraLocaleSets` is the seam an approved translation plugs into, and it has no production
 * caller today. It replaced `registerVisitorTemplateSet` and `clearVisitorTemplateSet`,
 * which mutated module state that lives for the whole Apps Script execution. Shipping
 * test-only mutation into deployable source means production carries functions whose only
 * purpose is to let a test change global behaviour, and one stray call would swap a
 * visitor-facing template at runtime. Injection gives the same extension seam with nothing
 * mutable to reach: the sets are built per call and never written to again.
 */
function realTemplates(extraLocaleSets) {
  var sets = { en: englishVisitorTemplates() };
  if (extraLocaleSets) {
    Object.keys(extraLocaleSets).forEach(function (code) {
      sets[code] = extraLocaleSets[code];
    });
  }

  function visitor(name, locale) {
    return pickTemplate(sets, locale || 'en', name);
  }

  return {
    /*
     * Each visitor-facing renderer takes an OPTIONAL trailing locale. Optional on purpose:
     * every existing caller and test fake that passes nothing still gets English, so this
     * added a capability without breaking a contract.
     */
    renderAcknowledgement: function (lead, config, locale) {
      var fn = visitor('renderAcknowledgement', locale);
      if (!fn) return { ok: false, permanent: true, reason: 'template_missing' };
      return fn(lead, config);
    },
    renderQrAcknowledgement: function (contact, config, locale) {
      var fn = visitor('renderQrAcknowledgement', locale);
      if (!fn) return { ok: false, permanent: true, reason: 'template_missing' };
      return fn(contact, config);
    },
    renderBookingConfirmation: function (lead, booking, config, locale) {
      var fn = visitor('renderBookingConfirmation', locale);
      if (!fn) return { ok: false, permanent: true, reason: 'template_missing' };
      return fn(lead, booking, config);
    },

    // Internal, always English. No locale parameter, so no caller can ask for one.
    renderPartnerNotification: renderInternalNotification,
    renderQrDigest: renderQrDigest
  };
}
