/**
 * The booking confirmation.
 *
 * One pure function returning { ok, subject, htmlBody, textBody, icsContent, icsFilename }.
 * The plain-text part is written here as a specification, not generated by stripping tags.
 * Shared pieces live in EmailHelpers.js; the two rules that govern every template in this
 * folder are stated there.
 *
 * ICS helpers at the bottom generate a valid RFC 5545 iCalendar file attached to every
 * confirmed booking. The file opens correctly in Google Calendar, Outlook, and Apple
 * Calendar. For video_meeting bookings the Meet link appears in DESCRIPTION, LOCATION,
 * and URL fields and also in the email body.
 */

/**
 * Sent ONLY after the Calendar service has confirmed the event exists.
 *
 * The approved Pass 2A source carries this template ("Call confirmed"), so it is
 * implemented. It is never rendered speculatively: Booking.js calls the calendar
 * synchronously and only a confirmed result reaches here, because a message headed
 * "You are on the calendar" that was sent before the calendar agreed is the single
 * worst thing this system could send.
 */
function renderBookingConfirmation(lead, booking, config) {
  if (!lead || !lead.email) return { ok: false, permanent: true, reason: 'no_recipient_address' };
  if (!booking || booking.status !== 'confirmed') {
    return { ok: false, permanent: true, reason: 'booking_not_confirmed' };
  }

  var first = firstNameOf(lead.fullName);
  var headlineText = first ? 'You are on the calendar, ' + first + '.' : 'You are on the calendar.';

  var isVideo = booking.mode === 'video_meeting';
  var hasMeet = isVideo && booking.meetLink;

  var rows = [
    ['When', formatInstant(booking.slotStart, config)],
    ['Format', labelFor(BOOKING_MODE_LABELS, booking.mode)],
    ['Length', booking.durationMinutes + ' minutes']
  ];

  var leadText = 'Here are the details. You can reply to this message if anything needs to change.';

  var body =
    block(eyebrow('Call confirmed')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    block(panel('Your call', rows), 'padding-top:22px;');

  if (hasMeet) {
    body += block(meetLinkBlock(booking.meetLink), 'padding-top:20px;');
  }

  body += block(note('Nothing to prepare. If you already have a rent roll or operating statement at hand it can be useful, and if not the conversation works without it.'));

  var subject = 'Your call is confirmed';

  var textLines = [
    textRule(subject),
    '',
    headlineText,
    '',
    textWrap(leadText),
    '',
    textRule('Your call'),
    rows.map(function (r) { return textRow(r[0], r[1]); }).join('\n')
  ];

  if (hasMeet) {
    textLines.push('');
    textLines.push(textRule('Join Google Meet'));
    textLines.push(escText(booking.meetLink));
  }

  textLines.push('');
  textLines.push(textWrap('Nothing to prepare. If you already have a rent roll or operating statement at hand it can be useful, and if not the conversation works without it.'));
  textLines.push('');
  textLines.push('--');
  textLines.push(FIRM_DISPLAY_NAME);
  textLines.push(FIRM_FOCUS);

  var text = textLines.filter(function (l) { return l !== ''; }).join('\n');

  var slotEnd = toIso(addMinutes(parseIso(booking.slotStart), booking.durationMinutes));
  var icsContent = buildIcs({
    uid: lead.leadId + '@axispoint',
    summary: isVideo ? 'AxisPoint video meeting' : 'AxisPoint call',
    description: hasMeet
      ? 'Join Google Meet: ' + booking.meetLink
      : 'Your call with AxisPoint Partners.',
    location: hasMeet ? booking.meetLink : '',
    url: hasMeet ? booking.meetLink : '',
    dtstart: booking.slotStart,
    dtend: slotEnd
  });

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Property Management',
      preheader: 'Your call is confirmed.',
      body: body,
      footerNote: 'You are receiving this because you scheduled a call with AxisPoint Partners.',
      footerLegal: 'Sent from Houston, Texas. You can reply to this message at any time.',
      logoUrl: config.logoUrl
    }),
    textBody: text,
    icsContent: icsContent,
    icsFilename: 'booking.ics'
  };
}

/**
 * The Meet link section rendered in the email body for video_meeting bookings.
 *
 * The link is safe to use as both the href destination and the display text because
 * esc() encodes it for an HTML attribute and a text node in one pass. The browser
 * decodes &#47; back to / in the href, so the URL remains valid.
 */
function meetLinkBlock(meetLink) {
  var PALETTE_TEAL = '#24A5BC';
  var PALETTE_TEAL_DEEP = '#1B8DA2';
  var FONT_BODY_LOCAL = "'Figtree', Arial, Helvetica, sans-serif";

  return '<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" ' +
    'style="width:100%;background:rgba(36,165,188,0.09);border:1px solid ' + PALETTE_TEAL + ';border-left:3px solid ' + PALETTE_TEAL + ';">' +
    '<tr><td style="padding:14px 16px;">' +
    '<div style="font-family:' + FONT_BODY_LOCAL + ';font-size:14.5px;font-weight:700;color:#1C1628;line-height:1.45;">Join Google Meet</div>' +
    '<div style="font-family:' + FONT_BODY_LOCAL + ';font-size:14px;font-weight:400;color:rgba(28,22,40,0.68);line-height:1.6;padding-top:4px;">' +
    '<a href="' + esc(meetLink) + '" style="color:' + PALETTE_TEAL_DEEP + ';text-decoration:none;word-break:break-all;">' +
    esc(meetLink) + '</a>' +
    '</div>' +
    '</td></tr></table>';
}

/* ── ICS (RFC 5545) helpers ────────────────────────────────────────────────── */

/**
 * Generates a complete, spec-compliant iCalendar string for one VEVENT.
 *
 * - Line endings: CRLF (required by RFC 5545 §3.1)
 * - Line folding: lines exceeding 75 octets are folded with CRLF + SPACE
 * - Property values: commas, semicolons, backslashes, and newlines are escaped
 * - DTSTAMP: the current UTC instant (valid per RFC 5545; not stored so replays differ)
 * - METHOD:PUBLISH: signals this is a one-way notification, not an invite
 */
function buildIcs(spec) {
  var CRLF = '\r\n';
  var now = new Date();

  var lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//AxisPoint Partners//Booking Confirmation//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    'UID:' + icsEscapeValue(spec.uid),
    'DTSTAMP:' + icsDateTimeUtc(now),
    'DTSTART:' + icsDateTimeUtc(new Date(spec.dtstart)),
    'DTEND:' + icsDateTimeUtc(new Date(spec.dtend)),
    'SUMMARY:' + icsEscapeValue(spec.summary)
  ];

  if (spec.description) {
    lines.push('DESCRIPTION:' + icsEscapeValue(spec.description));
  }
  if (spec.location) {
    lines.push('LOCATION:' + icsEscapeValue(spec.location));
  }
  if (spec.url) {
    lines.push('URL:' + spec.url);
  }

  lines.push('END:VEVENT');
  lines.push('END:VCALENDAR');

  return lines.map(function (line) { return icsFold(line, CRLF); }).join('');
}

/** Format a JS Date as YYYYMMDDTHHMMSSZ (UTC, per RFC 5545). */
function icsDateTimeUtc(date) {
  var d = date instanceof Date ? date : new Date(date);
  var pad = function (n) { return n < 10 ? '0' + n : '' + n; };
  return '' + d.getUTCFullYear() +
    pad(d.getUTCMonth() + 1) +
    pad(d.getUTCDate()) +
    'T' +
    pad(d.getUTCHours()) +
    pad(d.getUTCMinutes()) +
    pad(d.getUTCSeconds()) +
    'Z';
}

/**
 * Escape a property value per RFC 5545 §3.3.11 (TEXT type).
 *
 * Backslashes must be escaped first to avoid double-escaping the others.
 */
function icsEscapeValue(value) {
  return String(value === null || value === undefined ? '' : value)
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r\n/g, '\\n')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\n');
}

/**
 * Fold a property line at 75 octets per RFC 5545 §3.1.
 *
 * For ASCII content (which all our values are after escaping), octets == characters.
 * Each continuation line is prefixed with a single SPACE.
 */
function icsFold(line, CRLF) {
  if (line.length <= 75) return line + CRLF;
  var result = line.slice(0, 75) + CRLF;
  var pos = 75;
  while (pos < line.length) {
    result += ' ' + line.slice(pos, pos + 74) + CRLF;
    pos += 74;
  }
  return result;
}
