/**
 * The booking confirmation.
 *
 * One pure function returning { ok, subject, htmlBody, textBody }. The plain-text part is
 * written here as a specification, not generated by stripping tags. Shared pieces live in
 * EmailHelpers.js; the two rules that govern every template in this folder are stated there.
 */

/**
 * Sent ONLY after the Calendar service has confirmed the event exists.
 *
 * The approved Pass 2A source carries this template ("Call confirmed"), so it is
 * implemented. It is never rendered speculatively: Booking.js calls the calendar
 * synchronously and only a confirmed result reaches here, because a message headed
 * "You are on the calendar" that was sent before the calendar agreed is the single
 * worst thing this system could send.
 */
function renderBookingConfirmation(lead, booking, config) {
  if (!lead || !lead.email) return { ok: false, permanent: true, reason: 'no_recipient_address' };
  if (!booking || booking.status !== 'confirmed') {
    return { ok: false, permanent: true, reason: 'booking_not_confirmed' };
  }

  var first = firstNameOf(lead.fullName);
  var headlineText = first ? 'You are on the calendar, ' + first + '.' : 'You are on the calendar.';

  var rows = [
    ['When', formatInstant(booking.slotStart, config)],
    ['Format', labelFor(BOOKING_MODE_LABELS, booking.mode)],
    ['Length', booking.durationMinutes + ' minutes']
  ];

  var leadText = 'Here are the details. You can reply to this message if anything needs to change.';

  var body =
    block(eyebrow('Call confirmed')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    block(panel('Your call', rows), 'padding-top:22px;') +
    block(note('Nothing to prepare. If you already have a rent roll or operating statement at hand it can be useful, and if not the conversation works without it.'));

  var subject = 'Your call is confirmed';

  var text = [
    textRule(subject),
    '',
    headlineText,
    '',
    textWrap(leadText),
    '',
    textRule('Your call'),
    rows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    '',
    textWrap('Nothing to prepare. If you already have a rent roll or operating statement at hand it can be useful, and if not the conversation works without it.'),
    '',
    '--',
    FIRM_DISPLAY_NAME,
    FIRM_FOCUS
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Property Management',
      preheader: 'Your call is confirmed.',
      body: body,
      footerNote: 'You are receiving this because you scheduled a call with AxisPoint Partners.',
      footerLegal: 'Sent from Houston, Texas. You can reply to this message at any time.',
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}
