/**
 * Pieces more than one V2 email template needs.
 *
 * This file was `Templates.js` until the renderers moved into one file each; it keeps the
 * doctrine that governs all of them, plus the helpers they share. It renders no message on
 * its own. **Do not add a second copy of anything here to a renderer file.** V1's templates
 * existed in two hand-synced copies and the two drifted silently until a parity test caught
 * it; one copy of each piece, called across files, is the whole point of the arrangement.
 *
 * Apps Script concatenates every pushed file into ONE global scope, so a renderer in a
 * sibling file calls `firstNameOf` by bare name with no import, and nothing here may read a
 * value from another file at load time.
 *
 * Every renderer returns { ok, subject, htmlBody, textBody }, and its plain-text part is
 * WRITTEN as a specification rather than generated by stripping tags, because the design
 * treats it as the real second half of a multipart alternative: a partner has to be able to
 * work a whole digest from the text part alone.
 *
 * TWO RULES RUN THROUGH EVERY TEMPLATE IN THIS FOLDER.
 *
 * 1. Human labels, never wire tokens. `property_owner_operator` is a storage value.
 *    See Labels.js.
 *
 * 2. Missing optional values DISAPPEAR rather than rendering empty. A row that must
 *    exist but has no verified value is omitted, never shown blank and never filled
 *    with an invented placeholder. The single exception is the digest, where "Not
 *    provided" is itself information: an empty Email row is the signal that no
 *    acknowledgement could be sent.
 *
 * Nothing in this folder contains a tracking pixel, an open-tracking image, a click-wrapped
 * link, marketing enrollment, nurture language, or a preference centre. These are
 * transactional messages.
 */

var FIRM_DISPLAY_NAME = 'AxisPoint Partners';
var FIRM_FOCUS = 'Property Management, Houston, Texas';

function firstNameOf(fullName) {
  var n = normalizeWhitespace(fullName);
  if (n === '') return '';
  return n.split(' ')[0];
}

/** Adds a row only when the value is present. Optional values disappear cleanly. */
function pushRow(rows, key, value) {
  var v = normalizeWhitespace(value);
  if (v !== '') rows.push([key, v]);
}

/**
 * Human date and time with the zone NAMED IN WORDS.
 *
 * The zone is never omitted. A time without a zone in an email that crosses time zones
 * is an appointment somebody will miss, so if the offset cannot be resolved the ISO
 * instant is printed instead of a friendly-looking but ambiguous local time.
 */
function formatInstant(iso, config) {
  var d = parseIso(iso);
  if (!d) return String(iso || '');
  var resolver = (config && config.offsetResolver) || null;
  if (typeof resolver !== 'function') return d.toISOString();

  var local = new Date(d.getTime() + resolver(d) * 60000);
  var months = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  var days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

  var hour24 = local.getUTCHours();
  var suffix = hour24 >= 12 ? 'PM' : 'AM';
  var hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  var minutes = local.getUTCMinutes();
  var mm = minutes < 10 ? '0' + minutes : String(minutes);

  return days[local.getUTCDay()] + ', ' + months[local.getUTCMonth()] + ' ' + local.getUTCDate() +
    ', ' + local.getUTCFullYear() + ', ' + hour12 + ':' + mm + ' ' + suffix + ' Central Time';
}

/** Short form used inside a digest record, where the year is already in the window line. */
function formatCollected(iso, config) {
  var d = parseIso(iso);
  if (!d) return String(iso || '');
  var resolver = (config && config.offsetResolver) || null;
  if (typeof resolver !== 'function') return d.toISOString();

  var local = new Date(d.getTime() + resolver(d) * 60000);
  var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  var hour24 = local.getUTCHours();
  var suffix = hour24 >= 12 ? 'PM' : 'AM';
  var hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  var minutes = local.getUTCMinutes();
  var mm = minutes < 10 ? '0' + minutes : String(minutes);

  return months[local.getUTCMonth()] + ' ' + local.getUTCDate() + ', ' + hour12 + ':' + mm + ' ' + suffix + ' Central';
}
