/**
 * The internal website inquiry notification.
 *
 * One pure function returning { ok, subject, htmlBody, textBody }. The plain-text part is
 * written here as a specification, not generated by stripping tags. Shared pieces live in
 * EmailHelpers.js; the two rules that govern every template in this folder are stated there.
 */

/**
 * Sent to the partners immediately when a website service inquiry arrives.
 *
 * Website inquiries keep IMMEDIATE notification. Only QR Contacts moved to the daily
 * digest, because a scanned card is an acquisition record and an inquiry is a request
 * with a clock running on it.
 *
 * There is deliberately NO action button. The approved Pass 2A specimen draws one at a
 * placeholder destination; the internal review surface still does not exist, and a dead
 * link in an internal email is worse than no link.
 */
function renderInternalNotification(lead, config) {
  if (!lead) return { ok: false, permanent: true, reason: 'lead_missing' };

  var pathwayLabel = labelFor(PATHWAY_LABELS, lead.pathway, 'Inquiry');
  var headlineText = normalizeWhitespace(lead.fullName) +
    (normalizeWhitespace(lead.organization) ? ', ' + normalizeWhitespace(lead.organization) : '');

  var contactRows = [
    ['Name', lead.fullName],
    ['Email', lead.email || NOT_PROVIDED_LABEL, !lead.email],
    ['Phone', lead.phone || NOT_PROVIDED_LABEL, !lead.phone],
    ['Ownership group', lead.organization || NOT_PROVIDED_LABEL, !lead.organization],
    ['Preferred language', localeLabel(lead.preferredFollowUpLocale)]
  ];

  var body =
    block(eyebrow('New ' + pathwayLabel.toLowerCase() + ' request')) +
    block(headline(headlineText || 'New inquiry')) +
    block(panel('Contact', contactRows), 'padding-top:22px;');

  var propertyRows = [];
  if (lead.pathway === 'management_proposal') {
    propertyRows = [
      ['Property or portfolio', lead.propertyLocation || NOT_PROVIDED_LABEL, !lead.propertyLocation],
      ['Type', labelFor(PROPERTY_TYPE_LABELS, lead.propertyType)],
      ['Scope', labelFor(PROPERTY_SCOPE_LABELS, lead.propertyScope)],
      ['Units or square footage', lead.propertyScale || NOT_PROVIDED_LABEL, !lead.propertyScale],
      ['Current situation', labelFor(SITUATION_LABELS, lead.situationCurrent)],
      ['Service intent', labelFor(SERVICE_SCOPE_LABELS, lead.serviceScope)],
      ['Timing', labelFor(TIMING_LABELS, lead.situationTiming)]
    ];
    body += block(panel('Property', propertyRows), 'padding-top:16px;');
    if (normalizeWhitespace(lead.situationNotes)) {
      body += block(panel('In their words', [['Notes', lead.situationNotes]]), 'padding-top:16px;');
    }
  } else {
    propertyRows = [['Topic', labelFor(TOPIC_LABELS, lead.topic)]];
    body += block(panel('Request', propertyRows), 'padding-top:16px;');
  }

  var submissionRows = [
    ['Source', lead.sourceCategory === 'qr' ? 'QR card' : 'Website'],
    ['Landing page', lead.landingPage || NOT_PROVIDED_LABEL, !lead.landingPage],
    ['Response due', lead.slaDueAt ? formatInstant(lead.slaDueAt, config) : 'No commitment', !lead.slaDueAt],
    ['Current owner', ownerLabel(lead.ownerPartner)],
    ['Possible existing contact', lead.possibleMatches ? 'Yes, see the Contacts tab' : 'None', !lead.possibleMatches]
  ];
  body += block(panel('Submission', submissionRows), 'padding-top:16px;');
  body += block(note('Internal only. This message stays in English regardless of the visitor preferred language, which is shown above so the reply goes out in the right language.'));

  var subject = 'New ' + pathwayLabel.toLowerCase() + ' request';

  var text = [
    textRule(subject),
    headlineText,
    '',
    textRule('Contact'),
    contactRows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    '',
    textRule(lead.pathway === 'management_proposal' ? 'Property' : 'Request'),
    propertyRows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    normalizeWhitespace(lead.situationNotes) ? '\n' + textRule('In their words') + '\n' + textWrap(lead.situationNotes) : '',
    '',
    textRule('Submission'),
    submissionRows.map(function (r) { return textRow(r[0], r[1]); }).join('\n'),
    '',
    textWrap('Internal only. This message stays in English regardless of the visitor preferred language.')
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Internal notification',
      preheader: subject + ', ' + (lead.propertyLocation || 'website'),
      body: body,
      footerNote: 'Internal AxisPoint notification. Do not forward outside the firm.',
      footerLegal: 'Generated from a website submission.',
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}
