/**
 * The QR Contact acknowledgement, and the identity block it prints.
 *
 * One pure function returning { ok, subject, htmlBody, textBody }. The plain-text part is
 * written here as a specification, not generated by stripping tags. Shared pieces live in
 * EmailHelpers.js; the two rules that govern every template in this folder are stated there.
 */

/*
 * THE QR ACKNOWLEDGEMENT MAKES NO CORRECTION OR REMOVAL PROMISE, AND MUST NOT.
 *
 * It used to carry a gated block saying a reply would update or delete someone's record,
 * rendered only when two Script Properties confirmed a monitored mailbox and a written
 * procedure existed. Neither is offered as a feature, so the promise, its two gates, and
 * the reply invitation in the footer were removed outright rather than left switchable.
 * Do not reintroduce copy inviting a reply to correct or remove a record without a real
 * procedure behind it: the reason the gate existed is the reason the copy is gone.
 */
var QR_ACK_FOOTER_LEGAL = 'Sent from Houston, Texas.';

/**
 * Who the acknowledgement says has the details.
 *
 * Falls back to the firm whenever the partner's own direct address is not configured,
 * because a partner block with no way to reach that partner is worse than the firm
 * block, which at least resolves.
 */
function acknowledgementIdentity(acquisitionSource, config) {
  var isPartner = PARTNERS.indexOf(acquisitionSource) !== -1;
  var directEmail = isPartner ? (config.partnerDirectEmail || {})[acquisitionSource] : '';

  if (isPartner && directEmail) {
    return {
      isPartner: true,
      name: PARTNER_LABELS[acquisitionSource],
      title: 'Partner, AxisPoint Partners',
      email: directEmail,
      phone: (config.partnerDirectPhone || {})[acquisitionSource] || '',
      website: config.websiteUrl || ''
    };
  }

  return {
    isPartner: false,
    name: FIRM_DISPLAY_NAME,
    title: FIRM_FOCUS,
    email: config.firmEmail || '',
    phone: config.firmPhone || '',
    website: config.websiteUrl || ''
  };
}

/** Rows for the "who you connected with" panel. Unverified rows are omitted. */
function identityRows(identity) {
  var rows = [[identity.isPartner ? 'Name' : 'Name', identity.name]];
  rows.push([identity.isPartner ? 'Title' : 'Focus', identity.title]);
  if (identity.email) rows.push(['Email', identity.email]);
  if (identity.phone) rows.push(['Phone', identity.phone]);
  if (identity.website) rows.push(['Website', identity.website]);
  return rows;
}

function identityTextRows(identity) {
  var out = [textRow('Name', identity.name), textRow(identity.isPartner ? 'Title' : 'Focus', identity.title)];
  if (identity.email) out.push(textRow('Email', identity.email));
  if (identity.phone) out.push(textRow('Phone', identity.phone));
  if (identity.website) out.push(textRow('Website', identity.website));
  return out.join('\n');
}

/**
 * Sent to the person who shared their details from a scanned card.
 *
 * DATA MINIMIZATION IS THE SHAPE OF THIS EMAIL. The submitted address has not been
 * verified as belonging to the person who typed it, so the DISPLAY NAME is the only
 * submitted value that appears anywhere in it. Phone, company, role, and category are
 * never echoed. Echoing an unverified record back would mail somebody else's phone
 * number to whoever the address actually belongs to.
 *
 * There is also no button. The approved shell allows one dominant action and this
 * message has nothing for the recipient to do; a Save Contact action is deliberately
 * withheld until a permanent profile URL or a verified vCard delivery method exists.
 */
function renderQrAcknowledgement(contact, config) {
  if (!contact || !contact.email) {
    return { ok: false, permanent: true, reason: 'no_recipient_address' };
  }

  var identity = acknowledgementIdentity(contact.acquisitionSource, config);
  if (!identity.email) {
    return { ok: false, permanent: true, reason: 'no_verified_sender_identity' };
  }

  var first = firstNameOf(contact.fullName);
  var greeting = first ? 'Thank you, ' + first + '.' : 'Thank you.';
  var headlineText = greeting + ' Your details are with ' + identity.name + '.';

  var leadText = identity.isPartner
    ? 'You shared your contact information from ' + identity.name +
      "'s AxisPoint card. It has been received. Nothing further is needed from you."
    : 'You shared your contact information from an AxisPoint card that did not resolve to a ' +
      'partner profile. It has been received by AxisPoint Partners. Nothing further is needed from you.';

  var receipt = identity.isPartner
    ? 'Received and stored. They are not repeated in this email, because this address has not been verified as yours.'
    : 'Received and stored by AxisPoint Partners. They are not repeated in this email, because this address has not been verified as yours.';

  var body =
    block(eyebrow('Your details were received')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    block(panel('Your contact details', [['Status', receipt, true]]), 'padding-top:22px;') +
    block(panel(identity.isPartner ? 'Who you connected with' : 'Who has your details', identityRows(identity)), 'padding-top:16px;') +
    block(callout('info', '', 'This is not a mailing list',
      'Sharing your details from a card does not subscribe you to anything. They are used only to follow up on the conversation you had.'), 'padding-top:16px;') +
    block(signatureHtml(identity), 'padding-top:20px;');

  var subject = identity.name + ' has your contact details';

  var text = [
    textRule(subject),
    '',
    greeting,
    '',
    textWrap(leadText),
    '',
    textRule('Your contact details'),
    textWrap(receipt),
    '',
    textRule(identity.isPartner ? 'Who you connected with' : 'Who has your details'),
    identityTextRows(identity),
    '',
    textRule('This is not a mailing list'),
    textWrap('Sharing your details from a card does not subscribe you to anything. They are used only to follow up on the conversation you had.'),
    '--',
    identity.name,
    identity.title,
    identity.email,
    identity.phone || '',
    identity.website || '',
    '',
    FIRM_DISPLAY_NAME + ' | Houston, Texas',
    textWrap('You are receiving this because you shared your details from an AxisPoint card.')
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: 'Contact exchange',
      preheader: 'Your contact details were received.',
      body: body,
      footerNote: 'You are receiving this because you shared your details from an AxisPoint card.',
      footerLegal: QR_ACK_FOOTER_LEGAL,
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}

function signatureHtml(identity) {
  var out = '<div style="border-top:1px solid ' + PALETTE.hair + ';padding-top:18px;">' +
    '<div style="' + styleFont(16, 700, PALETTE.ink, 1.4) + 'letter-spacing:-0.01em;">' + esc(identity.name) + '</div>' +
    '<div style="' + styleFont(14, 400, PALETTE.muted, 1.5) + 'padding-top:2px;">' + esc(identity.title) + '</div>';
  if (identity.email) {
    out += '<div style="' + styleFont(14, 600, PALETTE.tealDeep, 1.5) + 'padding-top:8px;">' + esc(identity.email) + '</div>';
  }
  if (identity.phone) {
    out += '<div style="' + styleFont(14, 400, PALETTE.muted, 1.5) + '">' + esc(identity.phone) + '</div>';
  }
  if (identity.website) {
    out += '<div style="' + styleFont(14, 400, PALETTE.muted, 1.5) + '">' + esc(identity.website) + ', Houston, Texas</div>';
  }
  return out + '</div>';
}
