/**
 * The website inquiry acknowledgement.
 *
 * One pure function returning { ok, subject, htmlBody, textBody }. The plain-text part is
 * written here as a specification, not generated by stripping tags. Shared pieces live in
 * EmailHelpers.js; the two rules that govern every template in this folder are stated there.
 */

/**
 * Sent to somebody who submitted a service inquiry on the website.
 *
 * Unlike the QR acknowledgement this one DOES repeat the submission back, because the
 * person deliberately described a property and the repetition is the proof that a human
 * will read it. It still carries no response-time promise beyond what the SLA policy
 * actually commits to, and it makes no claim about who will reply.
 */
function renderWebsiteAcknowledgement(lead, config) {
  if (!lead || !lead.email) return { ok: false, permanent: true, reason: 'no_recipient_address' };

  var first = firstNameOf(lead.fullName);
  var isProposal = lead.pathway === 'management_proposal';
  var isInvestor = lead.pathway === 'investor_services';

  var headlineText = (first ? 'Thank you, ' + first + '. ' : 'Thank you. ') +
    (isProposal ? 'We have your property details.' : 'We have your message.');

  var headerMeta = labelFor(PATHWAY_LABELS, lead.pathway, 'Your inquiry');
  var preheader = isProposal
    ? 'We have your details. Here is what happens next.'
    : 'We have your message. A Partner will be in touch.';
  var footerNote = isProposal
    ? 'You are receiving this because you contacted AxisPoint Partners about property management.'
    : isInvestor
      ? 'You are receiving this because you contacted AxisPoint Partners about investor services.'
      : 'You are receiving this because you contacted AxisPoint Partners.';

  var rows = [];
  if (isProposal) {
    pushRow(rows, 'Property or portfolio', lead.propertyLocation);
    pushRow(rows, 'Type', labelFor(PROPERTY_TYPE_LABELS, lead.propertyType, ''));
    pushRow(rows, 'Scope', labelFor(PROPERTY_SCOPE_LABELS, lead.propertyScope, ''));
    pushRow(rows, 'Units or square footage', lead.propertyScaleUnknown === true || lead.propertyScaleUnknown === 'TRUE' ? '' : lead.propertyScale);
    pushRow(rows, 'Ownership group', lead.organization);
    pushRow(rows, 'Service interest', labelFor(SERVICE_SCOPE_LABELS, lead.serviceScope, ''));
    pushRow(rows, 'Timing', labelFor(TIMING_LABELS, lead.situationTiming, ''));
  } else {
    pushRow(rows, 'Pathway', labelFor(PATHWAY_LABELS, lead.pathway, ''));
    pushRow(rows, 'Topic', labelFor(TOPIC_LABELS, lead.topic, ''));
    pushRow(rows, 'Ownership group', lead.organization);
  }

  var leadText = 'A Partner will review what you sent and reply to you. This message confirms what reached us.';

  var body =
    block(eyebrow('Your request')) +
    block(headline(headlineText)) +
    block(leadPara(leadText)) +
    (rows.length > 0
      ? block(panel(isProposal ? 'The property' : 'What you sent', rows), 'padding-top:22px;')
      : '') +
    block(para('You can reply to this message with anything you would like to add.'));

  var subject = isProposal
    ? 'We have your property details'
    : 'We have your message';

  var textRows = rows.map(function (r) { return textRow(r[0], r[1]); }).join('\n');

  var text = [
    textRule(subject),
    '',
    headlineText,
    '',
    textWrap(leadText),
    '',
    rows.length > 0 ? textRule(isProposal ? 'The property' : 'What you sent') : '',
    textRows,
    '',
    textWrap('You can reply to this message with anything you would like to add.'),
    '',
    '--',
    FIRM_DISPLAY_NAME,
    FIRM_FOCUS
  ].filter(function (l) { return l !== ''; }).join('\n');

  return {
    ok: true,
    subject: escSubject(subject),
    htmlBody: shell({
      title: subject,
      headerMeta: headerMeta,
      preheader: preheader,
      body: body,
      footerNote: footerNote,
      footerLegal: 'Sent from Houston, Texas. You can reply to this message with anything you would like to add.',
      logoUrl: config.logoUrl
    }),
    textBody: text
  };
}
