import type { Messages } from '../../messages';

/**
 * SPANISH. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Spanish has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready. Do not describe it
 * as any of those things.
 *
 * WHAT IT IS FOR. Giving a native reader something concrete to correct, and letting the
 * localization machinery be exercised end to end in local preview before any translation
 * budget is committed. A wrong sentence a reviewer can strike out is more useful than a
 * blank they have to compose into.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors:
 *   1. `es` is `enabled: false, review: 'unreviewed'` in `../../locales.ts`, so the selector
 *      never offers it, no route resolves to it, and no `hreflang` entry names it.
 *   2. This directory leaves the module graph in every build. Only a running dev server can
 *      reach it. See `apps/web/vite.config.ts` and `../none.ts`.
 *
 * PROMOTION is described in `../reviewed/index.ts`. It requires a native reader's
 * corrections. Moving the file is the last step, not the first.
 *
 * REGISTER. Formal `usted` throughout, matching the English copy's direct, professional
 * tone. A reviewer should check that choice first: it is the decision most likely to be
 * wrong for the intended Houston readership, and it affects nearly every string here.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const ES: Partial<Messages> = {
  gatewayTitle: '¿Qué le gustaría tratar?',
  gatewayLead: 'Elija la opción que mejor se ajuste a su situación. Puede cambiarla más adelante.',
  gatewayOwnerKicker: 'La mayoría de los propietarios empieza aquí',
  gatewayOwnerTitle: 'Propietario',
  gatewayOwnerBody: 'Soy propietario o superviso una propiedad y necesito administración.',
  gatewayOwnerAction: 'Comenzar con los datos de la propiedad',
  gatewayAssetTitle: 'Gestión de activos',
  gatewayAssetBody:
    'Soy propietario y quiero ayuda para dirigir la estrategia, el rendimiento y los informes.',
  gatewayInvestorTitle: 'Servicios para inversionistas',
  gatewayInvestorBody:
    'Me preparo para adquirir bienes raíces comerciales y necesito un equipo operativo.',
  gatewayGeneralTitle: 'Consulta general',
  gatewayGeneralBody: 'Otro asunto. Proveedores, prensa, empleo o una pregunta.',

  propertyTypeMultifamily: 'Multifamiliar',
  propertyTypeRetail: 'Comercial minorista',
  propertyTypeMixedPortfolio: 'Cartera mixta',
  propertyTypeAnother: 'Otro tipo de propiedad',
  propertyScopeOne: 'Una propiedad',
  propertyScopePortfolio: 'Cartera',

  situationReplace: 'Reemplazar la administración actual',
  situationMoveAway: 'Dejar de autoadministrar',
  situationRecentlyAcquired: 'Adquirida recientemente o bajo contrato',
  situationLeaseUp: 'Ocupación inicial o recuperación',
  situationOperations: 'Problemas de operación o de informes',
  situationExploring: 'Explorando opciones de administración',
  situationSomethingElse: 'Otra cosa',

  involvementPm: 'Administración de propiedades',
  involvementPmHint: 'Operar la propiedad en el día a día.',
  involvementPmAm: 'Administración de propiedades + Gestión de activos',
  involvementPmAmHint: 'Operar la propiedad y ayudar a dirigir la estrategia de inversión.',
  involvementNotSure: 'No estoy seguro',
  involvementNotSureHint: 'Ayúdenme a determinar el nivel de participación adecuado.',

  timingImmediately: 'De inmediato',
  timingWithin30: 'Dentro de 30 días',
  timing30to60: 'De 30 a 60 días',
  timing60to90: 'De 60 a 90 días',
  timingStillExploring: 'Todavía explorando',

  investorTopicFirstAcquisition: 'Explorando mi primera adquisición',
  investorTopicUnderContract: 'Bajo contrato ahora',
  investorTopicActivelySearching: 'Buscando activamente',
  investorTopicOwnProperty: 'Tengo propiedad y necesito un equipo operativo',
  investorTopicSomethingElse: 'Otra cosa',
  generalTopicQuestion: 'Una pregunta sobre AxisPoint',
  generalTopicVendor: 'Proveedor o prestador de servicios',
  generalTopicEmployment: 'Empleo',
  generalTopicPress: 'Prensa o medios',
  generalTopicSomethingElse: 'Otra cosa',

  bookingModePhone: 'Llamada telefónica',
  bookingModeVideo: 'Videoconferencia',

  scaleUnitsLabel: 'Unidades aproximadas',
  scaleUnitsPlaceholder: 'Por ejemplo 184',
  scaleUnitsHelp:
    'Una cifra redonda es suficiente. Estamos dimensionando el equipo operativo, no auditando el registro de rentas.',
  scaleSqftLabel: 'Superficie aproximada en pies cuadrados',
  scaleSqftPlaceholder: 'Por ejemplo 42,000',
  scaleSqftHelp: 'El área bruta arrendable es la cifra más útil aquí.',
  scaleMixedLabel: 'Escala combinada aproximada',
  scaleMixedPlaceholder: 'Por ejemplo 300 unidades y 40,000 pies cuadrados',
  scaleMixedHelp:
    'Unidades, pies cuadrados o ambos. Indíquenos la cifra en los términos que usted maneje.',
  scaleOtherLabel: 'Escala aproximada',
  scaleOtherPlaceholder: 'Unidades, pies cuadrados u otra medida',
  scaleOtherHelp:
    'Describa el tamaño en los términos que tengan sentido para este tipo de propiedad.',
  scaleFallbackLabel: 'Escala aproximada',
  scaleFallbackPlaceholder: 'Unidades o pies cuadrados',
  scaleFallbackHelp: 'Elija un tipo de propiedad arriba y esto se adapta a la medida correcta.',

  investorKicker: 'Servicios para inversionistas',
  investorTitle: 'Cuéntenos en qué punto del proceso se encuentra.',
  investorLead:
    'Con una nota breve basta para empezar. Nos pondremos en contacto para concertar una conversación.',
  investorTopicLabel: '¿En qué punto del proceso se encuentra?',
  investorNoteLabel: '¿Qué está considerando?',
  investorNotePlaceholder: 'Tipo de activo, mercado o plazo',
  generalKicker: 'Consulta general',
  generalTitle: '¿En qué podemos ayudarle?',
  generalLead: 'Díganos quién es y qué necesita. Lo dirigiremos al socio adecuado.',
  generalTopicLabel: '¿De qué se trata?',
  generalNoteLabel: 'Su mensaje',
  generalNotePlaceholder: 'Con unas pocas frases basta',
  // Mirrors the English `SHORT_PATHS` value, which is the short 'Company' and NOT the
  // management-proposal field's longer label. Keep them distinct here too.
  organizationLabel: 'Empresa',
  submitLabel: 'Enviar consulta',

  nameHelp: 'Como le gustaría que nos dirijamos a usted.',
  nameError: 'Indique el nombre por el que debemos preguntar cuando llamemos.',
  emailHelp: 'Donde enviaremos nuestra respuesta y cualquier detalle de seguimiento.',
  emailError:
    'A esta dirección le falta la parte que va después del signo @. Agregue la dirección completa, por ejemplo nombre@empresa.com.',
  topicError: 'Elija la opción que mejor describa su consulta.',
  // Names THIS locale, not English. The English catalog reads 'Same as this page, English'.
  followUpSameAsPage: 'Igual que esta página, español',
  selectOne: 'Seleccione una opción',
  notSpecified: 'No especificado',

  bookingCandidateNote:
    'Los horarios se muestran en hora del centro, Houston. La disponibilidad se confirma al reservar.',
  bookingSlotTaken: 'Ese horario ya no está disponible. Elija otro.',
  bookingFailed: 'No pudimos confirmar ese horario. No se reservó nada. Inténtelo de nuevo.',
  bookingRefused: 'No pudimos reservar ese horario, y volver a intentarlo no ayudaría.',
  bookingUnavailable: 'La programación no está disponible en este momento. No se reservó nada.',
  bookingDurationLabel: '30 minutos',
  // Brand name. Not translated in any locale.
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'Administración de propiedades',
  navAssetManagement: 'Gestión de activos',
  navInvestorServices: 'Servicios para inversionistas',
  // The firm's people, not business partners in general.
  navPartners: 'Socios',
  navContact: 'Contacto',
  navCta: 'Solicitar una propuesta de administración',
  navHomeAria: 'AxisPoint, inicio',
  navPrimaryAria: 'Principal',
  navMenu: 'Menú',
  navMenuDialogAria: 'Menú del sitio',
  navCloseMenu: 'Cerrar menú',

  skipToContent: 'Ir al contenido principal',

  footerPositioning:
    'Primero la administración de propiedades, con gestión de activos disponible cuando la propiedad requiere una capa estratégica por encima.',
  footerServices: 'Servicios',
  footerFirm: 'La firma',
  footerLocation: 'Houston, Texas',
  footerStatewide: 'Al servicio de propietarios en todo Texas',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'Las actividades de corretaje y arrendamiento se realizan a través de nuestro socio con licencia. AxisPoint Partners no brinda asesoría fiscal ni legal. Este sitio web tiene únicamente fines informativos y no constituye una oferta de venta de valores.',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'Página no encontrada',
  notFoundAction: 'Ir al inicio',
  languageChooseAria: 'Elegir idioma. Idioma actual: {language}.',
  languageListAria: 'Elegir idioma',

  /* ══ Marketing pages (PR 3) ══
   * Proper nouns are preserved exactly: AxisPoint, Houston, Texas, Dallas, Fort Worth,
   * San Antonio, Austin, and both partner names. No claim, number, or destination changed. */

  partnersSignature: 'Zachary Russell y Ethaniel Vu, socios.',
  pmRunsAmDirectsTitle:
    'La administración de propiedades opera la propiedad. La gestión de activos dirige la inversión.',

  homeMetaTitle: 'AxisPoint Partners | Administración de propiedades comerciales en Texas',
  homeMetaDescription:
    'AxisPoint administra propiedades multifamiliares y comerciales para propietarios en todo Texas, desde las operaciones en sitio y los controles financieros hasta el desempeño de proveedores y los informes al propietario.',
  homeHeroAlt: 'Jardín y fachada de un conjunto multifamiliar al atardecer',
  homeHeroTitle: 'Un solo equipo responsable de cómo funciona su propiedad.',
  homeHeroLead:
    'AxisPoint administra propiedades multifamiliares y comerciales para propietarios en todo Texas, desde las operaciones en sitio y los controles financieros hasta el desempeño de proveedores y los informes que leen los propietarios.',
  homeHeroQuietLink: 'Vea de qué nos hacemos responsables',
  homeHeroSignature: 'Dirigido por los socios desde Houston: Zachary Russell y Ethaniel Vu.',
  homeStripEyebrow: 'Primero la administración de propiedades',
  homeStripBody:
    'Enfoque principal: propiedades multifamiliares y comerciales en todo Texas. Sede en Houston.',
  homeWhyTitle: 'Por qué los propietarios llaman a AxisPoint',
  homeWhyLead: 'Normalmente por una de cuatro situaciones.',
  homeWhySituationManager: 'El administrador actual ha perdido la confianza de los propietarios.',
  homeWhySituationSelf: 'Autoadministrar se ha convertido en un segundo empleo.',
  homeWhySituationAcquired:
    'Una propiedad recién adquirida necesita un equipo operativo antes de que cierre el primer mes.',
  homeWhyOr: 'O',
  homeWhySituationReports:
    'los informes llegan a tiempo y aun así no explican la propiedad.',
  homeWhyBody:
    'La pregunta de fondo en las cuatro es la misma: quién responde hoy por la propiedad. AxisPoint la responde con un equipo responsable y dos socios lo bastante cerca del trabajo como para conocer la propiedad por su nombre.',
  homeWhyLink: 'De qué se hace responsable AxisPoint',
  homeStrategicEyebrow: 'Capa estratégica',
  homeStrategicBody:
    'Para propietarios que quieren una visión a nivel de propiedad por encima del trabajo operativo, AxisPoint conecta lo que hace la propiedad con los presupuestos, las prioridades de capital y las decisiones de retención. Se contrata cuando la propiedad lo requiere, no se vende por defecto.',
  homeInvestorEyebrow: 'Un camino aparte',
  homeInvestorBody:
    '¿Entra en bienes raíces comerciales sin un equipo operativo detrás? Servicios para inversionistas es la vía de entrada.',
  homeClosingTitle: 'Cuéntenos qué necesita la propiedad ahora.',
  homeClosingBody:
    'Envíe la propiedad, la situación actual de administración y el cambio que está considerando. Un socio lo lee y responde.',

  pmMetaTitle: 'Administración de propiedades en Houston y en todo Texas | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint asume la responsabilidad operativa de propiedades multifamiliares y comerciales en Texas: operaciones en sitio, controles financieros, desempeño de proveedores e informes al propietario.',
  pmHeroTitle: 'Administración de propiedades comerciales en Houston y en todo Texas',
  pmHeroLead:
    'AxisPoint asume la responsabilidad operativa de propiedades multifamiliares y comerciales: el equipo en sitio, el dinero, los proveedores y los informes que los propietarios usan para decidir.',
  pmSeeFunctions: 'Vea las cuatro funciones operativas',
  pmPhotoAlt:
    'Vista aérea de un conjunto multifamiliar de Texas y el centro comercial contiguo',
  pmResponsibilityTitle: 'De qué se hace responsable AxisPoint',
  pmResponsibilityBody:
    'Todo lo que determina cómo funciona la propiedad día a día, y un solo registro de ello para los propietarios. Cuando algo sale mal en la propiedad, los propietarios no tienen que averiguar a quién llamar.',
  pmFunctionsTitle: 'Cuatro funciones operativas, un equipo responsable',
  pmFnOnsiteTitle: 'Operaciones en sitio',
  pmFnOnsiteLede:
    'Las personas en la propiedad y las rutinas que mantienen. Decisiones de personal, supervisión del arrendamiento, estándares de respuesta y calendarios de preparación que mantienen la propiedad conforme al plan semana a semana.',
  pmFnOnsiteItem1: 'Personal y supervisión en sitio',
  pmFnOnsiteItem2: 'Supervisión del arrendamiento',
  pmFnOnsiteItem3: 'Respuesta a residentes e inquilinos',
  pmFnOnsiteItem4: 'Desocupaciones y preparación de unidades',
  pmFnOnsiteItem5: 'Mantenimiento preventivo',
  pmFnFinancialTitle: 'Controles financieros',
  pmFnFinancialLede:
    'Presupuestos elaborados con los propietarios, umbrales de aprobación acordados de antemano y un cierre mensual en el que cualquier cifra puede rastrearse hasta la decisión que la originó.',
  pmFnFinancialItem1: 'Presupuestos anuales y reproyecciones',
  pmFnFinancialItem2: 'Umbrales de aprobación',
  pmFnFinancialItem3: 'Cobranza y morosidad',
  pmFnFinancialItem4: 'Cuentas por pagar y cierre de mes',
  pmFnFinancialItem5: 'Explicación de variaciones',
  pmFnVendorTitle: 'Desempeño de proveedores',
  pmFnVendorLede:
    'Trabajo con alcance definido, disciplina real de licitación y seguimiento medido por la calidad del resultado y no por el cierre de un ticket.',
  pmFnVendorItem1: 'Alcance y proceso de licitación',
  pmFnVendorItem2: 'Cumplimiento contractual y de seguros',
  pmFnVendorItem3: 'Verificación de calidad',
  pmFnVendorItem4: 'Coordinación de proyectos de capital',
  pmFnReportingTitle: 'Informes y comunicación con el propietario',
  pmFnReportingLede:
    'Un solo registro de lo que ocurrió en la propiedad, lo que costó y lo que viene, además de un socio que responde entre periodos de reporte.',
  pmFnReportingItem1: 'Paquete de informes mensuales',
  pmFnReportingItem2: 'Narrativa operativa',
  pmFnReportingItem3: 'Seguimiento de capital y proyectos',
  pmFnReportingItem4: 'Acceso directo a un socio',
  pmStrengthsTitle: 'Dónde AxisPoint es más fuerte',
  pmStrengthsBody:
    'Estas son las situaciones para las que está construido el equipo. Son áreas de fortaleza y no requisitos, y una propiedad fuera de ellas sigue mereciendo una conversación.',
  pmStrengthTypesTitle: 'Tipos de propiedad',
  pmStrengthTypesItem1: 'Multifamiliar como enfoque principal',
  pmStrengthTypesItem2: 'Comercial minorista como enfoque principal',
  pmStrengthTypesItem3: 'Propiedades que pueden sostener personal en sitio',
  pmStrengthTypesItem4: 'Carteras coordinadas de un mismo propietario',
  pmStrengthTypesItem5: 'Carteras dispersas gestionadas como un solo programa',
  pmStrengthGeographyTitle: 'Geografía',
  pmStrengthGeographyItem1: 'Houston y su área metropolitana',
  pmStrengthGeographyItem2: 'Dallas y Fort Worth',
  pmStrengthGeographyItem3: 'San Antonio',
  pmStrengthGeographyItem4: 'Austin',
  pmStrengthGeographyItem5: 'Propietarios en todo Texas',
  pmStrengthAssignmentsTitle: 'Asignaciones',
  pmStrengthAssignmentsItem1: 'Transiciones de administración',
  pmStrengthAssignmentsItem2: 'Ocupación inicial',
  pmStrengthAssignmentsItem3: 'Programas de capital intensivos',
  pmStrengthAssignmentsItem4: 'Problemas operativos postergados',
  pmStrengthAssignmentsItem5: 'Asignaciones de recuperación',
  pmQuestionsTitle: 'Preguntas que hacen los propietarios antes de cambiar',
  pmQ1: '¿Cuánto tarda una transición de administración?',
  pmA1: 'Depende de la propiedad y del administrador saliente, pero el plan se redacta antes de la fecha de inicio: personal, sistemas, banca, registros de proveedores y comunicación con residentes o inquilinos tienen cada uno un responsable y una fecha.',
  pmQ2: '¿Quién responderá realmente por mi propiedad?',
  pmA2: 'Un socio. Zachary Russell y Ethaniel Vu se mantienen lo bastante cerca del trabajo como para conocer la propiedad por su nombre, y los propietarios no pasan por una capa de cuentas para llegar a ellos.',
  pmQ3: '¿Cómo son los informes mes a mes?',
  pmA3: 'Un paquete constante en un calendario constante, con una narrativa escrita que explica las variaciones en lugar de dejar que los propietarios interpreten las cifras solos.',
  pmQ4: '¿Pueden asumir una propiedad con problemas postergados?',
  pmA4: 'Sí. El mantenimiento postergado, el trabajo de capital sin resolver y las vacantes de personal son razones habituales por las que llaman los propietarios. La propuesta indica qué se atiende primero y en qué orden.',
  pmRelatedEyebrow: 'Relacionado',
  pmRelatedAsset:
    'La gestión de activos se sitúa por encima del trabajo operativo, para propietarios que quieren la visión de la inversión',
  pmRelatedInvestor:
    'Servicios para inversionistas es la vía de entrada para clientes con capital y sin equipo operativo',
  pmClosingTitle: 'Envíenos la propiedad y la situación.',
  pmClosingBody:
    'Una propuesta de administración cubre el personal, el paquete de informes, el plan de transición y quién en AxisPoint responde por la propiedad.',

  amMetaTitle: 'Gestión de activos para propietarios en Texas | AxisPoint Partners',
  amMetaDescription:
    'Una visión a nivel de propiedad por encima del trabajo operativo: prioridades de capital, dirección presupuestaria y decisiones de retención, informadas por el equipo que ya opera la propiedad.',
  amHeroTitle: 'Gestión de activos para propietarios en Texas',
  amHeroAnswer:
    'Una visión a nivel de propiedad por encima del trabajo operativo: prioridades de capital, dirección presupuestaria y decisiones de retención, informadas por un equipo que ya opera la propiedad.',
  amPhotoAlt: 'Torre del centro de Houston y pasarela elevada vistas desde la calle',
  amRelationshipEyebrow: 'La relación',
  amRelationshipBody:
    'La gestión de activos es una capa por encima del trabajo operativo, no un reemplazo. Conecta lo que hace la propiedad semana a semana con los presupuestos, las prioridades de capital y la conversación sobre retener o vender. Los propietarios la contratan cuando la propiedad lo requiere.',
  amLayersTitle: 'Dos capas, dichas con claridad',
  amDecidesEyebrow: 'La gestión de activos decide',
  amDecidesItem1: 'Prioridades de capital y su secuencia',
  amDecidesItem2: 'Dirección presupuestaria y postura de reproyección',
  amDecidesItem3: 'Preguntas de retención, refinanciamiento y venta',
  amDecidesItem4: 'Revisión del desempeño frente a la intención de los propietarios',
  amExecutesEyebrow: 'La administración de propiedades ejecuta',
  amExecutesItem1: 'Operaciones en sitio y personal',
  amExecutesItem2: 'Controles financieros y cierre mensual',
  amExecutesItem3: 'Alcance y desempeño de proveedores',
  amExecutesItem4: 'Informes y comunicación con el propietario',
  amClosingTitle: 'Empiece por la propiedad y añada la capa superior.',
  amClosingBody:
    'La mayoría de los propietarios empieza con la administración de propiedades. La gestión de activos se añade cuando las preguntas de inversión necesitan que las responda el mismo equipo.',

  isMetaTitle:
    'Servicios para inversionistas en bienes raíces comerciales de Texas | AxisPoint Partners',
  isMetaDescription:
    'Para clientes con capital que adquieren propiedades multifamiliares o comerciales en Texas y quieren el lado operativo resuelto antes de la compra, no después.',
  isHeroTitle:
    'Una vía de entrada a los bienes raíces comerciales de Texas con un equipo operativo detrás',
  isHeroAnswer:
    'Para clientes con capital que adquieren propiedades multifamiliares o comerciales en Texas y quieren el lado operativo resuelto antes de la compra, no después.',
  isPhotoAlt: 'Vista aérea de un intercambio vial en Houston',
  isWhoEyebrow: 'Para quién es',
  isWhoLead: 'Clientes con capital que necesitan un equipo operativo antes de poder actuar.',
  isWhoBody:
    'Servicios para inversionistas es el menor de los tres caminos y sigue siéndolo a propósito. Existe para propietarios que entran en los bienes raíces comerciales, o que entran en Texas, y quieren el lado operativo resuelto desde la primera propiedad en lugar de armarlo después del cierre.',
  isTimelineBeforeLabel: 'Antes de la compra',
  isTimelineBeforeBody:
    'Una lectura operativa de lo que costará operar la propiedad, para que los supuestos detrás de la oferta sean los que usaría un administrador.',
  isTimelineClosingLabel: 'Al cierre',
  isTimelineClosingBody:
    'Un equipo de administración listo desde el primer día, con personal, sistemas y relaciones con proveedores preparados en lugar de pendientes.',
  isTimelineAfterLabel: 'Después de la primera propiedad',
  isTimelineAfterBody:
    'La relación pasa a Administración de propiedades, con Gestión de activos añadida si la visión de los propietarios lo requiere.',
  isClosingTitle: 'Cuéntenos qué busca adquirir.',
  isClosingBody:
    'Envíe el tipo de propiedad, el mercado y el plazo. Un socio responde con una lectura operativa y cómo sería la administración.',
  isClosingCta: 'Hablar de una adquisición',

  partnersMetaTitle: 'Socios | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint está dirigida por sus socios desde Houston. Zachary Russell y Ethaniel Vu permanecen en las propiedades que asumen, de modo que los propietarios hablan con quienes toman las decisiones.',
  partnersHeroTitle: 'Dos socios, directamente responsables del trabajo',
  partnersHeroAnswer:
    'AxisPoint está dirigida por sus socios desde Houston. Quienes aceptan el encargo son quienes permanecen en él.',
  partnersRoleLabel: 'Socio',
  partnerRussellBody:
    'Trabaja directamente en el desempeño operativo: decisiones de personal, transiciones, programas de capital y las propiedades de la cartera que requieren atención este mes.',
  partnerVuBody:
    'Trabaja directamente en los controles financieros y el registro para los propietarios: presupuestos, disciplina de aprobaciones, cierre mensual y los informes que los propietarios usan para decidir.',
  partnersHowEyebrow: 'Cómo trabajamos',
  partnersHowBody:
    'Ambos socios permanecen en las propiedades que asumen. Los propietarios hablan con quienes toman las decisiones, no con una capa dispuesta delante de ellos.',
  partnersClosingTitle: 'Hable con un socio sobre su propiedad.',
  partnersClosingBody:
    'Envíe la propiedad y la situación. El socio que lo lea es quien respondería por ella.',

  /* ══ Contact page and intake (PR 4) ══
   * Every value here is DISPLAY TEXT. None is stored or sent: the wire carries stable
   * snake_case tokens, unchanged by translation. Placeholders {name} {email} {count} {day}
   * {time} {mode} {language} must survive exactly, spelling included. */

  contactEyebrow: 'Contacto',
  contactHeroTitle: 'Contacte con AxisPoint',
  contactHeroLead:
    'Dirigido por los socios desde Houston, al servicio de propietarios en todo Texas. Díganos qué necesita y un socio lo lee.',
  contactMetaTitle: 'Contacte con AxisPoint | AxisPoint Partners',
  contactMetaDescription:
    'Comuníquese directamente con AxisPoint desde Houston, Texas, con servicio a propietarios en todo el estado. Elija la vía que corresponda a su situación o escriba a info@axispoint.llc.',
  contactPathwayPmAm: 'Administración de propiedades y gestión de activos',
  contactPmMetaTitle: 'Solicitar una propuesta de administración | AxisPoint Partners',
  contactPmMetaDescription:
    'Envíe la propiedad, la situación actual de administración y el cambio que está considerando. Un socio lo lee y responde.',
  contactAmMetaTitle:
    'Solicitar una propuesta de administración con gestión de activos | AxisPoint Partners',
  contactAmMetaDescription:
    'Inicie la propuesta de administración con el interés en gestión de activos identificado, para que el trabajo operativo y la visión de la inversión los lleve el mismo equipo.',
  contactIsMetaTitle: 'Consulta de servicios para inversionistas | AxisPoint Partners',
  contactIsMetaDescription:
    'Cuéntenos en qué punto del proceso se encuentra. Un socio responde con una lectura operativa y cómo sería la administración.',
  contactGeneralMetaTitle: 'Contacte con AxisPoint | AxisPoint Partners',
  contactGeneralMetaDescription:
    'Díganos quién es y qué necesita. Lo dirigiremos al socio adecuado.',

  fieldOptional: 'Opcional',

  gatewayEmailPrefix: '¿Prefiere el correo? Escriba a',

  ledgerChangePath: 'Cambiar de vía',
  labelProperty: 'Propiedad',
  labelPropertyEmpty: 'Tipo, ubicación y escala',
  labelSituation: 'Situación',
  labelSituationEmpty: 'Qué necesita cambiar',
  labelContact: 'Contacto',
  labelContactEmpty: 'Cómo damos seguimiento',
  labelInvolvement: 'Participación',
  labelPathway: 'Vía',
  labelTopic: 'Tema',
  labelFollowUpLanguage: 'Idioma de seguimiento',

  confirmKickerProperty: 'Datos de la propiedad enviados',
  confirmKickerInquiry: 'Consulta enviada',
  confirmTitleProperty: 'Gracias, {name}. Tenemos los datos de su propiedad.',
  confirmTitleInquiry: 'Gracias, {name}. Su consulta está con nosotros.',
  confirmBodyProperty: 'Zachary o Ethaniel revisarán la información y darán seguimiento directamente.',
  confirmBodyInquiry:
    'Zachary o Ethaniel la revisarán y darán seguimiento directamente a {email}.',
  confirmWhatYouSent: 'Lo que envió',
  confirmScheduleCta: 'Programar una llamada de 30 minutos',
  confirmWait: 'Prefiero esperar el seguimiento',
  backToAxisPoint: 'Volver a AxisPoint',

  scheduleKicker: 'Paso opcional',
  scheduleTitle: 'Programar una llamada de 30 minutos',
  scheduleLead:
    'Los datos de su propiedad ya fueron enviados. Elija un horario solo si le resulta útil.',
  scheduleSelectDate: 'Seleccione una fecha',
  scheduleSelectTime: 'Seleccione una hora',
  scheduleChooseDateFirst: 'Elija una fecha para ver los horarios.',
  scheduleHowMeet: '¿Cómo prefiere que nos reunamos?',
  scheduleSelectedLabel: 'Seleccionado',
  scheduleSelectedSummary: '{day} a las {time}, {mode}',
  scheduleSelectedEmpty: 'Elija una fecha, una hora y la forma de reunirse',
  scheduleConfirm: 'Confirmar este horario',
  scheduleBooking: 'Reservando',

  scheduledKicker: 'Llamada confirmada',
  scheduledTitle: 'Ya está en el calendario.',
  labelWhen: 'Cuándo',
  labelFormat: 'Formato',
  labelLength: 'Duración',
  labelWith: 'Con',
  // "Central" names the firm's zone and is not translated: the instant is computed in
  // America/Chicago regardless of the reader's language.
  scheduledWhenValue: '{day}, {time} Central',
  scheduledInviteNote:
    'Se enviará una invitación de calendario a {email}. Responda a ella si necesita cambiar el horario.',
  scheduledDevNote:
    'Vista previa de desarrollo. El comando de reserva se ejecutó contra el simulador, así que no se creó ningún evento de calendario ni se envió ninguna invitación.',

  skippedTitle: 'Sin llamada programada. No necesitamos nada más de usted.',
  skippedBody:
    'Los datos de su propiedad están con Zachary y Ethaniel, y lo contactarán en {email}. Todavía puede elegir un horario si le resulta útil.',

  errorSummaryOne: 'Un campo necesita atención.',
  errorSummaryTwo: 'Dos campos necesitan atención.',
  errorSummaryMany: '{count} campos necesitan atención.',
  errorSummaryFixInquiry:
    'Corrija los campos marcados abajo y luego envíe la consulta de nuevo.',
  errorSummaryFixProperty:
    'Agregue su nombre completo y una dirección de correo a la que podamos responder, y luego envíe los datos de la propiedad de nuevo.',
  failedTitleInquiry: 'No pudimos enviar su consulta.',
  failedTitleProperty: 'No pudimos enviar los datos de su propiedad.',
  failedBody:
    'Sus respuestas siguen aquí. Inténtelo de nuevo o comuníquese directamente con AxisPoint.',
  tryAgain: 'Intentar de nuevo',
  unavailableTitle: 'El envío no está disponible en este momento.',
  unavailableBody:
    'No se envió nada. Sus respuestas siguen aquí y, mientras tanto, puede comunicarse directamente con AxisPoint.',
  blockedBody:
    'No se envió nada, y volver a intentarlo no ayudaría. Sus respuestas siguen aquí. Comuníquese directamente con AxisPoint.',
  emailAxisPoint: 'Escribir a AxisPoint',

  fieldFullName: 'Nombre completo',
  fieldEmail: 'Correo electrónico',
  fieldPhone: 'Teléfono',
  fieldPhonePlaceholder: '(713) 000 0000',
  fieldPhoneHelp: 'Agregue un número si prefiere una llamada directa.',
  fieldCompanyOwnership: 'Empresa o grupo propietario',
  fieldLanguageFollowUp: 'Idioma para el seguimiento',
  followUpHelpChosen:
    'Responderemos en {language} cuando haya un socio disponible, y en inglés en caso contrario.',
  followUpHelpDefault: 'Déjelo así y respondemos en el idioma de esta página.',
  sending: 'Enviando',
  noDocuments: 'No hacen falta documentos en esta etapa.',

  step1Title: 'Cuéntenos sobre su propiedad.',
  step1Lead:
    'Unos pocos datos nos ayudarán a entender qué posee, qué necesita cambiar y si AxisPoint es el socio operativo adecuado.',
  step1SubTitle: '¿De qué estamos hablando?',
  legendPropertyType: 'Tipo de propiedad',
  legendPropertyScope: 'Alcance de la propiedad',
  fieldLocation: '¿Dónde está ubicada la propiedad?',
  fieldLocationPlaceholder: 'Ciudad o mercado',
  fieldLocationHelp:
    'Por ahora basta con la ciudad o el mercado. No hace falta la dirección exacta.',
  fieldPropertyCount: 'Número de propiedades',
  fieldPropertyCountPlaceholder: 'Por ejemplo 6',
  notSure: 'No estoy seguro',
  continueLabel: 'Continuar',
  step1Footer: 'Paso 1 de 3. Unos 60 a 90 segundos en total.',

  step2Title: '¿Qué necesita cambiar?',
  legendCurrentSituation: 'Situación actual',
  legendInvolvement: '¿Dónde le gustaría que participe AxisPoint?',
  fieldTiming: 'Plazo',
  fieldTimingPlaceholder: 'Seleccione un plazo',
  fieldUnderstand: '¿Qué deberíamos saber antes de hablar?',
  fieldUnderstandPlaceholder:
    'Cualquier cosa sobre la propiedad, el administrador actual o el plazo',
  backLabel: 'Atrás',

  step3Title: '¿Cómo damos seguimiento?',
  privacyNote:
    'AxisPoint usará esta información para revisar su consulta y darle seguimiento directamente.',
  sendPropertyDetails: 'Enviar los datos de la propiedad',
};
