import type { Messages } from '../../messages';

/**
 * SPANISH. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Spanish has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready. Do not describe it
 * as any of those things.
 *
 * WHAT IT IS FOR. Giving a native reader something concrete to correct, and letting the
 * localization machinery be exercised end to end in local preview before any translation
 * budget is committed. A wrong sentence a reviewer can strike out is more useful than a
 * blank they have to compose into.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors:
 *   1. `es` is `enabled: false, review: 'unreviewed'` in `../../locales.ts`, so the selector
 *      never offers it, no route resolves to it, and no `hreflang` entry names it.
 *   2. This directory leaves the module graph in every build. Only a running dev server can
 *      reach it. See `apps/web/vite.config.ts` and `../none.ts`.
 *
 * PROMOTION is described in `../reviewed/index.ts`. It requires a native reader's
 * corrections. Moving the file is the last step, not the first.
 *
 * REGISTER. Formal `usted` throughout, matching the English copy's direct, professional
 * tone. A reviewer should check that choice first: it is the decision most likely to be
 * wrong for the intended Houston readership, and it affects nearly every string here.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const ES: Partial<Messages> = {
  gatewayTitle: '¿Qué le gustaría tratar?',
  gatewayLead: 'Elija la opción que mejor se ajuste a su situación. Puede cambiarla más adelante.',
  gatewayOwnerKicker: 'La mayoría de los propietarios empieza aquí',
  gatewayOwnerTitle: 'Propietario',
  gatewayOwnerBody: 'Soy propietario o superviso una propiedad y necesito administración.',
  gatewayOwnerAction: 'Comenzar con los datos de la propiedad',
  gatewayAssetTitle: 'Gestión de activos',
  gatewayAssetBody:
    'Soy propietario y quiero ayuda para dirigir la estrategia, el rendimiento y los informes.',
  gatewayInvestorTitle: 'Servicios para inversionistas',
  gatewayInvestorBody:
    'Me preparo para adquirir bienes raíces comerciales y necesito un equipo operativo.',
  gatewayGeneralTitle: 'Consulta general',
  gatewayGeneralBody: 'Otro asunto. Proveedores, prensa, empleo o una pregunta.',

  propertyTypeMultifamily: 'Multifamiliar',
  propertyTypeRetail: 'Comercial minorista',
  propertyTypeMixedPortfolio: 'Cartera mixta',
  propertyTypeAnother: 'Otro tipo de propiedad',
  propertyScopeOne: 'Una propiedad',
  propertyScopePortfolio: 'Cartera',

  situationReplace: 'Reemplazar la administración actual',
  situationMoveAway: 'Dejar de autoadministrar',
  situationRecentlyAcquired: 'Adquirida recientemente o bajo contrato',
  situationLeaseUp: 'Ocupación inicial o recuperación',
  situationOperations: 'Problemas de operación o de informes',
  situationExploring: 'Explorando opciones de administración',
  situationSomethingElse: 'Otra cosa',

  involvementPm: 'Administración de propiedades',
  involvementPmHint: 'Operar la propiedad en el día a día.',
  involvementPmAm: 'Administración de propiedades + Gestión de activos',
  involvementPmAmHint: 'Operar la propiedad y ayudar a dirigir la estrategia de inversión.',
  involvementNotSure: 'No estoy seguro',
  involvementNotSureHint: 'Ayúdenme a determinar el nivel de participación adecuado.',

  timingImmediately: 'De inmediato',
  timingWithin30: 'Dentro de 30 días',
  timing30to60: 'De 30 a 60 días',
  timing60to90: 'De 60 a 90 días',
  timingStillExploring: 'Todavía explorando',

  investorTopicFirstAcquisition: 'Explorando mi primera adquisición',
  investorTopicUnderContract: 'Bajo contrato ahora',
  investorTopicActivelySearching: 'Buscando activamente',
  investorTopicOwnProperty: 'Tengo propiedad y necesito un equipo operativo',
  investorTopicSomethingElse: 'Otra cosa',
  generalTopicQuestion: 'Una pregunta sobre AxisPoint',
  generalTopicVendor: 'Proveedor o prestador de servicios',
  generalTopicEmployment: 'Empleo',
  generalTopicPress: 'Prensa o medios',
  generalTopicSomethingElse: 'Otra cosa',

  bookingModePhone: 'Llamada telefónica',
  bookingModeVideo: 'Videoconferencia',

  scaleUnitsLabel: 'Unidades aproximadas',
  scaleUnitsPlaceholder: 'Por ejemplo 184',
  scaleUnitsHelp:
    'Una cifra redonda es suficiente. Estamos dimensionando el equipo operativo, no auditando el registro de rentas.',
  scaleSqftLabel: 'Superficie aproximada en pies cuadrados',
  scaleSqftPlaceholder: 'Por ejemplo 42,000',
  scaleSqftHelp: 'El área bruta arrendable es la cifra más útil aquí.',
  scaleMixedLabel: 'Escala combinada aproximada',
  scaleMixedPlaceholder: 'Por ejemplo 300 unidades y 40,000 pies cuadrados',
  scaleMixedHelp:
    'Unidades, pies cuadrados o ambos. Indíquenos la cifra en los términos que usted maneje.',
  scaleOtherLabel: 'Escala aproximada',
  scaleOtherPlaceholder: 'Unidades, pies cuadrados u otra medida',
  scaleOtherHelp:
    'Describa el tamaño en los términos que tengan sentido para este tipo de propiedad.',
  scaleFallbackLabel: 'Escala aproximada',
  scaleFallbackPlaceholder: 'Unidades o pies cuadrados',
  scaleFallbackHelp: 'Elija un tipo de propiedad arriba y esto se adapta a la medida correcta.',

  investorKicker: 'Servicios para inversionistas',
  investorTitle: 'Cuéntenos en qué punto del proceso se encuentra.',
  investorLead:
    'Con una nota breve basta para empezar. Nos pondremos en contacto para concertar una conversación.',
  investorTopicLabel: '¿En qué punto del proceso se encuentra?',
  investorNoteLabel: '¿Qué está considerando?',
  investorNotePlaceholder: 'Tipo de activo, mercado o plazo',
  generalKicker: 'Consulta general',
  generalTitle: '¿En qué podemos ayudarle?',
  generalLead: 'Díganos quién es y qué necesita. Lo dirigiremos al socio adecuado.',
  generalTopicLabel: '¿De qué se trata?',
  generalNoteLabel: 'Su mensaje',
  generalNotePlaceholder: 'Con unas pocas frases basta',
  // Mirrors the English `SHORT_PATHS` value, which is the short 'Company' and NOT the
  // management-proposal field's longer label. Keep them distinct here too.
  organizationLabel: 'Empresa',
  submitLabel: 'Enviar consulta',

  nameHelp: 'Como le gustaría que nos dirijamos a usted.',
  nameError: 'Indique el nombre por el que debemos preguntar cuando llamemos.',
  emailHelp: 'Donde enviaremos nuestra respuesta y cualquier detalle de seguimiento.',
  emailError:
    'A esta dirección le falta la parte que va después del signo @. Agregue la dirección completa, por ejemplo nombre@empresa.com.',
  topicError: 'Elija la opción que mejor describa su consulta.',
  // Names THIS locale, not English. The English catalog reads 'Same as this page, English'.
  followUpSameAsPage: 'Igual que esta página, español',
  selectOne: 'Seleccione una opción',
  notSpecified: 'No especificado',

  bookingCandidateNote:
    'Los horarios se muestran en hora del centro, Houston. La disponibilidad se confirma al reservar.',
  bookingSlotTaken: 'Ese horario ya no está disponible. Elija otro.',
  bookingFailed: 'No pudimos confirmar ese horario. No se reservó nada. Inténtelo de nuevo.',
  bookingRefused: 'No pudimos reservar ese horario, y volver a intentarlo no ayudaría.',
  bookingUnavailable: 'La programación no está disponible en este momento. No se reservó nada.',
  bookingDurationLabel: '30 minutos',
  // Brand name. Not translated in any locale.
  bookingWithLabel: 'AxisPoint Partners',
};
