import type { Messages } from '../../messages';

/**
 * GUJARATI. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Gujarati has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `gu` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * REGISTER. `તમે` throughout. As in Hindi, the commercial-real-estate vocabulary is the weak
 * point rather than the grammar: સંપત્તિ વ્યવસ્થાપન for asset management is formally correct
 * but a Houston Gujarati business reader may simply use the English term. A reviewer should
 * go term by term on that question.
 *
 * GENDER. First-person verbs agree with the speaker's gender and the visitor's is unknown;
 * the masculine default is used (`કરી રહ્યો છું`). A reviewer should choose a neutral
 * construction or accept it. Flagged rather than hidden.
 *
 * LINE HEIGHT. 1.55 in the registry. Gujarati matras sit above and below the base line and
 * clip at Latin leading. Check rendered output, not the source.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const GU: Partial<Messages> = {
  gatewayTitle: 'તમે શેના વિશે વાત કરવા માંગો છો?',
  gatewayLead:
    'તમારી પરિસ્થિતિ સાથે સૌથી વધુ મેળ ખાતો વિકલ્પ પસંદ કરો. તમે પછીથી બદલી શકો છો.',
  gatewayOwnerKicker: 'મોટા ભાગના માલિકો અહીંથી શરૂ કરે છે',
  gatewayOwnerTitle: 'મિલકતના માલિક',
  gatewayOwnerBody: 'મારી પાસે મિલકત છે અથવા હું તેની દેખરેખ રાખું છું અને મને વ્યવસ્થાપનની જરૂર છે.',
  gatewayOwnerAction: 'મિલકતની વિગતો શરૂ કરો',
  gatewayAssetTitle: 'સંપત્તિ વ્યવસ્થાપન',
  gatewayAssetBody:
    'મારી પાસે મિલકત છે અને મને વ્યૂહરચના, કામગીરી અને અહેવાલોની દિશા નક્કી કરવામાં મદદ જોઈએ છે.',
  gatewayInvestorTitle: 'રોકાણકાર સેવાઓ',
  gatewayInvestorBody:
    'હું વાણિજ્યિક મિલકત ખરીદવાની તૈયારી કરી રહ્યો છું અને મને સંચાલન ટીમ જોઈએ છે.',
  gatewayGeneralTitle: 'સામાન્ય પૂછપરછ',
  gatewayGeneralBody: 'બીજું કંઈક. વિક્રેતા, પ્રેસ, રોજગાર અથવા કોઈ પ્રશ્ન.',

  propertyTypeMultifamily: 'બહુ-કૌટુંબિક',
  propertyTypeRetail: 'છૂટક',
  propertyTypeMixedPortfolio: 'મિશ્ર પોર્ટફોલિયો',
  propertyTypeAnother: 'અન્ય પ્રકારની મિલકત',
  propertyScopeOne: 'એક મિલકત',
  propertyScopePortfolio: 'પોર્ટફોલિયો',

  situationReplace: 'હાલનું વ્યવસ્થાપન બદલવું',
  situationMoveAway: 'જાતે વ્યવસ્થાપન કરવાનું છોડવું',
  situationRecentlyAcquired: 'તાજેતરમાં ખરીદેલી અથવા કરાર હેઠળ',
  situationLeaseUp: 'ભાડે આપવાની શરૂઆત અથવા કામગીરી સુધારવી',
  situationOperations: 'સંચાલન અથવા અહેવાલોની સમસ્યાઓ',
  situationExploring: 'વ્યવસ્થાપનના વિકલ્પો જોઈ રહ્યા છીએ',
  situationSomethingElse: 'બીજું કંઈક',

  involvementPm: 'મિલકત વ્યવસ્થાપન',
  involvementPmHint: 'મિલકતનું રોજિંદું સંચાલન.',
  involvementPmAm: 'મિલકત વ્યવસ્થાપન + સંપત્તિ વ્યવસ્થાપન',
  involvementPmAmHint: 'મિલકતનું સંચાલન અને રોકાણ વ્યૂહરચના નક્કી કરવામાં મદદ.',
  involvementNotSure: 'ખાતરી નથી',
  involvementNotSureHint: 'યોગ્ય સ્તર નક્કી કરવામાં મને મદદ કરો.',

  timingImmediately: 'તરત જ',
  timingWithin30: '30 દિવસમાં',
  timing30to60: '30 થી 60 દિવસ',
  timing60to90: '60 થી 90 દિવસ',
  timingStillExploring: 'હજુ વિચારી રહ્યા છીએ',

  investorTopicFirstAcquisition: 'મારી પહેલી ખરીદી વિશે વિચારી રહ્યો છું',
  investorTopicUnderContract: 'હાલમાં કરાર હેઠળ',
  investorTopicActivelySearching: 'સક્રિય રીતે શોધી રહ્યા છીએ',
  investorTopicOwnProperty: 'મિલકત છે, સંચાલન ટીમ જોઈએ છે',
  investorTopicSomethingElse: 'બીજું કંઈક',
  generalTopicQuestion: 'AxisPoint વિશે એક પ્રશ્ન',
  generalTopicVendor: 'વિક્રેતા અથવા સેવા પ્રદાતા',
  generalTopicEmployment: 'રોજગાર',
  generalTopicPress: 'પ્રેસ અથવા મીડિયા',
  generalTopicSomethingElse: 'બીજું કંઈક',

  bookingModePhone: 'ફોન કૉલ',
  bookingModeVideo: 'વીડિયો મીટિંગ',

  scaleUnitsLabel: 'અંદાજિત એકમો',
  scaleUnitsPlaceholder: 'ઉદાહરણ તરીકે 184',
  scaleUnitsHelp:
    'આશરે આંકડો પૂરતો છે. અમે સંચાલન ટીમનું કદ નક્કી કરી રહ્યા છીએ, ભાડાની નોંધની તપાસ નહીં.',
  scaleSqftLabel: 'અંદાજિત ક્ષેત્રફળ, ચોરસ ફૂટ',
  scaleSqftPlaceholder: 'ઉદાહરણ તરીકે 42,000',
  scaleSqftHelp: 'કુલ ભાડે આપી શકાય તેવું ક્ષેત્રફળ અહીં સૌથી ઉપયોગી આંકડો છે.',
  scaleMixedLabel: 'અંદાજિત સંયુક્ત કદ',
  scaleMixedPlaceholder: 'ઉદાહરણ તરીકે 300 એકમો અને 40,000 ચોરસ ફૂટ',
  scaleMixedHelp: 'એકમો, ચોરસ ફૂટ અથવા બંને. તમે જે રીતે હિસાબ રાખો છો તે રીતે જણાવો.',
  scaleOtherLabel: 'અંદાજિત કદ',
  scaleOtherPlaceholder: 'એકમો, ચોરસ ફૂટ અથવા અન્ય માપ',
  scaleOtherHelp: 'આ પ્રકારની મિલકત માટે યોગ્ય હોય તે માપમાં કદ જણાવો.',
  scaleFallbackLabel: 'અંદાજિત કદ',
  scaleFallbackPlaceholder: 'એકમો અથવા ચોરસ ફૂટ',
  scaleFallbackHelp: 'ઉપર મિલકતનો પ્રકાર પસંદ કરો, આ યોગ્ય માપ પ્રમાણે બદલાઈ જશે.',

  investorKicker: 'રોકાણકાર સેવાઓ',
  investorTitle: 'જણાવો કે તમે પ્રક્રિયામાં ક્યાં છો.',
  investorLead: 'શરૂ કરવા માટે ટૂંકી નોંધ પૂરતી છે. વાતચીત ગોઠવવા અમે સંપર્ક કરીશું.',
  investorTopicLabel: 'તમે પ્રક્રિયામાં ક્યાં છો?',
  investorNoteLabel: 'તમે શેના પર વિચાર કરી રહ્યા છો?',
  investorNotePlaceholder: 'સંપત્તિનો પ્રકાર, બજાર અથવા સમયમર્યાદા',
  generalKicker: 'સામાન્ય પૂછપરછ',
  generalTitle: 'અમે શેમાં મદદ કરી શકીએ?',
  generalLead:
    'જણાવો કે તમે કોણ છો અને તમને શું જોઈએ છે. અમે તેને યોગ્ય ભાગીદાર સુધી પહોંચાડીશું.',
  generalTopicLabel: 'આ શેના વિશે છે?',
  generalNoteLabel: 'તમારો સંદેશ',
  generalNotePlaceholder: 'થોડાં વાક્યો પૂરતાં છે',
  organizationLabel: 'કંપની',
  submitLabel: 'પૂછપરછ મોકલો',

  nameHelp: 'તમે ઇચ્છો છો કે અમે તમને કયા નામે સંબોધીએ.',
  nameError: 'અમે ફોન કરીએ ત્યારે જે નામ પૂછવું જોઈએ તે દાખલ કરો.',
  emailHelp: 'જ્યાં અમે અમારો જવાબ અને આગળની વિગતો મોકલીશું.',
  emailError:
    'આ સરનામામાં @ ચિહ્ન પછીનો ભાગ નથી. પૂરું સરનામું દાખલ કરો, ઉદાહરણ તરીકે name@company.com.',
  topicError: 'તમારી પૂછપરછને સૌથી સારી રીતે વર્ણવતો વિકલ્પ પસંદ કરો.',
  followUpSameAsPage: 'આ પૃષ્ઠ જેવું જ, ગુજરાતી',
  selectOne: 'એક પસંદ કરો',
  notSpecified: 'જણાવેલ નથી',

  bookingCandidateNote:
    'સમય સેન્ટ્રલ ટાઇમ, હ્યુસ્ટનમાં દર્શાવેલ છે. ઉપલબ્ધતાની ખાતરી બુકિંગ સમયે થાય છે.',
  bookingSlotTaken: 'તે સમય હવે ઉપલબ્ધ નથી. કૃપા કરીને બીજો પસંદ કરો.',
  bookingFailed: 'અમે તે સમયની ખાતરી કરી શક્યા નહીં. કંઈ બુક થયું નથી. ફરી પ્રયાસ કરો.',
  bookingRefused: 'અમે તે સમય બુક કરી શક્યા નહીં, અને ફરી પ્રયાસ કરવાથી મદદ મળશે નહીં.',
  bookingUnavailable: 'અત્યારે સમય નક્કી કરવાનું ઉપલબ્ધ નથી. કંઈ બુક થયું નથી.',
  bookingDurationLabel: '30 મિનિટ',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'મિલકત વ્યવસ્થાપન',
  navAssetManagement: 'સંપત્તિ વ્યવસ્થાપન',
  navInvestorServices: 'રોકાણકાર સેવાઓ',
  navPartners: 'ભાગીદારો',
  navContact: 'સંપર્ક',
  navCta: 'વ્યવસ્થાપન દરખાસ્તની વિનંતી કરો',
  navHomeAria: 'AxisPoint, હોમ',
  navPrimaryAria: 'મુખ્ય',
  navMenu: 'મેનૂ',
  navMenuDialogAria: 'સાઇટ મેનૂ',
  navCloseMenu: 'મેનૂ બંધ કરો',

  skipToContent: 'મુખ્ય સામગ્રી પર જાઓ',

  footerPositioning:
    'પહેલાં મિલકત વ્યવસ્થાપન, અને જ્યારે મિલકતને ઉપર વ્યૂહાત્મક સ્તરની જરૂર હોય ત્યારે સંપત્તિ વ્યવસ્થાપન પણ ઉપલબ્ધ.',
  footerServices: 'સેવાઓ',
  footerFirm: 'પેઢી',
  footerLocation: 'હ્યુસ્ટન, ટેક્સાસ',
  footerStatewide: 'સમગ્ર ટેક્સાસમાં માલિકોની સેવા',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'બ્રોકરેજ અને લીઝિંગ પ્રવૃત્તિઓ અમારા લાઇસન્સ ધરાવતા ભાગીદાર દ્વારા હાથ ધરવામાં આવે છે. AxisPoint Partners કર કે કાનૂની સલાહ આપતું નથી. આ વેબસાઇટ ફક્ત માહિતીના હેતુ માટે છે અને સિક્યોરિટીઝ વેચવાની ઓફર નથી.',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'પૃષ્ઠ મળ્યું નથી',
  notFoundAction: 'હોમ પર જાઓ',
  languageChooseAria: 'ભાષા પસંદ કરો. વર્તમાન ભાષા: {language}.',
  languageListAria: 'ભાષા પસંદ કરો',

  /* ══ Marketing pages (PR 3) ══
   * Proper nouns preserved in Latin script: AxisPoint and both partner names, matching every
   * other locale and `PartnersPage.tsx`, which renders the names in Latin regardless of
   * locale. Place names use established Gujarati forms: હ્યુસ્ટન, ટેક્સાસ, ડલાસ, ફોર્ટ વર્થ,
   * સાન એન્ટોનિયો, ઓસ્ટિન. */

  partnersSignature: 'Zachary Russell અને Ethaniel Vu, ભાગીદારો.',
  pmRunsAmDirectsTitle:
    'મિલકત વ્યવસ્થાપન મિલકત ચલાવે છે. સંપત્તિ વ્યવસ્થાપન રોકાણની દિશા નક્કી કરે છે.',

  homeMetaTitle: 'AxisPoint Partners | ટેક્સાસમાં વાણિજ્યિક મિલકત વ્યવસ્થાપન',
  homeMetaDescription:
    'AxisPoint સમગ્ર ટેક્સાસમાં માલિકો માટે બહુ-કૌટુંબિક અને છૂટક મિલકતોનું વ્યવસ્થાપન કરે છે, સ્થળ પરની કામગીરી અને નાણાકીય નિયંત્રણથી લઈને વિક્રેતાની કામગીરી અને માલિકોને અપાતા અહેવાલો સુધી.',
  homeHeroAlt: 'સૂર્યાસ્ત સમયે બહુ-કૌટુંબિક સંકુલનું લૉન અને ઇમારતનો આગળનો ભાગ',
  homeHeroTitle: 'તમારી મિલકત કેવી રીતે ચાલે છે તેની જવાબદારી લેતી એક ટીમ.',
  homeHeroLead:
    'AxisPoint સમગ્ર ટેક્સાસમાં માલિકો માટે બહુ-કૌટુંબિક અને છૂટક મિલકતોનું વ્યવસ્થાપન કરે છે, સ્થળ પરની કામગીરી અને નાણાકીય નિયંત્રણથી લઈને વિક્રેતાની કામગીરી અને માલિકો ખરેખર વાંચે છે તે અહેવાલો સુધી.',
  homeHeroQuietLink: 'જુઓ અમે શેની જવાબદારી લઈએ છીએ',
  homeHeroSignature: 'હ્યુસ્ટનથી ભાગીદારો Zachary Russell અને Ethaniel Vu ના નેતૃત્વમાં.',
  homeStripEyebrow: 'પહેલાં મિલકત વ્યવસ્થાપન',
  homeStripBody:
    'મુખ્ય ધ્યાન: સમગ્ર ટેક્સાસમાં બહુ-કૌટુંબિક અને છૂટક મિલકતો. મુખ્ય કાર્યાલય હ્યુસ્ટનમાં.',
  homeWhyTitle: 'માલિકો AxisPoint નો સંપર્ક કેમ કરે છે',
  homeWhyLead: 'સામાન્ય રીતે ચાર પરિસ્થિતિઓમાંથી એક.',
  homeWhySituationManager: 'હાલના વ્યવસ્થાપકે માલિકોનો વિશ્વાસ ગુમાવ્યો છે.',
  homeWhySituationSelf: 'જાતે વ્યવસ્થાપન કરવું બીજી નોકરી બની ગયું છે.',
  homeWhySituationAcquired:
    'તાજેતરમાં ખરીદેલી મિલકતને પહેલો મહિનો પૂરો થાય તે પહેલાં સંચાલન ટીમ જોઈએ છે.',
  homeWhyOr: 'અથવા',
  homeWhySituationReports: 'અહેવાલો સમયસર આવે છે અને છતાં મિલકતની સ્થિતિ સમજાવતા નથી.',
  homeWhyBody:
    'ચારેયની નીચેનો પ્રશ્ન એક જ છે: આજે મિલકત માટે કોણ જવાબ આપે છે. AxisPoint તેનો જવાબ એક જવાબદાર ટીમ અને એવા બે ભાગીદારોથી આપે છે જે કામની એટલી નજીક છે કે મિલકતને નામથી ઓળખે છે.',
  homeWhyLink: 'AxisPoint શેની જવાબદારી લે છે',
  homeStrategicEyebrow: 'વ્યૂહાત્મક સ્તર',
  homeStrategicBody:
    'જે માલિકો સંચાલન કાર્યની ઉપર માલિકી-સ્તરનો દૃષ્ટિકોણ ઇચ્છે છે તેમના માટે, AxisPoint મિલકતની કામગીરીને બજેટ, મૂડી પ્રાથમિકતાઓ અને જાળવી રાખવાના નિર્ણયો સાથે જોડે છે. મિલકતને જરૂર હોય ત્યારે જ લેવાય છે, ધોરણ તરીકે વેચાતું નથી.',
  homeInvestorEyebrow: 'એક અલગ માર્ગ',
  homeInvestorBody:
    'સંચાલન ટીમ વિના વાણિજ્યિક મિલકતમાં પ્રવેશી રહ્યા છો? રોકાણકાર સેવાઓ એ પ્રવેશનો માર્ગ છે.',
  homeClosingTitle: 'જણાવો કે મિલકતને હવે શું જોઈએ છે.',
  homeClosingBody:
    'મિલકત, વ્યવસ્થાપનની હાલની સ્થિતિ, અને તમે વિચારી રહ્યા છો તે ફેરફાર મોકલો. એક ભાગીદાર તે વાંચીને જવાબ આપે છે.',

  pmMetaTitle: 'હ્યુસ્ટન અને સમગ્ર ટેક્સાસમાં મિલકત વ્યવસ્થાપન | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint ટેક્સાસમાં બહુ-કૌટુંબિક અને છૂટક મિલકતોની સંચાલન જવાબદારી લે છે: સ્થળ પરની કામગીરી, નાણાકીય નિયંત્રણ, વિક્રેતાની કામગીરી અને માલિકોને અહેવાલ.',
  pmHeroTitle: 'હ્યુસ્ટન અને સમગ્ર ટેક્સાસમાં વાણિજ્યિક મિલકત વ્યવસ્થાપન',
  pmHeroLead:
    'AxisPoint બહુ-કૌટુંબિક અને છૂટક મિલકતોની સંચાલન જવાબદારી લે છે: સ્થળ પરની ટીમ, નાણાં, વિક્રેતાઓ, અને માલિકો નિર્ણય લેવા માટે વાપરે છે તે અહેવાલો.',
  pmSeeFunctions: 'ચાર સંચાલન કાર્યો જુઓ',
  pmPhotoAlt: 'ટેક્સાસના બહુ-કૌટુંબિક સંકુલ અને બાજુના છૂટક કેન્દ્રનું હવાઈ દૃશ્ય',
  pmResponsibilityTitle: 'AxisPoint શેની જવાબદારી લે છે',
  pmResponsibilityBody:
    'મિલકત રોજ કેવી રીતે ચાલે છે તે નક્કી કરતી દરેક બાબત, અને તેનો માલિકો માટેનો એક જ રેકોર્ડ. મિલકત પર કંઈ ખોટું થાય ત્યારે માલિકોએ કોને ફોન કરવો તે શોધવું પડતું નથી.',
  pmFunctionsTitle: 'ચાર સંચાલન કાર્યો, એક જવાબદાર ટીમ',
  pmFnOnsiteTitle: 'સ્થળ પરની કામગીરી',
  pmFnOnsiteLede:
    'મિલકત પરના લોકો અને તેઓ જે નિયમો પાળે છે. સ્ટાફના નિર્ણયો, ભાડાની દેખરેખ, પ્રતિસાદના ધોરણો અને તૈયારીના સમયપત્રક જે મિલકતને દર અઠવાડિયે યોજના પ્રમાણે રાખે છે.',
  pmFnOnsiteItem1: 'સ્થળ પર સ્ટાફ અને દેખરેખ',
  pmFnOnsiteItem2: 'ભાડાની દેખરેખ',
  pmFnOnsiteItem3: 'રહેવાસી અને ભાડૂતનો પ્રતિસાદ',
  pmFnOnsiteItem4: 'ખાલી થવું અને ફરી તૈયારી',
  pmFnOnsiteItem5: 'નિવારક જાળવણી',
  pmFnFinancialTitle: 'નાણાકીય નિયંત્રણ',
  pmFnFinancialLede:
    'માલિકો સાથે બનાવેલા બજેટ, અગાઉથી નક્કી કરેલી મંજૂરીની મર્યાદાઓ, અને એવું માસિક સમાપન જેમાં દરેક આંકડો તેની પાછળના નિર્ણય સુધી પાછો શોધી શકાય.',
  pmFnFinancialItem1: 'વાર્ષિક બજેટ અને પુનઃઅનુમાન',
  pmFnFinancialItem2: 'મંજૂરીની મર્યાદાઓ',
  pmFnFinancialItem3: 'વસૂલાત અને બાકી રકમ',
  pmFnFinancialItem4: 'ચૂકવવાપાત્ર રકમ અને માસાંત સમાપન',
  pmFnFinancialItem5: 'તફાવતની સમજૂતી',
  pmFnVendorTitle: 'વિક્રેતાની કામગીરી',
  pmFnVendorLede:
    'સ્પષ્ટ વ્યાપવાળું કામ, વાસ્તવિક ટેન્ડર શિસ્ત, અને એવું અનુસરણ જે ટિકિટ બંધ થવાથી નહીં પણ પરિણામની ગુણવત્તાથી માપવામાં આવે છે.',
  pmFnVendorItem1: 'વ્યાપ અને ટેન્ડર પ્રક્રિયા',
  pmFnVendorItem2: 'કરાર અને વીમાનું પાલન',
  pmFnVendorItem3: 'ગુણવત્તાની ચકાસણી',
  pmFnVendorItem4: 'મૂડી પ્રોજેક્ટનું સંકલન',
  pmFnReportingTitle: 'માલિકોને અહેવાલ અને સંવાદ',
  pmFnReportingLede:
    'મિલકત પર શું થયું, તેનો ખર્ચ કેટલો રહ્યો અને હવે શું આવે છે તેનો એક રેકોર્ડ, સાથે એક ભાગીદાર જે અહેવાલના સમયગાળા વચ્ચે પણ જવાબ આપે છે.',
  pmFnReportingItem1: 'માસિક અહેવાલ પેકેજ',
  pmFnReportingItem2: 'સંચાલન વર્ણન',
  pmFnReportingItem3: 'મૂડી અને પ્રોજેક્ટ ટ્રેકિંગ',
  pmFnReportingItem4: 'ભાગીદાર સુધી સીધી પહોંચ',
  pmStrengthsTitle: 'AxisPoint ક્યાં સૌથી મજબૂત છે',
  pmStrengthsBody:
    'આ એવી પરિસ્થિતિઓ છે જેના માટે ટીમ બનેલી છે. આ જરૂરિયાતો નહીં પણ મજબૂતીના ક્ષેત્રો છે, અને તેની બહારની મિલકત વિશે પણ વાત કરવી યોગ્ય છે.',
  pmStrengthTypesTitle: 'મિલકતના પ્રકારો',
  pmStrengthTypesItem1: 'બહુ-કૌટુંબિક મુખ્ય ધ્યાન તરીકે',
  pmStrengthTypesItem2: 'છૂટક મુખ્ય ધ્યાન તરીકે',
  pmStrengthTypesItem3: 'સ્થળ પર સ્ટાફ રાખી શકે તેવી મિલકતો',
  pmStrengthTypesItem4: 'એક જ માલિક હેઠળના સંકલિત પોર્ટફોલિયો',
  pmStrengthTypesItem5: 'વિખરાયેલી મિલકતો એક જ કાર્યક્રમ તરીકે ચલાવવી',
  pmStrengthGeographyTitle: 'ભૂગોળ',
  pmStrengthGeographyItem1: 'હ્યુસ્ટન અને આસપાસનો મહાનગર વિસ્તાર',
  pmStrengthGeographyItem2: 'ડલાસ અને ફોર્ટ વર્થ',
  pmStrengthGeographyItem3: 'સાન એન્ટોનિયો',
  pmStrengthGeographyItem4: 'ઓસ્ટિન',
  pmStrengthGeographyItem5: 'સમગ્ર ટેક્સાસમાં માલિકો',
  pmStrengthAssignmentsTitle: 'કામગીરીના પ્રકારો',
  pmStrengthAssignmentsItem1: 'વ્યવસ્થાપનનું હસ્તાંતરણ',
  pmStrengthAssignmentsItem2: 'ભાડે આપવાની શરૂઆત',
  pmStrengthAssignmentsItem3: 'મોટા મૂડી કાર્યક્રમો',
  pmStrengthAssignmentsItem4: 'મુલતવી રહેલી સંચાલન સમસ્યાઓ',
  pmStrengthAssignmentsItem5: 'સ્થિતિ સુધારવાની કામગીરી',
  pmQuestionsTitle: 'બદલતા પહેલાં માલિકો જે પ્રશ્નો પૂછે છે',
  pmQ1: 'વ્યવસ્થાપનનું હસ્તાંતરણ કેટલો સમય લે છે?',
  pmA1: 'તે મિલકત અને જતા વ્યવસ્થાપક પર આધાર રાખે છે, પરંતુ યોજના શરૂઆતની તારીખ પહેલાં લખાઈ જાય છે: સ્ટાફ, સિસ્ટમ, બેંકિંગ, વિક્રેતાના રેકોર્ડ, અને રહેવાસી કે ભાડૂત સાથેનો સંવાદ, દરેકનો એક જવાબદાર અને એક તારીખ હોય છે.',
  pmQ2: 'મારી મિલકત માટે ખરેખર કોણ જવાબ આપશે?',
  pmA2: 'એક ભાગીદાર. Zachary Russell અને Ethaniel Vu કામની એટલી નજીક રહે છે કે મિલકતને નામથી ઓળખે છે, અને તેમના સુધી પહોંચવા માલિકોએ કોઈ ખાતા-સ્તરમાંથી પસાર થવું પડતું નથી.',
  pmQ3: 'મહિને મહિને અહેવાલ કેવો હોય છે?',
  pmA3: 'સુસંગત સમયપત્રક પર સુસંગત પેકેજ, જેમાં લેખિત વર્ણન તફાવતોની સમજૂતી આપે છે, બદલે કે માલિકો આંકડા જાતે સમજે.',
  pmQ4: 'શું તમે મુલતવી સમસ્યાઓવાળી મિલકત સંભાળી શકો?',
  pmA4: 'હા. મુલતવી જાળવણી, અધૂરું મૂડી કામ અને સ્ટાફની ખેંચ, માલિકો સંપર્ક કરે તેનાં સામાન્ય કારણો છે. દરખાસ્તમાં જણાવાય છે કે પહેલાં શું અને કયા ક્રમમાં હાથ ધરાશે.',
  pmRelatedEyebrow: 'સંબંધિત',
  pmRelatedAsset:
    'સંપત્તિ વ્યવસ્થાપન સંચાલન કાર્યની ઉપર છે, જે માલિકો રોકાણનો દૃષ્ટિકોણ ઇચ્છે છે તેમના માટે',
  pmRelatedInvestor:
    'રોકાણકાર સેવાઓ એ મૂડી તૈયાર હોય પણ સંચાલન ટીમ ન હોય તેવા ગ્રાહકો માટેનો પ્રવેશમાર્ગ છે',
  pmClosingTitle: 'અમને મિલકત અને પરિસ્થિતિ મોકલો.',
  pmClosingBody:
    'એક વ્યવસ્થાપન દરખાસ્તમાં સ્ટાફ, અહેવાલ પેકેજ, હસ્તાંતરણ યોજના, અને AxisPoint માં મિલકત માટે કોણ જવાબ આપે છે તે આવરી લેવાય છે.',

  amMetaTitle: 'ટેક્સાસના મિલકત માલિકો માટે સંપત્તિ વ્યવસ્થાપન | AxisPoint Partners',
  amMetaDescription:
    'સંચાલન કાર્યની ઉપર માલિકી-સ્તરનો દૃષ્ટિકોણ: મૂડી પ્રાથમિકતાઓ, બજેટની દિશા અને જાળવી રાખવાના નિર્ણયો, જે ટીમ પહેલેથી મિલકત ચલાવે છે તેની માહિતી પર આધારિત.',
  amHeroTitle: 'ટેક્સાસના મિલકત માલિકો માટે સંપત્તિ વ્યવસ્થાપન',
  amHeroAnswer:
    'સંચાલન કાર્યની ઉપર માલિકી-સ્તરનો દૃષ્ટિકોણ: મૂડી પ્રાથમિકતાઓ, બજેટની દિશા અને જાળવી રાખવાના નિર્ણયો, જે ટીમ પહેલેથી મિલકત ચલાવે છે તેની માહિતી પર આધારિત.',
  amPhotoAlt: 'રસ્તાની સપાટીએથી દેખાતો હ્યુસ્ટન ડાઉનટાઉનનો ટાવર અને ઊંચો રાહદારી માર્ગ',
  amRelationshipEyebrow: 'આ સંબંધ',
  amRelationshipBody:
    'સંપત્તિ વ્યવસ્થાપન સંચાલન કાર્યની ઉપરનું એક સ્તર છે, તેનો વિકલ્પ નહીં. તે મિલકત અઠવાડિયે અઠવાડિયે શું કરે છે તેને બજેટ, મૂડી પ્રાથમિકતાઓ અને રાખવી કે વેચવી તેની ચર્ચા સાથે જોડે છે. માલિકો તેને ત્યારે લે છે જ્યારે મિલકતને જરૂર હોય.',
  amLayersTitle: 'બે સ્તર, સ્પષ્ટ શબ્દોમાં',
  amDecidesEyebrow: 'સંપત્તિ વ્યવસ્થાપન નક્કી કરે છે',
  amDecidesItem1: 'મૂડી પ્રાથમિકતાઓ અને તેમનો ક્રમ',
  amDecidesItem2: 'બજેટની દિશા અને પુનઃઅનુમાનનું વલણ',
  amDecidesItem3: 'રાખવા, પુનર્ધિરાણ અને વેચાણના પ્રશ્નો',
  amDecidesItem4: 'માલિકોના ઇરાદા સામે કામગીરીની સમીક્ષા',
  amExecutesEyebrow: 'મિલકત વ્યવસ્થાપન અમલ કરે છે',
  amExecutesItem1: 'સ્થળ પરની કામગીરી અને સ્ટાફ',
  amExecutesItem2: 'નાણાકીય નિયંત્રણ અને માસિક સમાપન',
  amExecutesItem3: 'વિક્રેતાનો વ્યાપ અને કામગીરી',
  amExecutesItem4: 'માલિકોને અહેવાલ અને સંવાદ',
  amClosingTitle: 'મિલકતથી શરૂ કરો, પછી ઉપરનું સ્તર ઉમેરો.',
  amClosingBody:
    'મોટા ભાગના માલિકો મિલકત વ્યવસ્થાપનથી શરૂ કરે છે. રોકાણના પ્રશ્નોના જવાબ એ જ ટીમ પાસેથી જોઈએ ત્યારે સંપત્તિ વ્યવસ્થાપન ઉમેરાય છે.',

  isMetaTitle: 'ટેક્સાસની વાણિજ્યિક મિલકત માટે રોકાણકાર સેવાઓ | AxisPoint Partners',
  isMetaDescription:
    'ટેક્સાસમાં બહુ-કૌટુંબિક કે છૂટક મિલકત ખરીદતા મૂડી-તૈયાર ગ્રાહકો માટે, જેઓ ઇચ્છે છે કે સંચાલન બાજુ ખરીદી પહેલાં ગોઠવાય, પછી નહીં.',
  isHeroTitle: 'સંચાલન ટીમ સાથે ટેક્સાસની વાણિજ્યિક મિલકતમાં પ્રવેશનો માર્ગ',
  isHeroAnswer:
    'ટેક્સાસમાં બહુ-કૌટુંબિક કે છૂટક મિલકત ખરીદતા મૂડી-તૈયાર ગ્રાહકો માટે, જેઓ ઇચ્છે છે કે સંચાલન બાજુ ખરીદી પહેલાં ગોઠવાય, પછી નહીં.',
  isPhotoAlt: 'હ્યુસ્ટનમાં એક ધોરીમાર્ગના ઇન્ટરચેન્જનું હવાઈ દૃશ્ય',
  isWhoEyebrow: 'આ કોના માટે છે',
  isWhoLead: 'એવા મૂડી-તૈયાર ગ્રાહકો જેમને પગલું ભરતા પહેલાં સંચાલન ટીમ જોઈએ છે.',
  isWhoBody:
    'રોકાણકાર સેવાઓ ત્રણ માર્ગોમાં સૌથી નાનો છે અને જાણીજોઈને એવો જ રહે છે. તે એવા માલિકો માટે છે જે વાણિજ્યિક મિલકતમાં, અથવા ટેક્સાસમાં, પ્રવેશી રહ્યા છે અને ઇચ્છે છે કે સંચાલન બાજુ પહેલી મિલકતથી જ સંભાળાય, સોદો પૂરો થયા પછી જોડવામાં ન આવે.',
  isTimelineBeforeLabel: 'ખરીદી પહેલાં',
  isTimelineBeforeBody:
    'મિલકત ચલાવવામાં શું લાગશે તેનું સંચાલન મૂલ્યાંકન, જેથી ઓફર પાછળની ધારણાઓ એ જ હોય જે એક વ્યવસ્થાપક વાપરે.',
  isTimelineClosingLabel: 'સોદાના સમયે',
  isTimelineClosingBody:
    'પહેલા દિવસથી વ્યવસ્થાપન ટીમ હાજર, જેમાં સ્ટાફ, સિસ્ટમ અને વિક્રેતા સંબંધો બાકી નહીં પણ તૈયાર હોય.',
  isTimelineAfterLabel: 'પહેલી મિલકત પછી',
  isTimelineAfterBody:
    'સંબંધ મિલકત વ્યવસ્થાપનમાં જાય છે, અને માલિકોનો દૃષ્ટિકોણ માંગે તો સંપત્તિ વ્યવસ્થાપન પણ ઉમેરાય છે.',
  isClosingTitle: 'જણાવો કે તમે શું ખરીદવા માંગો છો.',
  isClosingBody:
    'મિલકતનો પ્રકાર, બજાર અને સમયમર્યાદા મોકલો. એક ભાગીદાર સંચાલન મૂલ્યાંકન સાથે જવાબ આપે છે અને વ્યવસ્થાપન કેવું હશે તે જણાવે છે.',
  isClosingCta: 'ખરીદી અંગે ચર્ચા કરો',

  partnersMetaTitle: 'ભાગીદારો | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint હ્યુસ્ટનથી ભાગીદારોના નેતૃત્વમાં ચાલે છે. Zachary Russell અને Ethaniel Vu તેઓ જે મિલકતો સંભાળે છે તેની સાથે રહે છે, જેથી માલિકો નિર્ણય લેનારાઓ સાથે સીધી વાત કરે છે.',
  partnersHeroTitle: 'બે ભાગીદારો, કામ માટે સીધા જવાબદાર',
  partnersHeroAnswer:
    'AxisPoint હ્યુસ્ટનથી ભાગીદારોના નેતૃત્વમાં ચાલે છે. જે કામ સ્વીકારે છે, તે જ તેની સાથે રહે છે.',
  partnersRoleLabel: 'ભાગીદાર',
  partnerRussellBody:
    'સીધા સંચાલન કામગીરી પર કામ કરે છે: સ્ટાફના નિર્ણયો, હસ્તાંતરણ, મૂડી કાર્યક્રમો, અને પોર્ટફોલિયોની એ મિલકતો જેને આ મહિને ધ્યાન જોઈએ છે.',
  partnerVuBody:
    'સીધા નાણાકીય નિયંત્રણ અને માલિકો માટેના રેકોર્ડ પર કામ કરે છે: બજેટ, મંજૂરીની શિસ્ત, માસિક સમાપન, અને માલિકો નિર્ણય લેવા વાપરે છે તે અહેવાલો.',
  partnersHowEyebrow: 'અમે કેવી રીતે કામ કરીએ છીએ',
  partnersHowBody:
    'બંને ભાગીદારો તેઓ જે મિલકતો સંભાળે છે તેની સાથે રહે છે. માલિકો નિર્ણય લેનારાઓ સાથે વાત કરે છે, તેમની આગળ ગોઠવેલા કોઈ સ્તર સાથે નહીં.',
  partnersClosingTitle: 'તમારી મિલકત વિશે કોઈ ભાગીદાર સાથે વાત કરો.',
  partnersClosingBody:
    'મિલકત અને પરિસ્થિતિ મોકલો. જે ભાગીદાર તે વાંચે છે, તે જ તેનો જવાબ આપશે.',

  /* ══ Contact page and intake (PR 4) ══
   * Display text only; stored values stay stable snake_case tokens. Placeholders
   * {name} {email} {count} {day} {time} {mode} {language} must survive exactly. */

  contactEyebrow: 'સંપર્ક',
  contactHeroTitle: 'AxisPoint નો સંપર્ક કરો',
  contactHeroLead:
    'હ્યુસ્ટનથી ભાગીદારોના નેતૃત્વમાં, સમગ્ર ટેક્સાસના માલિકોની સેવા. જણાવો કે તમને શું જોઈએ છે અને એક ભાગીદાર તે વાંચે છે.',
  contactMetaTitle: 'AxisPoint નો સંપર્ક કરો | AxisPoint Partners',
  contactMetaDescription:
    'હ્યુસ્ટન, ટેક્સાસથી સીધા AxisPoint સુધી પહોંચો, સમગ્ર રાજ્યના માલિકોની સેવા. તમારી પરિસ્થિતિને અનુરૂપ માર્ગ પસંદ કરો, અથવા info@axispoint.llc પર લખો.',
  contactPathwayPmAm: 'મિલકત વ્યવસ્થાપન અને સંપત્તિ વ્યવસ્થાપન',
  contactPmMetaTitle: 'વ્યવસ્થાપન દરખાસ્તની વિનંતી કરો | AxisPoint Partners',
  contactPmMetaDescription:
    'મિલકત, વ્યવસ્થાપનની હાલની સ્થિતિ, અને તમે વિચારી રહ્યા છો તે ફેરફાર મોકલો. એક ભાગીદાર તે વાંચીને જવાબ આપે છે.',
  contactAmMetaTitle:
    'સંપત્તિ વ્યવસ્થાપન સહિત વ્યવસ્થાપન દરખાસ્તની વિનંતી કરો | AxisPoint Partners',
  contactAmMetaDescription:
    'વ્યવસ્થાપન દરખાસ્તમાં સંપત્તિ વ્યવસ્થાપનની રુચિ સ્પષ્ટ કરીને શરૂ કરો, જેથી સંચાલન કાર્ય અને રોકાણનો દૃષ્ટિકોણ એક જ ટીમ સંભાળે.',
  contactIsMetaTitle: 'રોકાણકાર સેવાઓ અંગે પૂછપરછ | AxisPoint Partners',
  contactIsMetaDescription:
    'જણાવો કે તમે પ્રક્રિયામાં ક્યાં છો. એક ભાગીદાર સંચાલન મૂલ્યાંકન સાથે જવાબ આપે છે અને વ્યવસ્થાપન કેવું હશે તે જણાવે છે.',
  contactGeneralMetaTitle: 'AxisPoint નો સંપર્ક કરો | AxisPoint Partners',
  contactGeneralMetaDescription:
    'જણાવો કે તમે કોણ છો અને તમને શું જોઈએ છે. અમે તેને યોગ્ય ભાગીદાર સુધી પહોંચાડીશું.',

  fieldOptional: 'વૈકલ્પિક',

  gatewayEmailPrefix: 'ઈમેલ વધુ ગમે છે? લખો',

  ledgerChangePath: 'માર્ગ બદલો',
  labelProperty: 'મિલકત',
  labelPropertyEmpty: 'પ્રકાર, સ્થાન અને કદ',
  labelSituation: 'પરિસ્થિતિ',
  labelSituationEmpty: 'શું બદલવાની જરૂર છે',
  labelContact: 'સંપર્ક',
  labelContactEmpty: 'અમે કેવી રીતે સંપર્ક કરીએ',
  labelInvolvement: 'સંડોવણી',
  labelPathway: 'માર્ગ',
  labelTopic: 'વિષય',
  labelFollowUpLanguage: 'સંપર્કની ભાષા',

  confirmKickerProperty: 'મિલકતની વિગતો મોકલાઈ',
  confirmKickerInquiry: 'પૂછપરછ મોકલાઈ',
  confirmTitleProperty: 'આભાર, {name}. અમને તમારી મિલકતની વિગતો મળી ગઈ છે.',
  confirmTitleInquiry: 'આભાર, {name}. તમારી પૂછપરછ અમારી પાસે છે.',
  confirmBodyProperty: 'Zachary અથવા Ethaniel માહિતી જોઈને સીધો સંપર્ક કરશે.',
  confirmBodyInquiry: 'Zachary અથવા Ethaniel તે જોઈને સીધા {email} પર સંપર્ક કરશે.',
  confirmWhatYouSent: 'તમે શું મોકલ્યું',
  confirmScheduleCta: '30 મિનિટનો કૉલ ગોઠવો',
  confirmWait: 'હું સંપર્કની રાહ જોઈશ',
  backToAxisPoint: 'AxisPoint પર પાછા',

  scheduleKicker: 'વૈકલ્પિક આગળનું પગલું',
  scheduleTitle: '30 મિનિટનો કૉલ ગોઠવો',
  scheduleLead:
    'તમારી મિલકતની વિગતો પહેલેથી મોકલાઈ ગઈ છે. સમય ત્યારે જ પસંદ કરો જ્યારે તે તમારા માટે ઉપયોગી હોય.',
  scheduleSelectDate: 'તારીખ પસંદ કરો',
  scheduleSelectTime: 'સમય પસંદ કરો',
  scheduleChooseDateFirst: 'સમય જોવા માટે પહેલાં તારીખ પસંદ કરો.',
  scheduleHowMeet: 'આપણે કઈ રીતે વાત કરીએ?',
  scheduleSelectedLabel: 'પસંદ કરેલું',
  scheduleSelectedSummary: '{day} ના રોજ {time} વાગ્યે, {mode}',
  scheduleSelectedEmpty: 'તારીખ, સમય અને વાત કરવાની રીત પસંદ કરો',
  scheduleConfirm: 'આ સમય નક્કી કરો',
  scheduleBooking: 'ગોઠવાઈ રહ્યું છે',

  scheduledKicker: 'કૉલ નક્કી થયો',
  scheduledTitle: 'તમે કૅલેન્ડરમાં છો.',
  labelWhen: 'ક્યારે',
  labelFormat: 'સ્વરૂપ',
  labelLength: 'અવધિ',
  labelWith: 'કોની સાથે',
  scheduledWhenValue: '{day}, {time} Central',
  scheduledInviteNote:
    'કૅલેન્ડર આમંત્રણ {email} પર જશે. સમય બદલવો હોય તો તેનો જ જવાબ આપો.',
  scheduledDevNote:
    'ડેવલપમેન્ટ પૂર્વાવલોકન. બુકિંગ કમાન્ડ સિમ્યુલેટર પર ચાલ્યો, તેથી કોઈ કૅલેન્ડર ઇવેન્ટ બન્યો નથી અને કોઈ આમંત્રણ મોકલાયું નથી.',

  skippedTitle: 'કોઈ કૉલ ગોઠવાયો નથી. તમારી પાસેથી બીજું કંઈ જોઈતું નથી.',
  skippedBody:
    'તમારી મિલકતની વિગતો Zachary અને Ethaniel પાસે છે, અને તેઓ {email} પર તમારો સંપર્ક કરશે. પછીથી ઉપયોગી લાગે તો તમે હજુ પણ સમય પસંદ કરી શકો છો.',

  errorSummaryOne: 'એક ક્ષેત્ર પર ધ્યાન જોઈએ.',
  errorSummaryTwo: 'બે ક્ષેત્રો પર ધ્યાન જોઈએ.',
  errorSummaryMany: '{count} ક્ષેત્રો પર ધ્યાન જોઈએ.',
  errorSummaryFixInquiry: 'નીચે ચિહ્નિત ક્ષેત્રો સુધારો, પછી પૂછપરછ ફરી મોકલો.',
  errorSummaryFixProperty:
    'તમારું પૂરું નામ અને અમે જવાબ આપી શકીએ તેવું ઈમેલ સરનામું ઉમેરો, પછી મિલકતની વિગતો ફરી મોકલો.',
  failedTitleInquiry: 'અમે તમારી પૂછપરછ મોકલી શક્યા નહીં.',
  failedTitleProperty: 'અમે તમારી મિલકતની વિગતો મોકલી શક્યા નહીં.',
  failedBody: 'તમારા જવાબો હજુ અહીં જ છે. ફરી પ્રયાસ કરો અથવા સીધા AxisPoint નો સંપર્ક કરો.',
  tryAgain: 'ફરી પ્રયાસ કરો',
  unavailableTitle: 'અત્યારે મોકલવાનું ઉપલબ્ધ નથી.',
  unavailableBody:
    'કંઈ મોકલાયું નથી. તમારા જવાબો હજુ અહીં જ છે, અને દરમિયાન તમે સીધા AxisPoint નો સંપર્ક કરી શકો છો.',
  blockedBody:
    'કંઈ મોકલાયું નથી, અને ફરી પ્રયાસ કરવાથી મદદ મળશે નહીં. તમારા જવાબો હજુ અહીં જ છે. કૃપા કરીને સીધા AxisPoint નો સંપર્ક કરો.',
  emailAxisPoint: 'AxisPoint ને ઈમેલ કરો',

  fieldFullName: 'પૂરું નામ',
  fieldEmail: 'ઈમેલ',
  fieldPhone: 'ફોન',
  fieldPhonePlaceholder: '(713) 000 0000',
  fieldPhoneHelp: 'સીધો કૉલ ગમતો હોય તો નંબર ઉમેરો.',
  fieldCompanyOwnership: 'કંપની અથવા માલિકી જૂથ',
  fieldLanguageFollowUp: 'સંપર્ક માટેની ભાષા',
  followUpHelpChosen:
    'જ્યાં ભાગીદાર ઉપલબ્ધ હશે ત્યાં અમે {language} માં જવાબ આપીશું, અન્યથા અંગ્રેજીમાં.',
  followUpHelpDefault: 'આને એમ જ રહેવા દો અને અમે આ પૃષ્ઠની ભાષામાં જવાબ આપીશું.',
  sending: 'મોકલાઈ રહ્યું છે',
  noDocuments: 'આ તબક્કે કોઈ દસ્તાવેજની જરૂર નથી.',

  step1Title: 'તમારી મિલકત વિશે જણાવો.',
  step1Lead:
    'થોડી વિગતો અમને સમજવામાં મદદ કરશે કે તમારી પાસે શું છે, શું બદલવાની જરૂર છે, અને AxisPoint યોગ્ય સંચાલન ભાગીદાર છે કે નહીં.',
  step1SubTitle: 'આપણે શેની ચર્ચા કરી રહ્યા છીએ?',
  legendPropertyType: 'મિલકતનો પ્રકાર',
  legendPropertyScope: 'મિલકતનો વ્યાપ',
  fieldLocation: 'મિલકત ક્યાં આવેલી છે?',
  fieldLocationPlaceholder: 'શહેર અથવા બજાર',
  fieldLocationHelp: 'હાલ પૂરતું શહેર અથવા બજાર પૂરતું છે. પૂરું સરનામું જરૂરી નથી.',
  fieldPropertyCount: 'મિલકતોની સંખ્યા',
  fieldPropertyCountPlaceholder: 'ઉદાહરણ તરીકે 6',
  notSure: 'ખાતરી નથી',
  continueLabel: 'આગળ વધો',
  step1Footer: 'પગલું 1 માંથી 3. કુલ મળીને આશરે 60 થી 90 સેકન્ડ.',

  step2Title: 'શું બદલવાની જરૂર છે?',
  legendCurrentSituation: 'હાલની પરિસ્થિતિ',
  legendInvolvement: 'તમે AxisPoint ની સંડોવણી ક્યાં ઇચ્છશો?',
  fieldTiming: 'સમય',
  fieldTimingPlaceholder: 'સમયગાળો પસંદ કરો',
  fieldUnderstand: 'વાત કરતા પહેલાં અમારે શું સમજવું જોઈએ?',
  fieldUnderstandPlaceholder:
    'મિલકત, હાલના વ્યવસ્થાપક અથવા સમયમર્યાદા વિશે કંઈ પણ',
  backLabel: 'પાછળ',

  step3Title: 'અમે કેવી રીતે સંપર્ક કરીએ?',
  privacyNote:
    'AxisPoint આ માહિતીનો ઉપયોગ તમારી પૂછપરછની સમીક્ષા કરવા અને સીધો તમારો સંપર્ક કરવા માટે કરશે.',
  sendPropertyDetails: 'મિલકતની વિગતો મોકલો',
};
