import type { Messages } from '../../messages';

/**
 * GUJARATI. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Gujarati has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `gu` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * REGISTER. `તમે` throughout. As in Hindi, the commercial-real-estate vocabulary is the weak
 * point rather than the grammar: સંપત્તિ વ્યવસ્થાપન for asset management is formally correct
 * but a Houston Gujarati business reader may simply use the English term. A reviewer should
 * go term by term on that question.
 *
 * GENDER. First-person verbs agree with the speaker's gender and the visitor's is unknown;
 * the masculine default is used (`કરી રહ્યો છું`). A reviewer should choose a neutral
 * construction or accept it. Flagged rather than hidden.
 *
 * LINE HEIGHT. 1.55 in the registry. Gujarati matras sit above and below the base line and
 * clip at Latin leading. Check rendered output, not the source.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const GU: Partial<Messages> = {
  gatewayTitle: 'તમે શેના વિશે વાત કરવા માંગો છો?',
  gatewayLead:
    'તમારી પરિસ્થિતિ સાથે સૌથી વધુ મેળ ખાતો વિકલ્પ પસંદ કરો. તમે પછીથી બદલી શકો છો.',
  gatewayOwnerKicker: 'મોટા ભાગના માલિકો અહીંથી શરૂ કરે છે',
  gatewayOwnerTitle: 'મિલકતના માલિક',
  gatewayOwnerBody: 'મારી પાસે મિલકત છે અથવા હું તેની દેખરેખ રાખું છું અને મને વ્યવસ્થાપનની જરૂર છે.',
  gatewayOwnerAction: 'મિલકતની વિગતો શરૂ કરો',
  gatewayAssetTitle: 'સંપત્તિ વ્યવસ્થાપન',
  gatewayAssetBody:
    'મારી પાસે મિલકત છે અને મને વ્યૂહરચના, કામગીરી અને અહેવાલોની દિશા નક્કી કરવામાં મદદ જોઈએ છે.',
  gatewayInvestorTitle: 'રોકાણકાર સેવાઓ',
  gatewayInvestorBody:
    'હું વાણિજ્યિક મિલકત ખરીદવાની તૈયારી કરી રહ્યો છું અને મને સંચાલન ટીમ જોઈએ છે.',
  gatewayGeneralTitle: 'સામાન્ય પૂછપરછ',
  gatewayGeneralBody: 'બીજું કંઈક. વિક્રેતા, પ્રેસ, રોજગાર અથવા કોઈ પ્રશ્ન.',

  propertyTypeMultifamily: 'બહુ-કૌટુંબિક',
  propertyTypeRetail: 'છૂટક',
  propertyTypeMixedPortfolio: 'મિશ્ર પોર્ટફોલિયો',
  propertyTypeAnother: 'અન્ય પ્રકારની મિલકત',
  propertyScopeOne: 'એક મિલકત',
  propertyScopePortfolio: 'પોર્ટફોલિયો',

  situationReplace: 'હાલનું વ્યવસ્થાપન બદલવું',
  situationMoveAway: 'જાતે વ્યવસ્થાપન કરવાનું છોડવું',
  situationRecentlyAcquired: 'તાજેતરમાં ખરીદેલી અથવા કરાર હેઠળ',
  situationLeaseUp: 'ભાડે આપવાની શરૂઆત અથવા કામગીરી સુધારવી',
  situationOperations: 'સંચાલન અથવા અહેવાલોની સમસ્યાઓ',
  situationExploring: 'વ્યવસ્થાપનના વિકલ્પો જોઈ રહ્યા છીએ',
  situationSomethingElse: 'બીજું કંઈક',

  involvementPm: 'મિલકત વ્યવસ્થાપન',
  involvementPmHint: 'મિલકતનું રોજિંદું સંચાલન.',
  involvementPmAm: 'મિલકત વ્યવસ્થાપન + સંપત્તિ વ્યવસ્થાપન',
  involvementPmAmHint: 'મિલકતનું સંચાલન અને રોકાણ વ્યૂહરચના નક્કી કરવામાં મદદ.',
  involvementNotSure: 'ખાતરી નથી',
  involvementNotSureHint: 'યોગ્ય સ્તર નક્કી કરવામાં મને મદદ કરો.',

  timingImmediately: 'તરત જ',
  timingWithin30: '30 દિવસમાં',
  timing30to60: '30 થી 60 દિવસ',
  timing60to90: '60 થી 90 દિવસ',
  timingStillExploring: 'હજુ વિચારી રહ્યા છીએ',

  investorTopicFirstAcquisition: 'મારી પહેલી ખરીદી વિશે વિચારી રહ્યો છું',
  investorTopicUnderContract: 'હાલમાં કરાર હેઠળ',
  investorTopicActivelySearching: 'સક્રિય રીતે શોધી રહ્યા છીએ',
  investorTopicOwnProperty: 'મિલકત છે, સંચાલન ટીમ જોઈએ છે',
  investorTopicSomethingElse: 'બીજું કંઈક',
  generalTopicQuestion: 'AxisPoint વિશે એક પ્રશ્ન',
  generalTopicVendor: 'વિક્રેતા અથવા સેવા પ્રદાતા',
  generalTopicEmployment: 'રોજગાર',
  generalTopicPress: 'પ્રેસ અથવા મીડિયા',
  generalTopicSomethingElse: 'બીજું કંઈક',

  bookingModePhone: 'ફોન કૉલ',
  bookingModeVideo: 'વીડિયો મીટિંગ',

  scaleUnitsLabel: 'અંદાજિત એકમો',
  scaleUnitsPlaceholder: 'ઉદાહરણ તરીકે 184',
  scaleUnitsHelp:
    'આશરે આંકડો પૂરતો છે. અમે સંચાલન ટીમનું કદ નક્કી કરી રહ્યા છીએ, ભાડાની નોંધની તપાસ નહીં.',
  scaleSqftLabel: 'અંદાજિત ક્ષેત્રફળ, ચોરસ ફૂટ',
  scaleSqftPlaceholder: 'ઉદાહરણ તરીકે 42,000',
  scaleSqftHelp: 'કુલ ભાડે આપી શકાય તેવું ક્ષેત્રફળ અહીં સૌથી ઉપયોગી આંકડો છે.',
  scaleMixedLabel: 'અંદાજિત સંયુક્ત કદ',
  scaleMixedPlaceholder: 'ઉદાહરણ તરીકે 300 એકમો અને 40,000 ચોરસ ફૂટ',
  scaleMixedHelp: 'એકમો, ચોરસ ફૂટ અથવા બંને. તમે જે રીતે હિસાબ રાખો છો તે રીતે જણાવો.',
  scaleOtherLabel: 'અંદાજિત કદ',
  scaleOtherPlaceholder: 'એકમો, ચોરસ ફૂટ અથવા અન્ય માપ',
  scaleOtherHelp: 'આ પ્રકારની મિલકત માટે યોગ્ય હોય તે માપમાં કદ જણાવો.',
  scaleFallbackLabel: 'અંદાજિત કદ',
  scaleFallbackPlaceholder: 'એકમો અથવા ચોરસ ફૂટ',
  scaleFallbackHelp: 'ઉપર મિલકતનો પ્રકાર પસંદ કરો, આ યોગ્ય માપ પ્રમાણે બદલાઈ જશે.',

  investorKicker: 'રોકાણકાર સેવાઓ',
  investorTitle: 'જણાવો કે તમે પ્રક્રિયામાં ક્યાં છો.',
  investorLead: 'શરૂ કરવા માટે ટૂંકી નોંધ પૂરતી છે. વાતચીત ગોઠવવા અમે સંપર્ક કરીશું.',
  investorTopicLabel: 'તમે પ્રક્રિયામાં ક્યાં છો?',
  investorNoteLabel: 'તમે શેના પર વિચાર કરી રહ્યા છો?',
  investorNotePlaceholder: 'સંપત્તિનો પ્રકાર, બજાર અથવા સમયમર્યાદા',
  generalKicker: 'સામાન્ય પૂછપરછ',
  generalTitle: 'અમે શેમાં મદદ કરી શકીએ?',
  generalLead:
    'જણાવો કે તમે કોણ છો અને તમને શું જોઈએ છે. અમે તેને યોગ્ય ભાગીદાર સુધી પહોંચાડીશું.',
  generalTopicLabel: 'આ શેના વિશે છે?',
  generalNoteLabel: 'તમારો સંદેશ',
  generalNotePlaceholder: 'થોડાં વાક્યો પૂરતાં છે',
  organizationLabel: 'કંપની',
  submitLabel: 'પૂછપરછ મોકલો',

  nameHelp: 'તમે ઇચ્છો છો કે અમે તમને કયા નામે સંબોધીએ.',
  nameError: 'અમે ફોન કરીએ ત્યારે જે નામ પૂછવું જોઈએ તે દાખલ કરો.',
  emailHelp: 'જ્યાં અમે અમારો જવાબ અને આગળની વિગતો મોકલીશું.',
  emailError:
    'આ સરનામામાં @ ચિહ્ન પછીનો ભાગ નથી. પૂરું સરનામું દાખલ કરો, ઉદાહરણ તરીકે name@company.com.',
  topicError: 'તમારી પૂછપરછને સૌથી સારી રીતે વર્ણવતો વિકલ્પ પસંદ કરો.',
  followUpSameAsPage: 'આ પૃષ્ઠ જેવું જ, ગુજરાતી',
  selectOne: 'એક પસંદ કરો',
  notSpecified: 'જણાવેલ નથી',

  bookingCandidateNote:
    'સમય સેન્ટ્રલ ટાઇમ, હ્યુસ્ટનમાં દર્શાવેલ છે. ઉપલબ્ધતાની ખાતરી બુકિંગ સમયે થાય છે.',
  bookingSlotTaken: 'તે સમય હવે ઉપલબ્ધ નથી. કૃપા કરીને બીજો પસંદ કરો.',
  bookingFailed: 'અમે તે સમયની ખાતરી કરી શક્યા નહીં. કંઈ બુક થયું નથી. ફરી પ્રયાસ કરો.',
  bookingRefused: 'અમે તે સમય બુક કરી શક્યા નહીં, અને ફરી પ્રયાસ કરવાથી મદદ મળશે નહીં.',
  bookingUnavailable: 'અત્યારે સમય નક્કી કરવાનું ઉપલબ્ધ નથી. કંઈ બુક થયું નથી.',
  bookingDurationLabel: '30 મિનિટ',
  bookingWithLabel: 'AxisPoint Partners',
};
