import type { Messages } from '../../messages';

/**
 * HINDI. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Hindi has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `hi` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * REGISTER. `आप` throughout. Vocabulary leans Sanskritic where a commercial-real-estate term
 * has no settled everyday Hindi equivalent (परिसंपत्ति प्रबंधन for asset management), which is
 * the register of formal business writing but can read as stiff. A reviewer should decide per
 * term whether the English loanword is what Houston readers actually use, since Hindi
 * business speech borrows heavily and this file mostly does not.
 *
 * GENDER. Several first-person strings assume a masculine speaker (`कर रहा हूं`), because
 * Hindi verbs agree with the speaker's gender and the visitor's is unknown. This is a real
 * defect in the source language's fit to the interface, not a slip: a reviewer should either
 * choose a gender-neutral construction or accept the default. Flagged rather than hidden.
 *
 * LINE HEIGHT. Devanagari carries 1.55 in the registry. Matras sit above and below the base
 * line, so this text clips at Latin leading. Check rendered output, not the source.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const HI: Partial<Messages> = {
  gatewayTitle: 'आप किस विषय पर बात करना चाहेंगे?',
  gatewayLead:
    'वह विकल्प चुनें जो आपकी स्थिति से सबसे अधिक मेल खाता हो। आप इसे बाद में बदल सकते हैं।',
  gatewayOwnerKicker: 'अधिकांश स्वामी यहीं से शुरू करते हैं',
  gatewayOwnerTitle: 'संपत्ति स्वामी',
  gatewayOwnerBody: 'मेरे पास एक संपत्ति है या मैं उसकी देखरेख करता हूं और मुझे प्रबंधन चाहिए।',
  gatewayOwnerAction: 'संपत्ति का विवरण शुरू करें',
  gatewayAssetTitle: 'परिसंपत्ति प्रबंधन',
  gatewayAssetBody:
    'मेरे पास संपत्ति है और मुझे रणनीति, प्रदर्शन और रिपोर्टिंग की दिशा तय करने में सहायता चाहिए।',
  gatewayInvestorTitle: 'निवेशक सेवाएं',
  gatewayInvestorBody:
    'मैं वाणिज्यिक अचल संपत्ति खरीदने की तैयारी कर रहा हूं और मुझे एक संचालन टीम चाहिए।',
  gatewayGeneralTitle: 'सामान्य पूछताछ',
  gatewayGeneralBody: 'कुछ और। विक्रेता, प्रेस, रोजगार या कोई प्रश्न।',

  propertyTypeMultifamily: 'बहु-पारिवारिक',
  propertyTypeRetail: 'खुदरा',
  propertyTypeMixedPortfolio: 'मिश्रित पोर्टफोलियो',
  propertyTypeAnother: 'अन्य प्रकार की संपत्ति',
  propertyScopeOne: 'एक संपत्ति',
  propertyScopePortfolio: 'पोर्टफोलियो',

  situationReplace: 'वर्तमान प्रबंधन बदलना',
  situationMoveAway: 'स्वयं प्रबंधन से हटना',
  situationRecentlyAcquired: 'हाल ही में खरीदी गई या अनुबंध के अधीन',
  situationLeaseUp: 'किराये पर देने की शुरुआत या स्थिति सुधारना',
  situationOperations: 'संचालन या रिपोर्टिंग से जुड़ी समस्याएं',
  situationExploring: 'प्रबंधन विकल्प देख रहे हैं',
  situationSomethingElse: 'कुछ और',

  involvementPm: 'संपत्ति प्रबंधन',
  involvementPmHint: 'संपत्ति का रोजमर्रा का संचालन।',
  involvementPmAm: 'संपत्ति प्रबंधन + परिसंपत्ति प्रबंधन',
  involvementPmAmHint: 'संपत्ति का संचालन और निवेश रणनीति तय करने में सहायता।',
  involvementNotSure: 'निश्चित नहीं',
  involvementNotSureHint: 'उपयुक्त स्तर तय करने में मेरी सहायता करें।',

  timingImmediately: 'तुरंत',
  timingWithin30: '30 दिनों के भीतर',
  timing30to60: '30 से 60 दिन',
  timing60to90: '60 से 90 दिन',
  timingStillExploring: 'अभी विचार कर रहे हैं',

  investorTopicFirstAcquisition: 'अपनी पहली खरीद पर विचार कर रहा हूं',
  investorTopicUnderContract: 'अभी अनुबंध के अधीन',
  investorTopicActivelySearching: 'सक्रिय रूप से खोज रहे हैं',
  investorTopicOwnProperty: 'संपत्ति है, संचालन टीम चाहिए',
  investorTopicSomethingElse: 'कुछ और',
  generalTopicQuestion: 'AxisPoint के बारे में एक प्रश्न',
  generalTopicVendor: 'विक्रेता या सेवा प्रदाता',
  generalTopicEmployment: 'रोजगार',
  generalTopicPress: 'प्रेस या मीडिया',
  generalTopicSomethingElse: 'कुछ और',

  bookingModePhone: 'फोन कॉल',
  bookingModeVideo: 'वीडियो बैठक',

  scaleUnitsLabel: 'अनुमानित इकाइयां',
  scaleUnitsPlaceholder: 'उदाहरण के लिए 184',
  scaleUnitsHelp:
    'एक मोटा आंकड़ा पर्याप्त है। हम संचालन टीम का आकार तय कर रहे हैं, किराया रिकॉर्ड की जांच नहीं।',
  scaleSqftLabel: 'अनुमानित क्षेत्रफल, वर्ग फुट',
  scaleSqftPlaceholder: 'उदाहरण के लिए 42,000',
  scaleSqftHelp: 'कुल किराये योग्य क्षेत्र यहां सबसे उपयोगी आंकड़ा है।',
  scaleMixedLabel: 'अनुमानित संयुक्त आकार',
  scaleMixedPlaceholder: 'उदाहरण के लिए 300 इकाइयां और 40,000 वर्ग फुट',
  scaleMixedHelp:
    'इकाइयां, वर्ग फुट या दोनों। जिस रूप में आप हिसाब रखते हैं, उसी में बताएं।',
  scaleOtherLabel: 'अनुमानित आकार',
  scaleOtherPlaceholder: 'इकाइयां, वर्ग फुट या कोई अन्य माप',
  scaleOtherHelp: 'इस प्रकार की संपत्ति के लिए जो माप उपयुक्त हो, उसी में आकार बताएं।',
  scaleFallbackLabel: 'अनुमानित आकार',
  scaleFallbackPlaceholder: 'इकाइयां या वर्ग फुट',
  scaleFallbackHelp: 'ऊपर संपत्ति का प्रकार चुनें और यह सही माप के अनुसार बदल जाएगा।',

  investorKicker: 'निवेशक सेवाएं',
  investorTitle: 'बताएं कि आप प्रक्रिया में कहां हैं।',
  investorLead:
    'शुरू करने के लिए एक छोटा सा नोट पर्याप्त है। बातचीत तय करने के लिए हम संपर्क करेंगे।',
  investorTopicLabel: 'आप प्रक्रिया में कहां हैं?',
  investorNoteLabel: 'आप किस पर विचार कर रहे हैं?',
  investorNotePlaceholder: 'परिसंपत्ति का प्रकार, बाजार या समय-सीमा',
  generalKicker: 'सामान्य पूछताछ',
  generalTitle: 'हम किसमें सहायता कर सकते हैं?',
  generalLead:
    'बताएं कि आप कौन हैं और आपको क्या चाहिए। हम इसे सही साझेदार तक पहुंचाएंगे।',
  generalTopicLabel: 'यह किस बारे में है?',
  generalNoteLabel: 'आपका संदेश',
  generalNotePlaceholder: 'कुछ वाक्य पर्याप्त हैं',
  organizationLabel: 'कंपनी',
  submitLabel: 'पूछताछ भेजें',

  nameHelp: 'आप चाहते हैं कि हम आपको किस नाम से संबोधित करें।',
  nameError: 'वह नाम दर्ज करें जो हमें कॉल करते समय पूछना चाहिए।',
  emailHelp: 'जहां हम अपना उत्तर और आगे की जानकारी भेजेंगे।',
  emailError:
    'इस पते में @ चिह्न के बाद का हिस्सा नहीं है। पूरा पता दर्ज करें, उदाहरण के लिए name@company.com।',
  topicError: 'वह विकल्प चुनें जो आपकी पूछताछ का सबसे सही वर्णन करता हो।',
  followUpSameAsPage: 'इस पृष्ठ के समान, हिन्दी',
  selectOne: 'एक चुनें',
  notSpecified: 'नहीं बताया गया',

  bookingCandidateNote:
    'समय सेंट्रल टाइम, ह्यूस्टन में दिखाया गया है। उपलब्धता की पुष्टि बुकिंग के समय होती है।',
  bookingSlotTaken: 'वह समय अब उपलब्ध नहीं है। कृपया दूसरा चुनें।',
  bookingFailed: 'हम उस समय की पुष्टि नहीं कर सके। कुछ भी बुक नहीं हुआ। फिर से प्रयास करें।',
  bookingRefused: 'हम उस समय को बुक नहीं कर सके, और दोबारा प्रयास करने से मदद नहीं मिलेगी।',
  bookingUnavailable: 'अभी बुकिंग उपलब्ध नहीं है। कुछ भी बुक नहीं हुआ।',
  bookingDurationLabel: '30 मिनट',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'संपत्ति प्रबंधन',
  navAssetManagement: 'परिसंपत्ति प्रबंधन',
  navInvestorServices: 'निवेशक सेवाएं',
  navPartners: 'साझेदार',
  navContact: 'संपर्क',
  navCta: 'प्रबंधन प्रस्ताव का अनुरोध करें',
  navHomeAria: 'AxisPoint, मुखपृष्ठ',
  navPrimaryAria: 'मुख्य',
  navMenu: 'मेन्यू',
  navMenuDialogAria: 'साइट मेन्यू',
  navCloseMenu: 'मेन्यू बंद करें',

  skipToContent: 'मुख्य सामग्री पर जाएं',

  footerPositioning:
    'पहले संपत्ति प्रबंधन, और जब संपत्ति को ऊपर एक रणनीतिक परत की जरूरत हो तो परिसंपत्ति प्रबंधन भी उपलब्ध।',
  footerServices: 'सेवाएं',
  footerFirm: 'फर्म',
  footerLocation: 'ह्यूस्टन, टेक्सास',
  footerStatewide: 'पूरे टेक्सास में संपत्ति स्वामियों की सेवा',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'ब्रोकरेज और लीजिंग गतिविधियां हमारे लाइसेंस प्राप्त साझेदार के माध्यम से संचालित होती हैं। AxisPoint Partners कर या कानूनी सलाह नहीं देता। यह वेबसाइट केवल सूचना के उद्देश्य से है और प्रतिभूतियां बेचने का प्रस्ताव नहीं है।',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'पृष्ठ नहीं मिला',
  notFoundAction: 'मुखपृष्ठ पर जाएं',
  languageChooseAria: 'भाषा चुनें। वर्तमान भाषा: {language}।',
  languageListAria: 'भाषा चुनें',
};
