import type { Messages } from '../../messages';

/**
 * HINDI. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Hindi has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `hi` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * REGISTER. `आप` throughout. Vocabulary leans Sanskritic where a commercial-real-estate term
 * has no settled everyday Hindi equivalent (परिसंपत्ति प्रबंधन for asset management), which is
 * the register of formal business writing but can read as stiff. A reviewer should decide per
 * term whether the English loanword is what Houston readers actually use, since Hindi
 * business speech borrows heavily and this file mostly does not.
 *
 * GENDER. Several first-person strings assume a masculine speaker (`कर रहा हूं`), because
 * Hindi verbs agree with the speaker's gender and the visitor's is unknown. This is a real
 * defect in the source language's fit to the interface, not a slip: a reviewer should either
 * choose a gender-neutral construction or accept the default. Flagged rather than hidden.
 *
 * LINE HEIGHT. Devanagari carries 1.55 in the registry. Matras sit above and below the base
 * line, so this text clips at Latin leading. Check rendered output, not the source.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const HI: Partial<Messages> = {
  gatewayTitle: 'आप किस विषय पर बात करना चाहेंगे?',
  gatewayLead:
    'वह विकल्प चुनें जो आपकी स्थिति से सबसे अधिक मेल खाता हो। आप इसे बाद में बदल सकते हैं।',
  gatewayOwnerKicker: 'अधिकांश स्वामी यहीं से शुरू करते हैं',
  gatewayOwnerTitle: 'संपत्ति स्वामी',
  gatewayOwnerBody: 'मेरे पास एक संपत्ति है या मैं उसकी देखरेख करता हूं और मुझे प्रबंधन चाहिए।',
  gatewayOwnerAction: 'संपत्ति का विवरण शुरू करें',
  gatewayAssetTitle: 'परिसंपत्ति प्रबंधन',
  gatewayAssetBody:
    'मेरे पास संपत्ति है और मुझे रणनीति, प्रदर्शन और रिपोर्टिंग की दिशा तय करने में सहायता चाहिए।',
  gatewayInvestorTitle: 'निवेशक सेवाएं',
  gatewayInvestorBody:
    'मैं वाणिज्यिक अचल संपत्ति खरीदने की तैयारी कर रहा हूं और मुझे एक संचालन टीम चाहिए।',
  gatewayGeneralTitle: 'सामान्य पूछताछ',
  gatewayGeneralBody: 'कुछ और। विक्रेता, प्रेस, रोजगार या कोई प्रश्न।',

  propertyTypeMultifamily: 'बहु-पारिवारिक',
  propertyTypeRetail: 'खुदरा',
  propertyTypeMixedPortfolio: 'मिश्रित पोर्टफोलियो',
  propertyTypeAnother: 'अन्य प्रकार की संपत्ति',
  propertyScopeOne: 'एक संपत्ति',
  propertyScopePortfolio: 'पोर्टफोलियो',

  situationReplace: 'वर्तमान प्रबंधन बदलना',
  situationMoveAway: 'स्वयं प्रबंधन से हटना',
  situationRecentlyAcquired: 'हाल ही में खरीदी गई या अनुबंध के अधीन',
  situationLeaseUp: 'किराये पर देने की शुरुआत या स्थिति सुधारना',
  situationOperations: 'संचालन या रिपोर्टिंग से जुड़ी समस्याएं',
  situationExploring: 'प्रबंधन विकल्प देख रहे हैं',
  situationSomethingElse: 'कुछ और',

  involvementPm: 'संपत्ति प्रबंधन',
  involvementPmHint: 'संपत्ति का रोजमर्रा का संचालन।',
  involvementPmAm: 'संपत्ति प्रबंधन + परिसंपत्ति प्रबंधन',
  involvementPmAmHint: 'संपत्ति का संचालन और निवेश रणनीति तय करने में सहायता।',
  involvementNotSure: 'निश्चित नहीं',
  involvementNotSureHint: 'उपयुक्त स्तर तय करने में मेरी सहायता करें।',

  timingImmediately: 'तुरंत',
  timingWithin30: '30 दिनों के भीतर',
  timing30to60: '30 से 60 दिन',
  timing60to90: '60 से 90 दिन',
  timingStillExploring: 'अभी विचार कर रहे हैं',

  investorTopicFirstAcquisition: 'अपनी पहली खरीद पर विचार कर रहा हूं',
  investorTopicUnderContract: 'अभी अनुबंध के अधीन',
  investorTopicActivelySearching: 'सक्रिय रूप से खोज रहे हैं',
  investorTopicOwnProperty: 'संपत्ति है, संचालन टीम चाहिए',
  investorTopicSomethingElse: 'कुछ और',
  generalTopicQuestion: 'AxisPoint के बारे में एक प्रश्न',
  generalTopicVendor: 'विक्रेता या सेवा प्रदाता',
  generalTopicEmployment: 'रोजगार',
  generalTopicPress: 'प्रेस या मीडिया',
  generalTopicSomethingElse: 'कुछ और',

  bookingModePhone: 'फोन कॉल',
  bookingModeVideo: 'वीडियो बैठक',

  scaleUnitsLabel: 'अनुमानित इकाइयां',
  scaleUnitsPlaceholder: 'उदाहरण के लिए 184',
  scaleUnitsHelp:
    'एक मोटा आंकड़ा पर्याप्त है। हम संचालन टीम का आकार तय कर रहे हैं, किराया रिकॉर्ड की जांच नहीं।',
  scaleSqftLabel: 'अनुमानित क्षेत्रफल, वर्ग फुट',
  scaleSqftPlaceholder: 'उदाहरण के लिए 42,000',
  scaleSqftHelp: 'कुल किराये योग्य क्षेत्र यहां सबसे उपयोगी आंकड़ा है।',
  scaleMixedLabel: 'अनुमानित संयुक्त आकार',
  scaleMixedPlaceholder: 'उदाहरण के लिए 300 इकाइयां और 40,000 वर्ग फुट',
  scaleMixedHelp:
    'इकाइयां, वर्ग फुट या दोनों। जिस रूप में आप हिसाब रखते हैं, उसी में बताएं।',
  scaleOtherLabel: 'अनुमानित आकार',
  scaleOtherPlaceholder: 'इकाइयां, वर्ग फुट या कोई अन्य माप',
  scaleOtherHelp: 'इस प्रकार की संपत्ति के लिए जो माप उपयुक्त हो, उसी में आकार बताएं।',
  scaleFallbackLabel: 'अनुमानित आकार',
  scaleFallbackPlaceholder: 'इकाइयां या वर्ग फुट',
  scaleFallbackHelp: 'ऊपर संपत्ति का प्रकार चुनें और यह सही माप के अनुसार बदल जाएगा।',

  investorKicker: 'निवेशक सेवाएं',
  investorTitle: 'बताएं कि आप प्रक्रिया में कहां हैं।',
  investorLead:
    'शुरू करने के लिए एक छोटा सा नोट पर्याप्त है। बातचीत तय करने के लिए हम संपर्क करेंगे।',
  investorTopicLabel: 'आप प्रक्रिया में कहां हैं?',
  investorNoteLabel: 'आप किस पर विचार कर रहे हैं?',
  investorNotePlaceholder: 'परिसंपत्ति का प्रकार, बाजार या समय-सीमा',
  generalKicker: 'सामान्य पूछताछ',
  generalTitle: 'हम किसमें सहायता कर सकते हैं?',
  generalLead:
    'बताएं कि आप कौन हैं और आपको क्या चाहिए। हम इसे सही साझेदार तक पहुंचाएंगे।',
  generalTopicLabel: 'यह किस बारे में है?',
  generalNoteLabel: 'आपका संदेश',
  generalNotePlaceholder: 'कुछ वाक्य पर्याप्त हैं',
  organizationLabel: 'कंपनी',
  submitLabel: 'पूछताछ भेजें',

  nameHelp: 'आप चाहते हैं कि हम आपको किस नाम से संबोधित करें।',
  nameError: 'वह नाम दर्ज करें जो हमें कॉल करते समय पूछना चाहिए।',
  emailHelp: 'जहां हम अपना उत्तर और आगे की जानकारी भेजेंगे।',
  emailError:
    'इस पते में @ चिह्न के बाद का हिस्सा नहीं है। पूरा पता दर्ज करें, उदाहरण के लिए name@company.com।',
  topicError: 'वह विकल्प चुनें जो आपकी पूछताछ का सबसे सही वर्णन करता हो।',
  followUpSameAsPage: 'इस पृष्ठ के समान, हिन्दी',
  selectOne: 'एक चुनें',
  notSpecified: 'नहीं बताया गया',

  bookingCandidateNote:
    'समय सेंट्रल टाइम, ह्यूस्टन में दिखाया गया है। उपलब्धता की पुष्टि बुकिंग के समय होती है।',
  bookingSlotTaken: 'वह समय अब उपलब्ध नहीं है। कृपया दूसरा चुनें।',
  bookingFailed: 'हम उस समय की पुष्टि नहीं कर सके। कुछ भी बुक नहीं हुआ। फिर से प्रयास करें।',
  bookingRefused: 'हम उस समय को बुक नहीं कर सके, और दोबारा प्रयास करने से मदद नहीं मिलेगी।',
  bookingUnavailable: 'अभी बुकिंग उपलब्ध नहीं है। कुछ भी बुक नहीं हुआ।',
  bookingDurationLabel: '30 मिनट',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'संपत्ति प्रबंधन',
  navAssetManagement: 'परिसंपत्ति प्रबंधन',
  navInvestorServices: 'निवेशक सेवाएं',
  navPartners: 'साझेदार',
  navContact: 'संपर्क',
  navCta: 'प्रबंधन प्रस्ताव का अनुरोध करें',
  navHomeAria: 'AxisPoint, मुखपृष्ठ',
  navPrimaryAria: 'मुख्य',
  navMenu: 'मेन्यू',
  navMenuDialogAria: 'साइट मेन्यू',
  navCloseMenu: 'मेन्यू बंद करें',

  skipToContent: 'मुख्य सामग्री पर जाएं',

  footerPositioning:
    'पहले संपत्ति प्रबंधन, और जब संपत्ति को ऊपर एक रणनीतिक परत की जरूरत हो तो परिसंपत्ति प्रबंधन भी उपलब्ध।',
  footerServices: 'सेवाएं',
  footerFirm: 'फर्म',
  footerLocation: 'ह्यूस्टन, टेक्सास',
  footerStatewide: 'पूरे टेक्सास में संपत्ति स्वामियों की सेवा',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'ब्रोकरेज और लीजिंग गतिविधियां हमारे लाइसेंस प्राप्त साझेदार के माध्यम से संचालित होती हैं। AxisPoint Partners कर या कानूनी सलाह नहीं देता। यह वेबसाइट केवल सूचना के उद्देश्य से है और प्रतिभूतियां बेचने का प्रस्ताव नहीं है।',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'पृष्ठ नहीं मिला',
  notFoundAction: 'मुखपृष्ठ पर जाएं',
  languageChooseAria: 'भाषा चुनें। वर्तमान भाषा: {language}।',
  languageListAria: 'भाषा चुनें',

  /* ══ Marketing pages (PR 3) ══
   * Proper nouns preserved in Latin script: AxisPoint and both partner names. Place names
   * use established Devanagari forms (ह्यूस्टन, टेक्सास, डलास, फोर्ट वर्थ, सैन एंटोनियो, ऑस्टिन).
   * REVIEWER QUESTION carried over from the chrome: the real-estate vocabulary here leans
   * Sanskritic, and a Houston Hindi business reader may simply use the English terms. */

  partnersSignature: 'Zachary Russell और Ethaniel Vu, साझेदार।',
  pmRunsAmDirectsTitle:
    'संपत्ति प्रबंधन संपत्ति का संचालन करता है। परिसंपत्ति प्रबंधन निवेश की दिशा तय करता है।',

  homeMetaTitle: 'AxisPoint Partners | टेक्सास में वाणिज्यिक संपत्ति प्रबंधन',
  homeMetaDescription:
    'AxisPoint पूरे टेक्सास में स्वामियों के लिए बहु-पारिवारिक और खुदरा संपत्तियों का प्रबंधन करता है, साइट पर संचालन और वित्तीय नियंत्रण से लेकर विक्रेता प्रदर्शन और स्वामी रिपोर्टिंग तक।',
  homeHeroAlt: 'सूर्यास्त के समय बहु-पारिवारिक परिसर का लॉन और भवन का अग्रभाग',
  homeHeroTitle: 'आपकी संपत्ति कैसे चलती है, इसके लिए एक जवाबदेह टीम।',
  homeHeroLead:
    'AxisPoint पूरे टेक्सास में स्वामियों के लिए बहु-पारिवारिक और खुदरा संपत्तियों का प्रबंधन करता है, साइट पर संचालन और वित्तीय नियंत्रण से लेकर विक्रेता प्रदर्शन और उन रिपोर्टों तक जिन्हें स्वामी वास्तव में पढ़ते हैं।',
  homeHeroQuietLink: 'देखें कि हम किसकी जिम्मेदारी लेते हैं',
  homeHeroSignature: 'ह्यूस्टन से साझेदारों Zachary Russell और Ethaniel Vu के नेतृत्व में।',
  homeStripEyebrow: 'पहले संपत्ति प्रबंधन',
  homeStripBody:
    'मुख्य फोकस: पूरे टेक्सास में बहु-पारिवारिक और खुदरा संपत्तियां। मुख्यालय ह्यूस्टन में।',
  homeWhyTitle: 'स्वामी AxisPoint को क्यों बुलाते हैं',
  homeWhyLead: 'आमतौर पर चार स्थितियों में से एक।',
  homeWhySituationManager: 'मौजूदा प्रबंधक स्वामित्व का भरोसा खो चुका है।',
  homeWhySituationSelf: 'स्वयं प्रबंधन दूसरी नौकरी बन गया है।',
  homeWhySituationAcquired:
    'हाल ही में खरीदी गई संपत्ति को पहला महीना बंद होने से पहले एक संचालन टीम चाहिए।',
  homeWhyOr: 'या',
  homeWhySituationReports: 'रिपोर्ट समय पर आती हैं और फिर भी संपत्ति की स्थिति नहीं बतातीं।',
  homeWhyBody:
    'चारों के नीचे सवाल एक ही है: आज संपत्ति के लिए कौन जवाब दे रहा है। AxisPoint इसका उत्तर एक जवाबदेह टीम और दो ऐसे साझेदारों से देता है जो काम के इतने करीब हैं कि संपत्ति को नाम से जानते हैं।',
  homeWhyLink: 'AxisPoint किसकी जिम्मेदारी लेता है',
  homeStrategicEyebrow: 'रणनीतिक परत',
  homeStrategicBody:
    'उन स्वामियों के लिए जो संचालन कार्य के ऊपर स्वामित्व-स्तर का दृष्टिकोण चाहते हैं, AxisPoint संपत्ति के प्रदर्शन को बजट, पूंजी प्राथमिकताओं और होल्ड के निर्णयों से जोड़ता है। जब संपत्ति को इसकी जरूरत हो तभी लिया जाता है, इसे मानक रूप में नहीं बेचा जाता।',
  homeInvestorEyebrow: 'एक अलग रास्ता',
  homeInvestorBody:
    'बिना संचालन टीम के वाणिज्यिक अचल संपत्ति में उतर रहे हैं? निवेशक सेवाएं इसका प्रवेश मार्ग हैं।',
  homeClosingTitle: 'बताएं कि संपत्ति को आगे क्या चाहिए।',
  homeClosingBody:
    'संपत्ति, मौजूदा प्रबंधन की स्थिति और जो बदलाव आप सोच रहे हैं, वह भेजें। एक साझेदार उसे पढ़कर उत्तर देता है।',

  pmMetaTitle: 'ह्यूस्टन और पूरे टेक्सास में संपत्ति प्रबंधन | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint टेक्सास में बहु-पारिवारिक और खुदरा संपत्तियों की संचालन जिम्मेदारी लेता है: साइट पर संचालन, वित्तीय नियंत्रण, विक्रेता प्रदर्शन और स्वामी रिपोर्टिंग।',
  pmHeroTitle: 'ह्यूस्टन और पूरे टेक्सास में वाणिज्यिक संपत्ति प्रबंधन',
  pmHeroLead:
    'AxisPoint बहु-पारिवारिक और खुदरा संपत्तियों की संचालन जिम्मेदारी लेता है: साइट की टीम, पैसा, विक्रेता, और वे रिपोर्ट जिनसे स्वामी निर्णय लेते हैं।',
  pmSeeFunctions: 'चार संचालन कार्य देखें',
  pmPhotoAlt: 'टेक्सास के एक बहु-पारिवारिक परिसर और साथ लगे खुदरा केंद्र का हवाई दृश्य',
  pmResponsibilityTitle: 'AxisPoint किसकी जिम्मेदारी लेता है',
  pmResponsibilityBody:
    'वह सब कुछ जो तय करता है कि संपत्ति रोज कैसे चलती है, और उसका एक स्वामी-मुखी रिकॉर्ड। जब संपत्ति पर कुछ गलत होता है, तो स्वामियों को यह पता नहीं लगाना पड़ता कि किसे फोन करें।',
  pmFunctionsTitle: 'चार संचालन कार्य, एक जवाबदेह टीम',
  pmFnOnsiteTitle: 'साइट पर संचालन',
  pmFnOnsiteLede:
    'संपत्ति पर मौजूद लोग और वे नियम जिनका वे पालन करते हैं। स्टाफ के निर्णय, किराये की निगरानी, प्रतिक्रिया मानक और तैयारी की समय-सारणी जो संपत्ति को हर सप्ताह योजना पर बनाए रखती है।',
  pmFnOnsiteItem1: 'साइट पर स्टाफ और पर्यवेक्षण',
  pmFnOnsiteItem2: 'किराये की निगरानी',
  pmFnOnsiteItem3: 'निवासी और किरायेदार प्रतिक्रिया',
  pmFnOnsiteItem4: 'खाली होना और दोबारा तैयारी',
  pmFnOnsiteItem5: 'निवारक रखरखाव',
  pmFnFinancialTitle: 'वित्तीय नियंत्रण',
  pmFnFinancialLede:
    'स्वामित्व के साथ बनाए गए बजट, पहले से तय स्वीकृति सीमाएं, और ऐसा मासिक समापन जिसमें हर आंकड़ा उसके पीछे के निर्णय तक वापस खोजा जा सके।',
  pmFnFinancialItem1: 'वार्षिक बजट और पुनःपूर्वानुमान',
  pmFnFinancialItem2: 'स्वीकृति सीमाएं',
  pmFnFinancialItem3: 'वसूली और बकाया',
  pmFnFinancialItem4: 'देय राशि और माह-अंत समापन',
  pmFnFinancialItem5: 'अंतर का स्पष्टीकरण',
  pmFnVendorTitle: 'विक्रेता प्रदर्शन',
  pmFnVendorLede:
    'स्पष्ट दायरे वाला काम, वास्तविक बोली अनुशासन, और ऐसा अनुवर्तन जिसे टिकट बंद होने से नहीं, परिणाम की गुणवत्ता से मापा जाता है।',
  pmFnVendorItem1: 'दायरा और बोली प्रक्रिया',
  pmFnVendorItem2: 'अनुबंध और बीमा अनुपालन',
  pmFnVendorItem3: 'गुणवत्ता सत्यापन',
  pmFnVendorItem4: 'पूंजी परियोजना समन्वय',
  pmFnReportingTitle: 'स्वामी रिपोर्टिंग और संवाद',
  pmFnReportingLede:
    'संपत्ति पर क्या हुआ, उसकी लागत कितनी रही और आगे क्या है, इसका एक रिकॉर्ड, साथ ही एक साझेदार जो रिपोर्टिंग अवधियों के बीच भी उत्तर देता है।',
  pmFnReportingItem1: 'मासिक रिपोर्टिंग पैकेज',
  pmFnReportingItem2: 'संचालन विवरण',
  pmFnReportingItem3: 'पूंजी और परियोजना ट्रैकिंग',
  pmFnReportingItem4: 'साझेदार तक सीधी पहुंच',
  pmStrengthsTitle: 'AxisPoint कहां सबसे मजबूत है',
  pmStrengthsBody:
    'ये वे स्थितियां हैं जिनके लिए यह टीम बनी है। ये आवश्यकताएं नहीं, बल्कि मजबूती के क्षेत्र हैं, और इनसे बाहर की संपत्ति पर भी बातचीत सार्थक है।',
  pmStrengthTypesTitle: 'संपत्ति के प्रकार',
  pmStrengthTypesItem1: 'बहु-पारिवारिक मुख्य फोकस के रूप में',
  pmStrengthTypesItem2: 'खुदरा मुख्य फोकस के रूप में',
  pmStrengthTypesItem3: 'ऐसी संपत्तियां जो साइट पर स्टाफ रख सकें',
  pmStrengthTypesItem4: 'एक ही स्वामी के अंतर्गत समन्वित पोर्टफोलियो',
  pmStrengthTypesItem5: 'बिखरी हुई संपत्तियों का एक ही कार्यक्रम के रूप में संचालन',
  pmStrengthGeographyTitle: 'भूगोल',
  pmStrengthGeographyItem1: 'ह्यूस्टन और आसपास का महानगरीय क्षेत्र',
  pmStrengthGeographyItem2: 'डलास और फोर्ट वर्थ',
  pmStrengthGeographyItem3: 'सैन एंटोनियो',
  pmStrengthGeographyItem4: 'ऑस्टिन',
  pmStrengthGeographyItem5: 'पूरे टेक्सास में स्वामी',
  pmStrengthAssignmentsTitle: 'कार्यभार',
  pmStrengthAssignmentsItem1: 'प्रबंधन का हस्तांतरण',
  pmStrengthAssignmentsItem2: 'किराये की शुरुआत',
  pmStrengthAssignmentsItem3: 'भारी पूंजी कार्यक्रम',
  pmStrengthAssignmentsItem4: 'टाले गए संचालन संबंधी मसले',
  pmStrengthAssignmentsItem5: 'स्थिति सुधारने के कार्यभार',
  pmQuestionsTitle: 'बदलने से पहले स्वामी जो प्रश्न पूछते हैं',
  pmQ1: 'प्रबंधन के हस्तांतरण में कितना समय लगता है?',
  pmA1: 'यह संपत्ति और जाने वाले प्रबंधक पर निर्भर करता है, लेकिन योजना शुरुआत की तारीख से पहले लिख ली जाती है: स्टाफ, सिस्टम, बैंकिंग, विक्रेता रिकॉर्ड और निवासी या किरायेदार संवाद, हर एक का एक जिम्मेदार व्यक्ति और तारीख होती है।',
  pmQ2: 'मेरी संपत्ति के लिए वास्तव में कौन जवाब देगा?',
  pmA2: 'एक साझेदार। Zachary Russell और Ethaniel Vu काम के इतने करीब रहते हैं कि संपत्ति को नाम से जानते हैं, और उन तक पहुंचने के लिए स्वामियों को किसी खाता-परत से नहीं गुजरना पड़ता।',
  pmQ3: 'महीने-दर-महीने रिपोर्टिंग कैसी दिखती है?',
  pmA3: 'एक सुसंगत समय-सारणी पर एक सुसंगत पैकेज, जिसमें लिखित विवरण अंतर को समझाता है, बजाय इसके कि स्वामी आंकड़ों की व्याख्या अकेले करें।',
  pmQ4: 'क्या आप टाले गए मसलों वाली संपत्ति ले सकते हैं?',
  pmA4: 'हां। टाला गया रखरखाव, अधूरा पूंजी कार्य और स्टाफ की कमी, स्वामियों के संपर्क करने के सामान्य कारण हैं। प्रस्ताव में बताया जाता है कि पहले क्या और किस क्रम में संभाला जाएगा।',
  pmRelatedEyebrow: 'संबंधित',
  pmRelatedAsset:
    'परिसंपत्ति प्रबंधन संचालन कार्य के ऊपर है, उन स्वामियों के लिए जो निवेश का दृष्टिकोण चाहते हैं',
  pmRelatedInvestor:
    'निवेशक सेवाएं उन पूंजी-तैयार ग्राहकों का प्रवेश मार्ग हैं जिनके पास संचालन टीम नहीं है',
  pmClosingTitle: 'हमें संपत्ति और स्थिति भेजें।',
  pmClosingBody:
    'एक प्रबंधन प्रस्ताव में स्टाफ, रिपोर्टिंग पैकेज, हस्तांतरण योजना, और यह शामिल होता है कि AxisPoint में संपत्ति के लिए कौन जवाब देता है।',

  amMetaTitle: 'टेक्सास के संपत्ति स्वामियों के लिए परिसंपत्ति प्रबंधन | AxisPoint Partners',
  amMetaDescription:
    'संचालन कार्य के ऊपर स्वामित्व-स्तर का दृष्टिकोण: पूंजी प्राथमिकताएं, बजट की दिशा और होल्ड के निर्णय, उसी टीम की जानकारी पर आधारित जो पहले से संपत्ति चला रही है।',
  amHeroTitle: 'टेक्सास के संपत्ति स्वामियों के लिए परिसंपत्ति प्रबंधन',
  amHeroAnswer:
    'संचालन कार्य के ऊपर स्वामित्व-स्तर का दृष्टिकोण: पूंजी प्राथमिकताएं, बजट की दिशा और होल्ड के निर्णय, ऐसी टीम की जानकारी पर आधारित जो पहले से संपत्ति चला रही है।',
  amPhotoAlt: 'सड़क के स्तर से दिखता ह्यूस्टन डाउनटाउन का टॉवर और ऊपर बना पैदल मार्ग',
  amRelationshipEyebrow: 'यह रिश्ता',
  amRelationshipBody:
    'परिसंपत्ति प्रबंधन संचालन कार्य के ऊपर की एक परत है, उसका विकल्प नहीं। यह जोड़ता है कि संपत्ति सप्ताह-दर-सप्ताह क्या कर रही है, बजट, पूंजी प्राथमिकताओं और रखें-या-बेचें की बातचीत से। स्वामी इसे तब लेते हैं जब संपत्ति को इसकी जरूरत हो।',
  amLayersTitle: 'दो परतें, साफ शब्दों में',
  amDecidesEyebrow: 'परिसंपत्ति प्रबंधन तय करता है',
  amDecidesItem1: 'पूंजी प्राथमिकताएं और उनका क्रम',
  amDecidesItem2: 'बजट की दिशा और पुनःपूर्वानुमान का रुख',
  amDecidesItem3: 'रखने, पुनर्वित्त और बिक्री के प्रश्न',
  amDecidesItem4: 'स्वामित्व के इरादे के सापेक्ष प्रदर्शन की समीक्षा',
  amExecutesEyebrow: 'संपत्ति प्रबंधन क्रियान्वित करता है',
  amExecutesItem1: 'साइट पर संचालन और स्टाफ',
  amExecutesItem2: 'वित्तीय नियंत्रण और मासिक समापन',
  amExecutesItem3: 'विक्रेता का दायरा और प्रदर्शन',
  amExecutesItem4: 'स्वामी रिपोर्टिंग और संवाद',
  amClosingTitle: 'संपत्ति से शुरू करें, फिर ऊपर की परत जोड़ें।',
  amClosingBody:
    'अधिकांश स्वामी संपत्ति प्रबंधन से शुरू करते हैं। परिसंपत्ति प्रबंधन तब जोड़ा जाता है जब निवेश के प्रश्नों का उत्तर उसी टीम से चाहिए।',

  isMetaTitle:
    'टेक्सास की वाणिज्यिक अचल संपत्ति के लिए निवेशक सेवाएं | AxisPoint Partners',
  isMetaDescription:
    'उन पूंजी-तैयार ग्राहकों के लिए जो टेक्सास में बहु-पारिवारिक या खुदरा संपत्ति खरीद रहे हैं और चाहते हैं कि संचालन पक्ष खरीद से पहले तय हो, बाद में नहीं।',
  isHeroTitle:
    'संचालन टीम के साथ टेक्सास की वाणिज्यिक अचल संपत्ति में प्रवेश का रास्ता',
  isHeroAnswer:
    'उन पूंजी-तैयार ग्राहकों के लिए जो टेक्सास में बहु-पारिवारिक या खुदरा संपत्ति खरीद रहे हैं और चाहते हैं कि संचालन पक्ष खरीद से पहले तय हो, बाद में नहीं।',
  isPhotoAlt: 'ह्यूस्टन में एक राजमार्ग इंटरचेंज का हवाई दृश्य',
  isWhoEyebrow: 'यह किसके लिए है',
  isWhoLead: 'ऐसे पूंजी-तैयार ग्राहक जिन्हें कदम उठाने से पहले एक संचालन टीम चाहिए।',
  isWhoBody:
    'निवेशक सेवाएं तीनों रास्तों में सबसे छोटी हैं और जानबूझकर वैसी ही रहती हैं। यह उन स्वामियों के लिए है जो वाणिज्यिक अचल संपत्ति में, या टेक्सास में, प्रवेश कर रहे हैं और चाहते हैं कि संचालन पक्ष पहली संपत्ति से ही संभाला जाए, न कि सौदा पूरा होने के बाद जोड़ा जाए।',
  isTimelineBeforeLabel: 'खरीद से पहले',
  isTimelineBeforeBody:
    'संपत्ति को चलाने में क्या लगेगा, इसका एक संचालन आकलन, ताकि प्रस्ताव के पीछे की धारणाएं वही हों जो एक प्रबंधक इस्तेमाल करेगा।',
  isTimelineClosingLabel: 'सौदे के समय',
  isTimelineClosingBody:
    'पहले दिन से एक प्रबंधन टीम तैयार, जिसमें स्टाफ, सिस्टम और विक्रेता संबंध लंबित नहीं बल्कि तैयार हों।',
  isTimelineAfterLabel: 'पहली संपत्ति के बाद',
  isTimelineAfterBody:
    'संबंध संपत्ति प्रबंधन में चला जाता है, और यदि स्वामित्व का दृष्टिकोण मांगे तो परिसंपत्ति प्रबंधन भी जुड़ता है।',
  isClosingTitle: 'बताएं कि आप क्या खरीदना चाहते हैं।',
  isClosingBody:
    'संपत्ति का प्रकार, बाजार और समय-सीमा भेजें। एक साझेदार संचालन आकलन के साथ उत्तर देता है और बताता है कि प्रबंधन कैसा दिखेगा।',
  isClosingCta: 'खरीद पर चर्चा करें',

  partnersMetaTitle: 'साझेदार | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint ह्यूस्टन से साझेदारों के नेतृत्व में चलता है। Zachary Russell और Ethaniel Vu उन संपत्तियों पर बने रहते हैं जो वे लेते हैं, इसलिए स्वामी निर्णय लेने वालों से सीधे बात करते हैं।',
  partnersHeroTitle: 'दो साझेदार, काम के लिए सीधे जवाबदेह',
  partnersHeroAnswer:
    'AxisPoint ह्यूस्टन से साझेदारों के नेतृत्व में चलता है। जो काम लेते हैं, वही उस पर बने रहते हैं।',
  partnersRoleLabel: 'साझेदार',
  partnerRussellBody:
    'सीधे संचालन प्रदर्शन पर काम करते हैं: स्टाफ के निर्णय, हस्तांतरण, पूंजी कार्यक्रम, और पोर्टफोलियो की वे संपत्तियां जिन पर इस महीने ध्यान चाहिए।',
  partnerVuBody:
    'सीधे वित्तीय नियंत्रण और स्वामी-मुखी रिकॉर्ड पर काम करते हैं: बजट, स्वीकृति अनुशासन, मासिक समापन, और वे रिपोर्ट जिनसे स्वामी निर्णय लेते हैं।',
  partnersHowEyebrow: 'हम कैसे काम करते हैं',
  partnersHowBody:
    'दोनों साझेदार उन संपत्तियों पर बने रहते हैं जो वे लेते हैं। स्वामी निर्णय लेने वालों से बात करते हैं, उनके आगे खड़ी की गई किसी परत से नहीं।',
  partnersClosingTitle: 'अपनी संपत्ति के बारे में किसी साझेदार से बात करें।',
  partnersClosingBody:
    'संपत्ति और स्थिति भेजें। जो साझेदार उसे पढ़ता है, वही उसके लिए जवाब देगा।',
};
