import type { Messages } from '../../messages';

/**
 * PUNJABI (GURMUKHI). AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Punjabi has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `pa` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * SCRIPT. Gurmukhi, matching the registry's `Noto Sans Gurmukhi` stack and the `ਪੰਜਾਬੀ` native
 * name. Punjabi is also written in Shahmukhi (Perso-Arabic, RTL) by most Punjabi speakers in
 * Pakistan. The approved design chose Gurmukhi and lists `pa` as `direction: 'ltr'`, so this
 * file is Gurmukhi only. IF the intended Houston readership is substantially Pakistani
 * Punjabi, this is the wrong script and no amount of correcting the sentences below fixes
 * that. It is an audience decision for the owner, not a translation note, and it is recorded
 * in `docs/STATUS.md` rather than left implicit here.
 *
 * GENDER. First-person verbs agree with the speaker's gender and the visitor's is unknown;
 * the masculine default is used (`ਕਰ ਰਿਹਾ ਹਾਂ`). A reviewer should choose.
 *
 * LINE HEIGHT. 1.55 in the registry. Gurmukhi sits below a headline stroke with matras above
 * and below it, and clips at Latin leading. Check rendered output.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const PA: Partial<Messages> = {
  gatewayTitle: 'ਤੁਸੀਂ ਕਿਸ ਬਾਰੇ ਗੱਲ ਕਰਨੀ ਚਾਹੋਗੇ?',
  gatewayLead:
    'ਉਹ ਵਿਕਲਪ ਚੁਣੋ ਜੋ ਤੁਹਾਡੀ ਸਥਿਤੀ ਨਾਲ ਸਭ ਤੋਂ ਵੱਧ ਮੇਲ ਖਾਂਦਾ ਹੈ। ਤੁਸੀਂ ਬਾਅਦ ਵਿੱਚ ਬਦਲ ਸਕਦੇ ਹੋ।',
  gatewayOwnerKicker: 'ਬਹੁਤੇ ਮਾਲਕ ਇੱਥੋਂ ਹੀ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ',
  gatewayOwnerTitle: 'ਜਾਇਦਾਦ ਦੇ ਮਾਲਕ',
  gatewayOwnerBody: 'ਮੇਰੇ ਕੋਲ ਜਾਇਦਾਦ ਹੈ ਜਾਂ ਮੈਂ ਇਸ ਦੀ ਦੇਖਭਾਲ ਕਰਦਾ ਹਾਂ ਅਤੇ ਮੈਨੂੰ ਪ੍ਰਬੰਧਨ ਦੀ ਲੋੜ ਹੈ।',
  gatewayOwnerAction: 'ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਸ਼ੁਰੂ ਕਰੋ',
  gatewayAssetTitle: 'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  gatewayAssetBody:
    'ਮੇਰੇ ਕੋਲ ਜਾਇਦਾਦ ਹੈ ਅਤੇ ਮੈਨੂੰ ਰਣਨੀਤੀ, ਕਾਰਗੁਜ਼ਾਰੀ ਅਤੇ ਰਿਪੋਰਟਿੰਗ ਦੀ ਦਿਸ਼ਾ ਤੈਅ ਕਰਨ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।',
  gatewayInvestorTitle: 'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ',
  gatewayInvestorBody:
    'ਮੈਂ ਵਪਾਰਕ ਜਾਇਦਾਦ ਖਰੀਦਣ ਦੀ ਤਿਆਰੀ ਕਰ ਰਿਹਾ ਹਾਂ ਅਤੇ ਮੈਨੂੰ ਸੰਚਾਲਨ ਟੀਮ ਚਾਹੀਦੀ ਹੈ।',
  gatewayGeneralTitle: 'ਆਮ ਪੁੱਛਗਿੱਛ',
  gatewayGeneralBody: 'ਕੁਝ ਹੋਰ। ਵਿਕਰੇਤਾ, ਪ੍ਰੈਸ, ਰੁਜ਼ਗਾਰ ਜਾਂ ਕੋਈ ਸਵਾਲ।',

  propertyTypeMultifamily: 'ਬਹੁ-ਪਰਿਵਾਰਕ',
  propertyTypeRetail: 'ਪਰਚੂਨ',
  propertyTypeMixedPortfolio: 'ਮਿਸ਼ਰਤ ਪੋਰਟਫੋਲੀਓ',
  propertyTypeAnother: 'ਹੋਰ ਕਿਸਮ ਦੀ ਜਾਇਦਾਦ',
  propertyScopeOne: 'ਇੱਕ ਜਾਇਦਾਦ',
  propertyScopePortfolio: 'ਪੋਰਟਫੋਲੀਓ',

  situationReplace: 'ਮੌਜੂਦਾ ਪ੍ਰਬੰਧਨ ਬਦਲਣਾ',
  situationMoveAway: 'ਆਪ ਪ੍ਰਬੰਧਨ ਕਰਨਾ ਛੱਡਣਾ',
  situationRecentlyAcquired: 'ਹਾਲ ਹੀ ਵਿੱਚ ਖਰੀਦੀ ਜਾਂ ਸਮਝੌਤੇ ਅਧੀਨ',
  situationLeaseUp: 'ਕਿਰਾਏ ਦੀ ਸ਼ੁਰੂਆਤ ਜਾਂ ਕਾਰਗੁਜ਼ਾਰੀ ਸੁਧਾਰ',
  situationOperations: 'ਸੰਚਾਲਨ ਜਾਂ ਰਿਪੋਰਟਿੰਗ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ',
  situationExploring: 'ਪ੍ਰਬੰਧਨ ਦੇ ਵਿਕਲਪ ਵੇਖ ਰਹੇ ਹਾਂ',
  situationSomethingElse: 'ਕੁਝ ਹੋਰ',

  involvementPm: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ',
  involvementPmHint: 'ਜਾਇਦਾਦ ਦਾ ਰੋਜ਼ਾਨਾ ਸੰਚਾਲਨ।',
  involvementPmAm: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ + ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  involvementPmAmHint: 'ਜਾਇਦਾਦ ਦਾ ਸੰਚਾਲਨ ਅਤੇ ਨਿਵੇਸ਼ ਰਣਨੀਤੀ ਤੈਅ ਕਰਨ ਵਿੱਚ ਮਦਦ।',
  involvementNotSure: 'ਪੱਕਾ ਪਤਾ ਨਹੀਂ',
  involvementNotSureHint: 'ਢੁਕਵਾਂ ਪੱਧਰ ਤੈਅ ਕਰਨ ਵਿੱਚ ਮੇਰੀ ਮਦਦ ਕਰੋ।',

  timingImmediately: 'ਤੁਰੰਤ',
  timingWithin30: '30 ਦਿਨਾਂ ਵਿੱਚ',
  timing30to60: '30 ਤੋਂ 60 ਦਿਨ',
  timing60to90: '60 ਤੋਂ 90 ਦਿਨ',
  timingStillExploring: 'ਅਜੇ ਵਿਚਾਰ ਕਰ ਰਹੇ ਹਾਂ',

  investorTopicFirstAcquisition: 'ਆਪਣੀ ਪਹਿਲੀ ਖਰੀਦ ਬਾਰੇ ਵਿਚਾਰ ਕਰ ਰਿਹਾ ਹਾਂ',
  investorTopicUnderContract: 'ਇਸ ਵੇਲੇ ਸਮਝੌਤੇ ਅਧੀਨ',
  investorTopicActivelySearching: 'ਸਰਗਰਮੀ ਨਾਲ ਲੱਭ ਰਹੇ ਹਾਂ',
  investorTopicOwnProperty: 'ਜਾਇਦਾਦ ਹੈ, ਸੰਚਾਲਨ ਟੀਮ ਚਾਹੀਦੀ ਹੈ',
  investorTopicSomethingElse: 'ਕੁਝ ਹੋਰ',
  generalTopicQuestion: 'AxisPoint ਬਾਰੇ ਇੱਕ ਸਵਾਲ',
  generalTopicVendor: 'ਵਿਕਰੇਤਾ ਜਾਂ ਸੇਵਾ ਪ੍ਰਦਾਤਾ',
  generalTopicEmployment: 'ਰੁਜ਼ਗਾਰ',
  generalTopicPress: 'ਪ੍ਰੈਸ ਜਾਂ ਮੀਡੀਆ',
  generalTopicSomethingElse: 'ਕੁਝ ਹੋਰ',

  bookingModePhone: 'ਫ਼ੋਨ ਕਾਲ',
  bookingModeVideo: 'ਵੀਡੀਓ ਮੀਟਿੰਗ',

  scaleUnitsLabel: 'ਅੰਦਾਜ਼ਨ ਯੂਨਿਟ',
  scaleUnitsPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 184',
  scaleUnitsHelp:
    'ਮੋਟਾ ਅੰਕੜਾ ਕਾਫ਼ੀ ਹੈ। ਅਸੀਂ ਸੰਚਾਲਨ ਟੀਮ ਦਾ ਆਕਾਰ ਤੈਅ ਕਰ ਰਹੇ ਹਾਂ, ਕਿਰਾਏ ਦੇ ਰਿਕਾਰਡ ਦੀ ਜਾਂਚ ਨਹੀਂ।',
  scaleSqftLabel: 'ਅੰਦਾਜ਼ਨ ਖੇਤਰਫਲ, ਵਰਗ ਫੁੱਟ',
  scaleSqftPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 42,000',
  scaleSqftHelp: 'ਕੁੱਲ ਕਿਰਾਏ ਯੋਗ ਖੇਤਰ ਇੱਥੇ ਸਭ ਤੋਂ ਲਾਭਦਾਇਕ ਅੰਕੜਾ ਹੈ।',
  scaleMixedLabel: 'ਅੰਦਾਜ਼ਨ ਸੰਯੁਕਤ ਆਕਾਰ',
  scaleMixedPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 300 ਯੂਨਿਟ ਅਤੇ 40,000 ਵਰਗ ਫੁੱਟ',
  scaleMixedHelp: 'ਯੂਨਿਟ, ਵਰਗ ਫੁੱਟ ਜਾਂ ਦੋਵੇਂ। ਜਿਸ ਤਰ੍ਹਾਂ ਤੁਸੀਂ ਹਿਸਾਬ ਰੱਖਦੇ ਹੋ, ਉਸੇ ਤਰ੍ਹਾਂ ਦੱਸੋ।',
  scaleOtherLabel: 'ਅੰਦਾਜ਼ਨ ਆਕਾਰ',
  scaleOtherPlaceholder: 'ਯੂਨਿਟ, ਵਰਗ ਫੁੱਟ ਜਾਂ ਕੋਈ ਹੋਰ ਮਾਪ',
  scaleOtherHelp: 'ਇਸ ਕਿਸਮ ਦੀ ਜਾਇਦਾਦ ਲਈ ਜੋ ਮਾਪ ਢੁਕਵਾਂ ਹੋਵੇ, ਉਸੇ ਵਿੱਚ ਆਕਾਰ ਦੱਸੋ।',
  scaleFallbackLabel: 'ਅੰਦਾਜ਼ਨ ਆਕਾਰ',
  scaleFallbackPlaceholder: 'ਯੂਨਿਟ ਜਾਂ ਵਰਗ ਫੁੱਟ',
  scaleFallbackHelp: 'ਉੱਪਰ ਜਾਇਦਾਦ ਦੀ ਕਿਸਮ ਚੁਣੋ, ਇਹ ਸਹੀ ਮਾਪ ਅਨੁਸਾਰ ਬਦਲ ਜਾਵੇਗਾ।',

  investorKicker: 'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ',
  investorTitle: 'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਕਿੱਥੇ ਹੋ।',
  investorLead: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਛੋਟਾ ਜਿਹਾ ਨੋਟ ਕਾਫ਼ੀ ਹੈ। ਗੱਲਬਾਤ ਤੈਅ ਕਰਨ ਲਈ ਅਸੀਂ ਸੰਪਰਕ ਕਰਾਂਗੇ।',
  investorTopicLabel: 'ਤੁਸੀਂ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਕਿੱਥੇ ਹੋ?',
  investorNoteLabel: 'ਤੁਸੀਂ ਕਿਸ ਬਾਰੇ ਵਿਚਾਰ ਕਰ ਰਹੇ ਹੋ?',
  investorNotePlaceholder: 'ਸੰਪਤੀ ਦੀ ਕਿਸਮ, ਬਾਜ਼ਾਰ ਜਾਂ ਸਮਾਂ-ਸੀਮਾ',
  generalKicker: 'ਆਮ ਪੁੱਛਗਿੱਛ',
  generalTitle: 'ਅਸੀਂ ਕਿਸ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?',
  generalLead:
    'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕੌਣ ਹੋ ਅਤੇ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ। ਅਸੀਂ ਇਸਨੂੰ ਸਹੀ ਭਾਈਵਾਲ ਤੱਕ ਪਹੁੰਚਾਵਾਂਗੇ।',
  generalTopicLabel: 'ਇਹ ਕਿਸ ਬਾਰੇ ਹੈ?',
  generalNoteLabel: 'ਤੁਹਾਡਾ ਸੁਨੇਹਾ',
  generalNotePlaceholder: 'ਕੁਝ ਵਾਕ ਕਾਫ਼ੀ ਹਨ',
  organizationLabel: 'ਕੰਪਨੀ',
  submitLabel: 'ਪੁੱਛਗਿੱਛ ਭੇਜੋ',

  nameHelp: 'ਤੁਸੀਂ ਚਾਹੁੰਦੇ ਹੋ ਕਿ ਅਸੀਂ ਤੁਹਾਨੂੰ ਕਿਸ ਨਾਮ ਨਾਲ ਸੰਬੋਧਿਤ ਕਰੀਏ।',
  nameError: 'ਉਹ ਨਾਮ ਦਰਜ ਕਰੋ ਜੋ ਸਾਨੂੰ ਕਾਲ ਕਰਨ ਵੇਲੇ ਪੁੱਛਣਾ ਚਾਹੀਦਾ ਹੈ।',
  emailHelp: 'ਜਿੱਥੇ ਅਸੀਂ ਆਪਣਾ ਜਵਾਬ ਅਤੇ ਅੱਗੇ ਦੀ ਜਾਣਕਾਰੀ ਭੇਜਾਂਗੇ।',
  emailError:
    'ਇਸ ਪਤੇ ਵਿੱਚ @ ਨਿਸ਼ਾਨ ਤੋਂ ਬਾਅਦ ਵਾਲਾ ਹਿੱਸਾ ਨਹੀਂ ਹੈ। ਪੂਰਾ ਪਤਾ ਦਰਜ ਕਰੋ, ਉਦਾਹਰਨ ਲਈ name@company.com।',
  topicError: 'ਉਹ ਵਿਕਲਪ ਚੁਣੋ ਜੋ ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਨੂੰ ਸਭ ਤੋਂ ਵਧੀਆ ਦੱਸਦਾ ਹੈ।',
  followUpSameAsPage: 'ਇਸ ਪੰਨੇ ਵਾਂਗ, ਪੰਜਾਬੀ',
  selectOne: 'ਇੱਕ ਚੁਣੋ',
  notSpecified: 'ਨਹੀਂ ਦੱਸਿਆ ਗਿਆ',

  bookingCandidateNote:
    'ਸਮਾਂ ਸੈਂਟਰਲ ਟਾਈਮ, ਹਿਊਸਟਨ ਵਿੱਚ ਦਿਖਾਇਆ ਗਿਆ ਹੈ। ਉਪਲਬਧਤਾ ਦੀ ਪੁਸ਼ਟੀ ਬੁਕਿੰਗ ਵੇਲੇ ਹੁੰਦੀ ਹੈ।',
  bookingSlotTaken: 'ਉਹ ਸਮਾਂ ਹੁਣ ਉਪਲਬਧ ਨਹੀਂ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਹੋਰ ਚੁਣੋ।',
  bookingFailed: 'ਅਸੀਂ ਉਸ ਸਮੇਂ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ ਕਰ ਸਕੇ। ਕੁਝ ਵੀ ਬੁੱਕ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  bookingRefused: 'ਅਸੀਂ ਉਹ ਸਮਾਂ ਬੁੱਕ ਨਹੀਂ ਕਰ ਸਕੇ, ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰਨ ਨਾਲ ਮਦਦ ਨਹੀਂ ਮਿਲੇਗੀ।',
  bookingUnavailable: 'ਇਸ ਵੇਲੇ ਸਮਾਂ ਤੈਅ ਕਰਨਾ ਉਪਲਬਧ ਨਹੀਂ। ਕੁਝ ਵੀ ਬੁੱਕ ਨਹੀਂ ਹੋਇਆ।',
  bookingDurationLabel: '30 ਮਿੰਟ',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ',
  navAssetManagement: 'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  navInvestorServices: 'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ',
  navPartners: 'ਭਾਈਵਾਲ',
  navContact: 'ਸੰਪਰਕ',
  navCta: 'ਪ੍ਰਬੰਧਨ ਪ੍ਰਸਤਾਵ ਦੀ ਬੇਨਤੀ ਕਰੋ',
  navHomeAria: 'AxisPoint, ਹੋਮ',
  navPrimaryAria: 'ਮੁੱਖ',
  navMenu: 'ਮੀਨੂ',
  navMenuDialogAria: 'ਸਾਈਟ ਮੀਨੂ',
  navCloseMenu: 'ਮੀਨੂ ਬੰਦ ਕਰੋ',

  skipToContent: 'ਮੁੱਖ ਸਮੱਗਰੀ ਤੇ ਜਾਓ',

  footerPositioning:
    'ਪਹਿਲਾਂ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ, ਅਤੇ ਜਦੋਂ ਜਾਇਦਾਦ ਨੂੰ ਉੱਪਰ ਇੱਕ ਰਣਨੀਤਕ ਪਰਤ ਦੀ ਲੋੜ ਹੋਵੇ ਤਾਂ ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਵੀ ਉਪਲਬਧ।',
  footerServices: 'ਸੇਵਾਵਾਂ',
  footerFirm: 'ਫਰਮ',
  footerLocation: 'ਹਿਊਸਟਨ, ਟੈਕਸਾਸ',
  footerStatewide: 'ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਮਾਲਕਾਂ ਦੀ ਸੇਵਾ',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'ਬ੍ਰੋਕਰੇਜ ਅਤੇ ਲੀਜ਼ਿੰਗ ਗਤੀਵਿਧੀਆਂ ਸਾਡੇ ਲਾਇਸੰਸਸ਼ੁਦਾ ਭਾਈਵਾਲ ਰਾਹੀਂ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ। AxisPoint Partners ਟੈਕਸ ਜਾਂ ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ ਦਿੰਦਾ। ਇਹ ਵੈੱਬਸਾਈਟ ਸਿਰਫ਼ ਜਾਣਕਾਰੀ ਦੇ ਉਦੇਸ਼ ਲਈ ਹੈ ਅਤੇ ਪ੍ਰਤੀਭੂਤੀਆਂ ਵੇਚਣ ਦੀ ਪੇਸ਼ਕਸ਼ ਨਹੀਂ ਹੈ।',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'ਪੰਨਾ ਨਹੀਂ ਮਿਲਿਆ',
  notFoundAction: 'ਹੋਮ ਤੇ ਜਾਓ',
  languageChooseAria: 'ਭਾਸ਼ਾ ਚੁਣੋ। ਮੌਜੂਦਾ ਭਾਸ਼ਾ: {language}।',
  languageListAria: 'ਭਾਸ਼ਾ ਚੁਣੋ',

  /* ══ Marketing pages (PR 3) ══
   * Proper nouns preserved in Latin script: AxisPoint and both partner names, matching every
   * other locale and `PartnersPage.tsx`, which renders the names in Latin regardless of
   * locale. Place names use established Gurmukhi forms: ਹਿਊਸਟਨ, ਟੈਕਸਾਸ, ਡੈਲਸ, ਫੋਰਟ ਵਰਥ,
   * ਸੈਨ ਐਂਟੋਨੀਓ, ਔਸਟਿਨ. The Gurmukhi-versus-Shahmukhi audience question in the file header
   * applies to all of this copy, not only the chrome. */

  partnersSignature: 'Zachary Russell ਅਤੇ Ethaniel Vu, ਭਾਈਵਾਲ।',
  pmRunsAmDirectsTitle:
    'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ ਜਾਇਦਾਦ ਚਲਾਉਂਦਾ ਹੈ। ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਨਿਵੇਸ਼ ਦੀ ਦਿਸ਼ਾ ਤੈਅ ਕਰਦਾ ਹੈ।',

  homeMetaTitle: 'AxisPoint Partners | ਟੈਕਸਾਸ ਵਿੱਚ ਵਪਾਰਕ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ',
  homeMetaDescription:
    'AxisPoint ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਮਾਲਕਾਂ ਲਈ ਬਹੁ-ਪਰਿਵਾਰਕ ਅਤੇ ਪਰਚੂਨ ਜਾਇਦਾਦਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਦਾ ਹੈ, ਮੌਕੇ ਦੇ ਕੰਮਕਾਜ ਅਤੇ ਵਿੱਤੀ ਨਿਯੰਤਰਣ ਤੋਂ ਲੈ ਕੇ ਵਿਕਰੇਤਾ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ ਅਤੇ ਮਾਲਕਾਂ ਨੂੰ ਦਿੱਤੀ ਜਾਂਦੀ ਰਿਪੋਰਟਿੰਗ ਤੱਕ।',
  homeHeroAlt: 'ਸੂਰਜ ਡੁੱਬਣ ਵੇਲੇ ਬਹੁ-ਪਰਿਵਾਰਕ ਕੰਪਲੈਕਸ ਦਾ ਲਾਅਨ ਅਤੇ ਇਮਾਰਤ ਦਾ ਅਗਲਾ ਹਿੱਸਾ',
  homeHeroTitle: 'ਤੁਹਾਡੀ ਜਾਇਦਾਦ ਕਿਵੇਂ ਚੱਲਦੀ ਹੈ, ਇਸ ਲਈ ਇੱਕ ਜ਼ਿੰਮੇਵਾਰ ਟੀਮ।',
  homeHeroLead:
    'AxisPoint ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਮਾਲਕਾਂ ਲਈ ਬਹੁ-ਪਰਿਵਾਰਕ ਅਤੇ ਪਰਚੂਨ ਜਾਇਦਾਦਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਦਾ ਹੈ, ਮੌਕੇ ਦੇ ਕੰਮਕਾਜ ਅਤੇ ਵਿੱਤੀ ਨਿਯੰਤਰਣ ਤੋਂ ਲੈ ਕੇ ਵਿਕਰੇਤਾ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ ਅਤੇ ਉਹਨਾਂ ਰਿਪੋਰਟਾਂ ਤੱਕ ਜੋ ਮਾਲਕ ਅਸਲ ਵਿੱਚ ਪੜ੍ਹਦੇ ਹਨ।',
  homeHeroQuietLink: 'ਵੇਖੋ ਅਸੀਂ ਕਿਸ ਦੀ ਜ਼ਿੰਮੇਵਾਰੀ ਲੈਂਦੇ ਹਾਂ',
  homeHeroSignature: 'ਹਿਊਸਟਨ ਤੋਂ ਭਾਈਵਾਲਾਂ Zachary Russell ਅਤੇ Ethaniel Vu ਦੀ ਅਗਵਾਈ ਵਿੱਚ।',
  homeStripEyebrow: 'ਪਹਿਲਾਂ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ',
  homeStripBody:
    'ਮੁੱਖ ਧਿਆਨ: ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਬਹੁ-ਪਰਿਵਾਰਕ ਅਤੇ ਪਰਚੂਨ ਜਾਇਦਾਦਾਂ। ਮੁੱਖ ਦਫ਼ਤਰ ਹਿਊਸਟਨ ਵਿੱਚ।',
  homeWhyTitle: 'ਮਾਲਕ AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਿਉਂ ਕਰਦੇ ਹਨ',
  homeWhyLead: 'ਆਮ ਤੌਰ ਤੇ ਚਾਰ ਹਾਲਾਤਾਂ ਵਿੱਚੋਂ ਇੱਕ।',
  homeWhySituationManager: 'ਮੌਜੂਦਾ ਪ੍ਰਬੰਧਕ ਮਾਲਕਾਂ ਦਾ ਭਰੋਸਾ ਗੁਆ ਚੁੱਕਾ ਹੈ।',
  homeWhySituationSelf: 'ਆਪ ਪ੍ਰਬੰਧਨ ਕਰਨਾ ਦੂਜੀ ਨੌਕਰੀ ਬਣ ਗਿਆ ਹੈ।',
  homeWhySituationAcquired:
    'ਹਾਲ ਹੀ ਵਿੱਚ ਖਰੀਦੀ ਜਾਇਦਾਦ ਨੂੰ ਪਹਿਲਾ ਮਹੀਨਾ ਮੁੱਕਣ ਤੋਂ ਪਹਿਲਾਂ ਸੰਚਾਲਨ ਟੀਮ ਚਾਹੀਦੀ ਹੈ।',
  homeWhyOr: 'ਜਾਂ',
  homeWhySituationReports: 'ਰਿਪੋਰਟਾਂ ਸਮੇਂ ਸਿਰ ਆਉਂਦੀਆਂ ਹਨ ਅਤੇ ਫਿਰ ਵੀ ਜਾਇਦਾਦ ਦੀ ਹਾਲਤ ਨਹੀਂ ਦੱਸਦੀਆਂ।',
  homeWhyBody:
    'ਚਾਰਾਂ ਦੇ ਹੇਠਾਂ ਸਵਾਲ ਇੱਕੋ ਹੀ ਹੈ: ਅੱਜ ਜਾਇਦਾਦ ਲਈ ਜਵਾਬ ਕੌਣ ਦੇ ਰਿਹਾ ਹੈ। AxisPoint ਇਸ ਦਾ ਜਵਾਬ ਇੱਕ ਜ਼ਿੰਮੇਵਾਰ ਟੀਮ ਅਤੇ ਦੋ ਅਜਿਹੇ ਭਾਈਵਾਲਾਂ ਨਾਲ ਦਿੰਦਾ ਹੈ ਜੋ ਕੰਮ ਦੇ ਇੰਨੇ ਨੇੜੇ ਹਨ ਕਿ ਜਾਇਦਾਦ ਨੂੰ ਨਾਮ ਤੋਂ ਜਾਣਦੇ ਹਨ।',
  homeWhyLink: 'AxisPoint ਕਿਸ ਦੀ ਜ਼ਿੰਮੇਵਾਰੀ ਲੈਂਦਾ ਹੈ',
  homeStrategicEyebrow: 'ਰਣਨੀਤਕ ਪਰਤ',
  homeStrategicBody:
    'ਉਹਨਾਂ ਮਾਲਕਾਂ ਲਈ ਜੋ ਸੰਚਾਲਨ ਕੰਮ ਤੋਂ ਉੱਪਰ ਮਾਲਕੀ-ਪੱਧਰ ਦਾ ਨਜ਼ਰੀਆ ਚਾਹੁੰਦੇ ਹਨ, AxisPoint ਜਾਇਦਾਦ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ ਨੂੰ ਬਜਟ, ਪੂੰਜੀ ਤਰਜੀਹਾਂ ਅਤੇ ਰੱਖਣ ਦੇ ਫੈਸਲਿਆਂ ਨਾਲ ਜੋੜਦਾ ਹੈ। ਜਦੋਂ ਜਾਇਦਾਦ ਨੂੰ ਲੋੜ ਹੋਵੇ ਤਦ ਹੀ ਲਿਆ ਜਾਂਦਾ ਹੈ, ਇਸਨੂੰ ਮਿਆਰ ਵਜੋਂ ਨਹੀਂ ਵੇਚਿਆ ਜਾਂਦਾ।',
  homeInvestorEyebrow: 'ਇੱਕ ਵੱਖਰਾ ਰਾਹ',
  homeInvestorBody:
    'ਸੰਚਾਲਨ ਟੀਮ ਤੋਂ ਬਿਨਾਂ ਵਪਾਰਕ ਜਾਇਦਾਦ ਵਿੱਚ ਆ ਰਹੇ ਹੋ? ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ ਹੀ ਦਾਖਲੇ ਦਾ ਰਾਹ ਹਨ।',
  homeClosingTitle: 'ਦੱਸੋ ਕਿ ਜਾਇਦਾਦ ਨੂੰ ਅੱਗੇ ਕੀ ਚਾਹੀਦਾ ਹੈ।',
  homeClosingBody:
    'ਜਾਇਦਾਦ, ਪ੍ਰਬੰਧਨ ਦੀ ਮੌਜੂਦਾ ਹਾਲਤ, ਅਤੇ ਜੋ ਤਬਦੀਲੀ ਤੁਸੀਂ ਸੋਚ ਰਹੇ ਹੋ, ਭੇਜੋ। ਇੱਕ ਭਾਈਵਾਲ ਇਸਨੂੰ ਪੜ੍ਹ ਕੇ ਜਵਾਬ ਦਿੰਦਾ ਹੈ।',

  pmMetaTitle: 'ਹਿਊਸਟਨ ਅਤੇ ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint ਟੈਕਸਾਸ ਵਿੱਚ ਬਹੁ-ਪਰਿਵਾਰਕ ਅਤੇ ਪਰਚੂਨ ਜਾਇਦਾਦਾਂ ਦੀ ਸੰਚਾਲਨ ਜ਼ਿੰਮੇਵਾਰੀ ਲੈਂਦਾ ਹੈ: ਮੌਕੇ ਦਾ ਕੰਮਕਾਜ, ਵਿੱਤੀ ਨਿਯੰਤਰਣ, ਵਿਕਰੇਤਾ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ ਅਤੇ ਮਾਲਕਾਂ ਨੂੰ ਰਿਪੋਰਟਿੰਗ।',
  pmHeroTitle: 'ਹਿਊਸਟਨ ਅਤੇ ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਵਪਾਰਕ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ',
  pmHeroLead:
    'AxisPoint ਬਹੁ-ਪਰਿਵਾਰਕ ਅਤੇ ਪਰਚੂਨ ਜਾਇਦਾਦਾਂ ਦੀ ਸੰਚਾਲਨ ਜ਼ਿੰਮੇਵਾਰੀ ਲੈਂਦਾ ਹੈ: ਮੌਕੇ ਦੀ ਟੀਮ, ਪੈਸਾ, ਵਿਕਰੇਤਾ, ਅਤੇ ਉਹ ਰਿਪੋਰਟਾਂ ਜਿਨ੍ਹਾਂ ਨਾਲ ਮਾਲਕ ਫੈਸਲੇ ਲੈਂਦੇ ਹਨ।',
  pmSeeFunctions: 'ਚਾਰ ਸੰਚਾਲਨ ਕਾਰਜ ਵੇਖੋ',
  pmPhotoAlt: 'ਟੈਕਸਾਸ ਦੇ ਬਹੁ-ਪਰਿਵਾਰਕ ਕੰਪਲੈਕਸ ਅਤੇ ਨਾਲ ਲੱਗਦੇ ਪਰਚੂਨ ਕੇਂਦਰ ਦਾ ਹਵਾਈ ਦ੍ਰਿਸ਼',
  pmResponsibilityTitle: 'AxisPoint ਕਿਸ ਦੀ ਜ਼ਿੰਮੇਵਾਰੀ ਲੈਂਦਾ ਹੈ',
  pmResponsibilityBody:
    'ਹਰ ਉਹ ਚੀਜ਼ ਜੋ ਤੈਅ ਕਰਦੀ ਹੈ ਕਿ ਜਾਇਦਾਦ ਰੋਜ਼ ਕਿਵੇਂ ਚੱਲਦੀ ਹੈ, ਅਤੇ ਉਸ ਦਾ ਮਾਲਕਾਂ ਲਈ ਇੱਕ ਹੀ ਰਿਕਾਰਡ। ਜਦੋਂ ਜਾਇਦਾਦ ਤੇ ਕੁਝ ਗਲਤ ਹੁੰਦਾ ਹੈ, ਮਾਲਕਾਂ ਨੂੰ ਇਹ ਲੱਭਣਾ ਨਹੀਂ ਪੈਂਦਾ ਕਿ ਕਿਸ ਨੂੰ ਫ਼ੋਨ ਕਰਨਾ ਹੈ।',
  pmFunctionsTitle: 'ਚਾਰ ਸੰਚਾਲਨ ਕਾਰਜ, ਇੱਕ ਜ਼ਿੰਮੇਵਾਰ ਟੀਮ',
  pmFnOnsiteTitle: 'ਮੌਕੇ ਦਾ ਕੰਮਕਾਜ',
  pmFnOnsiteLede:
    'ਜਾਇਦਾਦ ਤੇ ਮੌਜੂਦ ਲੋਕ ਅਤੇ ਉਹ ਨਿਯਮ ਜਿਨ੍ਹਾਂ ਤੇ ਉਹ ਕਾਇਮ ਰਹਿੰਦੇ ਹਨ। ਸਟਾਫ਼ ਦੇ ਫੈਸਲੇ, ਕਿਰਾਏ ਦੀ ਨਿਗਰਾਨੀ, ਜਵਾਬਦੇਹੀ ਦੇ ਮਿਆਰ, ਅਤੇ ਤਿਆਰੀ ਦੇ ਸਮਾਂ-ਸਾਰਣੀ ਜੋ ਜਾਇਦਾਦ ਨੂੰ ਹਰ ਹਫ਼ਤੇ ਯੋਜਨਾ ਮੁਤਾਬਕ ਰੱਖਦੇ ਹਨ।',
  pmFnOnsiteItem1: 'ਮੌਕੇ ਤੇ ਸਟਾਫ਼ ਅਤੇ ਨਿਗਰਾਨੀ',
  pmFnOnsiteItem2: 'ਕਿਰਾਏ ਦੀ ਨਿਗਰਾਨੀ',
  pmFnOnsiteItem3: 'ਵਸਨੀਕਾਂ ਅਤੇ ਕਿਰਾਏਦਾਰਾਂ ਦਾ ਜਵਾਬ',
  pmFnOnsiteItem4: 'ਖਾਲੀ ਹੋਣਾ ਅਤੇ ਮੁੜ ਤਿਆਰੀ',
  pmFnOnsiteItem5: 'ਬਚਾਅ ਸੰਭਾਲ',
  pmFnFinancialTitle: 'ਵਿੱਤੀ ਨਿਯੰਤਰਣ',
  pmFnFinancialLede:
    'ਮਾਲਕਾਂ ਨਾਲ ਬਣਾਏ ਬਜਟ, ਪਹਿਲਾਂ ਤੋਂ ਤੈਅ ਮਨਜ਼ੂਰੀ ਦੀਆਂ ਹੱਦਾਂ, ਅਤੇ ਅਜਿਹਾ ਮਹੀਨਾਵਾਰ ਸਮਾਪਨ ਜਿਸ ਵਿੱਚ ਹਰ ਅੰਕੜਾ ਉਸ ਦੇ ਪਿੱਛੇ ਦੇ ਫੈਸਲੇ ਤੱਕ ਵਾਪਸ ਲੱਭਿਆ ਜਾ ਸਕੇ।',
  pmFnFinancialItem1: 'ਸਾਲਾਨਾ ਬਜਟ ਅਤੇ ਮੁੜ-ਅਨੁਮਾਨ',
  pmFnFinancialItem2: 'ਮਨਜ਼ੂਰੀ ਦੀਆਂ ਹੱਦਾਂ',
  pmFnFinancialItem3: 'ਵਸੂਲੀ ਅਤੇ ਬਕਾਇਆ',
  pmFnFinancialItem4: 'ਦੇਣਯੋਗ ਰਕਮਾਂ ਅਤੇ ਮਹੀਨੇ ਦੇ ਅੰਤ ਦਾ ਸਮਾਪਨ',
  pmFnFinancialItem5: 'ਫ਼ਰਕ ਦੀ ਵਿਆਖਿਆ',
  pmFnVendorTitle: 'ਵਿਕਰੇਤਾ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ',
  pmFnVendorLede:
    'ਸਪਸ਼ਟ ਦਾਇਰੇ ਵਾਲਾ ਕੰਮ, ਅਸਲੀ ਬੋਲੀ ਦਾ ਅਨੁਸ਼ਾਸਨ, ਅਤੇ ਅਜਿਹੀ ਪੈਰਵੀ ਜੋ ਟਿਕਟ ਬੰਦ ਹੋਣ ਨਾਲ ਨਹੀਂ ਸਗੋਂ ਨਤੀਜੇ ਦੀ ਗੁਣਵੱਤਾ ਨਾਲ ਮਾਪੀ ਜਾਂਦੀ ਹੈ।',
  pmFnVendorItem1: 'ਦਾਇਰਾ ਅਤੇ ਬੋਲੀ ਪ੍ਰਕਿਰਿਆ',
  pmFnVendorItem2: 'ਇਕਰਾਰਨਾਮਾ ਅਤੇ ਬੀਮਾ ਪਾਲਣਾ',
  pmFnVendorItem3: 'ਗੁਣਵੱਤਾ ਦੀ ਪੁਸ਼ਟੀ',
  pmFnVendorItem4: 'ਪੂੰਜੀ ਪ੍ਰੋਜੈਕਟ ਤਾਲਮੇਲ',
  pmFnReportingTitle: 'ਮਾਲਕਾਂ ਨੂੰ ਰਿਪੋਰਟਿੰਗ ਅਤੇ ਸੰਪਰਕ',
  pmFnReportingLede:
    'ਇੱਕ ਰਿਕਾਰਡ ਕਿ ਜਾਇਦਾਦ ਤੇ ਕੀ ਹੋਇਆ, ਉਸ ਤੇ ਕਿੰਨਾ ਖਰਚ ਆਇਆ ਅਤੇ ਅੱਗੇ ਕੀ ਹੈ, ਨਾਲ ਹੀ ਇੱਕ ਭਾਈਵਾਲ ਜੋ ਰਿਪੋਰਟਿੰਗ ਦੇ ਸਮਿਆਂ ਵਿਚਕਾਰ ਵੀ ਜਵਾਬ ਦਿੰਦਾ ਹੈ।',
  pmFnReportingItem1: 'ਮਹੀਨਾਵਾਰ ਰਿਪੋਰਟਿੰਗ ਪੈਕੇਜ',
  pmFnReportingItem2: 'ਸੰਚਾਲਨ ਵੇਰਵਾ',
  pmFnReportingItem3: 'ਪੂੰਜੀ ਅਤੇ ਪ੍ਰੋਜੈਕਟ ਟਰੈਕਿੰਗ',
  pmFnReportingItem4: 'ਭਾਈਵਾਲ ਤੱਕ ਸਿੱਧੀ ਪਹੁੰਚ',
  pmStrengthsTitle: 'AxisPoint ਕਿੱਥੇ ਸਭ ਤੋਂ ਮਜ਼ਬੂਤ ਹੈ',
  pmStrengthsBody:
    'ਇਹ ਉਹ ਹਾਲਾਤ ਹਨ ਜਿਨ੍ਹਾਂ ਲਈ ਇਹ ਟੀਮ ਬਣੀ ਹੈ। ਇਹ ਸ਼ਰਤਾਂ ਨਹੀਂ ਸਗੋਂ ਮਜ਼ਬੂਤੀ ਦੇ ਖੇਤਰ ਹਨ, ਅਤੇ ਇਨ੍ਹਾਂ ਤੋਂ ਬਾਹਰ ਦੀ ਜਾਇਦਾਦ ਬਾਰੇ ਵੀ ਗੱਲ ਕਰਨੀ ਬਣਦੀ ਹੈ।',
  pmStrengthTypesTitle: 'ਜਾਇਦਾਦ ਦੀਆਂ ਕਿਸਮਾਂ',
  pmStrengthTypesItem1: 'ਬਹੁ-ਪਰਿਵਾਰਕ ਮੁੱਖ ਧਿਆਨ ਵਜੋਂ',
  pmStrengthTypesItem2: 'ਪਰਚੂਨ ਮੁੱਖ ਧਿਆਨ ਵਜੋਂ',
  pmStrengthTypesItem3: 'ਅਜਿਹੀਆਂ ਜਾਇਦਾਦਾਂ ਜੋ ਮੌਕੇ ਤੇ ਸਟਾਫ਼ ਰੱਖ ਸਕਣ',
  pmStrengthTypesItem4: 'ਇੱਕੋ ਮਾਲਕ ਹੇਠ ਤਾਲਮੇਲ ਵਾਲੇ ਪੋਰਟਫੋਲੀਓ',
  pmStrengthTypesItem5: 'ਖਿੰਡੀਆਂ ਜਾਇਦਾਦਾਂ ਨੂੰ ਇੱਕੋ ਪ੍ਰੋਗਰਾਮ ਵਜੋਂ ਚਲਾਉਣਾ',
  pmStrengthGeographyTitle: 'ਭੂਗੋਲ',
  pmStrengthGeographyItem1: 'ਹਿਊਸਟਨ ਅਤੇ ਆਲੇ-ਦੁਆਲੇ ਦਾ ਮਹਾਂਨਗਰੀ ਖੇਤਰ',
  pmStrengthGeographyItem2: 'ਡੈਲਸ ਅਤੇ ਫੋਰਟ ਵਰਥ',
  pmStrengthGeographyItem3: 'ਸੈਨ ਐਂਟੋਨੀਓ',
  pmStrengthGeographyItem4: 'ਔਸਟਿਨ',
  pmStrengthGeographyItem5: 'ਪੂਰੇ ਟੈਕਸਾਸ ਵਿੱਚ ਮਾਲਕ',
  pmStrengthAssignmentsTitle: 'ਕੰਮ ਦੀਆਂ ਕਿਸਮਾਂ',
  pmStrengthAssignmentsItem1: 'ਪ੍ਰਬੰਧਨ ਦਾ ਤਬਾਦਲਾ',
  pmStrengthAssignmentsItem2: 'ਕਿਰਾਏ ਦੀ ਸ਼ੁਰੂਆਤ',
  pmStrengthAssignmentsItem3: 'ਵੱਡੇ ਪੂੰਜੀ ਪ੍ਰੋਗਰਾਮ',
  pmStrengthAssignmentsItem4: 'ਟਾਲੀਆਂ ਗਈਆਂ ਸੰਚਾਲਨ ਸਮੱਸਿਆਵਾਂ',
  pmStrengthAssignmentsItem5: 'ਹਾਲਾਤ ਸੁਧਾਰਨ ਦੇ ਕੰਮ',
  pmQuestionsTitle: 'ਬਦਲਣ ਤੋਂ ਪਹਿਲਾਂ ਮਾਲਕ ਜੋ ਸਵਾਲ ਪੁੱਛਦੇ ਹਨ',
  pmQ1: 'ਪ੍ਰਬੰਧਨ ਦੇ ਤਬਾਦਲੇ ਵਿੱਚ ਕਿੰਨਾ ਸਮਾਂ ਲੱਗਦਾ ਹੈ?',
  pmA1: 'ਇਹ ਜਾਇਦਾਦ ਅਤੇ ਜਾ ਰਹੇ ਪ੍ਰਬੰਧਕ ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ, ਪਰ ਯੋਜਨਾ ਸ਼ੁਰੂਆਤੀ ਤਾਰੀਖ਼ ਤੋਂ ਪਹਿਲਾਂ ਲਿਖ ਲਈ ਜਾਂਦੀ ਹੈ: ਸਟਾਫ਼, ਸਿਸਟਮ, ਬੈਂਕਿੰਗ, ਵਿਕਰੇਤਾ ਰਿਕਾਰਡ, ਅਤੇ ਵਸਨੀਕਾਂ ਜਾਂ ਕਿਰਾਏਦਾਰਾਂ ਨਾਲ ਸੰਪਰਕ, ਹਰੇਕ ਦਾ ਇੱਕ ਜ਼ਿੰਮੇਵਾਰ ਅਤੇ ਇੱਕ ਤਾਰੀਖ਼ ਹੁੰਦੀ ਹੈ।',
  pmQ2: 'ਮੇਰੀ ਜਾਇਦਾਦ ਲਈ ਅਸਲ ਵਿੱਚ ਜਵਾਬ ਕੌਣ ਦੇਵੇਗਾ?',
  pmA2: 'ਇੱਕ ਭਾਈਵਾਲ। Zachary Russell ਅਤੇ Ethaniel Vu ਕੰਮ ਦੇ ਇੰਨੇ ਨੇੜੇ ਰਹਿੰਦੇ ਹਨ ਕਿ ਜਾਇਦਾਦ ਨੂੰ ਨਾਮ ਤੋਂ ਜਾਣਦੇ ਹਨ, ਅਤੇ ਉਹਨਾਂ ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਮਾਲਕਾਂ ਨੂੰ ਕਿਸੇ ਖਾਤਾ-ਪਰਤ ਵਿੱਚੋਂ ਲੰਘਣਾ ਨਹੀਂ ਪੈਂਦਾ।',
  pmQ3: 'ਮਹੀਨੇ-ਦਰ-ਮਹੀਨੇ ਰਿਪੋਰਟਿੰਗ ਕਿਹੋ ਜਿਹੀ ਹੁੰਦੀ ਹੈ?',
  pmA3: 'ਇੱਕ ਨਿਯਮਤ ਸਮਾਂ-ਸਾਰਣੀ ਤੇ ਇੱਕ ਨਿਯਮਤ ਪੈਕੇਜ, ਜਿਸ ਨਾਲ ਲਿਖਤੀ ਵੇਰਵਾ ਫ਼ਰਕਾਂ ਦੀ ਵਿਆਖਿਆ ਕਰਦਾ ਹੈ, ਨਾ ਕਿ ਮਾਲਕ ਅੰਕੜੇ ਆਪ ਸਮਝਣ।',
  pmQ4: 'ਕੀ ਤੁਸੀਂ ਟਾਲੀਆਂ ਸਮੱਸਿਆਵਾਂ ਵਾਲੀ ਜਾਇਦਾਦ ਸੰਭਾਲ ਸਕਦੇ ਹੋ?',
  pmA4: 'ਹਾਂ। ਟਾਲੀ ਗਈ ਸੰਭਾਲ, ਅਧੂਰਾ ਪੂੰਜੀ ਕੰਮ ਅਤੇ ਸਟਾਫ਼ ਦੀ ਘਾਟ, ਮਾਲਕਾਂ ਦੇ ਸੰਪਰਕ ਕਰਨ ਦੇ ਆਮ ਕਾਰਨ ਹਨ। ਪ੍ਰਸਤਾਵ ਵਿੱਚ ਦੱਸਿਆ ਜਾਂਦਾ ਹੈ ਕਿ ਪਹਿਲਾਂ ਕੀ ਅਤੇ ਕਿਸ ਕ੍ਰਮ ਵਿੱਚ ਕੀਤਾ ਜਾਵੇਗਾ।',
  pmRelatedEyebrow: 'ਸਬੰਧਿਤ',
  pmRelatedAsset:
    'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਸੰਚਾਲਨ ਕੰਮ ਤੋਂ ਉੱਪਰ ਹੈ, ਉਹਨਾਂ ਮਾਲਕਾਂ ਲਈ ਜੋ ਨਿਵੇਸ਼ ਦਾ ਨਜ਼ਰੀਆ ਚਾਹੁੰਦੇ ਹਨ',
  pmRelatedInvestor:
    'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ ਉਹਨਾਂ ਪੂੰਜੀ-ਤਿਆਰ ਗਾਹਕਾਂ ਦਾ ਦਾਖਲਾ ਰਾਹ ਹਨ ਜਿਨ੍ਹਾਂ ਕੋਲ ਸੰਚਾਲਨ ਟੀਮ ਨਹੀਂ',
  pmClosingTitle: 'ਸਾਨੂੰ ਜਾਇਦਾਦ ਅਤੇ ਹਾਲਾਤ ਭੇਜੋ।',
  pmClosingBody:
    'ਇੱਕ ਪ੍ਰਬੰਧਨ ਪ੍ਰਸਤਾਵ ਵਿੱਚ ਸਟਾਫ਼, ਰਿਪੋਰਟਿੰਗ ਪੈਕੇਜ, ਤਬਾਦਲੇ ਦੀ ਯੋਜਨਾ, ਅਤੇ ਇਹ ਸ਼ਾਮਲ ਹੁੰਦਾ ਹੈ ਕਿ AxisPoint ਵਿੱਚ ਜਾਇਦਾਦ ਲਈ ਜਵਾਬ ਕੌਣ ਦਿੰਦਾ ਹੈ।',

  amMetaTitle: 'ਟੈਕਸਾਸ ਦੇ ਜਾਇਦਾਦ ਮਾਲਕਾਂ ਲਈ ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ | AxisPoint Partners',
  amMetaDescription:
    'ਸੰਚਾਲਨ ਕੰਮ ਤੋਂ ਉੱਪਰ ਮਾਲਕੀ-ਪੱਧਰ ਦਾ ਨਜ਼ਰੀਆ: ਪੂੰਜੀ ਤਰਜੀਹਾਂ, ਬਜਟ ਦੀ ਦਿਸ਼ਾ ਅਤੇ ਰੱਖਣ ਦੇ ਫੈਸਲੇ, ਉਸੇ ਟੀਮ ਦੀ ਜਾਣਕਾਰੀ ਤੇ ਆਧਾਰਿਤ ਜੋ ਪਹਿਲਾਂ ਹੀ ਜਾਇਦਾਦ ਚਲਾ ਰਹੀ ਹੈ।',
  amHeroTitle: 'ਟੈਕਸਾਸ ਦੇ ਜਾਇਦਾਦ ਮਾਲਕਾਂ ਲਈ ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  amHeroAnswer:
    'ਸੰਚਾਲਨ ਕੰਮ ਤੋਂ ਉੱਪਰ ਮਾਲਕੀ-ਪੱਧਰ ਦਾ ਨਜ਼ਰੀਆ: ਪੂੰਜੀ ਤਰਜੀਹਾਂ, ਬਜਟ ਦੀ ਦਿਸ਼ਾ ਅਤੇ ਰੱਖਣ ਦੇ ਫੈਸਲੇ, ਅਜਿਹੀ ਟੀਮ ਦੀ ਜਾਣਕਾਰੀ ਤੇ ਆਧਾਰਿਤ ਜੋ ਪਹਿਲਾਂ ਹੀ ਜਾਇਦਾਦ ਚਲਾ ਰਹੀ ਹੈ।',
  amPhotoAlt: 'ਸੜਕ ਦੇ ਪੱਧਰ ਤੋਂ ਦਿਖਦਾ ਹਿਊਸਟਨ ਡਾਊਨਟਾਊਨ ਦਾ ਟਾਵਰ ਅਤੇ ਉੱਚਾ ਪੈਦਲ ਰਸਤਾ',
  amRelationshipEyebrow: 'ਇਹ ਰਿਸ਼ਤਾ',
  amRelationshipBody:
    'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਸੰਚਾਲਨ ਕੰਮ ਤੋਂ ਉੱਪਰ ਦੀ ਇੱਕ ਪਰਤ ਹੈ, ਇਸ ਦਾ ਬਦਲ ਨਹੀਂ। ਇਹ ਜੋੜਦਾ ਹੈ ਕਿ ਜਾਇਦਾਦ ਹਫ਼ਤੇ-ਦਰ-ਹਫ਼ਤੇ ਕੀ ਕਰ ਰਹੀ ਹੈ, ਬਜਟ, ਪੂੰਜੀ ਤਰਜੀਹਾਂ ਅਤੇ ਰੱਖਣ ਜਾਂ ਵੇਚਣ ਦੀ ਗੱਲਬਾਤ ਨਾਲ। ਮਾਲਕ ਇਸਨੂੰ ਤਦ ਲੈਂਦੇ ਹਨ ਜਦੋਂ ਜਾਇਦਾਦ ਨੂੰ ਲੋੜ ਹੋਵੇ।',
  amLayersTitle: 'ਦੋ ਪਰਤਾਂ, ਸਾਫ਼ ਸ਼ਬਦਾਂ ਵਿੱਚ',
  amDecidesEyebrow: 'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਫੈਸਲਾ ਕਰਦਾ ਹੈ',
  amDecidesItem1: 'ਪੂੰਜੀ ਤਰਜੀਹਾਂ ਅਤੇ ਉਹਨਾਂ ਦਾ ਕ੍ਰਮ',
  amDecidesItem2: 'ਬਜਟ ਦੀ ਦਿਸ਼ਾ ਅਤੇ ਮੁੜ-ਅਨੁਮਾਨ ਦਾ ਰੁਖ਼',
  amDecidesItem3: 'ਰੱਖਣ, ਮੁੜ-ਵਿੱਤ ਅਤੇ ਵੇਚਣ ਦੇ ਸਵਾਲ',
  amDecidesItem4: 'ਮਾਲਕਾਂ ਦੇ ਇਰਾਦੇ ਦੇ ਮੁਕਾਬਲੇ ਕਾਰਗੁਜ਼ਾਰੀ ਦੀ ਸਮੀਖਿਆ',
  amExecutesEyebrow: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ ਅਮਲ ਕਰਦਾ ਹੈ',
  amExecutesItem1: 'ਮੌਕੇ ਦਾ ਕੰਮਕਾਜ ਅਤੇ ਸਟਾਫ਼',
  amExecutesItem2: 'ਵਿੱਤੀ ਨਿਯੰਤਰਣ ਅਤੇ ਮਹੀਨਾਵਾਰ ਸਮਾਪਨ',
  amExecutesItem3: 'ਵਿਕਰੇਤਾ ਦਾ ਦਾਇਰਾ ਅਤੇ ਕਾਰਗੁਜ਼ਾਰੀ',
  amExecutesItem4: 'ਮਾਲਕਾਂ ਨੂੰ ਰਿਪੋਰਟਿੰਗ ਅਤੇ ਸੰਪਰਕ',
  amClosingTitle: 'ਜਾਇਦਾਦ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋ, ਫਿਰ ਉੱਪਰਲੀ ਪਰਤ ਜੋੜੋ।',
  amClosingBody:
    'ਬਹੁਤੇ ਮਾਲਕ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ ਤੋਂ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ। ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਤਦ ਜੋੜਿਆ ਜਾਂਦਾ ਹੈ ਜਦੋਂ ਨਿਵੇਸ਼ ਦੇ ਸਵਾਲਾਂ ਦਾ ਜਵਾਬ ਉਸੇ ਟੀਮ ਤੋਂ ਚਾਹੀਦਾ ਹੋਵੇ।',

  isMetaTitle: 'ਟੈਕਸਾਸ ਦੀ ਵਪਾਰਕ ਜਾਇਦਾਦ ਲਈ ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ | AxisPoint Partners',
  isMetaDescription:
    'ਟੈਕਸਾਸ ਵਿੱਚ ਬਹੁ-ਪਰਿਵਾਰਕ ਜਾਂ ਪਰਚੂਨ ਜਾਇਦਾਦ ਖਰੀਦ ਰਹੇ ਪੂੰਜੀ-ਤਿਆਰ ਗਾਹਕਾਂ ਲਈ, ਜੋ ਚਾਹੁੰਦੇ ਹਨ ਕਿ ਸੰਚਾਲਨ ਪੱਖ ਖਰੀਦ ਤੋਂ ਪਹਿਲਾਂ ਤੈਅ ਹੋਵੇ, ਬਾਅਦ ਵਿੱਚ ਨਹੀਂ।',
  isHeroTitle: 'ਸੰਚਾਲਨ ਟੀਮ ਨਾਲ ਟੈਕਸਾਸ ਦੀ ਵਪਾਰਕ ਜਾਇਦਾਦ ਵਿੱਚ ਦਾਖਲੇ ਦਾ ਰਾਹ',
  isHeroAnswer:
    'ਟੈਕਸਾਸ ਵਿੱਚ ਬਹੁ-ਪਰਿਵਾਰਕ ਜਾਂ ਪਰਚੂਨ ਜਾਇਦਾਦ ਖਰੀਦ ਰਹੇ ਪੂੰਜੀ-ਤਿਆਰ ਗਾਹਕਾਂ ਲਈ, ਜੋ ਚਾਹੁੰਦੇ ਹਨ ਕਿ ਸੰਚਾਲਨ ਪੱਖ ਖਰੀਦ ਤੋਂ ਪਹਿਲਾਂ ਤੈਅ ਹੋਵੇ, ਬਾਅਦ ਵਿੱਚ ਨਹੀਂ।',
  isPhotoAlt: 'ਹਿਊਸਟਨ ਵਿੱਚ ਇੱਕ ਹਾਈਵੇ ਇੰਟਰਚੇਂਜ ਦਾ ਹਵਾਈ ਦ੍ਰਿਸ਼',
  isWhoEyebrow: 'ਇਹ ਕਿਸ ਲਈ ਹੈ',
  isWhoLead: 'ਅਜਿਹੇ ਪੂੰਜੀ-ਤਿਆਰ ਗਾਹਕ ਜਿਨ੍ਹਾਂ ਨੂੰ ਕਦਮ ਚੁੱਕਣ ਤੋਂ ਪਹਿਲਾਂ ਸੰਚਾਲਨ ਟੀਮ ਚਾਹੀਦੀ ਹੈ।',
  isWhoBody:
    'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ ਤਿੰਨਾਂ ਰਾਹਾਂ ਵਿੱਚੋਂ ਸਭ ਤੋਂ ਛੋਟਾ ਹੈ ਅਤੇ ਜਾਣ-ਬੁੱਝ ਕੇ ਉਵੇਂ ਹੀ ਰਹਿੰਦਾ ਹੈ। ਇਹ ਉਹਨਾਂ ਮਾਲਕਾਂ ਲਈ ਹੈ ਜੋ ਵਪਾਰਕ ਜਾਇਦਾਦ ਵਿੱਚ, ਜਾਂ ਟੈਕਸਾਸ ਵਿੱਚ, ਦਾਖਲ ਹੋ ਰਹੇ ਹਨ ਅਤੇ ਚਾਹੁੰਦੇ ਹਨ ਕਿ ਸੰਚਾਲਨ ਪੱਖ ਪਹਿਲੀ ਜਾਇਦਾਦ ਤੋਂ ਹੀ ਸੰਭਾਲਿਆ ਜਾਵੇ, ਨਾ ਕਿ ਸੌਦਾ ਪੂਰਾ ਹੋਣ ਮਗਰੋਂ ਜੋੜਿਆ ਜਾਵੇ।',
  isTimelineBeforeLabel: 'ਖਰੀਦ ਤੋਂ ਪਹਿਲਾਂ',
  isTimelineBeforeBody:
    'ਜਾਇਦਾਦ ਚਲਾਉਣ ਵਿੱਚ ਕੀ ਲੱਗੇਗਾ, ਇਸ ਦਾ ਸੰਚਾਲਨ ਮੁਲਾਂਕਣ, ਤਾਂ ਜੋ ਪੇਸ਼ਕਸ਼ ਦੇ ਪਿੱਛੇ ਦੀਆਂ ਧਾਰਨਾਵਾਂ ਉਹੀ ਹੋਣ ਜੋ ਇੱਕ ਪ੍ਰਬੰਧਕ ਵਰਤੇਗਾ।',
  isTimelineClosingLabel: 'ਸੌਦੇ ਵੇਲੇ',
  isTimelineClosingBody:
    'ਪਹਿਲੇ ਦਿਨ ਤੋਂ ਪ੍ਰਬੰਧਨ ਟੀਮ ਹਾਜ਼ਰ, ਜਿਸ ਵਿੱਚ ਸਟਾਫ਼, ਸਿਸਟਮ ਅਤੇ ਵਿਕਰੇਤਾ ਸਬੰਧ ਬਕਾਇਆ ਨਹੀਂ ਸਗੋਂ ਤਿਆਰ ਹੋਣ।',
  isTimelineAfterLabel: 'ਪਹਿਲੀ ਜਾਇਦਾਦ ਤੋਂ ਬਾਅਦ',
  isTimelineAfterBody:
    'ਰਿਸ਼ਤਾ ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ ਵਿੱਚ ਚਲਾ ਜਾਂਦਾ ਹੈ, ਅਤੇ ਜੇ ਮਾਲਕਾਂ ਦਾ ਨਜ਼ਰੀਆ ਮੰਗ ਕਰੇ ਤਾਂ ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਵੀ ਜੁੜਦਾ ਹੈ।',
  isClosingTitle: 'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕੀ ਖਰੀਦਣਾ ਚਾਹੁੰਦੇ ਹੋ।',
  isClosingBody:
    'ਜਾਇਦਾਦ ਦੀ ਕਿਸਮ, ਬਾਜ਼ਾਰ ਅਤੇ ਸਮਾਂ-ਸੀਮਾ ਭੇਜੋ। ਇੱਕ ਭਾਈਵਾਲ ਸੰਚਾਲਨ ਮੁਲਾਂਕਣ ਨਾਲ ਜਵਾਬ ਦਿੰਦਾ ਹੈ ਅਤੇ ਦੱਸਦਾ ਹੈ ਕਿ ਪ੍ਰਬੰਧਨ ਕਿਹੋ ਜਿਹਾ ਹੋਵੇਗਾ।',
  isClosingCta: 'ਖਰੀਦ ਬਾਰੇ ਗੱਲ ਕਰੋ',

  partnersMetaTitle: 'ਭਾਈਵਾਲ | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint ਹਿਊਸਟਨ ਤੋਂ ਭਾਈਵਾਲਾਂ ਦੀ ਅਗਵਾਈ ਵਿੱਚ ਚੱਲਦਾ ਹੈ। Zachary Russell ਅਤੇ Ethaniel Vu ਉਹਨਾਂ ਜਾਇਦਾਦਾਂ ਨਾਲ ਜੁੜੇ ਰਹਿੰਦੇ ਹਨ ਜੋ ਉਹ ਸੰਭਾਲਦੇ ਹਨ, ਇਸ ਲਈ ਮਾਲਕ ਫੈਸਲਾ ਕਰਨ ਵਾਲਿਆਂ ਨਾਲ ਸਿੱਧੀ ਗੱਲ ਕਰਦੇ ਹਨ।',
  partnersHeroTitle: 'ਦੋ ਭਾਈਵਾਲ, ਕੰਮ ਲਈ ਸਿੱਧੇ ਜ਼ਿੰਮੇਵਾਰ',
  partnersHeroAnswer:
    'AxisPoint ਹਿਊਸਟਨ ਤੋਂ ਭਾਈਵਾਲਾਂ ਦੀ ਅਗਵਾਈ ਵਿੱਚ ਚੱਲਦਾ ਹੈ। ਜੋ ਕੰਮ ਸਵੀਕਾਰ ਕਰਦੇ ਹਨ, ਉਹੀ ਉਸ ਨਾਲ ਜੁੜੇ ਰਹਿੰਦੇ ਹਨ।',
  partnersRoleLabel: 'ਭਾਈਵਾਲ',
  partnerRussellBody:
    'ਸਿੱਧੇ ਸੰਚਾਲਨ ਕਾਰਗੁਜ਼ਾਰੀ ਤੇ ਕੰਮ ਕਰਦੇ ਹਨ: ਸਟਾਫ਼ ਦੇ ਫੈਸਲੇ, ਤਬਾਦਲੇ, ਪੂੰਜੀ ਪ੍ਰੋਗਰਾਮ, ਅਤੇ ਪੋਰਟਫੋਲੀਓ ਦੀਆਂ ਉਹ ਜਾਇਦਾਦਾਂ ਜਿਨ੍ਹਾਂ ਵੱਲ ਇਸ ਮਹੀਨੇ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ।',
  partnerVuBody:
    'ਸਿੱਧੇ ਵਿੱਤੀ ਨਿਯੰਤਰਣ ਅਤੇ ਮਾਲਕਾਂ ਲਈ ਤਿਆਰ ਰਿਕਾਰਡ ਤੇ ਕੰਮ ਕਰਦੇ ਹਨ: ਬਜਟ, ਮਨਜ਼ੂਰੀ ਦਾ ਅਨੁਸ਼ਾਸਨ, ਮਹੀਨਾਵਾਰ ਸਮਾਪਨ, ਅਤੇ ਉਹ ਰਿਪੋਰਟਾਂ ਜਿਨ੍ਹਾਂ ਨਾਲ ਮਾਲਕ ਫੈਸਲੇ ਲੈਂਦੇ ਹਨ।',
  partnersHowEyebrow: 'ਅਸੀਂ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਾਂ',
  partnersHowBody:
    'ਦੋਵੇਂ ਭਾਈਵਾਲ ਉਹਨਾਂ ਜਾਇਦਾਦਾਂ ਨਾਲ ਜੁੜੇ ਰਹਿੰਦੇ ਹਨ ਜੋ ਉਹ ਸੰਭਾਲਦੇ ਹਨ। ਮਾਲਕ ਫੈਸਲਾ ਕਰਨ ਵਾਲਿਆਂ ਨਾਲ ਗੱਲ ਕਰਦੇ ਹਨ, ਨਾ ਕਿ ਉਹਨਾਂ ਦੇ ਅੱਗੇ ਖੜ੍ਹੀ ਕੀਤੀ ਕਿਸੇ ਪਰਤ ਨਾਲ।',
  partnersClosingTitle: 'ਆਪਣੀ ਜਾਇਦਾਦ ਬਾਰੇ ਕਿਸੇ ਭਾਈਵਾਲ ਨਾਲ ਗੱਲ ਕਰੋ।',
  partnersClosingBody:
    'ਜਾਇਦਾਦ ਅਤੇ ਹਾਲਾਤ ਭੇਜੋ। ਜੋ ਭਾਈਵਾਲ ਇਸਨੂੰ ਪੜ੍ਹਦਾ ਹੈ, ਉਹੀ ਇਸ ਦਾ ਜਵਾਬ ਦੇਵੇਗਾ।',

  /* ══ Contact page and intake (PR 4) ══
   * Display text only; stored values stay stable snake_case tokens. Placeholders
   * {name} {email} {count} {day} {time} {mode} {language} must survive exactly. */

  contactEyebrow: 'ਸੰਪਰਕ',
  contactHeroTitle: 'AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
  contactHeroLead:
    'ਹਿਊਸਟਨ ਤੋਂ ਭਾਈਵਾਲਾਂ ਦੀ ਅਗਵਾਈ ਵਿੱਚ, ਪੂਰੇ ਟੈਕਸਾਸ ਦੇ ਮਾਲਕਾਂ ਦੀ ਸੇਵਾ। ਦੱਸੋ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ ਅਤੇ ਇੱਕ ਭਾਈਵਾਲ ਇਸਨੂੰ ਪੜ੍ਹਦਾ ਹੈ।',
  contactMetaTitle: 'AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਰੋ | AxisPoint Partners',
  contactMetaDescription:
    'ਹਿਊਸਟਨ, ਟੈਕਸਾਸ ਤੋਂ ਸਿੱਧੇ AxisPoint ਤੱਕ ਪਹੁੰਚੋ, ਪੂਰੇ ਰਾਜ ਦੇ ਮਾਲਕਾਂ ਦੀ ਸੇਵਾ। ਆਪਣੇ ਹਾਲਾਤ ਨਾਲ ਮੇਲ ਖਾਂਦਾ ਰਾਹ ਚੁਣੋ, ਜਾਂ info@axispoint.llc ਤੇ ਲਿਖੋ।',
  contactPathwayPmAm: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ ਅਤੇ ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  contactPmMetaTitle: 'ਪ੍ਰਬੰਧਨ ਪ੍ਰਸਤਾਵ ਦੀ ਬੇਨਤੀ ਕਰੋ | AxisPoint Partners',
  contactPmMetaDescription:
    'ਜਾਇਦਾਦ, ਪ੍ਰਬੰਧਨ ਦੀ ਮੌਜੂਦਾ ਹਾਲਤ, ਅਤੇ ਜੋ ਤਬਦੀਲੀ ਤੁਸੀਂ ਸੋਚ ਰਹੇ ਹੋ, ਭੇਜੋ। ਇੱਕ ਭਾਈਵਾਲ ਇਸਨੂੰ ਪੜ੍ਹ ਕੇ ਜਵਾਬ ਦਿੰਦਾ ਹੈ।',
  contactAmMetaTitle:
    'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਸਮੇਤ ਪ੍ਰਬੰਧਨ ਪ੍ਰਸਤਾਵ ਦੀ ਬੇਨਤੀ ਕਰੋ | AxisPoint Partners',
  contactAmMetaDescription:
    'ਪ੍ਰਬੰਧਨ ਪ੍ਰਸਤਾਵ ਵਿੱਚ ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ ਦੀ ਦਿਲਚਸਪੀ ਸਪਸ਼ਟ ਕਰ ਕੇ ਸ਼ੁਰੂ ਕਰੋ, ਤਾਂ ਜੋ ਸੰਚਾਲਨ ਕੰਮ ਅਤੇ ਨਿਵੇਸ਼ ਦਾ ਨਜ਼ਰੀਆ ਇੱਕੋ ਟੀਮ ਸੰਭਾਲੇ।',
  contactIsMetaTitle: 'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ ਬਾਰੇ ਪੁੱਛਗਿੱਛ | AxisPoint Partners',
  contactIsMetaDescription:
    'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਕਿੱਥੇ ਹੋ। ਇੱਕ ਭਾਈਵਾਲ ਸੰਚਾਲਨ ਮੁਲਾਂਕਣ ਨਾਲ ਜਵਾਬ ਦਿੰਦਾ ਹੈ ਅਤੇ ਦੱਸਦਾ ਹੈ ਕਿ ਪ੍ਰਬੰਧਨ ਕਿਹੋ ਜਿਹਾ ਹੋਵੇਗਾ।',
  contactGeneralMetaTitle: 'AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਰੋ | AxisPoint Partners',
  contactGeneralMetaDescription:
    'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕੌਣ ਹੋ ਅਤੇ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ। ਅਸੀਂ ਇਸਨੂੰ ਸਹੀ ਭਾਈਵਾਲ ਤੱਕ ਪਹੁੰਚਾਵਾਂਗੇ।',

  fieldOptional: 'ਵਿਕਲਪਿਕ',

  gatewayEmailPrefix: 'ਈਮੇਲ ਵੱਧ ਪਸੰਦ ਹੈ? ਲਿਖੋ',

  ledgerChangePath: 'ਰਾਹ ਬਦਲੋ',
  labelProperty: 'ਜਾਇਦਾਦ',
  labelPropertyEmpty: 'ਕਿਸਮ, ਥਾਂ ਅਤੇ ਆਕਾਰ',
  labelSituation: 'ਹਾਲਾਤ',
  labelSituationEmpty: 'ਕੀ ਬਦਲਣ ਦੀ ਲੋੜ ਹੈ',
  labelContact: 'ਸੰਪਰਕ',
  labelContactEmpty: 'ਅਸੀਂ ਕਿਵੇਂ ਸੰਪਰਕ ਕਰੀਏ',
  labelInvolvement: 'ਸ਼ਮੂਲੀਅਤ',
  labelPathway: 'ਰਾਹ',
  labelTopic: 'ਵਿਸ਼ਾ',
  labelFollowUpLanguage: 'ਸੰਪਰਕ ਦੀ ਭਾਸ਼ਾ',

  confirmKickerProperty: 'ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਭੇਜ ਦਿੱਤੇ',
  confirmKickerInquiry: 'ਪੁੱਛਗਿੱਛ ਭੇਜ ਦਿੱਤੀ',
  confirmTitleProperty: 'ਧੰਨਵਾਦ, {name}। ਸਾਨੂੰ ਤੁਹਾਡੀ ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਮਿਲ ਗਏ ਹਨ।',
  confirmTitleInquiry: 'ਧੰਨਵਾਦ, {name}। ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਸਾਡੇ ਕੋਲ ਹੈ।',
  confirmBodyProperty: 'Zachary ਜਾਂ Ethaniel ਜਾਣਕਾਰੀ ਵੇਖ ਕੇ ਸਿੱਧਾ ਸੰਪਰਕ ਕਰਨਗੇ।',
  confirmBodyInquiry: 'Zachary ਜਾਂ Ethaniel ਇਸਨੂੰ ਵੇਖ ਕੇ ਸਿੱਧਾ {email} ਤੇ ਸੰਪਰਕ ਕਰਨਗੇ।',
  confirmWhatYouSent: 'ਤੁਸੀਂ ਕੀ ਭੇਜਿਆ',
  confirmScheduleCta: '30 ਮਿੰਟ ਦੀ ਕਾਲ ਤੈਅ ਕਰੋ',
  confirmWait: 'ਮੈਂ ਸੰਪਰਕ ਦੀ ਉਡੀਕ ਕਰਾਂਗਾ',
  backToAxisPoint: 'AxisPoint ਤੇ ਵਾਪਸ',

  scheduleKicker: 'ਵਿਕਲਪਿਕ ਅਗਲਾ ਕਦਮ',
  scheduleTitle: '30 ਮਿੰਟ ਦੀ ਕਾਲ ਤੈਅ ਕਰੋ',
  scheduleLead:
    'ਤੁਹਾਡੀ ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਪਹਿਲਾਂ ਹੀ ਭੇਜੇ ਜਾ ਚੁੱਕੇ ਹਨ। ਸਮਾਂ ਤਾਂ ਹੀ ਚੁਣੋ ਜੇ ਇਹ ਤੁਹਾਡੇ ਲਈ ਲਾਭਦਾਇਕ ਹੋਵੇ।',
  scheduleSelectDate: 'ਤਾਰੀਖ਼ ਚੁਣੋ',
  scheduleSelectTime: 'ਸਮਾਂ ਚੁਣੋ',
  scheduleChooseDateFirst: 'ਸਮੇਂ ਵੇਖਣ ਲਈ ਪਹਿਲਾਂ ਤਾਰੀਖ਼ ਚੁਣੋ।',
  scheduleHowMeet: 'ਅਸੀਂ ਕਿਸ ਤਰ੍ਹਾਂ ਗੱਲ ਕਰੀਏ?',
  scheduleSelectedLabel: 'ਚੁਣਿਆ ਗਿਆ',
  scheduleSelectedSummary: '{day} ਨੂੰ {time} ਵਜੇ, {mode}',
  scheduleSelectedEmpty: 'ਤਾਰੀਖ਼, ਸਮਾਂ ਅਤੇ ਗੱਲ ਕਰਨ ਦਾ ਤਰੀਕਾ ਚੁਣੋ',
  scheduleConfirm: 'ਇਹ ਸਮਾਂ ਪੱਕਾ ਕਰੋ',
  scheduleBooking: 'ਤੈਅ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ',

  scheduledKicker: 'ਕਾਲ ਪੱਕੀ ਹੋਈ',
  scheduledTitle: 'ਤੁਸੀਂ ਕੈਲੰਡਰ ਵਿੱਚ ਹੋ।',
  labelWhen: 'ਕਦੋਂ',
  labelFormat: 'ਰੂਪ',
  labelLength: 'ਮਿਆਦ',
  labelWith: 'ਕਿਸ ਨਾਲ',
  scheduledWhenValue: '{day}, {time} Central',
  scheduledInviteNote:
    'ਕੈਲੰਡਰ ਸੱਦਾ {email} ਤੇ ਜਾਵੇਗਾ। ਸਮਾਂ ਬਦਲਣਾ ਹੋਵੇ ਤਾਂ ਉਸੇ ਦਾ ਜਵਾਬ ਦਿਓ।',
  scheduledDevNote:
    'ਡਿਵੈਲਪਮੈਂਟ ਝਲਕ। ਬੁਕਿੰਗ ਕਮਾਂਡ ਸਿਮੂਲੇਟਰ ਤੇ ਚੱਲੀ, ਇਸ ਲਈ ਕੋਈ ਕੈਲੰਡਰ ਇਵੈਂਟ ਨਹੀਂ ਬਣਿਆ ਅਤੇ ਕੋਈ ਸੱਦਾ ਨਹੀਂ ਭੇਜਿਆ ਗਿਆ।',

  skippedTitle: 'ਕੋਈ ਕਾਲ ਤੈਅ ਨਹੀਂ ਹੋਈ। ਤੁਹਾਡੇ ਤੋਂ ਹੋਰ ਕੁਝ ਨਹੀਂ ਚਾਹੀਦਾ।',
  skippedBody:
    'ਤੁਹਾਡੀ ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ Zachary ਅਤੇ Ethaniel ਕੋਲ ਹਨ, ਅਤੇ ਉਹ {email} ਤੇ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਨਗੇ। ਬਾਅਦ ਵਿੱਚ ਲਾਭਦਾਇਕ ਲੱਗੇ ਤਾਂ ਤੁਸੀਂ ਹੁਣ ਵੀ ਸਮਾਂ ਚੁਣ ਸਕਦੇ ਹੋ।',

  errorSummaryOne: 'ਇੱਕ ਖਾਨੇ ਵੱਲ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ।',
  errorSummaryTwo: 'ਦੋ ਖਾਨਿਆਂ ਵੱਲ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ।',
  errorSummaryMany: '{count} ਖਾਨਿਆਂ ਵੱਲ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ।',
  errorSummaryFixInquiry: 'ਹੇਠਾਂ ਨਿਸ਼ਾਨਬੱਧ ਖਾਨੇ ਠੀਕ ਕਰੋ, ਫਿਰ ਪੁੱਛਗਿੱਛ ਦੁਬਾਰਾ ਭੇਜੋ।',
  errorSummaryFixProperty:
    'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਅਤੇ ਇੱਕ ਈਮੇਲ ਪਤਾ ਸ਼ਾਮਲ ਕਰੋ ਜਿਸ ਤੇ ਅਸੀਂ ਜਵਾਬ ਦੇ ਸਕੀਏ, ਫਿਰ ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਦੁਬਾਰਾ ਭੇਜੋ।',
  failedTitleInquiry: 'ਅਸੀਂ ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਨਹੀਂ ਭੇਜ ਸਕੇ।',
  failedTitleProperty: 'ਅਸੀਂ ਤੁਹਾਡੀ ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਨਹੀਂ ਭੇਜ ਸਕੇ।',
  failedBody: 'ਤੁਹਾਡੇ ਜਵਾਬ ਹੁਣ ਵੀ ਇੱਥੇ ਹਨ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਸਿੱਧਾ AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
  tryAgain: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  unavailableTitle: 'ਇਸ ਵੇਲੇ ਭੇਜਣਾ ਉਪਲਬਧ ਨਹੀਂ।',
  unavailableBody:
    'ਕੁਝ ਨਹੀਂ ਭੇਜਿਆ ਗਿਆ। ਤੁਹਾਡੇ ਜਵਾਬ ਹੁਣ ਵੀ ਇੱਥੇ ਹਨ, ਅਤੇ ਇਸ ਦੌਰਾਨ ਤੁਸੀਂ ਸਿੱਧਾ AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਰ ਸਕਦੇ ਹੋ।',
  blockedBody:
    'ਕੁਝ ਨਹੀਂ ਭੇਜਿਆ ਗਿਆ, ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰਨ ਨਾਲ ਮਦਦ ਨਹੀਂ ਮਿਲੇਗੀ। ਤੁਹਾਡੇ ਜਵਾਬ ਹੁਣ ਵੀ ਇੱਥੇ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਸਿੱਧਾ AxisPoint ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
  emailAxisPoint: 'AxisPoint ਨੂੰ ਈਮੇਲ ਕਰੋ',

  fieldFullName: 'ਪੂਰਾ ਨਾਮ',
  fieldEmail: 'ਈਮੇਲ',
  fieldPhone: 'ਫ਼ੋਨ',
  fieldPhonePlaceholder: '(713) 000 0000',
  fieldPhoneHelp: 'ਸਿੱਧੀ ਕਾਲ ਪਸੰਦ ਹੋਵੇ ਤਾਂ ਨੰਬਰ ਸ਼ਾਮਲ ਕਰੋ।',
  fieldCompanyOwnership: 'ਕੰਪਨੀ ਜਾਂ ਮਾਲਕੀ ਸਮੂਹ',
  fieldLanguageFollowUp: 'ਸੰਪਰਕ ਲਈ ਭਾਸ਼ਾ',
  followUpHelpChosen:
    'ਜਿੱਥੇ ਕੋਈ ਭਾਈਵਾਲ ਉਪਲਬਧ ਹੋਵੇਗਾ ਉੱਥੇ ਅਸੀਂ {language} ਵਿੱਚ ਜਵਾਬ ਦੇਵਾਂਗੇ, ਨਹੀਂ ਤਾਂ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ।',
  followUpHelpDefault: 'ਇਸਨੂੰ ਇਵੇਂ ਹੀ ਰਹਿਣ ਦਿਓ ਅਤੇ ਅਸੀਂ ਇਸ ਪੰਨੇ ਦੀ ਭਾਸ਼ਾ ਵਿੱਚ ਜਵਾਬ ਦੇਵਾਂਗੇ।',
  sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ',
  noDocuments: 'ਇਸ ਪੜਾਅ ਤੇ ਕਿਸੇ ਦਸਤਾਵੇਜ਼ ਦੀ ਲੋੜ ਨਹੀਂ।',

  step1Title: 'ਆਪਣੀ ਜਾਇਦਾਦ ਬਾਰੇ ਦੱਸੋ।',
  step1Lead:
    'ਕੁਝ ਵੇਰਵੇ ਸਾਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਨਗੇ ਕਿ ਤੁਹਾਡੇ ਕੋਲ ਕੀ ਹੈ, ਕੀ ਬਦਲਣ ਦੀ ਲੋੜ ਹੈ, ਅਤੇ ਕੀ AxisPoint ਸਹੀ ਸੰਚਾਲਨ ਭਾਈਵਾਲ ਹੈ।',
  step1SubTitle: 'ਅਸੀਂ ਕਿਸ ਬਾਰੇ ਗੱਲ ਕਰ ਰਹੇ ਹਾਂ?',
  legendPropertyType: 'ਜਾਇਦਾਦ ਦੀ ਕਿਸਮ',
  legendPropertyScope: 'ਜਾਇਦਾਦ ਦਾ ਦਾਇਰਾ',
  fieldLocation: 'ਜਾਇਦਾਦ ਕਿੱਥੇ ਸਥਿਤ ਹੈ?',
  fieldLocationPlaceholder: 'ਸ਼ਹਿਰ ਜਾਂ ਬਾਜ਼ਾਰ',
  fieldLocationHelp: 'ਫ਼ਿਲਹਾਲ ਸ਼ਹਿਰ ਜਾਂ ਬਾਜ਼ਾਰ ਕਾਫ਼ੀ ਹੈ। ਪੂਰਾ ਪਤਾ ਲੋੜੀਂਦਾ ਨਹੀਂ।',
  fieldPropertyCount: 'ਜਾਇਦਾਦਾਂ ਦੀ ਗਿਣਤੀ',
  fieldPropertyCountPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 6',
  notSure: 'ਪੱਕਾ ਪਤਾ ਨਹੀਂ',
  continueLabel: 'ਜਾਰੀ ਰੱਖੋ',
  step1Footer: 'ਪੜਾਅ 1 ਵਿੱਚੋਂ 3। ਕੁੱਲ ਮਿਲਾ ਕੇ ਲਗਭਗ 60 ਤੋਂ 90 ਸਕਿੰਟ।',

  step2Title: 'ਕੀ ਬਦਲਣ ਦੀ ਲੋੜ ਹੈ?',
  legendCurrentSituation: 'ਮੌਜੂਦਾ ਹਾਲਾਤ',
  legendInvolvement: 'ਤੁਸੀਂ AxisPoint ਦੀ ਸ਼ਮੂਲੀਅਤ ਕਿੱਥੇ ਚਾਹੋਗੇ?',
  fieldTiming: 'ਸਮਾਂ',
  fieldTimingPlaceholder: 'ਇੱਕ ਸਮਾਂ-ਸੀਮਾ ਚੁਣੋ',
  fieldUnderstand: 'ਗੱਲ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਾਨੂੰ ਕੀ ਸਮਝ ਲੈਣਾ ਚਾਹੀਦਾ ਹੈ?',
  fieldUnderstandPlaceholder:
    'ਜਾਇਦਾਦ, ਮੌਜੂਦਾ ਪ੍ਰਬੰਧਕ ਜਾਂ ਸਮਾਂ-ਸੀਮਾ ਬਾਰੇ ਕੁਝ ਵੀ',
  backLabel: 'ਪਿੱਛੇ',

  step3Title: 'ਅਸੀਂ ਕਿਵੇਂ ਸੰਪਰਕ ਕਰੀਏ?',
  privacyNote:
    'AxisPoint ਇਸ ਜਾਣਕਾਰੀ ਦੀ ਵਰਤੋਂ ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਦੀ ਸਮੀਖਿਆ ਕਰਨ ਅਤੇ ਸਿੱਧਾ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਨ ਲਈ ਕਰੇਗਾ।',
  sendPropertyDetails: 'ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਭੇਜੋ',
};
