import type { Messages } from '../../messages';

/**
 * PUNJABI (GURMUKHI). AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Punjabi has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `pa` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * SCRIPT. Gurmukhi, matching the registry's `Noto Sans Gurmukhi` stack and the `ਪੰਜਾਬੀ` native
 * name. Punjabi is also written in Shahmukhi (Perso-Arabic, RTL) by most Punjabi speakers in
 * Pakistan. The approved design chose Gurmukhi and lists `pa` as `direction: 'ltr'`, so this
 * file is Gurmukhi only. IF the intended Houston readership is substantially Pakistani
 * Punjabi, this is the wrong script and no amount of correcting the sentences below fixes
 * that. It is an audience decision for the owner, not a translation note, and it is recorded
 * in `docs/STATUS.md` rather than left implicit here.
 *
 * GENDER. First-person verbs agree with the speaker's gender and the visitor's is unknown;
 * the masculine default is used (`ਕਰ ਰਿਹਾ ਹਾਂ`). A reviewer should choose.
 *
 * LINE HEIGHT. 1.55 in the registry. Gurmukhi sits below a headline stroke with matras above
 * and below it, and clips at Latin leading. Check rendered output.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const PA: Partial<Messages> = {
  gatewayTitle: 'ਤੁਸੀਂ ਕਿਸ ਬਾਰੇ ਗੱਲ ਕਰਨੀ ਚਾਹੋਗੇ?',
  gatewayLead:
    'ਉਹ ਵਿਕਲਪ ਚੁਣੋ ਜੋ ਤੁਹਾਡੀ ਸਥਿਤੀ ਨਾਲ ਸਭ ਤੋਂ ਵੱਧ ਮੇਲ ਖਾਂਦਾ ਹੈ। ਤੁਸੀਂ ਬਾਅਦ ਵਿੱਚ ਬਦਲ ਸਕਦੇ ਹੋ।',
  gatewayOwnerKicker: 'ਬਹੁਤੇ ਮਾਲਕ ਇੱਥੋਂ ਹੀ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ',
  gatewayOwnerTitle: 'ਜਾਇਦਾਦ ਦੇ ਮਾਲਕ',
  gatewayOwnerBody: 'ਮੇਰੇ ਕੋਲ ਜਾਇਦਾਦ ਹੈ ਜਾਂ ਮੈਂ ਇਸ ਦੀ ਦੇਖਭਾਲ ਕਰਦਾ ਹਾਂ ਅਤੇ ਮੈਨੂੰ ਪ੍ਰਬੰਧਨ ਦੀ ਲੋੜ ਹੈ।',
  gatewayOwnerAction: 'ਜਾਇਦਾਦ ਦੇ ਵੇਰਵੇ ਸ਼ੁਰੂ ਕਰੋ',
  gatewayAssetTitle: 'ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  gatewayAssetBody:
    'ਮੇਰੇ ਕੋਲ ਜਾਇਦਾਦ ਹੈ ਅਤੇ ਮੈਨੂੰ ਰਣਨੀਤੀ, ਕਾਰਗੁਜ਼ਾਰੀ ਅਤੇ ਰਿਪੋਰਟਿੰਗ ਦੀ ਦਿਸ਼ਾ ਤੈਅ ਕਰਨ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।',
  gatewayInvestorTitle: 'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ',
  gatewayInvestorBody:
    'ਮੈਂ ਵਪਾਰਕ ਜਾਇਦਾਦ ਖਰੀਦਣ ਦੀ ਤਿਆਰੀ ਕਰ ਰਿਹਾ ਹਾਂ ਅਤੇ ਮੈਨੂੰ ਸੰਚਾਲਨ ਟੀਮ ਚਾਹੀਦੀ ਹੈ।',
  gatewayGeneralTitle: 'ਆਮ ਪੁੱਛਗਿੱਛ',
  gatewayGeneralBody: 'ਕੁਝ ਹੋਰ। ਵਿਕਰੇਤਾ, ਪ੍ਰੈਸ, ਰੁਜ਼ਗਾਰ ਜਾਂ ਕੋਈ ਸਵਾਲ।',

  propertyTypeMultifamily: 'ਬਹੁ-ਪਰਿਵਾਰਕ',
  propertyTypeRetail: 'ਪਰਚੂਨ',
  propertyTypeMixedPortfolio: 'ਮਿਸ਼ਰਤ ਪੋਰਟਫੋਲੀਓ',
  propertyTypeAnother: 'ਹੋਰ ਕਿਸਮ ਦੀ ਜਾਇਦਾਦ',
  propertyScopeOne: 'ਇੱਕ ਜਾਇਦਾਦ',
  propertyScopePortfolio: 'ਪੋਰਟਫੋਲੀਓ',

  situationReplace: 'ਮੌਜੂਦਾ ਪ੍ਰਬੰਧਨ ਬਦਲਣਾ',
  situationMoveAway: 'ਆਪ ਪ੍ਰਬੰਧਨ ਕਰਨਾ ਛੱਡਣਾ',
  situationRecentlyAcquired: 'ਹਾਲ ਹੀ ਵਿੱਚ ਖਰੀਦੀ ਜਾਂ ਸਮਝੌਤੇ ਅਧੀਨ',
  situationLeaseUp: 'ਕਿਰਾਏ ਦੀ ਸ਼ੁਰੂਆਤ ਜਾਂ ਕਾਰਗੁਜ਼ਾਰੀ ਸੁਧਾਰ',
  situationOperations: 'ਸੰਚਾਲਨ ਜਾਂ ਰਿਪੋਰਟਿੰਗ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ',
  situationExploring: 'ਪ੍ਰਬੰਧਨ ਦੇ ਵਿਕਲਪ ਵੇਖ ਰਹੇ ਹਾਂ',
  situationSomethingElse: 'ਕੁਝ ਹੋਰ',

  involvementPm: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ',
  involvementPmHint: 'ਜਾਇਦਾਦ ਦਾ ਰੋਜ਼ਾਨਾ ਸੰਚਾਲਨ।',
  involvementPmAm: 'ਜਾਇਦਾਦ ਪ੍ਰਬੰਧਨ + ਸੰਪਤੀ ਪ੍ਰਬੰਧਨ',
  involvementPmAmHint: 'ਜਾਇਦਾਦ ਦਾ ਸੰਚਾਲਨ ਅਤੇ ਨਿਵੇਸ਼ ਰਣਨੀਤੀ ਤੈਅ ਕਰਨ ਵਿੱਚ ਮਦਦ।',
  involvementNotSure: 'ਪੱਕਾ ਪਤਾ ਨਹੀਂ',
  involvementNotSureHint: 'ਢੁਕਵਾਂ ਪੱਧਰ ਤੈਅ ਕਰਨ ਵਿੱਚ ਮੇਰੀ ਮਦਦ ਕਰੋ।',

  timingImmediately: 'ਤੁਰੰਤ',
  timingWithin30: '30 ਦਿਨਾਂ ਵਿੱਚ',
  timing30to60: '30 ਤੋਂ 60 ਦਿਨ',
  timing60to90: '60 ਤੋਂ 90 ਦਿਨ',
  timingStillExploring: 'ਅਜੇ ਵਿਚਾਰ ਕਰ ਰਹੇ ਹਾਂ',

  investorTopicFirstAcquisition: 'ਆਪਣੀ ਪਹਿਲੀ ਖਰੀਦ ਬਾਰੇ ਵਿਚਾਰ ਕਰ ਰਿਹਾ ਹਾਂ',
  investorTopicUnderContract: 'ਇਸ ਵੇਲੇ ਸਮਝੌਤੇ ਅਧੀਨ',
  investorTopicActivelySearching: 'ਸਰਗਰਮੀ ਨਾਲ ਲੱਭ ਰਹੇ ਹਾਂ',
  investorTopicOwnProperty: 'ਜਾਇਦਾਦ ਹੈ, ਸੰਚਾਲਨ ਟੀਮ ਚਾਹੀਦੀ ਹੈ',
  investorTopicSomethingElse: 'ਕੁਝ ਹੋਰ',
  generalTopicQuestion: 'AxisPoint ਬਾਰੇ ਇੱਕ ਸਵਾਲ',
  generalTopicVendor: 'ਵਿਕਰੇਤਾ ਜਾਂ ਸੇਵਾ ਪ੍ਰਦਾਤਾ',
  generalTopicEmployment: 'ਰੁਜ਼ਗਾਰ',
  generalTopicPress: 'ਪ੍ਰੈਸ ਜਾਂ ਮੀਡੀਆ',
  generalTopicSomethingElse: 'ਕੁਝ ਹੋਰ',

  bookingModePhone: 'ਫ਼ੋਨ ਕਾਲ',
  bookingModeVideo: 'ਵੀਡੀਓ ਮੀਟਿੰਗ',

  scaleUnitsLabel: 'ਅੰਦਾਜ਼ਨ ਯੂਨਿਟ',
  scaleUnitsPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 184',
  scaleUnitsHelp:
    'ਮੋਟਾ ਅੰਕੜਾ ਕਾਫ਼ੀ ਹੈ। ਅਸੀਂ ਸੰਚਾਲਨ ਟੀਮ ਦਾ ਆਕਾਰ ਤੈਅ ਕਰ ਰਹੇ ਹਾਂ, ਕਿਰਾਏ ਦੇ ਰਿਕਾਰਡ ਦੀ ਜਾਂਚ ਨਹੀਂ।',
  scaleSqftLabel: 'ਅੰਦਾਜ਼ਨ ਖੇਤਰਫਲ, ਵਰਗ ਫੁੱਟ',
  scaleSqftPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 42,000',
  scaleSqftHelp: 'ਕੁੱਲ ਕਿਰਾਏ ਯੋਗ ਖੇਤਰ ਇੱਥੇ ਸਭ ਤੋਂ ਲਾਭਦਾਇਕ ਅੰਕੜਾ ਹੈ।',
  scaleMixedLabel: 'ਅੰਦਾਜ਼ਨ ਸੰਯੁਕਤ ਆਕਾਰ',
  scaleMixedPlaceholder: 'ਉਦਾਹਰਨ ਲਈ 300 ਯੂਨਿਟ ਅਤੇ 40,000 ਵਰਗ ਫੁੱਟ',
  scaleMixedHelp: 'ਯੂਨਿਟ, ਵਰਗ ਫੁੱਟ ਜਾਂ ਦੋਵੇਂ। ਜਿਸ ਤਰ੍ਹਾਂ ਤੁਸੀਂ ਹਿਸਾਬ ਰੱਖਦੇ ਹੋ, ਉਸੇ ਤਰ੍ਹਾਂ ਦੱਸੋ।',
  scaleOtherLabel: 'ਅੰਦਾਜ਼ਨ ਆਕਾਰ',
  scaleOtherPlaceholder: 'ਯੂਨਿਟ, ਵਰਗ ਫੁੱਟ ਜਾਂ ਕੋਈ ਹੋਰ ਮਾਪ',
  scaleOtherHelp: 'ਇਸ ਕਿਸਮ ਦੀ ਜਾਇਦਾਦ ਲਈ ਜੋ ਮਾਪ ਢੁਕਵਾਂ ਹੋਵੇ, ਉਸੇ ਵਿੱਚ ਆਕਾਰ ਦੱਸੋ।',
  scaleFallbackLabel: 'ਅੰਦਾਜ਼ਨ ਆਕਾਰ',
  scaleFallbackPlaceholder: 'ਯੂਨਿਟ ਜਾਂ ਵਰਗ ਫੁੱਟ',
  scaleFallbackHelp: 'ਉੱਪਰ ਜਾਇਦਾਦ ਦੀ ਕਿਸਮ ਚੁਣੋ, ਇਹ ਸਹੀ ਮਾਪ ਅਨੁਸਾਰ ਬਦਲ ਜਾਵੇਗਾ।',

  investorKicker: 'ਨਿਵੇਸ਼ਕ ਸੇਵਾਵਾਂ',
  investorTitle: 'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਕਿੱਥੇ ਹੋ।',
  investorLead: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਛੋਟਾ ਜਿਹਾ ਨੋਟ ਕਾਫ਼ੀ ਹੈ। ਗੱਲਬਾਤ ਤੈਅ ਕਰਨ ਲਈ ਅਸੀਂ ਸੰਪਰਕ ਕਰਾਂਗੇ।',
  investorTopicLabel: 'ਤੁਸੀਂ ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ ਕਿੱਥੇ ਹੋ?',
  investorNoteLabel: 'ਤੁਸੀਂ ਕਿਸ ਬਾਰੇ ਵਿਚਾਰ ਕਰ ਰਹੇ ਹੋ?',
  investorNotePlaceholder: 'ਸੰਪਤੀ ਦੀ ਕਿਸਮ, ਬਾਜ਼ਾਰ ਜਾਂ ਸਮਾਂ-ਸੀਮਾ',
  generalKicker: 'ਆਮ ਪੁੱਛਗਿੱਛ',
  generalTitle: 'ਅਸੀਂ ਕਿਸ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?',
  generalLead:
    'ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕੌਣ ਹੋ ਅਤੇ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ। ਅਸੀਂ ਇਸਨੂੰ ਸਹੀ ਭਾਈਵਾਲ ਤੱਕ ਪਹੁੰਚਾਵਾਂਗੇ।',
  generalTopicLabel: 'ਇਹ ਕਿਸ ਬਾਰੇ ਹੈ?',
  generalNoteLabel: 'ਤੁਹਾਡਾ ਸੁਨੇਹਾ',
  generalNotePlaceholder: 'ਕੁਝ ਵਾਕ ਕਾਫ਼ੀ ਹਨ',
  organizationLabel: 'ਕੰਪਨੀ',
  submitLabel: 'ਪੁੱਛਗਿੱਛ ਭੇਜੋ',

  nameHelp: 'ਤੁਸੀਂ ਚਾਹੁੰਦੇ ਹੋ ਕਿ ਅਸੀਂ ਤੁਹਾਨੂੰ ਕਿਸ ਨਾਮ ਨਾਲ ਸੰਬੋਧਿਤ ਕਰੀਏ।',
  nameError: 'ਉਹ ਨਾਮ ਦਰਜ ਕਰੋ ਜੋ ਸਾਨੂੰ ਕਾਲ ਕਰਨ ਵੇਲੇ ਪੁੱਛਣਾ ਚਾਹੀਦਾ ਹੈ।',
  emailHelp: 'ਜਿੱਥੇ ਅਸੀਂ ਆਪਣਾ ਜਵਾਬ ਅਤੇ ਅੱਗੇ ਦੀ ਜਾਣਕਾਰੀ ਭੇਜਾਂਗੇ।',
  emailError:
    'ਇਸ ਪਤੇ ਵਿੱਚ @ ਨਿਸ਼ਾਨ ਤੋਂ ਬਾਅਦ ਵਾਲਾ ਹਿੱਸਾ ਨਹੀਂ ਹੈ। ਪੂਰਾ ਪਤਾ ਦਰਜ ਕਰੋ, ਉਦਾਹਰਨ ਲਈ name@company.com।',
  topicError: 'ਉਹ ਵਿਕਲਪ ਚੁਣੋ ਜੋ ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਨੂੰ ਸਭ ਤੋਂ ਵਧੀਆ ਦੱਸਦਾ ਹੈ।',
  followUpSameAsPage: 'ਇਸ ਪੰਨੇ ਵਾਂਗ, ਪੰਜਾਬੀ',
  selectOne: 'ਇੱਕ ਚੁਣੋ',
  notSpecified: 'ਨਹੀਂ ਦੱਸਿਆ ਗਿਆ',

  bookingCandidateNote:
    'ਸਮਾਂ ਸੈਂਟਰਲ ਟਾਈਮ, ਹਿਊਸਟਨ ਵਿੱਚ ਦਿਖਾਇਆ ਗਿਆ ਹੈ। ਉਪਲਬਧਤਾ ਦੀ ਪੁਸ਼ਟੀ ਬੁਕਿੰਗ ਵੇਲੇ ਹੁੰਦੀ ਹੈ।',
  bookingSlotTaken: 'ਉਹ ਸਮਾਂ ਹੁਣ ਉਪਲਬਧ ਨਹੀਂ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਹੋਰ ਚੁਣੋ।',
  bookingFailed: 'ਅਸੀਂ ਉਸ ਸਮੇਂ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ ਕਰ ਸਕੇ। ਕੁਝ ਵੀ ਬੁੱਕ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  bookingRefused: 'ਅਸੀਂ ਉਹ ਸਮਾਂ ਬੁੱਕ ਨਹੀਂ ਕਰ ਸਕੇ, ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰਨ ਨਾਲ ਮਦਦ ਨਹੀਂ ਮਿਲੇਗੀ।',
  bookingUnavailable: 'ਇਸ ਵੇਲੇ ਸਮਾਂ ਤੈਅ ਕਰਨਾ ਉਪਲਬਧ ਨਹੀਂ। ਕੁਝ ਵੀ ਬੁੱਕ ਨਹੀਂ ਹੋਇਆ।',
  bookingDurationLabel: '30 ਮਿੰਟ',
  bookingWithLabel: 'AxisPoint Partners',
};
