import type { Messages } from '../../messages';

/**
 * URDU. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Urdu has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `ur` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * ── THIS IS THE ONLY RTL LOCALE, AND IT IS THE ONE TO TEST HARDEST ──────────
 *
 * `direction: 'rtl'` in the registry, applied to `<html dir>` by `LocaleProvider`. Everything
 * below is what a reviewer and a layout check should be looking for:
 *
 * MIXED-DIRECTION STRINGS ARE THE RISK. Several values embed left-to-right runs inside
 * right-to-left text: `AxisPoint` in `generalTopicQuestion`, `name@company.com` and the bare
 * `@` in `emailError`, and Western digits in the timing and scale strings. The Unicode
 * bidirectional algorithm resolves these by itself and usually gets them right, but trailing
 * punctuation after an LTR run is the classic failure: an Urdu full stop (۔) after an email
 * address can render at the wrong end of the line. `emailError` and `generalTopicQuestion`
 * are the two strings to inspect visually first.
 *
 * NO BIDI CONTROL CHARACTERS ARE EMBEDDED HERE, deliberately. Invisible marks like U+200F
 * would paper over a layout bug in this one file while leaving it broken everywhere else,
 * and they survive into stored data and outbound mail where nobody expects them. If a string
 * renders wrongly, fix the CSS or the surrounding markup, not the data.
 *
 * PUNCTUATION. Urdu uses ۔ as the full stop and ، as the comma, not the Latin forms. Both are
 * used throughout. This is correct for the script and is unrelated to the project's
 * no-em-dash rule.
 *
 * LINE HEIGHT. 1.55 in the registry. Nastaliq-influenced faces need it; at Latin leading the
 * descenders collide. Noto Sans Arabic is the registry's stack and is naskh rather than
 * nastaliq, which many Urdu readers find noticeably less comfortable than a nastaliq face
 * such as Noto Nastaliq Urdu. THAT IS A REAL OPEN QUESTION for the reviewer, and it is a
 * font decision rather than a translation one. Recorded in `docs/STATUS.md`.
 *
 * GENDER. As in Hindi, first-person verbs agree with the speaker's gender and the visitor's
 * is unknown; the masculine default is used (`کر رہا ہوں`). A reviewer should choose.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const UR: Partial<Messages> = {
  gatewayTitle: 'آپ کس بارے میں بات کرنا چاہیں گے؟',
  gatewayLead:
    'وہ راستہ منتخب کریں جو آپ کی صورتحال سے سب سے زیادہ مطابقت رکھتا ہو۔ آپ بعد میں اسے تبدیل کر سکتے ہیں۔',
  gatewayOwnerKicker: 'زیادہ تر مالکان یہیں سے شروع کرتے ہیں',
  gatewayOwnerTitle: 'جائیداد کے مالک',
  gatewayOwnerBody: 'میں ایک جائیداد کا مالک ہوں یا اس کی نگرانی کرتا ہوں اور مجھے انتظام کی ضرورت ہے۔',
  gatewayOwnerAction: 'جائیداد کی تفصیلات شروع کریں',
  gatewayAssetTitle: 'اثاثہ جات کا انتظام',
  gatewayAssetBody:
    'میرے پاس جائیداد ہے اور مجھے حکمت عملی، کارکردگی اور رپورٹنگ کی رہنمائی میں مدد چاہیے۔',
  gatewayInvestorTitle: 'سرمایہ کاروں کے لیے خدمات',
  gatewayInvestorBody:
    'میں تجارتی جائیداد خریدنے کی تیاری کر رہا ہوں اور مجھے ایک آپریٹنگ ٹیم چاہیے۔',
  gatewayGeneralTitle: 'عمومی استفسار',
  gatewayGeneralBody: 'کچھ اور۔ وینڈرز، پریس، ملازمت یا کوئی سوال۔',

  propertyTypeMultifamily: 'کثیر خاندانی',
  propertyTypeRetail: 'ریٹیل',
  propertyTypeMixedPortfolio: 'مخلوط پورٹ فولیو',
  propertyTypeAnother: 'کسی اور قسم کی جائیداد',
  propertyScopeOne: 'ایک جائیداد',
  propertyScopePortfolio: 'پورٹ فولیو',

  situationReplace: 'موجودہ انتظام تبدیل کرنا',
  situationMoveAway: 'خود انتظام سے ہٹنا',
  situationRecentlyAcquired: 'حال ہی میں خریدی گئی یا معاہدے کے تحت',
  situationLeaseUp: 'ابتدائی کرایہ داری یا کارکردگی میں بہتری',
  situationOperations: 'آپریشنز یا رپورٹنگ کے مسائل',
  situationExploring: 'انتظامی اختیارات دیکھ رہے ہیں',
  situationSomethingElse: 'کچھ اور',

  involvementPm: 'جائیداد کا انتظام',
  involvementPmHint: 'جائیداد کو روزمرہ کی بنیاد پر چلانا۔',
  involvementPmAm: 'جائیداد کا انتظام + اثاثہ جات کا انتظام',
  involvementPmAmHint: 'جائیداد چلانا اور سرمایہ کاری کی حکمت عملی طے کرنے میں مدد کرنا۔',
  involvementNotSure: 'یقین نہیں',
  involvementNotSureHint: 'مناسب سطح طے کرنے میں میری مدد کریں۔',

  timingImmediately: 'فوری طور پر',
  timingWithin30: '30 دن کے اندر',
  timing30to60: '30 سے 60 دن',
  timing60to90: '60 سے 90 دن',
  timingStillExploring: 'ابھی غور کر رہے ہیں',

  investorTopicFirstAcquisition: 'اپنی پہلی خریداری پر غور کر رہا ہوں',
  investorTopicUnderContract: 'اس وقت معاہدے کے تحت',
  investorTopicActivelySearching: 'فعال طور پر تلاش کر رہے ہیں',
  investorTopicOwnProperty: 'جائیداد موجود ہے، آپریٹنگ ٹیم چاہیے',
  investorTopicSomethingElse: 'کچھ اور',
  // Embedded LTR brand name inside RTL text. Inspect this one visually first.
  generalTopicQuestion: 'AxisPoint کے بارے میں ایک سوال',
  generalTopicVendor: 'وینڈر یا سروس فراہم کنندہ',
  generalTopicEmployment: 'ملازمت',
  generalTopicPress: 'پریس یا میڈیا',
  generalTopicSomethingElse: 'کچھ اور',

  bookingModePhone: 'فون کال',
  bookingModeVideo: 'ویڈیو میٹنگ',

  scaleUnitsLabel: 'تخمینی یونٹس',
  scaleUnitsPlaceholder: 'مثال کے طور پر 184',
  scaleUnitsHelp:
    'ایک اندازاً عدد کافی ہے۔ ہم آپریٹنگ ٹیم کا حجم طے کر رہے ہیں، کرایہ ریکارڈ کا آڈٹ نہیں کر رہے۔',
  scaleSqftLabel: 'تخمینی رقبہ، مربع فٹ',
  scaleSqftPlaceholder: 'مثال کے طور پر 42,000',
  scaleSqftHelp: 'مجموعی قابل کرایہ رقبہ یہاں سب سے کارآمد عدد ہے۔',
  scaleMixedLabel: 'تخمینی مجموعی حجم',
  scaleMixedPlaceholder: 'مثال کے طور پر 300 یونٹ اور 40,000 مربع فٹ',
  scaleMixedHelp: 'یونٹس، مربع فٹ یا دونوں۔ جس طرح آپ حساب رکھتے ہیں، اسی طرح بتائیں۔',
  scaleOtherLabel: 'تخمینی حجم',
  scaleOtherPlaceholder: 'یونٹس، مربع فٹ یا کوئی اور پیمانہ',
  scaleOtherHelp: 'اس قسم کی جائیداد کے لیے جو پیمانہ مناسب ہو، اسی میں حجم بیان کریں۔',
  scaleFallbackLabel: 'تخمینی حجم',
  scaleFallbackPlaceholder: 'یونٹس یا مربع فٹ',
  scaleFallbackHelp: 'اوپر جائیداد کی قسم منتخب کریں، یہ خود درست پیمانے کے مطابق ہو جائے گا۔',

  investorKicker: 'سرمایہ کاروں کے لیے خدمات',
  investorTitle: 'بتائیں کہ آپ اس عمل میں کہاں ہیں۔',
  investorLead: 'شروع کرنے کے لیے ایک مختصر نوٹ کافی ہے۔ گفتگو طے کرنے کے لیے ہم رابطہ کریں گے۔',
  investorTopicLabel: 'آپ اس عمل میں کہاں ہیں؟',
  investorNoteLabel: 'آپ کس چیز پر غور کر رہے ہیں؟',
  investorNotePlaceholder: 'اثاثے کی قسم، مارکیٹ یا وقت',
  generalKicker: 'عمومی استفسار',
  generalTitle: 'ہم کس چیز میں مدد کر سکتے ہیں؟',
  generalLead: 'بتائیں کہ آپ کون ہیں اور آپ کو کیا چاہیے۔ ہم اسے مناسب پارٹنر تک پہنچائیں گے۔',
  generalTopicLabel: 'یہ کس بارے میں ہے؟',
  generalNoteLabel: 'آپ کا پیغام',
  generalNotePlaceholder: 'چند جملے کافی ہیں',
  organizationLabel: 'کمپنی',
  submitLabel: 'استفسار بھیجیں',

  nameHelp: 'آپ چاہتے ہیں کہ ہم آپ کو کس نام سے مخاطب کریں۔',
  nameError: 'وہ نام درج کریں جو ہمیں کال کرتے وقت پوچھنا چاہیے۔',
  emailHelp: 'جہاں ہم اپنا جواب اور آگے کی تفصیلات بھیجیں گے۔',
  // Two embedded LTR runs plus a trailing Urdu full stop. The highest-risk bidi string here.
  emailError:
    'اس پتے میں @ نشان کے بعد کا حصہ موجود نہیں۔ مکمل پتہ درج کریں، مثال کے طور پر name@company.com۔',
  topicError: 'وہ اختیار منتخب کریں جو آپ کے استفسار کو بہترین طور پر بیان کرتا ہو۔',
  followUpSameAsPage: 'اسی صفحے کی طرح، اردو',
  selectOne: 'ایک منتخب کریں',
  notSpecified: 'بیان نہیں کیا گیا',

  bookingCandidateNote:
    'اوقات سینٹرل ٹائم، ہیوسٹن میں دکھائے گئے ہیں۔ دستیابی کی تصدیق بکنگ کے وقت ہوتی ہے۔',
  bookingSlotTaken: 'وہ وقت اب دستیاب نہیں۔ براہ کرم کوئی اور منتخب کریں۔',
  bookingFailed: 'ہم اس وقت کی تصدیق نہ کر سکے۔ کچھ بک نہیں ہوا۔ دوبارہ کوشش کریں۔',
  bookingRefused: 'ہم وہ وقت بک نہ کر سکے، اور دوبارہ کوشش کرنے سے فائدہ نہیں ہوگا۔',
  bookingUnavailable: 'اس وقت شیڈولنگ دستیاب نہیں۔ کچھ بک نہیں ہوا۔',
  bookingDurationLabel: '30 منٹ',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'جائیداد کا انتظام',
  navAssetManagement: 'اثاثہ جات کا انتظام',
  navInvestorServices: 'سرمایہ کاروں کے لیے خدمات',
  navPartners: 'شراکت دار',
  navContact: 'رابطہ',
  navCta: 'انتظامی تجویز کی درخواست کریں',
  // LTR brand name followed by an Urdu comma. Another bidi string worth inspecting.
  navHomeAria: 'AxisPoint، ہوم',
  navPrimaryAria: 'بنیادی',
  navMenu: 'مینو',
  navMenuDialogAria: 'سائٹ مینو',
  navCloseMenu: 'مینو بند کریں',

  skipToContent: 'مرکزی مواد پر جائیں',

  footerPositioning:
    'پہلے جائیداد کا انتظام، اور جب جائیداد کو اوپر ایک حکمت عملی کی سطح درکار ہو تو اثاثہ جات کا انتظام بھی دستیاب ہے۔',
  footerServices: 'خدمات',
  footerFirm: 'فرم',
  footerLocation: 'ہیوسٹن، ٹیکساس',
  footerStatewide: 'پورے ٹیکساس میں مالکان کی خدمت',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'بروکریج اور لیزنگ کی سرگرمیاں ہمارے لائسنس یافتہ شراکت دار کے ذریعے انجام دی جاتی ہیں۔ AxisPoint Partners ٹیکس یا قانونی مشورہ فراہم نہیں کرتا۔ یہ ویب سائٹ صرف معلوماتی مقاصد کے لیے ہے اور سیکیورٹیز فروخت کرنے کی پیشکش نہیں ہے۔',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'صفحہ نہیں ملا',
  notFoundAction: 'ہوم پر جائیں',
  languageChooseAria: 'زبان منتخب کریں۔ موجودہ زبان: {language}۔',
  languageListAria: 'زبان منتخب کریں',

  /* ══ Marketing pages (PR 3) ══
   *
   * THE HIGHEST BIDI RISK IN THE WHOLE CATALOG IS HERE. These strings embed Latin runs
   * inside right-to-left prose far more often than the chrome did: `AxisPoint` appears in
   * headings and mid-sentence, and `Zachary Russell` and `Ethaniel Vu` appear inside
   * flowing text in four strings. Names are kept in Latin deliberately, matching every
   * other locale and matching `PartnersPage.tsx`, which renders them in Latin regardless of
   * locale. Transliterating them would show a reader two different spellings of the same
   * person on one page.
   *
   * The strings to inspect visually first are `pmA2`, `homeHeroSignature`,
   * `partnersSignature`, and `partnersMetaDescription`: each ends a Latin run near a comma
   * or an Urdu full stop (۔), which is exactly where the bidi algorithm places punctuation
   * at the wrong end of the line.
   *
   * NO BIDI CONTROL CHARACTERS ARE EMBEDDED, deliberately. See the file header.
   * Place names use established Urdu forms: ہیوسٹن، ٹیکساس، ڈیلاس، فورٹ ورتھ، سان انتونیو، آسٹن. */

  partnersSignature: 'Zachary Russell اور Ethaniel Vu، شراکت دار۔',
  pmRunsAmDirectsTitle:
    'جائیداد کا انتظام جائیداد چلاتا ہے۔ اثاثہ جات کا انتظام سرمایہ کاری کی سمت طے کرتا ہے۔',

  homeMetaTitle: 'AxisPoint Partners | ٹیکساس میں تجارتی جائیداد کا انتظام',
  homeMetaDescription:
    'AxisPoint پورے ٹیکساس میں مالکان کے لیے کثیر خاندانی اور ریٹیل جائیدادوں کا انتظام کرتا ہے، موقع پر آپریشنز اور مالی نگرانی سے لے کر وینڈر کی کارکردگی اور مالکان کو دی جانے والی رپورٹنگ تک۔',
  homeHeroAlt: 'غروب آفتاب کے وقت کثیر خاندانی رہائشی کمپلیکس کا لان اور عمارت کا سامنے کا رخ',
  homeHeroTitle: 'ایک ٹیم جو آپ کی جائیداد کے چلنے کی ذمہ دار ہو۔',
  homeHeroLead:
    'AxisPoint پورے ٹیکساس میں مالکان کے لیے کثیر خاندانی اور ریٹیل جائیدادوں کا انتظام کرتا ہے، موقع پر آپریشنز اور مالی نگرانی سے لے کر وینڈر کی کارکردگی اور ان رپورٹوں تک جو مالکان واقعی پڑھتے ہیں۔',
  homeHeroQuietLink: 'دیکھیں ہم کن چیزوں کی ذمہ داری لیتے ہیں',
  homeHeroSignature: 'ہیوسٹن سے شراکت داروں Zachary Russell اور Ethaniel Vu کی قیادت میں۔',
  homeStripEyebrow: 'پہلے جائیداد کا انتظام',
  homeStripBody:
    'بنیادی توجہ: پورے ٹیکساس میں کثیر خاندانی اور ریٹیل جائیدادیں۔ مرکزی دفتر ہیوسٹن میں۔',
  homeWhyTitle: 'مالکان AxisPoint سے رابطہ کیوں کرتے ہیں',
  homeWhyLead: 'عام طور پر چار صورتوں میں سے ایک۔',
  homeWhySituationManager: 'موجودہ منتظم مالکان کا اعتماد کھو چکا ہے۔',
  homeWhySituationSelf: 'خود انتظام کرنا دوسری ملازمت بن چکا ہے۔',
  homeWhySituationAcquired:
    'حال ہی میں خریدی گئی جائیداد کو پہلا مہینہ ختم ہونے سے پہلے ایک آپریٹنگ ٹیم درکار ہے۔',
  homeWhyOr: 'یا',
  homeWhySituationReports: 'رپورٹیں وقت پر آتی ہیں اور پھر بھی جائیداد کی صورتحال نہیں بتاتیں۔',
  homeWhyBody:
    'چاروں کے پیچھے سوال ایک ہی ہے: آج جائیداد کا جواب کون دے رہا ہے۔ AxisPoint اس کا جواب ایک ذمہ دار ٹیم اور دو ایسے شراکت داروں سے دیتا ہے جو کام کے اتنے قریب ہیں کہ جائیداد کو نام سے جانتے ہیں۔',
  homeWhyLink: 'AxisPoint کن چیزوں کی ذمہ داری لیتا ہے',
  homeStrategicEyebrow: 'حکمت عملی کی سطح',
  homeStrategicBody:
    'ان مالکان کے لیے جو آپریٹنگ کام کے اوپر ملکیتی سطح کا نقطہ نظر چاہتے ہیں، AxisPoint جائیداد کی کارکردگی کو بجٹ، سرمائے کی ترجیحات اور رکھنے کے فیصلوں سے جوڑتا ہے۔ جب جائیداد کو ضرورت ہو تبھی لیا جاتا ہے، اسے بطور معیار فروخت نہیں کیا جاتا۔',
  homeInvestorEyebrow: 'ایک الگ راستہ',
  homeInvestorBody:
    'آپریٹنگ ٹیم کے بغیر تجارتی جائیداد میں داخل ہو رہے ہیں؟ سرمایہ کاروں کے لیے خدمات ہی داخلے کا راستہ ہیں۔',
  homeClosingTitle: 'بتائیں کہ جائیداد کو آگے کیا درکار ہے۔',
  homeClosingBody:
    'جائیداد، انتظام کی موجودہ صورتحال، اور جو تبدیلی آپ سوچ رہے ہیں، بھیجیں۔ ایک شراکت دار اسے پڑھ کر جواب دیتا ہے۔',

  pmMetaTitle: 'ہیوسٹن اور پورے ٹیکساس میں جائیداد کا انتظام | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint ٹیکساس میں کثیر خاندانی اور ریٹیل جائیدادوں کی آپریٹنگ ذمہ داری لیتا ہے: موقع پر آپریشنز، مالی نگرانی، وینڈر کی کارکردگی اور مالکان کو رپورٹنگ۔',
  pmHeroTitle: 'ہیوسٹن اور پورے ٹیکساس میں تجارتی جائیداد کا انتظام',
  pmHeroLead:
    'AxisPoint کثیر خاندانی اور ریٹیل جائیدادوں کی آپریٹنگ ذمہ داری لیتا ہے: موقع پر موجود ٹیم، رقم، وینڈرز، اور وہ رپورٹیں جن سے مالکان فیصلے کرتے ہیں۔',
  pmSeeFunctions: 'چار آپریٹنگ شعبے دیکھیں',
  pmPhotoAlt: 'ٹیکساس کے ایک کثیر خاندانی کمپلیکس اور ملحقہ ریٹیل مرکز کا فضائی منظر',
  pmResponsibilityTitle: 'AxisPoint کن چیزوں کی ذمہ داری لیتا ہے',
  pmResponsibilityBody:
    'ہر وہ چیز جو طے کرتی ہے کہ جائیداد روزانہ کیسے چلتی ہے، اور اس کا ایک مالک کے لیے تیار ریکارڈ۔ جب جائیداد پر کچھ غلط ہوتا ہے تو مالکان کو یہ ڈھونڈنا نہیں پڑتا کہ کسے فون کریں۔',
  pmFunctionsTitle: 'چار آپریٹنگ شعبے، ایک ذمہ دار ٹیم',
  pmFnOnsiteTitle: 'موقع پر آپریشنز',
  pmFnOnsiteLede:
    'جائیداد پر موجود لوگ اور وہ معمولات جن پر وہ قائم رہتے ہیں۔ عملے کے فیصلے، کرایہ داری کی نگرانی، جواب دہی کے معیار، اور تیاری کے شیڈول جو جائیداد کو ہر ہفتے منصوبے کے مطابق رکھتے ہیں۔',
  pmFnOnsiteItem1: 'موقع پر عملہ اور نگرانی',
  pmFnOnsiteItem2: 'کرایہ داری کی نگرانی',
  pmFnOnsiteItem3: 'رہائشیوں اور کرایہ داروں کا جواب',
  pmFnOnsiteItem4: 'خالی ہونا اور دوبارہ تیاری',
  pmFnOnsiteItem5: 'احتیاطی دیکھ بھال',
  pmFnFinancialTitle: 'مالی نگرانی',
  pmFnFinancialLede:
    'مالکان کے ساتھ بنائے گئے بجٹ، پہلے سے طے شدہ منظوری کی حدود، اور ایسا ماہانہ اختتام جس میں ہر عدد اپنے پیچھے کے فیصلے تک واپس تلاش کیا جا سکے۔',
  pmFnFinancialItem1: 'سالانہ بجٹ اور نظرثانی شدہ پیش گوئی',
  pmFnFinancialItem2: 'منظوری کی حدود',
  pmFnFinancialItem3: 'وصولی اور واجبات',
  pmFnFinancialItem4: 'قابل ادائیگی رقوم اور ماہ کے آخر کا اختتام',
  pmFnFinancialItem5: 'فرق کی وضاحت',
  pmFnVendorTitle: 'وینڈر کی کارکردگی',
  pmFnVendorLede:
    'واضح دائرہ کار والا کام، حقیقی بولی کا نظم، اور ایسی پیروی جو ٹکٹ بند ہونے سے نہیں بلکہ نتیجے کے معیار سے ناپی جاتی ہے۔',
  pmFnVendorItem1: 'دائرہ کار اور بولی کا عمل',
  pmFnVendorItem2: 'معاہدے اور بیمے کی تعمیل',
  pmFnVendorItem3: 'معیار کی تصدیق',
  pmFnVendorItem4: 'سرمایہ منصوبوں کی ہم آہنگی',
  pmFnReportingTitle: 'مالکان کو رپورٹنگ اور رابطہ',
  pmFnReportingLede:
    'ایک ریکارڈ کہ جائیداد پر کیا ہوا، اس پر کیا لاگت آئی اور آگے کیا ہے، اور ساتھ ایک شراکت دار جو رپورٹنگ کے دورانیوں کے درمیان بھی جواب دیتا ہے۔',
  pmFnReportingItem1: 'ماہانہ رپورٹنگ پیکج',
  pmFnReportingItem2: 'آپریٹنگ تفصیل',
  pmFnReportingItem3: 'سرمائے اور منصوبوں کی نگرانی',
  pmFnReportingItem4: 'شراکت دار تک براہ راست رسائی',
  pmStrengthsTitle: 'AxisPoint کہاں سب سے مضبوط ہے',
  pmStrengthsBody:
    'یہ وہ صورتیں ہیں جن کے لیے یہ ٹیم بنی ہے۔ یہ شرائط نہیں بلکہ مضبوطی کے شعبے ہیں، اور ان سے باہر کی جائیداد پر بھی بات کرنا بامعنی ہے۔',
  pmStrengthTypesTitle: 'جائیداد کی اقسام',
  pmStrengthTypesItem1: 'کثیر خاندانی بنیادی توجہ کے طور پر',
  pmStrengthTypesItem2: 'ریٹیل بنیادی توجہ کے طور پر',
  pmStrengthTypesItem3: 'ایسی جائیدادیں جو موقع پر عملہ سنبھال سکیں',
  pmStrengthTypesItem4: 'ایک ہی مالک کے تحت مربوط پورٹ فولیو',
  pmStrengthTypesItem5: 'بکھری ہوئی جائیدادیں جو ایک ہی پروگرام کے طور پر چلائی جائیں',
  pmStrengthGeographyTitle: 'جغرافیہ',
  pmStrengthGeographyItem1: 'ہیوسٹن اور اس کا گرد و نواح',
  pmStrengthGeographyItem2: 'ڈیلاس اور فورٹ ورتھ',
  pmStrengthGeographyItem3: 'سان انتونیو',
  pmStrengthGeographyItem4: 'آسٹن',
  pmStrengthGeographyItem5: 'پورے ٹیکساس میں مالکان',
  pmStrengthAssignmentsTitle: 'ذمہ داریاں',
  pmStrengthAssignmentsItem1: 'انتظام کی منتقلی',
  pmStrengthAssignmentsItem2: 'ابتدائی کرایہ داری',
  pmStrengthAssignmentsItem3: 'بڑے سرمایہ پروگرام',
  pmStrengthAssignmentsItem4: 'مؤخر کیے گئے آپریٹنگ مسائل',
  pmStrengthAssignmentsItem5: 'کارکردگی بہتر بنانے کی ذمہ داریاں',
  pmQuestionsTitle: 'تبدیلی سے پہلے مالکان جو سوال کرتے ہیں',
  pmQ1: 'انتظام کی منتقلی میں کتنا وقت لگتا ہے؟',
  pmA1: 'یہ جائیداد اور جانے والے منتظم پر منحصر ہے، لیکن منصوبہ آغاز کی تاریخ سے پہلے لکھ لیا جاتا ہے: عملہ، نظام، بینکنگ، وینڈر ریکارڈ، اور رہائشیوں یا کرایہ داروں سے رابطہ، ہر ایک کا ایک ذمہ دار اور ایک تاریخ ہوتی ہے۔',
  pmQ2: 'میری جائیداد کا اصل میں جواب کون دے گا؟',
  pmA2: 'ایک شراکت دار۔ Zachary Russell اور Ethaniel Vu کام کے اتنے قریب رہتے ہیں کہ جائیداد کو نام سے جانتے ہیں، اور ان تک پہنچنے کے لیے مالکان کو کسی اکاؤنٹ کی تہہ سے نہیں گزرنا پڑتا۔',
  pmQ3: 'ماہ بہ ماہ رپورٹنگ کیسی ہوتی ہے؟',
  pmA3: 'ایک مستقل شیڈول پر ایک مستقل پیکج، جس کے ساتھ تحریری تفصیل فرق کی وضاحت کرتی ہے، بجائے اس کے کہ مالکان اعداد کو خود سمجھیں۔',
  pmQ4: 'کیا آپ مؤخر مسائل والی جائیداد سنبھال سکتے ہیں؟',
  pmA4: 'جی ہاں۔ مؤخر دیکھ بھال، نامکمل سرمایہ کام اور عملے کی کمی، مالکان کے رابطہ کرنے کی عام وجوہات ہیں۔ تجویز میں لکھا جاتا ہے کہ پہلے کیا اور کس ترتیب سے کیا جائے گا۔',
  pmRelatedEyebrow: 'متعلقہ',
  pmRelatedAsset:
    'اثاثہ جات کا انتظام آپریٹنگ کام کے اوپر ہے، ان مالکان کے لیے جو سرمایہ کاری کا نقطہ نظر چاہتے ہیں',
  pmRelatedInvestor:
    'سرمایہ کاروں کے لیے خدمات ان سرمایہ رکھنے والے کلائنٹس کا داخلی راستہ ہیں جن کے پاس آپریٹنگ ٹیم نہیں',
  pmClosingTitle: 'ہمیں جائیداد اور صورتحال بھیجیں۔',
  pmClosingBody:
    'ایک انتظامی تجویز میں عملہ، رپورٹنگ پیکج، منتقلی کا منصوبہ، اور یہ شامل ہوتا ہے کہ AxisPoint میں جائیداد کا جواب کون دیتا ہے۔',

  amMetaTitle: 'ٹیکساس کے جائیداد مالکان کے لیے اثاثہ جات کا انتظام | AxisPoint Partners',
  amMetaDescription:
    'آپریٹنگ کام کے اوپر ملکیتی سطح کا نقطہ نظر: سرمائے کی ترجیحات، بجٹ کی سمت اور رکھنے کے فیصلے، اسی ٹیم کی معلومات پر مبنی جو پہلے سے جائیداد چلا رہی ہے۔',
  amHeroTitle: 'ٹیکساس کے جائیداد مالکان کے لیے اثاثہ جات کا انتظام',
  amHeroAnswer:
    'آپریٹنگ کام کے اوپر ملکیتی سطح کا نقطہ نظر: سرمائے کی ترجیحات، بجٹ کی سمت اور رکھنے کے فیصلے، ایسی ٹیم کی معلومات پر مبنی جو پہلے سے جائیداد چلا رہی ہے۔',
  amPhotoAlt: 'سڑک کی سطح سے نظر آتا ہیوسٹن ڈاؤن ٹاؤن کا ٹاور اور بلند پیدل راستہ',
  amRelationshipEyebrow: 'یہ تعلق',
  amRelationshipBody:
    'اثاثہ جات کا انتظام آپریٹنگ کام کے اوپر ایک سطح ہے، اس کا متبادل نہیں۔ یہ جوڑتا ہے کہ جائیداد ہفتہ بہ ہفتہ کیا کر رہی ہے، بجٹ، سرمائے کی ترجیحات اور رکھنے یا بیچنے کی گفتگو سے۔ مالکان اسے تب لیتے ہیں جب جائیداد کو ضرورت ہو۔',
  amLayersTitle: 'دو سطحیں، صاف الفاظ میں',
  amDecidesEyebrow: 'اثاثہ جات کا انتظام فیصلہ کرتا ہے',
  amDecidesItem1: 'سرمائے کی ترجیحات اور ان کی ترتیب',
  amDecidesItem2: 'بجٹ کی سمت اور نظرثانی کا رجحان',
  amDecidesItem3: 'رکھنے، دوبارہ مالی بندوبست اور فروخت کے سوالات',
  amDecidesItem4: 'مالکان کے ارادے کے مقابلے میں کارکردگی کا جائزہ',
  amExecutesEyebrow: 'جائیداد کا انتظام عمل درآمد کرتا ہے',
  amExecutesItem1: 'موقع پر آپریشنز اور عملہ',
  amExecutesItem2: 'مالی نگرانی اور ماہانہ اختتام',
  amExecutesItem3: 'وینڈر کا دائرہ کار اور کارکردگی',
  amExecutesItem4: 'مالکان کو رپورٹنگ اور رابطہ',
  amClosingTitle: 'جائیداد سے شروع کریں، پھر اوپر کی سطح شامل کریں۔',
  amClosingBody:
    'زیادہ تر مالکان جائیداد کے انتظام سے شروع کرتے ہیں۔ اثاثہ جات کا انتظام تب شامل کیا جاتا ہے جب سرمایہ کاری کے سوالات کا جواب اسی ٹیم سے درکار ہو۔',

  isMetaTitle: 'ٹیکساس کی تجارتی جائیداد کے لیے سرمایہ کاروں کی خدمات | AxisPoint Partners',
  isMetaDescription:
    'ان سرمایہ رکھنے والے کلائنٹس کے لیے جو ٹیکساس میں کثیر خاندانی یا ریٹیل جائیداد خرید رہے ہیں اور چاہتے ہیں کہ آپریٹنگ پہلو خریداری سے پہلے طے ہو، بعد میں نہیں۔',
  isHeroTitle: 'آپریٹنگ ٹیم کے ساتھ ٹیکساس کی تجارتی جائیداد میں داخلے کا راستہ',
  isHeroAnswer:
    'ان سرمایہ رکھنے والے کلائنٹس کے لیے جو ٹیکساس میں کثیر خاندانی یا ریٹیل جائیداد خرید رہے ہیں اور چاہتے ہیں کہ آپریٹنگ پہلو خریداری سے پہلے طے ہو، بعد میں نہیں۔',
  isPhotoAlt: 'ہیوسٹن میں ایک شاہراہ کے انٹرچینج کا فضائی منظر',
  isWhoEyebrow: 'یہ کن کے لیے ہے',
  isWhoLead: 'ایسے کلائنٹس جن کے پاس سرمایہ موجود ہے مگر عمل کرنے سے پہلے آپریٹنگ ٹیم درکار ہے۔',
  isWhoBody:
    'سرمایہ کاروں کے لیے خدمات تینوں راستوں میں سب سے چھوٹا ہے اور جان بوجھ کر ایسا ہی رہتا ہے۔ یہ ان مالکان کے لیے ہے جو تجارتی جائیداد میں، یا ٹیکساس میں، داخل ہو رہے ہیں اور چاہتے ہیں کہ آپریٹنگ پہلو پہلی جائیداد سے ہی سنبھالا جائے، نہ کہ سودا مکمل ہونے کے بعد جوڑا جائے۔',
  isTimelineBeforeLabel: 'خریداری سے پہلے',
  isTimelineBeforeBody:
    'اس بات کا آپریٹنگ جائزہ کہ جائیداد چلانے میں کیا لگے گا، تاکہ پیشکش کے پیچھے کے مفروضے وہی ہوں جو ایک منتظم استعمال کرے گا۔',
  isTimelineClosingLabel: 'سودے کے وقت',
  isTimelineClosingBody:
    'پہلے دن سے ایک انتظامی ٹیم موجود، جس میں عملہ، نظام اور وینڈر تعلقات زیر التوا نہیں بلکہ تیار ہوں۔',
  isTimelineAfterLabel: 'پہلی جائیداد کے بعد',
  isTimelineAfterBody:
    'تعلق جائیداد کے انتظام میں منتقل ہو جاتا ہے، اور اگر مالکان کا نقطہ نظر تقاضا کرے تو اثاثہ جات کا انتظام بھی شامل ہوتا ہے۔',
  isClosingTitle: 'بتائیں کہ آپ کیا خریدنا چاہتے ہیں۔',
  isClosingBody:
    'جائیداد کی قسم، مارکیٹ اور وقت بھیجیں۔ ایک شراکت دار آپریٹنگ جائزے کے ساتھ جواب دیتا ہے اور بتاتا ہے کہ انتظام کیسا ہوگا۔',
  isClosingCta: 'خریداری پر بات کریں',

  partnersMetaTitle: 'شراکت دار | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint ہیوسٹن سے شراکت داروں کی قیادت میں چلتا ہے۔ Zachary Russell اور Ethaniel Vu ان جائیدادوں پر قائم رہتے ہیں جو وہ سنبھالتے ہیں، اس لیے مالکان فیصلہ کرنے والوں سے براہ راست بات کرتے ہیں۔',
  partnersHeroTitle: 'دو شراکت دار، کام کے براہ راست ذمہ دار',
  partnersHeroAnswer:
    'AxisPoint ہیوسٹن سے شراکت داروں کی قیادت میں چلتا ہے۔ جو ذمہ داری قبول کرتے ہیں، وہی اس پر قائم رہتے ہیں۔',
  partnersRoleLabel: 'شراکت دار',
  partnerRussellBody:
    'براہ راست آپریٹنگ کارکردگی پر کام کرتے ہیں: عملے کے فیصلے، منتقلیاں، سرمایہ پروگرام، اور پورٹ فولیو کی وہ جائیدادیں جن پر اس مہینے توجہ درکار ہے۔',
  partnerVuBody:
    'براہ راست مالی نگرانی اور مالکان کے لیے تیار ریکارڈ پر کام کرتے ہیں: بجٹ، منظوری کا نظم، ماہانہ اختتام، اور وہ رپورٹیں جن سے مالکان فیصلے کرتے ہیں۔',
  partnersHowEyebrow: 'ہم کیسے کام کرتے ہیں',
  partnersHowBody:
    'دونوں شراکت دار ان جائیدادوں پر قائم رہتے ہیں جو وہ سنبھالتے ہیں۔ مالکان فیصلہ کرنے والوں سے بات کرتے ہیں، نہ کہ ان کے آگے کھڑی کی گئی کسی تہہ سے۔',
  partnersClosingTitle: 'اپنی جائیداد کے بارے میں کسی شراکت دار سے بات کریں۔',
  partnersClosingBody:
    'جائیداد اور صورتحال بھیجیں۔ جو شراکت دار اسے پڑھتا ہے، وہی اس کا جواب دے گا۔',
};
