import type { Messages } from '../../messages';

/**
 * URDU. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Urdu has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `ur` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * ── THIS IS THE ONLY RTL LOCALE, AND IT IS THE ONE TO TEST HARDEST ──────────
 *
 * `direction: 'rtl'` in the registry, applied to `<html dir>` by `LocaleProvider`. Everything
 * below is what a reviewer and a layout check should be looking for:
 *
 * MIXED-DIRECTION STRINGS ARE THE RISK. Several values embed left-to-right runs inside
 * right-to-left text: `AxisPoint` in `generalTopicQuestion`, `name@company.com` and the bare
 * `@` in `emailError`, and Western digits in the timing and scale strings. The Unicode
 * bidirectional algorithm resolves these by itself and usually gets them right, but trailing
 * punctuation after an LTR run is the classic failure: an Urdu full stop (۔) after an email
 * address can render at the wrong end of the line. `emailError` and `generalTopicQuestion`
 * are the two strings to inspect visually first.
 *
 * NO BIDI CONTROL CHARACTERS ARE EMBEDDED HERE, deliberately. Invisible marks like U+200F
 * would paper over a layout bug in this one file while leaving it broken everywhere else,
 * and they survive into stored data and outbound mail where nobody expects them. If a string
 * renders wrongly, fix the CSS or the surrounding markup, not the data.
 *
 * PUNCTUATION. Urdu uses ۔ as the full stop and ، as the comma, not the Latin forms. Both are
 * used throughout. This is correct for the script and is unrelated to the project's
 * no-em-dash rule.
 *
 * LINE HEIGHT. 1.55 in the registry. Nastaliq-influenced faces need it; at Latin leading the
 * descenders collide. Noto Sans Arabic is the registry's stack and is naskh rather than
 * nastaliq, which many Urdu readers find noticeably less comfortable than a nastaliq face
 * such as Noto Nastaliq Urdu. THAT IS A REAL OPEN QUESTION for the reviewer, and it is a
 * font decision rather than a translation one. Recorded in `docs/STATUS.md`.
 *
 * GENDER. As in Hindi, first-person verbs agree with the speaker's gender and the visitor's
 * is unknown; the masculine default is used (`کر رہا ہوں`). A reviewer should choose.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const UR: Partial<Messages> = {
  gatewayTitle: 'آپ کس بارے میں بات کرنا چاہیں گے؟',
  gatewayLead:
    'وہ راستہ منتخب کریں جو آپ کی صورتحال سے سب سے زیادہ مطابقت رکھتا ہو۔ آپ بعد میں اسے تبدیل کر سکتے ہیں۔',
  gatewayOwnerKicker: 'زیادہ تر مالکان یہیں سے شروع کرتے ہیں',
  gatewayOwnerTitle: 'جائیداد کے مالک',
  gatewayOwnerBody: 'میں ایک جائیداد کا مالک ہوں یا اس کی نگرانی کرتا ہوں اور مجھے انتظام کی ضرورت ہے۔',
  gatewayOwnerAction: 'جائیداد کی تفصیلات شروع کریں',
  gatewayAssetTitle: 'اثاثہ جات کا انتظام',
  gatewayAssetBody:
    'میرے پاس جائیداد ہے اور مجھے حکمت عملی، کارکردگی اور رپورٹنگ کی رہنمائی میں مدد چاہیے۔',
  gatewayInvestorTitle: 'سرمایہ کاروں کے لیے خدمات',
  gatewayInvestorBody:
    'میں تجارتی جائیداد خریدنے کی تیاری کر رہا ہوں اور مجھے ایک آپریٹنگ ٹیم چاہیے۔',
  gatewayGeneralTitle: 'عمومی استفسار',
  gatewayGeneralBody: 'کچھ اور۔ وینڈرز، پریس، ملازمت یا کوئی سوال۔',

  propertyTypeMultifamily: 'کثیر خاندانی',
  propertyTypeRetail: 'ریٹیل',
  propertyTypeMixedPortfolio: 'مخلوط پورٹ فولیو',
  propertyTypeAnother: 'کسی اور قسم کی جائیداد',
  propertyScopeOne: 'ایک جائیداد',
  propertyScopePortfolio: 'پورٹ فولیو',

  situationReplace: 'موجودہ انتظام تبدیل کرنا',
  situationMoveAway: 'خود انتظام سے ہٹنا',
  situationRecentlyAcquired: 'حال ہی میں خریدی گئی یا معاہدے کے تحت',
  situationLeaseUp: 'ابتدائی کرایہ داری یا کارکردگی میں بہتری',
  situationOperations: 'آپریشنز یا رپورٹنگ کے مسائل',
  situationExploring: 'انتظامی اختیارات دیکھ رہے ہیں',
  situationSomethingElse: 'کچھ اور',

  involvementPm: 'جائیداد کا انتظام',
  involvementPmHint: 'جائیداد کو روزمرہ کی بنیاد پر چلانا۔',
  involvementPmAm: 'جائیداد کا انتظام + اثاثہ جات کا انتظام',
  involvementPmAmHint: 'جائیداد چلانا اور سرمایہ کاری کی حکمت عملی طے کرنے میں مدد کرنا۔',
  involvementNotSure: 'یقین نہیں',
  involvementNotSureHint: 'مناسب سطح طے کرنے میں میری مدد کریں۔',

  timingImmediately: 'فوری طور پر',
  timingWithin30: '30 دن کے اندر',
  timing30to60: '30 سے 60 دن',
  timing60to90: '60 سے 90 دن',
  timingStillExploring: 'ابھی غور کر رہے ہیں',

  investorTopicFirstAcquisition: 'اپنی پہلی خریداری پر غور کر رہا ہوں',
  investorTopicUnderContract: 'اس وقت معاہدے کے تحت',
  investorTopicActivelySearching: 'فعال طور پر تلاش کر رہے ہیں',
  investorTopicOwnProperty: 'جائیداد موجود ہے، آپریٹنگ ٹیم چاہیے',
  investorTopicSomethingElse: 'کچھ اور',
  // Embedded LTR brand name inside RTL text. Inspect this one visually first.
  generalTopicQuestion: 'AxisPoint کے بارے میں ایک سوال',
  generalTopicVendor: 'وینڈر یا سروس فراہم کنندہ',
  generalTopicEmployment: 'ملازمت',
  generalTopicPress: 'پریس یا میڈیا',
  generalTopicSomethingElse: 'کچھ اور',

  bookingModePhone: 'فون کال',
  bookingModeVideo: 'ویڈیو میٹنگ',

  scaleUnitsLabel: 'تخمینی یونٹس',
  scaleUnitsPlaceholder: 'مثال کے طور پر 184',
  scaleUnitsHelp:
    'ایک اندازاً عدد کافی ہے۔ ہم آپریٹنگ ٹیم کا حجم طے کر رہے ہیں، کرایہ ریکارڈ کا آڈٹ نہیں کر رہے۔',
  scaleSqftLabel: 'تخمینی رقبہ، مربع فٹ',
  scaleSqftPlaceholder: 'مثال کے طور پر 42,000',
  scaleSqftHelp: 'مجموعی قابل کرایہ رقبہ یہاں سب سے کارآمد عدد ہے۔',
  scaleMixedLabel: 'تخمینی مجموعی حجم',
  scaleMixedPlaceholder: 'مثال کے طور پر 300 یونٹ اور 40,000 مربع فٹ',
  scaleMixedHelp: 'یونٹس، مربع فٹ یا دونوں۔ جس طرح آپ حساب رکھتے ہیں، اسی طرح بتائیں۔',
  scaleOtherLabel: 'تخمینی حجم',
  scaleOtherPlaceholder: 'یونٹس، مربع فٹ یا کوئی اور پیمانہ',
  scaleOtherHelp: 'اس قسم کی جائیداد کے لیے جو پیمانہ مناسب ہو، اسی میں حجم بیان کریں۔',
  scaleFallbackLabel: 'تخمینی حجم',
  scaleFallbackPlaceholder: 'یونٹس یا مربع فٹ',
  scaleFallbackHelp: 'اوپر جائیداد کی قسم منتخب کریں، یہ خود درست پیمانے کے مطابق ہو جائے گا۔',

  investorKicker: 'سرمایہ کاروں کے لیے خدمات',
  investorTitle: 'بتائیں کہ آپ اس عمل میں کہاں ہیں۔',
  investorLead: 'شروع کرنے کے لیے ایک مختصر نوٹ کافی ہے۔ گفتگو طے کرنے کے لیے ہم رابطہ کریں گے۔',
  investorTopicLabel: 'آپ اس عمل میں کہاں ہیں؟',
  investorNoteLabel: 'آپ کس چیز پر غور کر رہے ہیں؟',
  investorNotePlaceholder: 'اثاثے کی قسم، مارکیٹ یا وقت',
  generalKicker: 'عمومی استفسار',
  generalTitle: 'ہم کس چیز میں مدد کر سکتے ہیں؟',
  generalLead: 'بتائیں کہ آپ کون ہیں اور آپ کو کیا چاہیے۔ ہم اسے مناسب پارٹنر تک پہنچائیں گے۔',
  generalTopicLabel: 'یہ کس بارے میں ہے؟',
  generalNoteLabel: 'آپ کا پیغام',
  generalNotePlaceholder: 'چند جملے کافی ہیں',
  organizationLabel: 'کمپنی',
  submitLabel: 'استفسار بھیجیں',

  nameHelp: 'آپ چاہتے ہیں کہ ہم آپ کو کس نام سے مخاطب کریں۔',
  nameError: 'وہ نام درج کریں جو ہمیں کال کرتے وقت پوچھنا چاہیے۔',
  emailHelp: 'جہاں ہم اپنا جواب اور آگے کی تفصیلات بھیجیں گے۔',
  // Two embedded LTR runs plus a trailing Urdu full stop. The highest-risk bidi string here.
  emailError:
    'اس پتے میں @ نشان کے بعد کا حصہ موجود نہیں۔ مکمل پتہ درج کریں، مثال کے طور پر name@company.com۔',
  topicError: 'وہ اختیار منتخب کریں جو آپ کے استفسار کو بہترین طور پر بیان کرتا ہو۔',
  followUpSameAsPage: 'اسی صفحے کی طرح، اردو',
  selectOne: 'ایک منتخب کریں',
  notSpecified: 'بیان نہیں کیا گیا',

  bookingCandidateNote:
    'اوقات سینٹرل ٹائم، ہیوسٹن میں دکھائے گئے ہیں۔ دستیابی کی تصدیق بکنگ کے وقت ہوتی ہے۔',
  bookingSlotTaken: 'وہ وقت اب دستیاب نہیں۔ براہ کرم کوئی اور منتخب کریں۔',
  bookingFailed: 'ہم اس وقت کی تصدیق نہ کر سکے۔ کچھ بک نہیں ہوا۔ دوبارہ کوشش کریں۔',
  bookingRefused: 'ہم وہ وقت بک نہ کر سکے، اور دوبارہ کوشش کرنے سے فائدہ نہیں ہوگا۔',
  bookingUnavailable: 'اس وقت شیڈولنگ دستیاب نہیں۔ کچھ بک نہیں ہوا۔',
  bookingDurationLabel: '30 منٹ',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'جائیداد کا انتظام',
  navAssetManagement: 'اثاثہ جات کا انتظام',
  navInvestorServices: 'سرمایہ کاروں کے لیے خدمات',
  navPartners: 'شراکت دار',
  navContact: 'رابطہ',
  navCta: 'انتظامی تجویز کی درخواست کریں',
  // LTR brand name followed by an Urdu comma. Another bidi string worth inspecting.
  navHomeAria: 'AxisPoint، ہوم',
  navPrimaryAria: 'بنیادی',
  navMenu: 'مینو',
  navMenuDialogAria: 'سائٹ مینو',
  navCloseMenu: 'مینو بند کریں',

  skipToContent: 'مرکزی مواد پر جائیں',

  footerPositioning:
    'پہلے جائیداد کا انتظام، اور جب جائیداد کو اوپر ایک حکمت عملی کی سطح درکار ہو تو اثاثہ جات کا انتظام بھی دستیاب ہے۔',
  footerServices: 'خدمات',
  footerFirm: 'فرم',
  footerLocation: 'ہیوسٹن، ٹیکساس',
  footerStatewide: 'پورے ٹیکساس میں مالکان کی خدمت',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'بروکریج اور لیزنگ کی سرگرمیاں ہمارے لائسنس یافتہ شراکت دار کے ذریعے انجام دی جاتی ہیں۔ AxisPoint Partners ٹیکس یا قانونی مشورہ فراہم نہیں کرتا۔ یہ ویب سائٹ صرف معلوماتی مقاصد کے لیے ہے اور سیکیورٹیز فروخت کرنے کی پیشکش نہیں ہے۔',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'صفحہ نہیں ملا',
  notFoundAction: 'ہوم پر جائیں',
  languageChooseAria: 'زبان منتخب کریں۔ موجودہ زبان: {language}۔',
  languageListAria: 'زبان منتخب کریں',
};
