import type { Messages } from '../../messages';

/**
 * VIETNAMESE. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Vietnamese has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `vi` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * REGISTER. `quý vị` throughout, which is formal and audience-neutral. A reviewer should
 * confirm it against the intended Houston Vietnamese readership: `anh/chị` would read as
 * warmer and more personal, `ông/bà` as more distant, and the choice runs through most of
 * the file rather than sitting in one string.
 *
 * DIACRITICS. Every tone mark here is load-bearing. `apps/web/tests/unicode.test.ts` already
 * proves Vietnamese text survives the wire path unchanged; this file is the display side of
 * the same requirement, and a reviewer should check the rendered page rather than the source.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const VI: Partial<Messages> = {
  gatewayTitle: 'Quý vị muốn trao đổi về điều gì?',
  gatewayLead:
    'Hãy chọn hướng phù hợp nhất với tình huống của quý vị. Quý vị có thể thay đổi sau.',
  gatewayOwnerKicker: 'Phần lớn chủ sở hữu bắt đầu từ đây',
  gatewayOwnerTitle: 'Chủ sở hữu bất động sản',
  gatewayOwnerBody: 'Tôi sở hữu hoặc phụ trách một bất động sản và cần dịch vụ quản lý.',
  gatewayOwnerAction: 'Bắt đầu nhập thông tin bất động sản',
  gatewayAssetTitle: 'Quản lý tài sản',
  gatewayAssetBody:
    'Tôi sở hữu bất động sản và muốn được hỗ trợ định hướng chiến lược, hiệu quả hoạt động và báo cáo.',
  gatewayInvestorTitle: 'Dịch vụ cho nhà đầu tư',
  gatewayInvestorBody:
    'Tôi đang chuẩn bị mua bất động sản thương mại và cần một đội ngũ vận hành.',
  gatewayGeneralTitle: 'Câu hỏi chung',
  gatewayGeneralBody: 'Việc khác. Nhà cung cấp, báo chí, tuyển dụng hoặc một câu hỏi.',

  propertyTypeMultifamily: 'Nhà ở nhiều căn hộ',
  propertyTypeRetail: 'Mặt bằng bán lẻ',
  propertyTypeMixedPortfolio: 'Danh mục hỗn hợp',
  propertyTypeAnother: 'Loại bất động sản khác',
  propertyScopeOne: 'Một bất động sản',
  propertyScopePortfolio: 'Danh mục đầu tư',

  situationReplace: 'Thay đơn vị quản lý hiện tại',
  situationMoveAway: 'Ngừng tự quản lý',
  situationRecentlyAcquired: 'Mới mua lại hoặc đang trong hợp đồng',
  situationLeaseUp: 'Giai đoạn cho thuê ban đầu hoặc cải thiện hoạt động',
  situationOperations: 'Vấn đề về vận hành hoặc báo cáo',
  situationExploring: 'Đang tìm hiểu các phương án quản lý',
  situationSomethingElse: 'Việc khác',

  involvementPm: 'Quản lý bất động sản',
  involvementPmHint: 'Vận hành bất động sản hằng ngày.',
  involvementPmAm: 'Quản lý bất động sản + Quản lý tài sản',
  involvementPmAmHint: 'Vận hành bất động sản và hỗ trợ định hướng chiến lược đầu tư.',
  involvementNotSure: 'Chưa chắc chắn',
  involvementNotSureHint: 'Hãy giúp tôi xác định mức độ tham gia phù hợp.',

  timingImmediately: 'Ngay lập tức',
  timingWithin30: 'Trong vòng 30 ngày',
  timing30to60: 'Từ 30 đến 60 ngày',
  timing60to90: 'Từ 60 đến 90 ngày',
  timingStillExploring: 'Vẫn đang tìm hiểu',

  investorTopicFirstAcquisition: 'Đang tìm hiểu thương vụ đầu tiên',
  investorTopicUnderContract: 'Hiện đang trong hợp đồng',
  investorTopicActivelySearching: 'Đang tích cực tìm kiếm',
  investorTopicOwnProperty: 'Đã có bất động sản, cần đội ngũ vận hành',
  investorTopicSomethingElse: 'Việc khác',
  generalTopicQuestion: 'Một câu hỏi về AxisPoint',
  generalTopicVendor: 'Nhà cung cấp hoặc đơn vị dịch vụ',
  generalTopicEmployment: 'Việc làm',
  generalTopicPress: 'Báo chí hoặc truyền thông',
  generalTopicSomethingElse: 'Việc khác',

  bookingModePhone: 'Gọi điện thoại',
  bookingModeVideo: 'Họp trực tuyến',

  scaleUnitsLabel: 'Số căn hộ ước tính',
  scaleUnitsPlaceholder: 'Ví dụ 184',
  scaleUnitsHelp:
    'Một con số làm tròn là đủ. Chúng tôi đang xác định quy mô đội ngũ vận hành, không kiểm toán bảng tiền thuê.',
  scaleSqftLabel: 'Diện tích ước tính theo foot vuông',
  scaleSqftPlaceholder: 'Ví dụ 42,000',
  scaleSqftHelp: 'Tổng diện tích cho thuê là con số hữu ích nhất ở đây.',
  scaleMixedLabel: 'Quy mô tổng hợp ước tính',
  scaleMixedPlaceholder: 'Ví dụ 300 căn và 40,000 foot vuông',
  scaleMixedHelp:
    'Số căn, diện tích hoặc cả hai. Hãy cho chúng tôi biết theo cách quý vị vẫn theo dõi.',
  scaleOtherLabel: 'Quy mô ước tính',
  scaleOtherPlaceholder: 'Số căn, foot vuông hoặc đơn vị đo khác',
  scaleOtherHelp: 'Hãy mô tả quy mô theo cách phù hợp với loại bất động sản này.',
  scaleFallbackLabel: 'Quy mô ước tính',
  scaleFallbackPlaceholder: 'Số căn hoặc foot vuông',
  scaleFallbackHelp:
    'Chọn loại bất động sản ở trên và mục này sẽ chuyển sang đơn vị đo phù hợp.',

  investorKicker: 'Dịch vụ cho nhà đầu tư',
  investorTitle: 'Hãy cho chúng tôi biết quý vị đang ở giai đoạn nào.',
  investorLead:
    'Một ghi chú ngắn là đủ để bắt đầu. Chúng tôi sẽ liên hệ để sắp xếp một cuộc trao đổi.',
  investorTopicLabel: 'Quý vị đang ở giai đoạn nào?',
  investorNoteLabel: 'Quý vị đang quan tâm đến điều gì?',
  investorNotePlaceholder: 'Loại tài sản, thị trường hoặc thời gian',
  generalKicker: 'Câu hỏi chung',
  generalTitle: 'Chúng tôi có thể giúp gì?',
  generalLead:
    'Hãy cho chúng tôi biết quý vị là ai và cần gì. Chúng tôi sẽ chuyển đến đúng đối tác.',
  generalTopicLabel: 'Đây là về việc gì?',
  generalNoteLabel: 'Lời nhắn của quý vị',
  generalNotePlaceholder: 'Vài câu là đủ',
  organizationLabel: 'Công ty',
  submitLabel: 'Gửi câu hỏi',

  nameHelp: 'Cách quý vị muốn chúng tôi xưng hô.',
  nameError: 'Hãy nhập tên chúng tôi nên hỏi khi gọi điện.',
  emailHelp: 'Nơi chúng tôi sẽ gửi phản hồi và các thông tin tiếp theo.',
  emailError:
    'Địa chỉ này thiếu phần sau dấu @. Hãy nhập địa chỉ đầy đủ, ví dụ name@company.com.',
  topicError: 'Hãy chọn phương án mô tả đúng nhất câu hỏi của quý vị.',
  followUpSameAsPage: 'Giống trang này, tiếng Việt',
  selectOne: 'Chọn một mục',
  notSpecified: 'Không có thông tin',

  bookingCandidateNote:
    'Thời gian hiển thị theo Giờ Miền Trung, Houston. Tình trạng còn trống được xác nhận khi quý vị đặt lịch.',
  bookingSlotTaken: 'Thời gian đó không còn trống. Hãy chọn giờ khác.',
  bookingFailed:
    'Chúng tôi không xác nhận được thời gian đó. Chưa có lịch nào được đặt. Hãy thử lại.',
  bookingRefused: 'Chúng tôi không đặt được thời gian đó, và thử lại cũng không giúp ích.',
  bookingUnavailable: 'Hiện chưa thể đặt lịch. Chưa có lịch nào được đặt.',
  bookingDurationLabel: '30 phút',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'Quản lý bất động sản',
  navAssetManagement: 'Quản lý tài sản',
  navInvestorServices: 'Dịch vụ cho nhà đầu tư',
  navPartners: 'Đối tác',
  navContact: 'Liên hệ',
  navCta: 'Yêu cầu đề xuất quản lý',
  navHomeAria: 'AxisPoint, trang chủ',
  navPrimaryAria: 'Chính',
  // Kept as the English loanword, which is what Vietnamese interfaces overwhelmingly use.
  // A reviewer may prefer 'Danh mục'.
  navMenu: 'Menu',
  navMenuDialogAria: 'Menu trang web',
  navCloseMenu: 'Đóng menu',

  skipToContent: 'Chuyển đến nội dung chính',

  footerPositioning:
    'Quản lý bất động sản trước tiên, kèm quản lý tài sản khi bất động sản cần một lớp chiến lược bên trên.',
  footerServices: 'Dịch vụ',
  footerFirm: 'Công ty',
  footerLocation: 'Houston, Texas',
  footerStatewide: 'Phục vụ chủ sở hữu trên toàn bang Texas',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'Hoạt động môi giới và cho thuê được thực hiện thông qua đối tác có giấy phép của chúng tôi. AxisPoint Partners không cung cấp tư vấn thuế hoặc pháp lý. Trang web này chỉ nhằm mục đích cung cấp thông tin và không cấu thành lời chào bán chứng khoán.',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'Không tìm thấy trang',
  notFoundAction: 'Về trang chủ',
  languageChooseAria: 'Chọn ngôn ngữ. Ngôn ngữ hiện tại: {language}.',
  languageListAria: 'Chọn ngôn ngữ',

  /* ══ Marketing pages (PR 3) ══
   * REVIEWER QUESTION: `Đối tác` is used for the firm's partners, matching `navPartners`.
   * It is the ordinary word for a business partner and may not carry the professional-firm
   * sense of "Partner" as a title. `thành viên hợp danh` is the legal term and reads
   * formally. One choice should be made and applied to both keys.
   * Proper nouns preserved: AxisPoint, Houston, Texas, Dallas, Fort Worth, San Antonio,
   * Austin, and both partner names. */

  partnersSignature: 'Zachary Russell và Ethaniel Vu, Đối tác.',
  pmRunsAmDirectsTitle:
    'Quản lý bất động sản vận hành tài sản. Quản lý tài sản định hướng khoản đầu tư.',

  homeMetaTitle: 'AxisPoint Partners | Quản lý bất động sản thương mại tại Texas',
  homeMetaDescription:
    'AxisPoint quản lý bất động sản nhà ở nhiều căn hộ và mặt bằng bán lẻ cho chủ sở hữu trên khắp Texas, từ vận hành tại chỗ và kiểm soát tài chính đến hiệu quả nhà cung cấp và báo cáo cho chủ sở hữu.',
  homeHeroAlt: 'Bãi cỏ và mặt đứng của một khu nhà ở nhiều căn hộ lúc hoàng hôn',
  homeHeroTitle: 'Một đội ngũ chịu trách nhiệm về cách bất động sản của quý vị vận hành.',
  homeHeroLead:
    'AxisPoint quản lý bất động sản nhà ở nhiều căn hộ và mặt bằng bán lẻ cho chủ sở hữu trên khắp Texas, từ vận hành tại chỗ và kiểm soát tài chính đến hiệu quả nhà cung cấp và những báo cáo mà chủ sở hữu thực sự đọc.',
  homeHeroQuietLink: 'Xem chúng tôi chịu trách nhiệm những gì',
  homeHeroSignature: 'Do các đối tác Zachary Russell và Ethaniel Vu điều hành từ Houston.',
  homeStripEyebrow: 'Quản lý bất động sản trước tiên',
  homeStripBody:
    'Trọng tâm chính: bất động sản nhà ở nhiều căn hộ và mặt bằng bán lẻ trên khắp Texas. Trụ sở tại Houston.',
  homeWhyTitle: 'Vì sao chủ sở hữu tìm đến AxisPoint',
  homeWhyLead: 'Thường là một trong bốn tình huống.',
  homeWhySituationManager: 'Đơn vị quản lý hiện tại đã đánh mất niềm tin của chủ sở hữu.',
  homeWhySituationSelf: 'Tự quản lý đã trở thành một công việc thứ hai.',
  homeWhySituationAcquired:
    'Một bất động sản vừa mua lại cần đội ngũ vận hành trước khi tháng đầu tiên khép lại.',
  homeWhyOr: 'Hoặc',
  homeWhySituationReports:
    'báo cáo đến đúng hạn nhưng vẫn không giải thích được tình hình bất động sản.',
  homeWhyBody:
    'Câu hỏi nằm dưới cả bốn tình huống đều giống nhau: hôm nay ai chịu trách nhiệm về bất động sản này. AxisPoint trả lời bằng một đội ngũ chịu trách nhiệm và hai đối tác đủ sát công việc để gọi tên từng bất động sản.',
  homeWhyLink: 'AxisPoint chịu trách nhiệm những gì',
  homeStrategicEyebrow: 'Lớp chiến lược',
  homeStrategicBody:
    'Với những chủ sở hữu muốn có góc nhìn ở cấp sở hữu bên trên công việc vận hành, AxisPoint kết nối những gì bất động sản đang làm với ngân sách, thứ tự ưu tiên vốn và các quyết định nắm giữ. Được sử dụng khi bất động sản thực sự cần, không bán kèm theo mặc định.',
  homeInvestorEyebrow: 'Một hướng đi riêng',
  homeInvestorBody:
    'Bước vào bất động sản thương mại mà chưa có đội ngũ vận hành phía sau? Dịch vụ cho nhà đầu tư là lối vào.',
  homeClosingTitle: 'Hãy cho chúng tôi biết bất động sản cần gì tiếp theo.',
  homeClosingBody:
    'Gửi thông tin bất động sản, tình hình quản lý hiện tại và thay đổi quý vị đang cân nhắc. Một đối tác sẽ đọc và phản hồi.',

  pmMetaTitle: 'Quản lý bất động sản tại Houston và khắp Texas | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint nhận trách nhiệm vận hành cho bất động sản nhà ở nhiều căn hộ và mặt bằng bán lẻ tại Texas: vận hành tại chỗ, kiểm soát tài chính, hiệu quả nhà cung cấp và báo cáo cho chủ sở hữu.',
  pmHeroTitle: 'Quản lý bất động sản thương mại tại Houston và khắp Texas',
  pmHeroLead:
    'AxisPoint nhận trách nhiệm vận hành cho bất động sản nhà ở nhiều căn hộ và mặt bằng bán lẻ: đội ngũ tại chỗ, dòng tiền, nhà cung cấp và những báo cáo chủ sở hữu dùng để ra quyết định.',
  pmSeeFunctions: 'Xem bốn chức năng vận hành',
  pmPhotoAlt:
    'Ảnh chụp từ trên cao một khu nhà ở nhiều căn hộ tại Texas và trung tâm bán lẻ liền kề',
  pmResponsibilityTitle: 'AxisPoint chịu trách nhiệm những gì',
  pmResponsibilityBody:
    'Mọi thứ quyết định cách bất động sản vận hành hằng ngày, và một hồ sơ duy nhất dành cho chủ sở hữu. Khi có sự cố tại bất động sản, chủ sở hữu không phải đi tìm xem nên gọi cho ai.',
  pmFunctionsTitle: 'Bốn chức năng vận hành, một đội ngũ chịu trách nhiệm',
  pmFnOnsiteTitle: 'Vận hành tại chỗ',
  pmFnOnsiteLede:
    'Những con người tại bất động sản và các quy trình họ tuân thủ. Quyết định nhân sự, giám sát cho thuê, tiêu chuẩn phản hồi và lịch bàn giao giữ cho bất động sản đi đúng kế hoạch từng tuần.',
  pmFnOnsiteItem1: 'Nhân sự và giám sát tại chỗ',
  pmFnOnsiteItem2: 'Giám sát cho thuê',
  pmFnOnsiteItem3: 'Phản hồi cư dân và khách thuê',
  pmFnOnsiteItem4: 'Bàn giao và chuẩn bị căn hộ',
  pmFnOnsiteItem5: 'Bảo trì phòng ngừa',
  pmFnFinancialTitle: 'Kiểm soát tài chính',
  pmFnFinancialLede:
    'Ngân sách lập cùng chủ sở hữu, ngưỡng phê duyệt thống nhất từ trước, và một kỳ khóa sổ hằng tháng trong đó mọi con số đều truy được về quyết định phía sau nó.',
  pmFnFinancialItem1: 'Ngân sách năm và dự báo điều chỉnh',
  pmFnFinancialItem2: 'Ngưỡng phê duyệt',
  pmFnFinancialItem3: 'Thu tiền và công nợ quá hạn',
  pmFnFinancialItem4: 'Công nợ phải trả và khóa sổ cuối tháng',
  pmFnFinancialItem5: 'Giải trình chênh lệch',
  pmFnVendorTitle: 'Hiệu quả nhà cung cấp',
  pmFnVendorLede:
    'Công việc có phạm vi rõ ràng, kỷ luật đấu thầu thực chất, và việc theo sát được đo bằng chất lượng kết quả thay vì bằng việc đóng một phiếu yêu cầu.',
  pmFnVendorItem1: 'Phạm vi và quy trình đấu thầu',
  pmFnVendorItem2: 'Tuân thủ hợp đồng và bảo hiểm',
  pmFnVendorItem3: 'Kiểm chứng chất lượng',
  pmFnVendorItem4: 'Điều phối dự án vốn',
  pmFnReportingTitle: 'Báo cáo và trao đổi với chủ sở hữu',
  pmFnReportingLede:
    'Một hồ sơ duy nhất về những gì đã diễn ra tại bất động sản, chi phí bao nhiêu và điều gì tiếp theo, cùng một đối tác trả lời giữa các kỳ báo cáo.',
  pmFnReportingItem1: 'Bộ báo cáo hằng tháng',
  pmFnReportingItem2: 'Thuyết minh vận hành',
  pmFnReportingItem3: 'Theo dõi vốn và dự án',
  pmFnReportingItem4: 'Liên hệ trực tiếp với đối tác',
  pmStrengthsTitle: 'AxisPoint mạnh nhất ở đâu',
  pmStrengthsBody:
    'Đây là những tình huống đội ngũ được xây dựng để xử lý. Chúng là thế mạnh chứ không phải điều kiện bắt buộc, và một bất động sản nằm ngoài đó vẫn đáng để trao đổi.',
  pmStrengthTypesTitle: 'Loại bất động sản',
  pmStrengthTypesItem1: 'Nhà ở nhiều căn hộ là trọng tâm chính',
  pmStrengthTypesItem2: 'Mặt bằng bán lẻ là trọng tâm chính',
  pmStrengthTypesItem3: 'Bất động sản có thể duy trì nhân sự tại chỗ',
  pmStrengthTypesItem4: 'Danh mục được điều phối chung dưới một chủ sở hữu',
  pmStrengthTypesItem5: 'Danh mục phân tán được vận hành như một chương trình duy nhất',
  pmStrengthGeographyTitle: 'Địa bàn',
  pmStrengthGeographyItem1: 'Houston và vùng đô thị lân cận',
  pmStrengthGeographyItem2: 'Dallas và Fort Worth',
  pmStrengthGeographyItem3: 'San Antonio',
  pmStrengthGeographyItem4: 'Austin',
  pmStrengthGeographyItem5: 'Chủ sở hữu trên toàn bang Texas',
  pmStrengthAssignmentsTitle: 'Loại công việc',
  pmStrengthAssignmentsItem1: 'Chuyển giao quản lý',
  pmStrengthAssignmentsItem2: 'Giai đoạn cho thuê ban đầu',
  pmStrengthAssignmentsItem3: 'Chương trình vốn lớn',
  pmStrengthAssignmentsItem4: 'Vấn đề vận hành bị trì hoãn',
  pmStrengthAssignmentsItem5: 'Công việc cải thiện hoạt động',
  pmQuestionsTitle: 'Những câu hỏi chủ sở hữu đặt ra trước khi đổi đơn vị quản lý',
  pmQ1: 'Một lần chuyển giao quản lý mất bao lâu?',
  pmA1: 'Điều đó tùy thuộc vào bất động sản và đơn vị quản lý cũ, nhưng kế hoạch được viết ra trước ngày bắt đầu: nhân sự, hệ thống, ngân hàng, hồ sơ nhà cung cấp và việc thông báo cho cư dân hoặc khách thuê đều có người phụ trách và mốc thời gian riêng.',
  pmQ2: 'Ai thực sự chịu trách nhiệm về bất động sản của tôi?',
  pmA2: 'Một đối tác. Zachary Russell và Ethaniel Vu đủ sát công việc để gọi tên từng bất động sản, và chủ sở hữu không phải đi qua một lớp quản lý khách hàng mới liên hệ được với họ.',
  pmQ3: 'Báo cáo hằng tháng trông như thế nào?',
  pmA3: 'Một bộ báo cáo nhất quán theo lịch nhất quán, kèm thuyết minh bằng văn bản giải thích các chênh lệch thay vì để chủ sở hữu tự diễn giải các con số.',
  pmQ4: 'Quý vị có nhận bất động sản đang tồn đọng vấn đề không?',
  pmA4: 'Có. Bảo trì bị trì hoãn, công việc vốn chưa xử lý và thiếu hụt nhân sự là những lý do phổ biến khiến chủ sở hữu liên hệ. Đề xuất sẽ nêu rõ việc gì được xử lý trước và theo thứ tự nào.',
  pmRelatedEyebrow: 'Liên quan',
  pmRelatedAsset:
    'Quản lý tài sản nằm bên trên công việc vận hành, dành cho chủ sở hữu muốn có góc nhìn đầu tư',
  pmRelatedInvestor:
    'Dịch vụ cho nhà đầu tư là lối vào dành cho khách hàng đã sẵn vốn nhưng chưa có đội ngũ vận hành',
  pmClosingTitle: 'Hãy gửi cho chúng tôi bất động sản và tình huống.',
  pmClosingBody:
    'Một đề xuất quản lý bao gồm nhân sự, bộ báo cáo, kế hoạch chuyển giao và ai tại AxisPoint chịu trách nhiệm về bất động sản.',

  amMetaTitle: 'Quản lý tài sản cho chủ sở hữu tại Texas | AxisPoint Partners',
  amMetaDescription:
    'Góc nhìn ở cấp sở hữu bên trên công việc vận hành: thứ tự ưu tiên vốn, định hướng ngân sách và quyết định nắm giữ, dựa trên thông tin từ chính đội ngũ đang vận hành bất động sản.',
  amHeroTitle: 'Quản lý tài sản cho chủ sở hữu tại Texas',
  amHeroAnswer:
    'Góc nhìn ở cấp sở hữu bên trên công việc vận hành: thứ tự ưu tiên vốn, định hướng ngân sách và quyết định nắm giữ, dựa trên thông tin từ một đội ngũ đang vận hành bất động sản.',
  amPhotoAlt: 'Tòa tháp trung tâm Houston và lối đi trên cao nhìn từ mặt đường',
  amRelationshipEyebrow: 'Mối quan hệ',
  amRelationshipBody:
    'Quản lý tài sản là một lớp bên trên công việc vận hành, không thay thế nó. Nó kết nối những gì bất động sản làm hằng tuần với ngân sách, thứ tự ưu tiên vốn và câu chuyện giữ hay bán. Chủ sở hữu sử dụng khi bất động sản thực sự cần.',
  amLayersTitle: 'Hai lớp, nói cho rõ',
  amDecidesEyebrow: 'Quản lý tài sản quyết định',
  amDecidesItem1: 'Thứ tự ưu tiên vốn và trình tự triển khai',
  amDecidesItem2: 'Định hướng ngân sách và quan điểm dự báo điều chỉnh',
  amDecidesItem3: 'Các câu hỏi về nắm giữ, tái tài trợ và chuyển nhượng',
  amDecidesItem4: 'Đánh giá hiệu quả so với ý định của chủ sở hữu',
  amExecutesEyebrow: 'Quản lý bất động sản thực thi',
  amExecutesItem1: 'Vận hành tại chỗ và nhân sự',
  amExecutesItem2: 'Kiểm soát tài chính và khóa sổ hằng tháng',
  amExecutesItem3: 'Phạm vi và hiệu quả nhà cung cấp',
  amExecutesItem4: 'Báo cáo và trao đổi với chủ sở hữu',
  amClosingTitle: 'Bắt đầu từ bất động sản, rồi thêm lớp bên trên.',
  amClosingBody:
    'Phần lớn chủ sở hữu bắt đầu bằng quản lý bất động sản. Quản lý tài sản được thêm vào khi các câu hỏi đầu tư cần chính đội ngũ đó trả lời.',

  isMetaTitle:
    'Dịch vụ cho nhà đầu tư bất động sản thương mại tại Texas | AxisPoint Partners',
  isMetaDescription:
    'Dành cho khách hàng đã sẵn vốn đang mua bất động sản nhà ở nhiều căn hộ hoặc mặt bằng bán lẻ tại Texas, muốn phần vận hành được tính đến trước khi mua chứ không phải sau đó.',
  isHeroTitle:
    'Một lối vào bất động sản thương mại Texas với đội ngũ vận hành phía sau',
  isHeroAnswer:
    'Dành cho khách hàng đã sẵn vốn đang mua bất động sản nhà ở nhiều căn hộ hoặc mặt bằng bán lẻ tại Texas, muốn phần vận hành được tính đến trước khi mua chứ không phải sau đó.',
  isPhotoAlt: 'Ảnh chụp từ trên cao một nút giao cao tốc ở Houston',
  isWhoEyebrow: 'Dành cho ai',
  isWhoLead: 'Khách hàng đã sẵn vốn nhưng cần một đội ngũ vận hành mới có thể hành động.',
  isWhoBody:
    'Dịch vụ cho nhà đầu tư là hướng nhỏ nhất trong ba hướng và cố ý giữ như vậy. Nó dành cho chủ sở hữu bước vào bất động sản thương mại, hoặc bước vào Texas, muốn phần vận hành được lo từ bất động sản đầu tiên thay vì ghép lại sau khi hoàn tất giao dịch.',
  isTimelineBeforeLabel: 'Trước khi mua',
  isTimelineBeforeBody:
    'Một đánh giá vận hành về chi phí thực tế để vận hành bất động sản, để các giả định phía sau mức chào giá đúng với giả định mà một đơn vị quản lý sẽ dùng.',
  isTimelineClosingLabel: 'Khi hoàn tất giao dịch',
  isTimelineClosingBody:
    'Đội ngũ quản lý có mặt ngay từ ngày đầu, với nhân sự, hệ thống và quan hệ nhà cung cấp đã sẵn sàng thay vì còn dang dở.',
  isTimelineAfterLabel: 'Sau bất động sản đầu tiên',
  isTimelineAfterBody:
    'Mối quan hệ chuyển sang Quản lý bất động sản, kèm Quản lý tài sản nếu góc nhìn của chủ sở hữu cần đến.',
  isClosingTitle: 'Hãy cho chúng tôi biết quý vị định mua gì.',
  isClosingBody:
    'Gửi loại bất động sản, thị trường và thời gian dự kiến. Một đối tác sẽ phản hồi kèm đánh giá vận hành và hình dung về công tác quản lý.',
  isClosingCta: 'Trao đổi về một thương vụ',

  partnersMetaTitle: 'Đối tác | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint do các đối tác điều hành từ Houston. Zachary Russell và Ethaniel Vu gắn bó với những bất động sản họ nhận, nên chủ sở hữu trao đổi trực tiếp với người ra quyết định.',
  partnersHeroTitle: 'Hai đối tác, trực tiếp chịu trách nhiệm về công việc',
  partnersHeroAnswer:
    'AxisPoint do các đối tác điều hành từ Houston. Người nhận công việc cũng chính là người gắn bó với nó.',
  partnersRoleLabel: 'Đối tác',
  partnerRussellBody:
    'Trực tiếp phụ trách hiệu quả vận hành: quyết định nhân sự, các đợt chuyển giao, chương trình vốn và những bất động sản trong danh mục cần chú ý trong tháng này.',
  partnerVuBody:
    'Trực tiếp phụ trách kiểm soát tài chính và hồ sơ dành cho chủ sở hữu: ngân sách, kỷ luật phê duyệt, khóa sổ hằng tháng và những báo cáo chủ sở hữu dùng để ra quyết định.',
  partnersHowEyebrow: 'Cách chúng tôi làm việc',
  partnersHowBody:
    'Cả hai đối tác đều gắn bó với những bất động sản họ nhận. Chủ sở hữu trao đổi với người ra quyết định, không phải với một lớp trung gian được xếp phía trước.',
  partnersClosingTitle: 'Trao đổi với một đối tác về bất động sản của quý vị.',
  partnersClosingBody:
    'Gửi bất động sản và tình huống. Đối tác đọc nó chính là người sẽ chịu trách nhiệm về nó.',

  /* ══ Contact page and intake (PR 4) ══
   * Display text only; stored values stay stable snake_case tokens. Placeholders
   * {name} {email} {count} {day} {time} {mode} {language} must survive exactly. */

  contactEyebrow: 'Liên hệ',
  contactHeroTitle: 'Liên hệ AxisPoint',
  contactHeroLead:
    'Do các đối tác điều hành từ Houston, phục vụ chủ sở hữu trên khắp Texas. Hãy cho chúng tôi biết quý vị cần gì và một đối tác sẽ đọc.',
  contactMetaTitle: 'Liên hệ AxisPoint | AxisPoint Partners',
  contactMetaDescription:
    'Liên hệ trực tiếp với AxisPoint từ Houston, Texas, phục vụ chủ sở hữu trên toàn bang. Hãy chọn hướng phù hợp với tình huống của quý vị, hoặc viết thư tới info@axispoint.llc.',
  contactPathwayPmAm: 'Quản lý bất động sản và quản lý tài sản',
  contactPmMetaTitle: 'Yêu cầu đề xuất quản lý | AxisPoint Partners',
  contactPmMetaDescription:
    'Gửi thông tin bất động sản, tình hình quản lý hiện tại và thay đổi quý vị đang cân nhắc. Một đối tác sẽ đọc và phản hồi.',
  contactAmMetaTitle: 'Yêu cầu đề xuất quản lý kèm quản lý tài sản | AxisPoint Partners',
  contactAmMetaDescription:
    'Bắt đầu đề xuất quản lý với nhu cầu quản lý tài sản được nêu rõ, để công việc vận hành và góc nhìn đầu tư do cùng một đội ngũ đảm nhận.',
  contactIsMetaTitle: 'Câu hỏi về dịch vụ cho nhà đầu tư | AxisPoint Partners',
  contactIsMetaDescription:
    'Hãy cho chúng tôi biết quý vị đang ở giai đoạn nào. Một đối tác sẽ phản hồi kèm đánh giá vận hành và hình dung về công tác quản lý.',
  contactGeneralMetaTitle: 'Liên hệ AxisPoint | AxisPoint Partners',
  contactGeneralMetaDescription:
    'Hãy cho chúng tôi biết quý vị là ai và cần gì. Chúng tôi sẽ chuyển đến đúng đối tác.',

  fieldOptional: 'Không bắt buộc',

  gatewayEmailPrefix: 'Quý vị thích dùng email hơn? Hãy viết tới',

  ledgerChangePath: 'Đổi hướng',
  labelProperty: 'Bất động sản',
  labelPropertyEmpty: 'Loại, vị trí và quy mô',
  labelSituation: 'Tình huống',
  labelSituationEmpty: 'Điều gì cần thay đổi',
  labelContact: 'Liên hệ',
  labelContactEmpty: 'Cách chúng tôi liên hệ lại',
  labelInvolvement: 'Mức độ tham gia',
  labelPathway: 'Hướng',
  labelTopic: 'Chủ đề',
  labelFollowUpLanguage: 'Ngôn ngữ liên hệ lại',

  confirmKickerProperty: 'Đã gửi thông tin bất động sản',
  confirmKickerInquiry: 'Đã gửi câu hỏi',
  confirmTitleProperty: 'Cảm ơn {name}. Chúng tôi đã nhận thông tin bất động sản của quý vị.',
  confirmTitleInquiry: 'Cảm ơn {name}. Câu hỏi của quý vị đã đến với chúng tôi.',
  confirmBodyProperty: 'Zachary hoặc Ethaniel sẽ xem lại thông tin và liên hệ trực tiếp.',
  confirmBodyInquiry: 'Zachary hoặc Ethaniel sẽ xem lại và liên hệ trực tiếp qua {email}.',
  confirmWhatYouSent: 'Những gì quý vị đã gửi',
  confirmScheduleCta: 'Đặt cuộc gọi 30 phút',
  confirmWait: 'Tôi sẽ chờ liên hệ lại',
  backToAxisPoint: 'Quay lại AxisPoint',

  scheduleKicker: 'Bước tiếp theo không bắt buộc',
  scheduleTitle: 'Đặt cuộc gọi 30 phút',
  scheduleLead:
    'Thông tin bất động sản của quý vị đã được gửi. Chỉ chọn giờ nếu điều đó hữu ích với quý vị.',
  scheduleSelectDate: 'Chọn ngày',
  scheduleSelectTime: 'Chọn giờ',
  scheduleChooseDateFirst: 'Hãy chọn ngày để xem các khung giờ.',
  scheduleHowMeet: 'Quý vị muốn trao đổi theo hình thức nào?',
  scheduleSelectedLabel: 'Đã chọn',
  scheduleSelectedSummary: '{day} lúc {time}, {mode}',
  scheduleSelectedEmpty: 'Hãy chọn ngày, giờ và hình thức trao đổi',
  scheduleConfirm: 'Xác nhận giờ này',
  scheduleBooking: 'Đang đặt lịch',

  scheduledKicker: 'Đã xác nhận cuộc gọi',
  scheduledTitle: 'Quý vị đã có trong lịch.',
  labelWhen: 'Thời gian',
  labelFormat: 'Hình thức',
  labelLength: 'Thời lượng',
  labelWith: 'Với',
  // "Central" là múi giờ của công ty và không được dịch: thời điểm luôn được tính theo
  // America/Chicago, bất kể người đọc dùng ngôn ngữ nào.
  scheduledWhenValue: '{day}, {time} Central',
  scheduledInviteNote:
    'Lời mời lịch sẽ được gửi tới {email}. Hãy trả lời lời mời đó nếu quý vị cần đổi giờ.',
  scheduledDevNote:
    'Bản xem trước dành cho phát triển. Lệnh đặt lịch chạy trên trình mô phỏng, nên không có sự kiện lịch nào được tạo và không có lời mời nào được gửi.',

  skippedTitle: 'Chưa đặt cuộc gọi nào. Quý vị không cần làm gì thêm.',
  skippedBody:
    'Thông tin bất động sản của quý vị đang ở chỗ Zachary và Ethaniel, và họ sẽ liên hệ qua {email}. Quý vị vẫn có thể chọn giờ nếu sau này thấy cần.',

  errorSummaryOne: 'Một mục cần được xem lại.',
  errorSummaryTwo: 'Hai mục cần được xem lại.',
  errorSummaryMany: '{count} mục cần được xem lại.',
  errorSummaryFixInquiry:
    'Hãy sửa các mục được đánh dấu bên dưới, rồi gửi lại câu hỏi.',
  errorSummaryFixProperty:
    'Hãy nhập họ tên và một địa chỉ email chúng tôi có thể phản hồi, rồi gửi lại thông tin bất động sản.',
  failedTitleInquiry: 'Chúng tôi không gửi được câu hỏi của quý vị.',
  failedTitleProperty: 'Chúng tôi không gửi được thông tin bất động sản của quý vị.',
  failedBody:
    'Các câu trả lời của quý vị vẫn còn đây. Hãy thử lại hoặc liên hệ trực tiếp với AxisPoint.',
  tryAgain: 'Thử lại',
  unavailableTitle: 'Hiện chưa thể gửi.',
  unavailableBody:
    'Chưa có gì được gửi. Các câu trả lời của quý vị vẫn còn đây, và trong lúc này quý vị có thể liên hệ trực tiếp với AxisPoint.',
  blockedBody:
    'Chưa có gì được gửi, và thử lại cũng không giúp ích. Các câu trả lời của quý vị vẫn còn đây. Hãy liên hệ trực tiếp với AxisPoint.',
  emailAxisPoint: 'Gửi email cho AxisPoint',

  fieldFullName: 'Họ và tên',
  fieldEmail: 'Email',
  fieldPhone: 'Điện thoại',
  fieldPhonePlaceholder: '(713) 000 0000',
  fieldPhoneHelp: 'Hãy để lại số nếu quý vị muốn được gọi trực tiếp.',
  fieldCompanyOwnership: 'Công ty hoặc nhóm sở hữu',
  fieldLanguageFollowUp: 'Ngôn ngữ khi liên hệ lại',
  followUpHelpChosen:
    'Chúng tôi sẽ trả lời bằng {language} khi có đối tác phù hợp, và bằng tiếng Anh trong các trường hợp khác.',
  followUpHelpDefault:
    'Cứ để nguyên và chúng tôi sẽ trả lời bằng ngôn ngữ của trang này.',
  sending: 'Đang gửi',
  noDocuments: 'Chưa cần tài liệu nào ở giai đoạn này.',

  step1Title: 'Hãy cho chúng tôi biết về bất động sản của quý vị.',
  step1Lead:
    'Một vài thông tin sẽ giúp chúng tôi hiểu quý vị đang sở hữu gì, điều gì cần thay đổi, và liệu AxisPoint có phải đối tác vận hành phù hợp hay không.',
  step1SubTitle: 'Chúng ta đang nói về điều gì?',
  legendPropertyType: 'Loại bất động sản',
  legendPropertyScope: 'Phạm vi bất động sản',
  fieldLocation: 'Bất động sản nằm ở đâu?',
  fieldLocationPlaceholder: 'Thành phố hoặc thị trường',
  fieldLocationHelp:
    'Hiện tại chỉ cần thành phố hoặc thị trường. Không cần địa chỉ cụ thể.',
  fieldPropertyCount: 'Số lượng bất động sản',
  fieldPropertyCountPlaceholder: 'Ví dụ 6',
  notSure: 'Chưa chắc',
  continueLabel: 'Tiếp tục',
  step1Footer: 'Bước 1 trên 3. Tổng cộng khoảng 60 đến 90 giây.',

  step2Title: 'Điều gì cần thay đổi?',
  legendCurrentSituation: 'Tình hình hiện tại',
  legendInvolvement: 'Quý vị muốn AxisPoint tham gia ở mức nào?',
  fieldTiming: 'Thời gian',
  fieldTimingPlaceholder: 'Chọn khung thời gian',
  fieldUnderstand: 'Chúng tôi nên biết điều gì trước khi trao đổi?',
  fieldUnderstandPlaceholder:
    'Bất cứ điều gì về bất động sản, đơn vị quản lý hiện tại hoặc thời gian',
  backLabel: 'Quay lại',

  step3Title: 'Chúng tôi nên liên hệ lại thế nào?',
  privacyNote:
    'AxisPoint sẽ dùng thông tin này để xem xét câu hỏi của quý vị và liên hệ trực tiếp.',
  sendPropertyDetails: 'Gửi thông tin bất động sản',
};
