import type { Messages } from '../../messages';

/**
 * VIETNAMESE. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Vietnamese has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `vi` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * REGISTER. `quý vị` throughout, which is formal and audience-neutral. A reviewer should
 * confirm it against the intended Houston Vietnamese readership: `anh/chị` would read as
 * warmer and more personal, `ông/bà` as more distant, and the choice runs through most of
 * the file rather than sitting in one string.
 *
 * DIACRITICS. Every tone mark here is load-bearing. `apps/web/tests/unicode.test.ts` already
 * proves Vietnamese text survives the wire path unchanged; this file is the display side of
 * the same requirement, and a reviewer should check the rendered page rather than the source.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const VI: Partial<Messages> = {
  gatewayTitle: 'Quý vị muốn trao đổi về điều gì?',
  gatewayLead:
    'Hãy chọn hướng phù hợp nhất với tình huống của quý vị. Quý vị có thể thay đổi sau.',
  gatewayOwnerKicker: 'Phần lớn chủ sở hữu bắt đầu từ đây',
  gatewayOwnerTitle: 'Chủ sở hữu bất động sản',
  gatewayOwnerBody: 'Tôi sở hữu hoặc phụ trách một bất động sản và cần dịch vụ quản lý.',
  gatewayOwnerAction: 'Bắt đầu nhập thông tin bất động sản',
  gatewayAssetTitle: 'Quản lý tài sản',
  gatewayAssetBody:
    'Tôi sở hữu bất động sản và muốn được hỗ trợ định hướng chiến lược, hiệu quả hoạt động và báo cáo.',
  gatewayInvestorTitle: 'Dịch vụ cho nhà đầu tư',
  gatewayInvestorBody:
    'Tôi đang chuẩn bị mua bất động sản thương mại và cần một đội ngũ vận hành.',
  gatewayGeneralTitle: 'Câu hỏi chung',
  gatewayGeneralBody: 'Việc khác. Nhà cung cấp, báo chí, tuyển dụng hoặc một câu hỏi.',

  propertyTypeMultifamily: 'Nhà ở nhiều căn hộ',
  propertyTypeRetail: 'Mặt bằng bán lẻ',
  propertyTypeMixedPortfolio: 'Danh mục hỗn hợp',
  propertyTypeAnother: 'Loại bất động sản khác',
  propertyScopeOne: 'Một bất động sản',
  propertyScopePortfolio: 'Danh mục đầu tư',

  situationReplace: 'Thay đơn vị quản lý hiện tại',
  situationMoveAway: 'Ngừng tự quản lý',
  situationRecentlyAcquired: 'Mới mua lại hoặc đang trong hợp đồng',
  situationLeaseUp: 'Giai đoạn cho thuê ban đầu hoặc cải thiện hoạt động',
  situationOperations: 'Vấn đề về vận hành hoặc báo cáo',
  situationExploring: 'Đang tìm hiểu các phương án quản lý',
  situationSomethingElse: 'Việc khác',

  involvementPm: 'Quản lý bất động sản',
  involvementPmHint: 'Vận hành bất động sản hằng ngày.',
  involvementPmAm: 'Quản lý bất động sản + Quản lý tài sản',
  involvementPmAmHint: 'Vận hành bất động sản và hỗ trợ định hướng chiến lược đầu tư.',
  involvementNotSure: 'Chưa chắc chắn',
  involvementNotSureHint: 'Hãy giúp tôi xác định mức độ tham gia phù hợp.',

  timingImmediately: 'Ngay lập tức',
  timingWithin30: 'Trong vòng 30 ngày',
  timing30to60: 'Từ 30 đến 60 ngày',
  timing60to90: 'Từ 60 đến 90 ngày',
  timingStillExploring: 'Vẫn đang tìm hiểu',

  investorTopicFirstAcquisition: 'Đang tìm hiểu thương vụ đầu tiên',
  investorTopicUnderContract: 'Hiện đang trong hợp đồng',
  investorTopicActivelySearching: 'Đang tích cực tìm kiếm',
  investorTopicOwnProperty: 'Đã có bất động sản, cần đội ngũ vận hành',
  investorTopicSomethingElse: 'Việc khác',
  generalTopicQuestion: 'Một câu hỏi về AxisPoint',
  generalTopicVendor: 'Nhà cung cấp hoặc đơn vị dịch vụ',
  generalTopicEmployment: 'Việc làm',
  generalTopicPress: 'Báo chí hoặc truyền thông',
  generalTopicSomethingElse: 'Việc khác',

  bookingModePhone: 'Gọi điện thoại',
  bookingModeVideo: 'Họp trực tuyến',

  scaleUnitsLabel: 'Số căn hộ ước tính',
  scaleUnitsPlaceholder: 'Ví dụ 184',
  scaleUnitsHelp:
    'Một con số làm tròn là đủ. Chúng tôi đang xác định quy mô đội ngũ vận hành, không kiểm toán bảng tiền thuê.',
  scaleSqftLabel: 'Diện tích ước tính theo foot vuông',
  scaleSqftPlaceholder: 'Ví dụ 42,000',
  scaleSqftHelp: 'Tổng diện tích cho thuê là con số hữu ích nhất ở đây.',
  scaleMixedLabel: 'Quy mô tổng hợp ước tính',
  scaleMixedPlaceholder: 'Ví dụ 300 căn và 40,000 foot vuông',
  scaleMixedHelp:
    'Số căn, diện tích hoặc cả hai. Hãy cho chúng tôi biết theo cách quý vị vẫn theo dõi.',
  scaleOtherLabel: 'Quy mô ước tính',
  scaleOtherPlaceholder: 'Số căn, foot vuông hoặc đơn vị đo khác',
  scaleOtherHelp: 'Hãy mô tả quy mô theo cách phù hợp với loại bất động sản này.',
  scaleFallbackLabel: 'Quy mô ước tính',
  scaleFallbackPlaceholder: 'Số căn hoặc foot vuông',
  scaleFallbackHelp:
    'Chọn loại bất động sản ở trên và mục này sẽ chuyển sang đơn vị đo phù hợp.',

  investorKicker: 'Dịch vụ cho nhà đầu tư',
  investorTitle: 'Hãy cho chúng tôi biết quý vị đang ở giai đoạn nào.',
  investorLead:
    'Một ghi chú ngắn là đủ để bắt đầu. Chúng tôi sẽ liên hệ để sắp xếp một cuộc trao đổi.',
  investorTopicLabel: 'Quý vị đang ở giai đoạn nào?',
  investorNoteLabel: 'Quý vị đang quan tâm đến điều gì?',
  investorNotePlaceholder: 'Loại tài sản, thị trường hoặc thời gian',
  generalKicker: 'Câu hỏi chung',
  generalTitle: 'Chúng tôi có thể giúp gì?',
  generalLead:
    'Hãy cho chúng tôi biết quý vị là ai và cần gì. Chúng tôi sẽ chuyển đến đúng đối tác.',
  generalTopicLabel: 'Đây là về việc gì?',
  generalNoteLabel: 'Lời nhắn của quý vị',
  generalNotePlaceholder: 'Vài câu là đủ',
  organizationLabel: 'Công ty',
  submitLabel: 'Gửi câu hỏi',

  nameHelp: 'Cách quý vị muốn chúng tôi xưng hô.',
  nameError: 'Hãy nhập tên chúng tôi nên hỏi khi gọi điện.',
  emailHelp: 'Nơi chúng tôi sẽ gửi phản hồi và các thông tin tiếp theo.',
  emailError:
    'Địa chỉ này thiếu phần sau dấu @. Hãy nhập địa chỉ đầy đủ, ví dụ name@company.com.',
  topicError: 'Hãy chọn phương án mô tả đúng nhất câu hỏi của quý vị.',
  followUpSameAsPage: 'Giống trang này, tiếng Việt',
  selectOne: 'Chọn một mục',
  notSpecified: 'Không có thông tin',

  bookingCandidateNote:
    'Thời gian hiển thị theo Giờ Miền Trung, Houston. Tình trạng còn trống được xác nhận khi quý vị đặt lịch.',
  bookingSlotTaken: 'Thời gian đó không còn trống. Hãy chọn giờ khác.',
  bookingFailed:
    'Chúng tôi không xác nhận được thời gian đó. Chưa có lịch nào được đặt. Hãy thử lại.',
  bookingRefused: 'Chúng tôi không đặt được thời gian đó, và thử lại cũng không giúp ích.',
  bookingUnavailable: 'Hiện chưa thể đặt lịch. Chưa có lịch nào được đặt.',
  bookingDurationLabel: '30 phút',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: 'Quản lý bất động sản',
  navAssetManagement: 'Quản lý tài sản',
  navInvestorServices: 'Dịch vụ cho nhà đầu tư',
  navPartners: 'Đối tác',
  navContact: 'Liên hệ',
  navCta: 'Yêu cầu đề xuất quản lý',
  navHomeAria: 'AxisPoint, trang chủ',
  navPrimaryAria: 'Chính',
  // Kept as the English loanword, which is what Vietnamese interfaces overwhelmingly use.
  // A reviewer may prefer 'Danh mục'.
  navMenu: 'Menu',
  navMenuDialogAria: 'Menu trang web',
  navCloseMenu: 'Đóng menu',

  skipToContent: 'Chuyển đến nội dung chính',

  footerPositioning:
    'Quản lý bất động sản trước tiên, kèm quản lý tài sản khi bất động sản cần một lớp chiến lược bên trên.',
  footerServices: 'Dịch vụ',
  footerFirm: 'Công ty',
  footerLocation: 'Houston, Texas',
  footerStatewide: 'Phục vụ chủ sở hữu trên toàn bang Texas',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    'Hoạt động môi giới và cho thuê được thực hiện thông qua đối tác có giấy phép của chúng tôi. AxisPoint Partners không cung cấp tư vấn thuế hoặc pháp lý. Trang web này chỉ nhằm mục đích cung cấp thông tin và không cấu thành lời chào bán chứng khoán.',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: 'Không tìm thấy trang',
  notFoundAction: 'Về trang chủ',
  languageChooseAria: 'Chọn ngôn ngữ. Ngôn ngữ hiện tại: {language}.',
  languageListAria: 'Chọn ngôn ngữ',
};
