import type { Messages } from '../../messages';

/**
 * SIMPLIFIED CHINESE. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Chinese has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `zh-Hans` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * SIMPLIFIED AND TRADITIONAL ARE SEPARATE FILES AND MUST STAY THAT WAY. The approved design
 * treats them as distinct locales with distinct font families and neither is a mechanical
 * conversion of the other: this file uses mainland vocabulary (软件/信息 conventions,
 * 物业管理), while `./zh-Hant.ts` uses Taiwan conventions. A reviewer should check the two
 * files independently rather than diffing one against a converted copy of the other.
 *
 * PUNCTUATION. Full-width punctuation throughout (，。？：), which is correct for this script
 * and is not the project's no-em-dash rule being violated. Latin brand names and email
 * examples keep half-width spacing around them.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const ZH_HANS: Partial<Messages> = {
  gatewayTitle: '您想咨询哪方面的事务？',
  gatewayLead: '请选择最符合您情况的方向。之后仍可更改。',
  gatewayOwnerKicker: '多数业主从这里开始',
  gatewayOwnerTitle: '物业业主',
  gatewayOwnerBody: '我拥有或负责一处物业，需要管理服务。',
  gatewayOwnerAction: '开始填写物业信息',
  gatewayAssetTitle: '资产管理',
  gatewayAssetBody: '我拥有物业，希望有人协助制定策略、提升表现并提供报告。',
  gatewayInvestorTitle: '投资者服务',
  gatewayInvestorBody: '我正准备收购商业地产，需要一支运营团队。',
  gatewayGeneralTitle: '一般咨询',
  gatewayGeneralBody: '其他事务。供应商、媒体、招聘或其他问题。',

  propertyTypeMultifamily: '多户住宅',
  propertyTypeRetail: '零售物业',
  propertyTypeMixedPortfolio: '混合型投资组合',
  propertyTypeAnother: '其他物业类型',
  propertyScopeOne: '单一物业',
  propertyScopePortfolio: '投资组合',

  situationReplace: '更换现有管理方',
  situationMoveAway: '不再自行管理',
  situationRecentlyAcquired: '近期收购或正在签约',
  situationLeaseUp: '招租期或扭转经营',
  situationOperations: '运营或报告方面的问题',
  situationExploring: '正在了解管理方案',
  situationSomethingElse: '其他情况',

  involvementPm: '物业管理',
  involvementPmHint: '负责物业的日常运营。',
  involvementPmAm: '物业管理 + 资产管理',
  involvementPmAmHint: '负责物业运营，并协助制定投资策略。',
  involvementNotSure: '尚不确定',
  involvementNotSureHint: '请帮我判断合适的参与程度。',

  timingImmediately: '立即',
  timingWithin30: '30 天内',
  timing30to60: '30 至 60 天',
  timing60to90: '60 至 90 天',
  timingStillExploring: '仍在考虑',

  investorTopicFirstAcquisition: '正在考虑首次收购',
  investorTopicUnderContract: '目前已签约',
  investorTopicActivelySearching: '正在积极寻找',
  investorTopicOwnProperty: '已有物业，需要运营团队',
  investorTopicSomethingElse: '其他情况',
  generalTopicQuestion: '关于 AxisPoint 的问题',
  generalTopicVendor: '供应商或服务提供方',
  generalTopicEmployment: '招聘就业',
  generalTopicPress: '媒体或新闻',
  generalTopicSomethingElse: '其他情况',

  bookingModePhone: '电话通话',
  bookingModeVideo: '视频会议',

  scaleUnitsLabel: '大致单元数',
  scaleUnitsPlaceholder: '例如 184',
  scaleUnitsHelp: '大致数字即可。我们是在评估运营团队规模，而不是审核租金表。',
  scaleSqftLabel: '大致面积（平方英尺）',
  scaleSqftPlaceholder: '例如 42,000',
  scaleSqftHelp: '可租赁总面积是最有参考价值的数字。',
  scaleMixedLabel: '大致综合规模',
  scaleMixedPlaceholder: '例如 300 个单元和 40,000 平方英尺',
  scaleMixedHelp: '单元数、面积或两者皆可。用您习惯的方式告诉我们。',
  scaleOtherLabel: '大致规模',
  scaleOtherPlaceholder: '单元数、平方英尺或其他计量方式',
  scaleOtherHelp: '请用适合此类物业的方式描述规模。',
  scaleFallbackLabel: '大致规模',
  scaleFallbackPlaceholder: '单元数或平方英尺',
  scaleFallbackHelp: '在上方选择物业类型，此处会自动调整为对应的计量方式。',

  investorKicker: '投资者服务',
  investorTitle: '请告诉我们您目前处于哪个阶段。',
  investorLead: '简短说明即可开始。我们会跟进安排一次沟通。',
  investorTopicLabel: '您目前处于哪个阶段？',
  investorNoteLabel: '您在关注什么？',
  investorNotePlaceholder: '资产类型、市场或时间安排',
  generalKicker: '一般咨询',
  generalTitle: '我们能帮您做什么？',
  generalLead: '请告诉我们您的身份和需求。我们会转交给合适的合伙人。',
  generalTopicLabel: '这是关于什么的？',
  generalNoteLabel: '您的留言',
  generalNotePlaceholder: '几句话就足够',
  organizationLabel: '公司',
  submitLabel: '发送咨询',

  nameHelp: '您希望我们如何称呼您。',
  nameError: '请填写我们致电时应当询问的姓名。',
  emailHelp: '我们将把回复和后续信息发送至此处。',
  emailError: '此地址缺少 @ 符号后面的部分。请填写完整地址，例如 name@company.com。',
  topicError: '请选择最能说明您咨询内容的选项。',
  followUpSameAsPage: '与本页相同，简体中文',
  selectOne: '请选择一项',
  notSpecified: '未填写',

  bookingCandidateNote: '时间以美国中部时间（休斯顿）显示。可用性在您预约时确认。',
  bookingSlotTaken: '该时间已不可用。请另选一个。',
  bookingFailed: '我们无法确认该时间。未完成任何预约。请重试。',
  bookingRefused: '我们无法预约该时间，重试也不会有帮助。',
  bookingUnavailable: '目前无法预约。未完成任何预约。',
  bookingDurationLabel: '30 分钟',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: '物业管理',
  navAssetManagement: '资产管理',
  navInvestorServices: '投资者服务',
  navPartners: '合伙人',
  navContact: '联系我们',
  navCta: '申请物业管理方案',
  navHomeAria: 'AxisPoint，首页',
  navPrimaryAria: '主导航',
  navMenu: '菜单',
  navMenuDialogAria: '网站菜单',
  navCloseMenu: '关闭菜单',

  skipToContent: '跳到主要内容',

  footerPositioning: '以物业管理为先，当物业需要更高一层的策略支持时，可加入资产管理。',
  footerServices: '服务',
  footerFirm: '公司',
  footerLocation: '德克萨斯州休斯顿',
  footerStatewide: '为德克萨斯州各地的业主提供服务',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    '经纪和租赁业务由我们持牌的合作方开展。AxisPoint Partners 不提供税务或法律建议。本网站仅供参考，不构成出售证券的要约。',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: '未找到页面',
  notFoundAction: '返回首页',
  languageChooseAria: '选择语言。当前语言：{language}。',
  languageListAria: '选择语言',

  /* ══ Marketing pages (PR 3) ══
   * Proper nouns preserved: AxisPoint and both partner names stay in Latin script. Place
   * names use the established Chinese forms (休斯顿, 德克萨斯州). No claim or number changed. */

  partnersSignature: 'Zachary Russell 与 Ethaniel Vu，合伙人。',
  pmRunsAmDirectsTitle: '物业管理负责运营物业，资产管理负责主导投资方向。',

  homeMetaTitle: 'AxisPoint Partners | 德克萨斯州商业物业管理',
  homeMetaDescription:
    'AxisPoint 为德克萨斯州各地的业主管理多户住宅和零售物业，涵盖现场运营、财务管控、供应商表现以及面向业主的报告。',
  homeHeroAlt: '黄昏时分多户住宅社区的草坪与建筑立面',
  homeHeroTitle: '由一个团队为您的物业运营负责。',
  homeHeroLead:
    'AxisPoint 为德克萨斯州各地的业主管理多户住宅和零售物业，涵盖现场运营、财务管控、供应商表现，以及业主实际阅读的报告。',
  homeHeroQuietLink: '了解我们承担哪些责任',
  homeHeroSignature: '由合伙人 Zachary Russell 与 Ethaniel Vu 在休斯顿主理。',
  homeStripEyebrow: '物业管理优先',
  homeStripBody: '主要方向：德克萨斯州各地的多户住宅与零售物业。总部位于休斯顿。',
  homeWhyTitle: '业主为什么联系 AxisPoint',
  homeWhyLead: '通常是四种情况之一。',
  homeWhySituationManager: '现有管理方已失去业主的信任。',
  homeWhySituationSelf: '自行管理已经变成第二份工作。',
  homeWhySituationAcquired: '新收购的物业需要在第一个月结束前就位一支运营团队。',
  homeWhyOr: '或者',
  homeWhySituationReports: '报告按时送达，却依然说不清物业的情况。',
  homeWhyBody:
    '这四种情况背后的问题是同一个：今天由谁为这处物业负责。AxisPoint 的回答是一个负责到底的团队，以及两位足够贴近现场、能叫得出物业名字的合伙人。',
  homeWhyLink: 'AxisPoint 承担哪些责任',
  homeStrategicEyebrow: '策略层',
  homeStrategicBody:
    '对于希望在运营工作之上获得业主视角的客户，AxisPoint 将物业的实际表现与预算、资本优先级和持有决策连接起来。在物业确有需要时才引入，而不是作为标配推销。',
  homeInvestorEyebrow: '另一条路径',
  homeInvestorBody: '进入商业地产却没有运营团队支持？投资者服务是您的入口。',
  homeClosingTitle: '告诉我们这处物业接下来需要什么。',
  homeClosingBody:
    '请提供物业情况、目前的管理状况，以及您正在考虑的调整。会有一位合伙人阅读并回复。',

  pmMetaTitle: '休斯顿及德克萨斯州各地的物业管理 | AxisPoint Partners',
  pmMetaDescription:
    'AxisPoint 为德克萨斯州的多户住宅和零售物业承担运营责任：现场运营、财务管控、供应商表现以及业主报告。',
  pmHeroTitle: '休斯顿及德克萨斯州各地的商业物业管理',
  pmHeroLead:
    'AxisPoint 为多户住宅和零售物业承担运营责任：现场团队、资金、供应商，以及业主用来做决策的报告。',
  pmSeeFunctions: '查看四项运营职能',
  pmPhotoAlt: '德克萨斯州一处多户住宅社区及毗邻零售中心的航拍视角',
  pmResponsibilityTitle: 'AxisPoint 承担哪些责任',
  pmResponsibilityBody:
    '决定物业日常运转的一切，以及一份面向业主的完整记录。物业出现问题时，业主不必再去打听该找谁。',
  pmFunctionsTitle: '四项运营职能，一个负责到底的团队',
  pmFnOnsiteTitle: '现场运营',
  pmFnOnsiteLede:
    '物业现场的人员以及他们坚持的工作规范。人员安排、租赁监督、响应标准和周转排期，让物业逐周按计划运转。',
  pmFnOnsiteItem1: '现场人员配置与监督',
  pmFnOnsiteItem2: '租赁监督',
  pmFnOnsiteItem3: '住户与租户响应',
  pmFnOnsiteItem4: '退租周转与交付准备',
  pmFnOnsiteItem5: '预防性维护',
  pmFnFinancialTitle: '财务管控',
  pmFnFinancialLede:
    '与业主共同编制的预算、事先约定的审批门槛，以及每一个数字都能追溯到相应决策的月度结账。',
  pmFnFinancialItem1: '年度预算与滚动预测',
  pmFnFinancialItem2: '审批门槛',
  pmFnFinancialItem3: '收款与欠费管理',
  pmFnFinancialItem4: '应付账款与月末结账',
  pmFnFinancialItem5: '差异说明',
  pmFnVendorTitle: '供应商表现',
  pmFnVendorLede:
    '明确界定的工作范围、真实的招标纪律，以及以结果质量而非工单关闭来衡量的跟进。',
  pmFnVendorItem1: '工作范围与招标流程',
  pmFnVendorItem2: '合同与保险合规',
  pmFnVendorItem3: '质量核验',
  pmFnVendorItem4: '资本项目协调',
  pmFnReportingTitle: '业主报告与沟通',
  pmFnReportingLede:
    '一份记录说明物业发生了什么、花了多少钱、接下来是什么，另有一位合伙人在报告周期之间随时答复。',
  pmFnReportingItem1: '月度报告包',
  pmFnReportingItem2: '运营说明',
  pmFnReportingItem3: '资本与项目追踪',
  pmFnReportingItem4: '直接联系合伙人',
  pmStrengthsTitle: 'AxisPoint 最擅长的领域',
  pmStrengthsBody:
    '这些是团队所擅长应对的情况。它们是优势领域而非硬性条件，不在其中的物业同样值得沟通。',
  pmStrengthTypesTitle: '物业类型',
  pmStrengthTypesItem1: '以多户住宅为主要方向',
  pmStrengthTypesItem2: '以零售物业为主要方向',
  pmStrengthTypesItem3: '能够支撑现场人员的物业',
  pmStrengthTypesItem4: '同一业主名下统筹管理的投资组合',
  pmStrengthTypesItem5: '作为单一项目运作的分散型投资组合',
  pmStrengthGeographyTitle: '地域',
  pmStrengthGeographyItem1: '休斯顿及周边都会区',
  pmStrengthGeographyItem2: '达拉斯与沃思堡',
  pmStrengthGeographyItem3: '圣安东尼奥',
  pmStrengthGeographyItem4: '奥斯汀',
  pmStrengthGeographyItem5: '德克萨斯州各地的业主',
  pmStrengthAssignmentsTitle: '委托类型',
  pmStrengthAssignmentsItem1: '管理方交接',
  pmStrengthAssignmentsItem2: '招租期',
  pmStrengthAssignmentsItem3: '大额资本项目',
  pmStrengthAssignmentsItem4: '长期积压的运营问题',
  pmStrengthAssignmentsItem5: '扭转经营的委托',
  pmQuestionsTitle: '业主在更换管理方前常问的问题',
  pmQ1: '管理交接需要多长时间？',
  pmA1: '这取决于物业本身和原管理方，但计划会在启动日期之前写好：人员、系统、银行账户、供应商记录，以及住户或租户沟通，每一项都有明确负责人和时间点。',
  pmQ2: '实际由谁为我的物业负责？',
  pmA2: '由合伙人负责。Zachary Russell 与 Ethaniel Vu 足够贴近现场，能叫得出物业的名字，业主也无需经过客户经理层级才能联系到他们。',
  pmQ3: '每月的报告是什么样的？',
  pmA3: '固定的报告包，按固定的时间提供，并附书面说明解释各项差异，而不是让业主自己去解读数字。',
  pmQ4: '你们能接手存在积压问题的物业吗？',
  pmA4: '可以。积压的维修、未完成的资本工作和人员缺口，都是业主来电的常见原因。方案中会写明先处理什么、按什么顺序处理。',
  pmRelatedEyebrow: '相关内容',
  pmRelatedAsset: '资产管理位于运营工作之上，面向希望获得投资视角的业主',
  pmRelatedInvestor: '投资者服务是尚无运营团队的资金充足客户的入口',
  pmClosingTitle: '把物业情况和现状发给我们。',
  pmClosingBody:
    '一份管理方案会涵盖人员配置、报告包、交接计划，以及 AxisPoint 由谁为该物业负责。',

  amMetaTitle: '面向德克萨斯州业主的资产管理 | AxisPoint Partners',
  amMetaDescription:
    '在运营工作之上的业主视角：资本优先级、预算方向和持有决策，由已在运营该物业的团队提供依据。',
  amHeroTitle: '面向德克萨斯州业主的资产管理',
  amHeroAnswer:
    '在运营工作之上的业主视角：资本优先级、预算方向和持有决策，由一支已在运营该物业的团队提供依据。',
  amPhotoAlt: '从街道视角看休斯顿市中心塔楼与高架步道',
  amRelationshipEyebrow: '两者的关系',
  amRelationshipBody:
    '资产管理是运营工作之上的一层，而不是取代运营。它把物业每周的实际表现与预算、资本优先级以及持有或出售的讨论连接起来。业主在物业确有需要时才引入。',
  amLayersTitle: '两个层次，说清楚',
  amDecidesEyebrow: '资产管理负责决定',
  amDecidesItem1: '资本优先级与推进顺序',
  amDecidesItem2: '预算方向与滚动预测取向',
  amDecidesItem3: '持有、再融资与处置的判断',
  amDecidesItem4: '对照业主意图的绩效评估',
  amExecutesEyebrow: '物业管理负责执行',
  amExecutesItem1: '现场运营与人员配置',
  amExecutesItem2: '财务管控与月度结账',
  amExecutesItem3: '供应商范围与表现',
  amExecutesItem4: '业主报告与沟通',
  amClosingTitle: '先从物业开始，再叠加上面这一层。',
  amClosingBody:
    '多数业主从物业管理开始。当投资层面的问题需要同一支团队来回答时，再加入资产管理。',

  isMetaTitle: '德克萨斯州商业地产投资者服务 | AxisPoint Partners',
  isMetaDescription:
    '面向在德克萨斯州收购多户住宅或零售物业的资金充足客户，希望在购买之前而非之后就把运营一侧安排妥当。',
  isHeroTitle: '带着运营团队进入德克萨斯州商业地产的路径',
  isHeroAnswer:
    '面向在德克萨斯州收购多户住宅或零售物业的资金充足客户，希望在购买之前而非之后就把运营一侧安排妥当。',
  isPhotoAlt: '休斯顿一处高速公路立交的航拍视角',
  isWhoEyebrow: '适合哪些人',
  isWhoLead: '资金已经就位、但需要运营团队才能行动的客户。',
  isWhoBody:
    '投资者服务是三条路径中最小的一条，而且刻意保持如此。它面向初次进入商业地产、或初次进入德克萨斯州的业主，他们希望从第一处物业起就把运营一侧安排好，而不是在成交之后再临时拼凑。',
  isTimelineBeforeLabel: '购买之前',
  isTimelineBeforeBody:
    '对这处物业的运营成本做出判断，使报价背后的假设与管理方实际会用的假设一致。',
  isTimelineClosingLabel: '成交时',
  isTimelineClosingBody:
    '管理团队第一天即到位，人员、系统和供应商关系都已就绪，而不是仍在筹备。',
  isTimelineAfterLabel: '第一处物业之后',
  isTimelineAfterBody: '合作关系转入物业管理；若业主视角有此需要，再加入资产管理。',
  isClosingTitle: '告诉我们您打算收购什么。',
  isClosingBody:
    '请提供物业类型、市场和时间安排。会有一位合伙人回复运营层面的判断，以及管理方案大致的样子。',
  isClosingCta: '洽谈收购事宜',

  partnersMetaTitle: '合伙人 | AxisPoint Partners',
  partnersMetaDescription:
    'AxisPoint 由合伙人在休斯顿主理。Zachary Russell 与 Ethaniel Vu 会持续跟进自己接手的物业，业主直接与做决定的人对话。',
  partnersHeroTitle: '两位合伙人，直接为工作负责',
  partnersHeroAnswer: 'AxisPoint 由合伙人在休斯顿主理。接下委托的人，就是持续跟进的人。',
  partnersRoleLabel: '合伙人',
  partnerRussellBody:
    '直接负责运营表现：人员决策、管理交接、资本项目，以及投资组合中本月需要重点关注的物业。',
  partnerVuBody:
    '直接负责财务管控和面向业主的记录：预算、审批纪律、月度结账，以及业主用来做决策的报告。',
  partnersHowEyebrow: '我们的工作方式',
  partnersHowBody:
    '两位合伙人都会持续跟进自己接手的物业。业主直接与做决定的人对话，而不是与安排在前面的一层人对接。',
  partnersClosingTitle: '就您的物业与合伙人聊一聊。',
  partnersClosingBody: '请提供物业情况和现状。阅读它的合伙人，就是将来为它负责的人。',
};
