import type { Messages } from '../../messages';

/**
 * SIMPLIFIED CHINESE. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Chinese has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `zh-Hans` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * SIMPLIFIED AND TRADITIONAL ARE SEPARATE FILES AND MUST STAY THAT WAY. The approved design
 * treats them as distinct locales with distinct font families and neither is a mechanical
 * conversion of the other: this file uses mainland vocabulary (软件/信息 conventions,
 * 物业管理), while `./zh-Hant.ts` uses Taiwan conventions. A reviewer should check the two
 * files independently rather than diffing one against a converted copy of the other.
 *
 * PUNCTUATION. Full-width punctuation throughout (，。？：), which is correct for this script
 * and is not the project's no-em-dash rule being violated. Latin brand names and email
 * examples keep half-width spacing around them.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const ZH_HANS: Partial<Messages> = {
  gatewayTitle: '您想咨询哪方面的事务？',
  gatewayLead: '请选择最符合您情况的方向。之后仍可更改。',
  gatewayOwnerKicker: '多数业主从这里开始',
  gatewayOwnerTitle: '物业业主',
  gatewayOwnerBody: '我拥有或负责一处物业，需要管理服务。',
  gatewayOwnerAction: '开始填写物业信息',
  gatewayAssetTitle: '资产管理',
  gatewayAssetBody: '我拥有物业，希望有人协助制定策略、提升表现并提供报告。',
  gatewayInvestorTitle: '投资者服务',
  gatewayInvestorBody: '我正准备收购商业地产，需要一支运营团队。',
  gatewayGeneralTitle: '一般咨询',
  gatewayGeneralBody: '其他事务。供应商、媒体、招聘或其他问题。',

  propertyTypeMultifamily: '多户住宅',
  propertyTypeRetail: '零售物业',
  propertyTypeMixedPortfolio: '混合型投资组合',
  propertyTypeAnother: '其他物业类型',
  propertyScopeOne: '单一物业',
  propertyScopePortfolio: '投资组合',

  situationReplace: '更换现有管理方',
  situationMoveAway: '不再自行管理',
  situationRecentlyAcquired: '近期收购或正在签约',
  situationLeaseUp: '招租期或扭转经营',
  situationOperations: '运营或报告方面的问题',
  situationExploring: '正在了解管理方案',
  situationSomethingElse: '其他情况',

  involvementPm: '物业管理',
  involvementPmHint: '负责物业的日常运营。',
  involvementPmAm: '物业管理 + 资产管理',
  involvementPmAmHint: '负责物业运营，并协助制定投资策略。',
  involvementNotSure: '尚不确定',
  involvementNotSureHint: '请帮我判断合适的参与程度。',

  timingImmediately: '立即',
  timingWithin30: '30 天内',
  timing30to60: '30 至 60 天',
  timing60to90: '60 至 90 天',
  timingStillExploring: '仍在考虑',

  investorTopicFirstAcquisition: '正在考虑首次收购',
  investorTopicUnderContract: '目前已签约',
  investorTopicActivelySearching: '正在积极寻找',
  investorTopicOwnProperty: '已有物业，需要运营团队',
  investorTopicSomethingElse: '其他情况',
  generalTopicQuestion: '关于 AxisPoint 的问题',
  generalTopicVendor: '供应商或服务提供方',
  generalTopicEmployment: '招聘就业',
  generalTopicPress: '媒体或新闻',
  generalTopicSomethingElse: '其他情况',

  bookingModePhone: '电话通话',
  bookingModeVideo: '视频会议',

  scaleUnitsLabel: '大致单元数',
  scaleUnitsPlaceholder: '例如 184',
  scaleUnitsHelp: '大致数字即可。我们是在评估运营团队规模，而不是审核租金表。',
  scaleSqftLabel: '大致面积（平方英尺）',
  scaleSqftPlaceholder: '例如 42,000',
  scaleSqftHelp: '可租赁总面积是最有参考价值的数字。',
  scaleMixedLabel: '大致综合规模',
  scaleMixedPlaceholder: '例如 300 个单元和 40,000 平方英尺',
  scaleMixedHelp: '单元数、面积或两者皆可。用您习惯的方式告诉我们。',
  scaleOtherLabel: '大致规模',
  scaleOtherPlaceholder: '单元数、平方英尺或其他计量方式',
  scaleOtherHelp: '请用适合此类物业的方式描述规模。',
  scaleFallbackLabel: '大致规模',
  scaleFallbackPlaceholder: '单元数或平方英尺',
  scaleFallbackHelp: '在上方选择物业类型，此处会自动调整为对应的计量方式。',

  investorKicker: '投资者服务',
  investorTitle: '请告诉我们您目前处于哪个阶段。',
  investorLead: '简短说明即可开始。我们会跟进安排一次沟通。',
  investorTopicLabel: '您目前处于哪个阶段？',
  investorNoteLabel: '您在关注什么？',
  investorNotePlaceholder: '资产类型、市场或时间安排',
  generalKicker: '一般咨询',
  generalTitle: '我们能帮您做什么？',
  generalLead: '请告诉我们您的身份和需求。我们会转交给合适的合伙人。',
  generalTopicLabel: '这是关于什么的？',
  generalNoteLabel: '您的留言',
  generalNotePlaceholder: '几句话就足够',
  organizationLabel: '公司',
  submitLabel: '发送咨询',

  nameHelp: '您希望我们如何称呼您。',
  nameError: '请填写我们致电时应当询问的姓名。',
  emailHelp: '我们将把回复和后续信息发送至此处。',
  emailError: '此地址缺少 @ 符号后面的部分。请填写完整地址，例如 name@company.com。',
  topicError: '请选择最能说明您咨询内容的选项。',
  followUpSameAsPage: '与本页相同，简体中文',
  selectOne: '请选择一项',
  notSpecified: '未填写',

  bookingCandidateNote: '时间以美国中部时间（休斯顿）显示。可用性在您预约时确认。',
  bookingSlotTaken: '该时间已不可用。请另选一个。',
  bookingFailed: '我们无法确认该时间。未完成任何预约。请重试。',
  bookingRefused: '我们无法预约该时间，重试也不会有帮助。',
  bookingUnavailable: '目前无法预约。未完成任何预约。',
  bookingDurationLabel: '30 分钟',
  bookingWithLabel: 'AxisPoint Partners',
};
