import type { Messages } from '../../messages';

/**
 * TRADITIONAL CHINESE. AUDIT CANDIDATE, NOT REVIEWED, NOT FOR PRODUCTION.
 *
 * WHAT THIS IS. Text generated by a language model (Claude) during the Multilingual Content
 * Rollout pass. No speaker of Chinese has read it. It has not been through a professional
 * translation pass, it is not approved, and it is not production-ready.
 *
 * TWO INDEPENDENT GUARDS keep it away from visitors: `zh-Hant` is `enabled: false,
 * review: 'unreviewed'` in `../../locales.ts`, and this directory leaves the module graph in
 * every build. See `../none.ts`. Promotion is described in `../reviewed/index.ts`.
 *
 * NOT A CONVERTED COPY OF `./zh-Hans.ts`. Character conversion alone produces text that reads
 * as mainland Chinese written in traditional characters, which is the specific failure the
 * approved design guards against by treating the two as separate locales with separate font
 * families. This file uses Taiwan vocabulary: 營運 rather than 运营, 視訊 rather than 视频,
 * 資訊 rather than 信息, 休士頓 rather than 休斯顿. A reviewer should read it on its own terms.
 *
 * A reviewer should also decide whether Taiwan or Hong Kong conventions are wanted. This file
 * assumes Taiwan. Hong Kong Cantonese readers would expect different vocabulary in several
 * places, and that is a product decision rather than a translation correction.
 */
export const AUDIT_CANDIDATE_MARKER = 'AXP_AUDIT_CANDIDATE_UNREVIEWED';

export const ZH_HANT: Partial<Messages> = {
  gatewayTitle: '您想諮詢哪方面的事務？',
  gatewayLead: '請選擇最符合您情況的方向。之後仍可變更。',
  gatewayOwnerKicker: '多數業主從這裡開始',
  gatewayOwnerTitle: '物業業主',
  gatewayOwnerBody: '我擁有或負責一處物業，需要管理服務。',
  gatewayOwnerAction: '開始填寫物業資料',
  gatewayAssetTitle: '資產管理',
  gatewayAssetBody: '我擁有物業，希望有人協助制定策略、提升表現並提供報告。',
  gatewayInvestorTitle: '投資者服務',
  gatewayInvestorBody: '我正準備收購商業地產，需要一支營運團隊。',
  gatewayGeneralTitle: '一般諮詢',
  gatewayGeneralBody: '其他事務。供應商、媒體、招聘或其他問題。',

  propertyTypeMultifamily: '多戶住宅',
  propertyTypeRetail: '零售物業',
  propertyTypeMixedPortfolio: '混合型投資組合',
  propertyTypeAnother: '其他物業類型',
  propertyScopeOne: '單一物業',
  propertyScopePortfolio: '投資組合',

  situationReplace: '更換現有管理方',
  situationMoveAway: '不再自行管理',
  situationRecentlyAcquired: '近期收購或正在簽約',
  situationLeaseUp: '招租期或扭轉經營',
  situationOperations: '營運或報告方面的問題',
  situationExploring: '正在了解管理方案',
  situationSomethingElse: '其他情況',

  involvementPm: '物業管理',
  involvementPmHint: '負責物業的日常營運。',
  involvementPmAm: '物業管理 + 資產管理',
  involvementPmAmHint: '負責物業營運，並協助制定投資策略。',
  involvementNotSure: '尚不確定',
  involvementNotSureHint: '請協助我判斷合適的參與程度。',

  timingImmediately: '立即',
  timingWithin30: '30 天內',
  timing30to60: '30 至 60 天',
  timing60to90: '60 至 90 天',
  timingStillExploring: '仍在考慮',

  investorTopicFirstAcquisition: '正在考慮首次收購',
  investorTopicUnderContract: '目前已簽約',
  investorTopicActivelySearching: '正在積極尋找',
  investorTopicOwnProperty: '已有物業，需要營運團隊',
  investorTopicSomethingElse: '其他情況',
  generalTopicQuestion: '關於 AxisPoint 的問題',
  generalTopicVendor: '供應商或服務提供方',
  generalTopicEmployment: '招聘就業',
  generalTopicPress: '媒體或新聞',
  generalTopicSomethingElse: '其他情況',

  bookingModePhone: '電話通話',
  bookingModeVideo: '視訊會議',

  scaleUnitsLabel: '大致單元數',
  scaleUnitsPlaceholder: '例如 184',
  scaleUnitsHelp: '大致數字即可。我們是在評估營運團隊規模，而不是稽核租金表。',
  scaleSqftLabel: '大致面積（平方英尺）',
  scaleSqftPlaceholder: '例如 42,000',
  scaleSqftHelp: '可出租總面積是最有參考價值的數字。',
  scaleMixedLabel: '大致綜合規模',
  scaleMixedPlaceholder: '例如 300 個單元和 40,000 平方英尺',
  scaleMixedHelp: '單元數、面積或兩者皆可。用您習慣的方式告訴我們。',
  scaleOtherLabel: '大致規模',
  scaleOtherPlaceholder: '單元數、平方英尺或其他計量方式',
  scaleOtherHelp: '請用適合此類物業的方式描述規模。',
  scaleFallbackLabel: '大致規模',
  scaleFallbackPlaceholder: '單元數或平方英尺',
  scaleFallbackHelp: '在上方選擇物業類型，此處會自動調整為對應的計量方式。',

  investorKicker: '投資者服務',
  investorTitle: '請告訴我們您目前處於哪個階段。',
  investorLead: '簡短說明即可開始。我們會跟進安排一次洽談。',
  investorTopicLabel: '您目前處於哪個階段？',
  investorNoteLabel: '您在關注什麼？',
  investorNotePlaceholder: '資產類型、市場或時間安排',
  generalKicker: '一般諮詢',
  generalTitle: '我們能為您做什麼？',
  generalLead: '請告訴我們您的身分和需求。我們會轉交給合適的合夥人。',
  generalTopicLabel: '這是關於什麼的？',
  generalNoteLabel: '您的留言',
  generalNotePlaceholder: '幾句話就足夠',
  organizationLabel: '公司',
  submitLabel: '送出諮詢',

  nameHelp: '您希望我們如何稱呼您。',
  nameError: '請填寫我們致電時應當詢問的姓名。',
  emailHelp: '我們將把回覆和後續資訊寄送至此處。',
  emailError: '此地址缺少 @ 符號後面的部分。請填寫完整地址，例如 name@company.com。',
  topicError: '請選擇最能說明您諮詢內容的選項。',
  followUpSameAsPage: '與本頁相同，繁體中文',
  selectOne: '請選擇一項',
  notSpecified: '未填寫',

  bookingCandidateNote: '時間以美國中部時間（休士頓）顯示。可預約時段於您預約時確認。',
  bookingSlotTaken: '該時間已無法預約。請另選一個。',
  bookingFailed: '我們無法確認該時間。未完成任何預約。請重試。',
  bookingRefused: '我們無法預約該時間，重試也不會有幫助。',
  bookingUnavailable: '目前無法安排預約。未完成任何預約。',
  bookingDurationLabel: '30 分鐘',
  bookingWithLabel: 'AxisPoint Partners',

  /* ── Site chrome (PR 2) ── */
  navPropertyManagement: '物業管理',
  navAssetManagement: '資產管理',
  navInvestorServices: '投資者服務',
  navPartners: '合夥人',
  navContact: '聯絡我們',
  navCta: '申請物業管理方案',
  navHomeAria: 'AxisPoint，首頁',
  navPrimaryAria: '主導覽',
  // Taiwan uses 選單 where the mainland uses 菜单. One of the clearest tells that this
  // file is not a character conversion of ./zh-Hans.ts.
  navMenu: '選單',
  navMenuDialogAria: '網站選單',
  navCloseMenu: '關閉選單',

  skipToContent: '跳到主要內容',

  footerPositioning: '以物業管理為先，當物業需要更高一層的策略支援時，可加入資產管理。',
  footerServices: '服務',
  footerFirm: '公司',
  footerLocation: '德克薩斯州休士頓',
  footerStatewide: '為德克薩斯州各地的業主提供服務',
  // LEGAL. Needs a qualified reviewer, not only a native reader. See the English original.
  footerLegal:
    '經紀和租賃業務由我們持牌的合作方開展。AxisPoint Partners 不提供稅務或法律建議。本網站僅供參考，不構成出售證券的要約。',
  footerCopyright: '© 2026 AxisPoint Partners',

  notFoundMessage: '找不到頁面',
  notFoundAction: '返回首頁',
  languageChooseAria: '選擇語言。目前語言：{language}。',
  languageListAria: '選擇語言',
};
